- examples/rp/src/bin/pio_ws2812.rs
This was discussed back in #1834, but I never got around to actually fixing it. I found in testing that using exactly 50us wasn't reliable, thus 55us.
> RP: Add explicit reset time to ws2812 write fn.

- embassy-stm32/build.rs
- embassy-stm32/src/time_driver.rs
I find there are some discussion about missing "TIM2" when use with "time-driver-any".
In my opinion, we should pick the capable TIM with minimal function first, to avoid consume more-powerful/common-used TIM for time-driver.
Other changes:
1. `TIM11` is `TIM_1CH`, so not capable for time-driver
2. Add missing `TIM20`(ADV), `TIM23`(GP32), `TIM24`(GP32) for candidators
3. `TIM_ADV` can also be use as time-driver (but yes, should be last ones to pick)
> Add missing TIM for time-driver; reorder time-driver selection when use "time-drvier-any"

- embassy-time/src/delay.rs
Seems like there isn't a reason not to do this :). It's already possible with a new type, see [this](https://github.com/MabezDev/embedded-fatfs/pull/20/files#diff-7213147062427ea584e8ccf1d7774b5567474d65bc02a9547fb4f444b6503014R99-R120).
> time: cloneable delay

- embassy-rp/src/gpio.rs
I just happened to read this.
I think it's a typo in #1728.
Original change:
https://github.com/embassy-rs/embassy/pull/1728/files#diff-f1f6b8e9c6e1d28058169a0a521287b2f9875e96e2cd7a9a5f7216f0139e5534L639-L645
> rp: Fix wrong io _bank calc

- embassy-nrf/src/gpio.rs
- embassy-nrf/src/spim.rs
Makes nrf SPIM pin drives configurable, similar to the TWIM peripheral.
Apparently, high drive messes up interfacing with 3-wire SPI.
> feat(nrf/spim): allow specifying drive of SPI pins

- embassy-hal-internal/src/peripheral.rs
- embassy-stm32/src/dma/bdma.rs
- embassy-stm32/src/dma/dma.rs
- embassy-stm32/src/dma/dmamux.rs
- embassy-stm32/src/dma/gpdma.rs
- embassy-stm32/src/timer/mod.rs
if you have `PeripheralRef<'a, AnyPIn>` for pin A, and `AnyPin` (owned) for pin B, you can `mem::swap` them.
so, getting access forever to pin A, just by "sacrificing" pin B
this defeats the point of PeripheralRef, which is if you got a `PeripheralRef<'a, T>` then you're only allowed to use the peripheral for `'a`.
Also some drivers rely on the fact only one instance of a singleton exists for soundness, so this is a soundness fix for those.
> hal-internal: remove impl DerefMut for PeripheralRef.

- embassy-stm32/src/usb/usb.rs
Confirmed to be needed on an STM32L422, and based on a quick look at L4/L4+ reference manuals, this bit is present and required to be set on all L4 chips that have some kind of USB peripheral (USB or OTG_FS). The `usb_otg` driver already sets it for `cfg(stm32l4)` and we should do the same thing here.
> USB needs PWR_CR2 USV set on STM32L4

- embassy-hal-internal/src/atomic_ring_buffer.rs
- embassy-nrf/src/buffered_uarte.rs
- embassy-nrf/src/uarte.rs
- tests/nrf52840/src/bin/buffered_uart.rs
- tests/nrf52840/src/bin/buffered_uart_full.rs
- tests/nrf52840/src/bin/buffered_uart_halves.rs
- nrf/buffered_uart: simplify split lifetimes.
- nrf/uart: add split_by_ref.
- nrf/buffered_uart: refactor so rx/tx halves are independent.
> nrf/uart: add support for tx-only and rx-only buffered uart.

- embassy-stm32/src/rcc/bd.rs
> stm32/rcc: workaround nonsense RAM suicide errata on backup domain reset.

- embassy-stm32/build.rs
- embassy-stm32/src/rcc/f013.rs
- embassy-stm32/src/rcc/mod.rs
- examples/stm32f3/src/bin/usart_dma.rs
- examples/stm32f334/src/bin/pwm.rs
Things still to do:
Opening the PR now to get basic feedback.
Documents Referenced:
- [RM0313](https://www.st.com/resource/en/reference_manual/rm0313-stm32f37xxx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) STM32F37xx Chips - No TIMSW available
- [RM0316](https://www.st.com/resource/en/reference_manual/rm0316-stm32f303xbcde-stm32f303x68-stm32f328x8-stm32f358xc-stm32f398xe-advanced-armbased-mcus-stmicroelectronics.pdf) STM32F303xx/STM32F3x8xx Chips - Section 9.2.10
- [RM0364](https://www.st.com/resource/en/reference_manual/rm0364-stm32f334xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) STM32F334xx Chips - Section 8.2.10
- [RM0365](https://www.st.com/resource/en/reference_manual/rm0365-stm32f302xbcde-and-stm32f302x68-advanced-armbased-32bit-mcus-stmicroelectronics.pdf) …
> Enable PLL Clocks for TIMx peripherals on STM32F3xx Chips

- embassy-usb/Cargo.toml
- examples/nrf52840/Cargo.toml
- examples/nrf5340/Cargo.toml
- examples/rp/Cargo.toml
- examples/stm32g4/Cargo.toml
- examples/stm32l5/Cargo.toml
`usbd-hid` released 0.7.0, this PR updates embassy-usb, using latest `usbd-hid`
> Bump `usbd-hid` version to 0.7.0

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/time_driver.rs
- embassy-stm32/src/timer/mod.rs
I'm sure there's a great reason for this being omitted, typo included, <s>but the thing seems to work</s> [bit eager there] and I really need TIM2 & 3 free, sooooo
edit: PR's scope now includes correctly using the TIMx_CC interrupt source for advanced timers (TIM1/8/20)
> stm32: time_driver: allow use of TIM1 for driver

- embassy-nrf/Cargo.toml
Most of the other `Cargo.toml` files have been already bumped to 0.4.1, so follow along with embassy-nrf.
> nrf: Bump embedded-storage-async to 0.4.1

- embassy-nrf/src/spim.rs
Now that SPIM driver seems to have most features enabled, comment out the traces triggered when tx buffer needs to be copied into RAM.
> nrf: spim: Hide the "Copying SPIM tx buffer into RAM for DMA" traces

- embassy-stm32/src/can/fd/peripheral.rs
- standard ID is stored in ID[28:18] for TX and RX elements
- set BRS bit correctly in TX elements (only set it if transmitting a FD frame *and* the user specified BRS)
> stm32: can: fd: fix SID read/write and BRS setting for TX

- embassy-stm32/src/rcc/h.rs
Currently, using any clock other than the HSE with FDCAN causes hardfaults due to the FDCANSEL register not being set correctly.
See [Issue 2620](https://github.com/embassy-rs/embassy/issues/2620). 
This PR is not complete, as logic may still be needed to set the frequency correctly.
> adding FDCANSEL logic for STM32H7x

- docs/modules/ROOT/pages/getting_started.adoc
* Linked to probe.rs website rather than the crates.io page
* Fixed some formatting errors (>:( grrr asciidoc)
* Added cargo add probe-rs failure mode
* Added pico-w vs pico blinky failure mode
* Added pico probe probe-rs info failure mode
* Linked to new project guide page
> [docs] Added some failure modes to watch out for

- embassy-stm32/src/can/fd/peripheral.rs
https://github.com/embassy-rs/embassy/pull/2635 Did some nice refactoring however the combined reader function only declared an 8 byte data buffer as per ClassicCan instead of the larger 64 byte that is needed in order to receive full-sized CAN FD frames.
> Buffer is not big enough for FD frames.

- docs/modules/ROOT/pages/basic_application.adoc
I forgot to edit one broken reference in #2641. This PR amends this change. #2641 was closed before i noticed the mistake. Sorry! :)
> docs: update broken reference in basic_application.adoc

- embassy-stm32/src/can/fdcan.rs
- examples/stm32g4/src/bin/can.rs
Writing to TX buffer also needs to fire an interrupt to kick off transmission if it is idle.
> Give CAN a kick when writing into TX buffer via sender.

- embassy-stm32/src/can/fd/config.rs
- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/fdcan.rs
Uses enum in pac introduced here: embassy-rs/stm32-data#429
Based on : https://github.com/embassy-rs/embassy/pull/2632
with added fix.
> stm32: can: fd: allow TX buffers in FIFO mode

- embassy-sync/src/channel.rs
I think that doing
```rust
let s = c.dyn_sender();
```
is a bit more ergonomic than
```rust
let s: DynamicSender<'_, _> = c.sender().into();
```
> Add constructor for dynamic channel

- embassy-stm32/Cargo.toml
- embassy-stm32/src/rcc/c0.rs
- embassy-stm32/src/rcc/g0.rs
- embassy-stm32/src/rcc/g4.rs
- examples/stm32g0/src/bin/hf_timer.rs
- examples/stm32g4/src/bin/adc.rs
- examples/stm32g4/src/bin/can.rs
- examples/stm32g4/src/bin/pll.rs
- examples/stm32g4/src/bin/usb_serial.rs
- tests/stm32/src/common.rs
for #2515
- **stm32/rcc: g4: consistent PllSource**
- **stm32/rcc: port g0 to new api.**
- **stm32/rcc: port c0 to new api. Add c0 HSIKER/HSISYS support.**
> stm32/rcc: port g0, c0 to new api. Add c0 HSIKER/HSISYS support.

- embassy-boot-nrf/src/lib.rs
- embassy-boot-rp/src/lib.rs
- embassy-boot-stm32/src/lib.rs
This way, we can choose to continue booting even if there's an issue with external flash, for example.
> Add support for handling bootloader setup failure in `embassy-boot`

- embassy-sync/src/zerocopy_channel.rs
Even though you can borrow() senders and receivers, they are borrow'ed &mut, so you cannot use more than one. And looking at the fn send implementation, it doesn't look like multiple senders would be safe, as it would hand out the same &mut slice to two senders? I've gone through this a few times in my head now and reached the same conclusion, but happy to be proven wrong!
(Specifically:  https://github.com/embassy-rs/embassy/blob/main/embassy-sync/src/zerocopy_channel.rs#L129)
> docs: clarify capabilities of zerocopy channel

- ci.sh
- examples/stm32f4/src/bin/rtc.rs
- examples/stm32h7/src/bin/rtc.rs
- examples/stm32l4/src/bin/rtc.rs
- examples/stm32wl/src/bin/rtc.rs
- ~cortex-m4 and cortex-m7 of stm32 chips have hardware float~ add a note about hf thing
- stm32f0 should be thumbv6m
- ~[stm32-metapac update need] stm32wl5, stm32wb35 and stm32wb55 are mix dual core chip (cortex-m4 & cortex-m0+)~
- remove some extra whitespace
> ci stm32: build target fix

- embassy-stm32/src/can/fd/config.rs
- embassy-stm32/src/can/fdcan.rs
This is gonna be a draft for the minute as I want to figure something out.
Does it make sense to possibly return `BusError` when the user requests a read? If so, the current impl isn't quite right, because some of the error states are persistent (particularly the Error Active -> Error Passive -> Bus Off states). If we're gonna return `BusError` upon read, I think it should only be from the LEC (last error code), as its bit field resets upon read.
Other error statuses should be accessible through other means.
Suggestions welcome. @cschuhen @Dirbaio
> stm32: fdcan: merge read impls, add setter for TxBufferMode, rename Queue -> Priority

- embassy-stm32/src/rcc/c0.rs
The HSI frequency should be 48 MHz, not 16. I checked the datasheets for both STM32C011x4/x6 and STM32C031x4/x6.
> Update stm32c0 HSI frequency

- embassy-stm32/src/timer/mod.rs
- embassy-stm32/src/timer/simple_pwm.rs
PR #2499 implemented timer hierarchy, but removed enable_outputs() from trait CaptureCompare16bitInstance and from SimplePwm.
This functions is required for advanced timers to set bit BDTR.MOE and to enable the output signal.
> STM32 SimplePwm: Fix regression and re-enable output pin

- embassy-stm32/src/rcc/h.rs
> Fix incorrect D1CPRE max for STM32H7 RM0468

- .vscode/settings.json
I personally don't like using _format on save_. I also personally hit ctrl+s after basically every character I type. Other people use editors differently and have different preferences. That's why we let people choose what they prefer and not force it upon them when they open this repository in code.
> Remove personal preferences regarding editor settings

- embassy-stm32/Cargo.toml
Pulls in https://github.com/embassy-rs/stm32-data/pull/433 https://github.com/embassy-rs/stm32-data/pull/434 https://github.com/embassy-rs/stm32-data/pull/435
> stm32: bump metapac version

- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/dma/mod.rs
- embassy-stm32/src/sdmmc/mod.rs
Adds DMA request priority as transfer option, while maintaining the current setting of `VERYHIGH` as the default.
Currently, all DMA transfers are set to the highest priority level and is not configurable. This is acceptable for most use cases but there are cases where priority must be configured for peripheral DMA to work properly, such as the CRYP peripheral. From ST manual RM0410:
> It is important that DMA controller empties the cryptographic processor output FIFO before filling up the cryptographic processor input FIFO. To achieve this, the DMA controller should be configured so that the transfer from the cryptographic peripheral to the memory has a higher priority than the transfer from the memory to the cryptographic peripheral.
> Configurable DMA Request Priority

- embassy-stm32/src/spi/mod.rs
Previously it would panic with message "unreachable", which isn't particularly clear about what the problem is and how to fix it.
> Improve panic message when requesting frequency higher than clock

- embassy-stm32/src/lib.rs
Config option to disable the dead battery behaviour on UCPD parts. Option since if you're using UCPD you need to configure that first before disabling (which will probably be done in the driver). also disables unconditionally on G070 and G0B0 since they aren't supposed to have UCPD but do have this feature.
cc @timokroeger but this doesn't depend on the UCPD driver
> stm32: add disable_ucpdx_dead_battery

- embassy-stm32/build.rs
- embassy-stm32/src/cryp/mod.rs
- examples/stm32f7/src/bin/cryp.rs
- tests/stm32/src/bin/cryp.rs
- tests/stm32/src/common.rs
Adds async CRYP API using DMA for STM32. STM32F7 example is updated to use async API. CRYP test is updated so that encryption occurs in blocking mode, then decryption occurs in async mode.
> STM32 CRYP DMA

- embassy-stm32/build.rs
- embassy-stm32/src/lib.rs
- embassy-stm32/src/ucpd.rs
- examples/stm32g4/src/bin/usb_c_pd.rs
Draft until my [hardware for testing arrives](https://www.cnx-software.com/2024/03/01/weact-stm32g4-tiny-board-stm32g4-mixed-signal-microcontroller/).
> STM32 USB Type-C/USB Power Delivery Interface (UCPD)

- embassy-embedded-hal/src/adapter/blocking_async.rs
According to https://github.com/rust-embedded-community/embedded-storage/blob/master/src/nor_flash.rs#L191, `MultiwriteNorFlash` trait adds nothing to `NorFlash`, it should be safe to impl `MultiwriteNorFlash` for `BlockingAsync`
> Impl `MultiwriteNorFlash` for `BlockingAsync`

- embassy-stm32/build.rs
Was looking through the RCC codegen when I was nerdsniped by the mention of an errata. After a bit of digging into it I discovered the situation already well described here: http://efton.sk/STM32/gotcha/g183.html including some forum posts where people have actually had issues: to be clear I haven't, and wasn't able to repro anything after some trying on my STM32G071, but that may be because that chip is too slow and/or simple. The only attempt at an Actually Correct implementation I found was here: https://community.st.com/t5/stm32-mcus-embedded-software/stm32-clock-and-delay-helper-functions/td-p/593082
Currently embassy-stm32 only mitigates this with a DSB on STM32F2: if nothing else it should be doing that on all chips since this is an errata on more chips than just F2 and a feature …
> stm32/rcc: wait for peripheral clock to be active. also, hold the peripheral reset while enabling the clock.

- embassy-embedded-hal/src/shared_bus/blocking/i2c.rs
This implements `transaction()` for the blocking `I2cDevice` in `embassy-embedded-hal` in the same way that the remaining methods from the `I2c` trait are forwarded to the underlying bus.
It mirrors the already existing forwarding of `transaction()` in the implementation of the asynchronous `I2cDevice`.
This is part of an upcoming series of PRs that may eventually solve #1417.
> Forward transaction() from blocking I2cDevice to underlying bus

- embassy-stm32/src/i2c/mod.rs
- embassy-stm32/src/i2c/v1.rs
- embassy-stm32/src/i2c/v2.rs
This implements blocking transactions for I2C v1 in `embassy-stm32`. The implementation follows the [transaction contract](https://docs.rs/embedded-hal/latest/embedded_hal/i2c/trait.I2c.html#tymethod.transaction), laid out by `embedded-hal`, i.e. merging consecutive operations of the same type.
The idea of using frame options to re-use the same basic building blocks for reading and writing is inspired by the [STM32CubeF2](https://www.st.com/en/embedded-software/stm32cubef2.html) HAL. This should allow us to extend this PR in a straightforward way to the implementation of asynchronous transactions.
The implementation was tested for all combinations of merged and non-merged read/write operations on an STM32F2 dev board ([NUCLEO-F207ZG](https://www.st.com/en/evaluation-tools/nucleo-f207zg.htm …
> stm32/i2c(v1): Implement blocking transactions

- embassy-stm32/Cargo.toml
- embassy-stm32/src/time_driver.rs
- embassy-stm32/src/timer/mod.rs
Commit https://github.com/embassy-rs/stm32-data/commit/cc525f1b252c91272529cbea1d3d4399b43c60b4 has changed the definition of the `psc` register.
Update timer/mod.rs to and time_driver.rs reflect the stm32-data change.
Fixes #2698
> stm32: Fix psc compile error with current stm32-data

- embassy-sync/Cargo.toml
Currently, using `embassy-sync` in unit tests on a non-embedded platform will result in linker errors when using the `CriticalSectionRawMutex`.
Without forwarding this feature, the user needs to understand that `embassy-sync` uses the `critical-section` crate, and add a dependency on it just to enable the feature.
With this change, users can just enable the `"std"` feature in a dev dependency on `embassy-sync`, and the linker error will be resolved.
> Forward the "std" feature to the critical-section crate in embassy-sync.

- embassy-embedded-hal/src/shared_bus/asynch/i2c.rs
- embassy-embedded-hal/src/shared_bus/asynch/spi.rs
- embassy-embedded-hal/src/shared_bus/blocking/i2c.rs
- embassy-embedded-hal/src/shared_bus/blocking/spi.rs
Some devices (sd cards is where I ran into it) require a slow/standard speed for initialization, then can go up to a higher speed.
> embassy-embedded-hal: Allow changing Spi/I2cDeviceWithConfig's config at runtime

- embassy-stm32/src/gpio.rs
- embassy-stm32/src/lib.rs
- examples/stm32l4/src/bin/spe_adin1110_http_server.rs
- tests/stm32/src/common.rs
On STM32L4[7-A]xx, STM32L5xxx and STM32U5xxx chips, the GPIOG[2..15] pins are only available once the IOSV bit has been set in PWR->CR2 (U5 chips have the bit in a funkier register).
This is meant to allow the user to have control over this power supply, so the GPIOG pins are initially insulated, until the user wishes to un-insulate them (or something like that?). For most applications, though, the VDDIO2 line is connected to the VDD line, and this behavior only gets in the way and causes confusing issues.
This PR adds an option in `embassy_stm32::Config`, called `enable_independent_io_supply`, which simply enables the IOSV bit. It is only available on chips for which I could find a mention of IOSV (STM32L4 and STM32L5) or IO2SV (STM32U5).
-----
This part of the behavior of the L4 chips …
> Add a config option to make the VDDIO2 supply line valid

- embassy-stm32/src/rcc/bd.rs
see ES0565 2.2.17 LSE low drive mode is not functional.
"The LSE oscillator may not start or may stop in low drive mode (LSEDRV = 00). Using this mode is forbidden."
> stm32 H5: LSE low drive mode is not functional

- embassy-stm32/src/usart/mod.rs
Weakens the requirement `TxDma: self::TxDma<T>` in the implementation of `embedded_io::Write` for both `Uart` and `UartTx`.
Provides implementations for `embedded_io::Read` for `Uart` and `UartRx`, as well as `embedded_io_async::Read`, bringing it to parity with `BufferedUart`.
These changes seem to be sufficient to make the blocking and async APIs available together in mixed scenarios, like in #2072.
Fixes #2072
> Provide embedded_io impls for Uart with and without Dma

- embassy-stm32/src/can/bx/mod.rs
This PR ensures that the RTR flag is respected when taking frames out of a mailbox or FIFO of a bxcan peripheral.
Without this PR, all frames are reported as data frames. With this PR, remote transmission requests are reported as such.
> embassy_stm32: Preseve the RTR flag in messages.

- embassy-stm32/src/can/bx/mod.rs
- embassy-stm32/src/can/bxcan.rs
- embassy-stm32/src/can/common.rs
- embassy-stm32/src/can/enums.rs
- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/fdcan.rs
- embassy-stm32/src/can/frame.rs
- examples/stm32f1/Cargo.toml
- examples/stm32f1/src/bin/can.rs
- examples/stm32g4/src/bin/can.rs
- examples/stm32h5/src/bin/can.rs
- examples/stm32h7/src/bin/can.rs
- tests/stm32/src/bin/can.rs
- tests/stm32/src/bin/can_common.rs
- tests/stm32/src/bin/fdcan.rs
Now that both FDCAN and BXCAN are using stm32-metapac we can allow the same runtime features for both:
1. Same runtime API's
2. Same runtime features (optional interrupt+channel based FIFO)
3. Same Frame structure
Despite the branch name. This PR consists mainly of:
1. Preference for BXCAN API differences, because it has been out in the wild LOTS longer
2. Superset of features. i.e. more flexible buffering came from FDCAN.
> Synchronise the feature sets and API between BXCAN and FDCAN.

- embassy-sync/README.md
This pull request fixes a small typo in `embassy-sync`.
> Fix a typo in embassy-sync

- embassy-rp/src/pwm.rs
This pull request renames all the PWM data structures of RP2040 from `Channel` to `Slice`. It modifies the comments to reflect the renames. It follows #2762.
> rp2040: rename all usages of pwm channel to pwm slices

- embassy-sync/src/lib.rs
- embassy-sync/src/semaphore.rs
This provides both a "greedy" and "fair" async semaphore implementation.
> Semaphore synchronization primitive

- docs/modules/ROOT/pages/faq.adoc
Adds a FAQ entry for helping users when their `memory.x` definition is not correct or missing
> Update faq.adoc with memory.x definition helping hand

- embassy-rp/src/pwm.rs
- examples/rp/src/bin/pwm_input.rs
- tests/rp/src/bin/pwm.rs
I created this simple change that allows pin B (the one that can be used as PWM counter input) to be set with pull-up or pull-down internal resistor.
I made tests for two most important cases. I was thinking about adding extra test for checking if the input is floating by default, but it even in case of code being wrong test could on occasion pass so I decided not to add it:
```
// PWM input is floating by default
{
let pin2 = Input::new(&mut p11, Pull::Down);
let pwm = Pwm::new_input(&mut p.PWM_CH3, &mut p7, Pull::None, InputMode::FallingEdge, cfg.clone());
Timer::after_millis(1).await;
assert!(pin2.is_low());
}
{
let pin2 = Input::new(&mut p11, Pull::Up);
let pwm = Pwm::new_input(&mut p.PWM_CH3, &mut p7, Pull::None, InputMode::FallingEdge, cfg.clone());
Timer::after_millis(1).await; …
```
> Add parameter for enabling pull-up and pull-down in RP PWM input mode

- embassy-stm32/src/qspi/mod.rs
> stm32/qspi: autodeduce transfer len from buffer len.

- embassy-stm32/src/adc/v3.rs
Otherwise, predictably, reading on channel 0 gives nonsense
Tested on the H503
> stm32: adc: v3: [h5] set OR.OP0 to 1 when ADCx_INP0 is selected, per RM

- embassy-usb/src/builder.rs
Fix the comment about the default value: this defaults to 64 rather than 8 bytes.
It seems like the max packet size for endpoint 0 should normally be selected automatically, rather than being part of the config.  At best it seems like this setting should just be a hint that gets used if when the bus is operating at full speed.  The contents of the device descriptor should ideally be updated with the correct max packet size after bus enumeration completes.  In practice always using 64 is probably fine if low speed environments never need to be supported. (Super speed requires a max packet size of 512 bytes, which I didn't list in the comments here.)
> USB: fix comments about the config.max_packet_size_0 field

- embassy-stm32/src/rcc/mod.rs
This allows enabling/disabling peripherals in drivers outside embassy.
> Expose RCC enable and disable methods

- ci.sh
- embassy-stm32/Cargo.toml
- embassy-stm32/src/exti.rs
- embassy-stm32/src/rcc/l.rs
- embassy-stm32/src/rcc/mco.rs
- embassy-stm32/src/rcc/mod.rs
- examples/stm32u0/.cargo/config.toml
- examples/stm32u0/Cargo.toml
- examples/stm32u0/build.rs
- examples/stm32u0/src/bin/blinky.rs
- examples/stm32u0/src/bin/button.rs
- examples/stm32u0/src/bin/button_exti.rs
- **stm32/spi,crc: update for new PAC**
- **stm32/flash: remove otp flash regions (removed in newer metapacs).**
- **stm32/adc: update g4 for new pac.**
- **Add stm32u0 support.**
> Add STM32U0 support.

- .github/ci/test.sh
- embassy-futures/src/yield_now.rs
Running `cargo test` in embassy-futures was failing.  The `no_run` tag on this doc example caused it to still try and compile this example, just not run it, and compilation failed.  This updates the example so that it can successfully compile and run.
> Fix embassy-futures test failure

- embassy-nrf/CHANGELOG.md
Basic changelog with template borrowed from some other embassy project.
Not sure whether this project actually adheres fully to SemVer - GPIO generic change would immediately force us to push 1.0.0 version.
Also, it might make sense to group changes by peripheral.
> nrf: Add basic CHANGELOG summarizing changes in embassy-nrf

- .github/ci/test-nightly.sh
- embassy-sync/src/mutex.rs
As requested in https://github.com/embassy-rs/embassy/issues/2768#issuecomment-2038277704.
Personally, I have never ever created a synchronization primitive so I have no clue if this implementation is sound. Everything was basically a copy and paste from the `futures` crate.
The "sound" part should be double checked for the `Send` and `Sync` implementations.
> Add `map` method

- embassy-stm32/Cargo.toml
- embassy-stm32/src/flash/u5.rs
- examples/stm32u5/Cargo.toml
Hi, 
This pull request adds support for non-secure flash operations. 
In short, if TrustZone is active (TZEN option bit is 1), it uses secure operations (as before), otherwise it will use non-secure operations. 
As a word of caution, this doesn't handle all flash configurations when TrustZone is active. For instance, one can configure watermark-based flash memory protection to designate areas as secure or non-secure. Per section 7.5.1, Table 58., the default configuration when TZEN =1, is that all flash memory is secure. We could expand on this by checking SECWMx_PSTRT and SECWMx_PEND to determine whether one is operating on secure or non-secure flash memory. Though, I figure this might be worthy a discussion.
I tested the existing stm32u5/flash.rs example on a NUCLEO-U575ZI-Q board with …
> Support non-secure flash operations on STM32U5

- embassy-stm32/src/flash/h50.rs
Depends on pac changes: https://github.com/embassy-rs/stm32-data/pull/463
Questions for reviewers:
1. I copied and modified routines in `h50.rs` from other flash impls like `g.rs`. Why, in these, are certain functions labelled `unsafe` despite no obvious memory safety issues? For example, my `perform_bank_swap()` requires an unsafe block for `clear_all_err()` because that function is labelled unsafe, for whatever reason.
2. Should I be peppering `fence(Ordering::SeqCst);` between reg accesses in functions like `perform_bank_swap()`?
3. Any concerns with the approach of having `pub` bank-swap-related functions in this family-specific file? I want these accessible by applications.
> stm32: flash: h50: implement bank swapping

- docs/modules/ROOT/pages/faq.adoc
Adds some commonly encountered issues.
Help wanted: if anyone has a working BDMA linker script setup, it would be good to add here.
> FAQ: Common STM32 stumbling blocks

- embassy-stm32/src/adc/mod.rs
e.g. H503 running at 250 MHz resulted in an upper bound of 17 us here (causing panic in `v3.rs`). casting up to u64 for intermediate calc allows the upper bound to be increased by a factor of 1e6
> stm32: adc: fix blocking_delay_us() overflowing when sys freq is high

- embassy-stm32/src/adc/g4.rs
The max number of channels for the ADCs in STM32G4 MCUs is 18 instead of 20, this is causing panic behaviour in smt32-metapac.
> Bug: There are at most 18 channels for the STM32G4 ADCs.

- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/fdcan.rs
FDCAN has no automatic bus-off recovery, see RM0492 p. 1600:
Also cleaned up the interrupt handler a little
> stm32: can: fd: implement bus-off recovery

- embassy-rp/src/pio/mod.rs
Accidentally calling `pull` on an empty RX FIFO can lead to difficult to debug errors.
I wonder if the `pull` function should be removed / deprecated, with a suggestion to use `try_pull` instead? As that would obviously be a breaking change, this PR only adds a hint to the doc comment for now.
> Add a comment to the pio rx fifo pull function

- embassy-stm32/src/can/bxcan/mod.rs
- embassy-stm32/src/can/bxcan/registers.rs
I've stumbled across an issue with the bxCAN async implementation, whereby if in a loop you are polling read() for events, and an error exists on the bus (any error), you end up with a situation where the processor will never sleep and is instead caught in an infinite loop of returning the same CAN peripheral error(s).
The issue is the current_error function returns a value if there is any errors set in the ESR register. However, that register is read only, and those errors persist until either the peripheral is reset, or the condition causing the error on the bus has been resolved and the TEC/REC counters are decremented via the successful reception/transmission of messages. 
Ideally, I believe the curr_error fn should only return an error if the ERRI flag is set in the MSR, at which …
> Fix CAN error handling

- embassy-usb/src/class/hid.rs
- examples/nrf52840/src/bin/usb_hid_keyboard.rs
- examples/nrf52840/src/bin/usb_hid_mouse.rs
- examples/rp/src/bin/usb_hid_keyboard.rs
- examples/rp/src/bin/usb_hid_mouse.rs
- examples/stm32f4/src/bin/usb_hid_keyboard.rs
- examples/stm32f4/src/bin/usb_hid_mouse.rs
- examples/stm32l5/src/bin/usb_hid_mouse.rs
Goal is to be able to act upon an outside report.
For example a report could show that CapsLock and NumLock are on, but we may only want to do an action if there is a change in those states. This can be done by keeping and comparing with a previous report in the RequestHandler.
I've updated the examples that were using that API.
> usb::hid::RequestHandler::set_report(&mut self, ...)

- docs/modules/ROOT/pages/embassy_in_the_wild.adoc
add [RMK](https://github.com/haobogu/rmk) to embassy in the wild 💓
RMK is a keyboard firmware project which based on embassy.
> doc: add RMK to embassy in the wild

- examples/rp/src/bin/pio_pwm.rs
- examples/rp/src/bin/pio_servo.rs
Two additional `rp` examples were added: `pio_pwm.rs`, a bare-metal example of how to do PWM with pio, and `pio_servo.rs`, a more extended example of PWM and pio with servos.
It is pretty common for people to wish to use Servos with their devices, but most people do not wish for the main cores to be kept busy running a servo or other PWM devices. So, these examples utilize the powerful PIO features of the RP2040 to do PWM instead of using the built-in PWM to prevent this from being an issue. These examples give further inspiration to others who wish to implement other things using PIO.
> Added PIO pwm examples for rp

- docs/modules/ROOT/pages/sharing_peripherals.adoc
- docs/modules/ROOT/pages/time_keeping.adoc
This is mostly so that when someone comes into this project sideways (they are linked into the document directly, into a section that has a code example) they have context so they know what they need to build the project correctly.
> Link back to Cargo.toml section.

- embassy-stm32/src/usb/otg.rs
- embassy-usb-synopsys-otg/src/lib.rs
The first two commits regroup things to hopefully eliminate some bounds checks. The third commit makes the max EP count configurable. Unfortunately we can't use a flavour-trait, doing so would require generic const exprs I believe, or is straight impossible. I believe this solution is more flexible than a cfg feature as it gives more control to HAL authors.
> Synopsys: Make max EP count configurable

- embassy-stm32/src/timer/low_level.rs
Fixes off-by-one ARR value for 32 bit timers. Now the code is consistent with [16bit timers](https://github.com/ftk/embassy/blob/e7bfd7bac90d254ea6dee408564d5e0f8a80ca19/embassy-stm32/src/timer/low_level.rs#L245)
> stm32 timer: fix 32bit timer off by one ARR error

- embassy-usb/src/builder.rs
- embassy-usb/src/class/mod.rs
- embassy-usb/src/class/web_usb.rs
- examples/rp/src/bin/usb_webusb.rs
I created an implementation for the WebUSB spec that can be found here: https://wicg.github.io/webusb/.
This is a rough draft and I just wanted to get a feel for whether you'd be willing to consider this functionality as a part of embassy.
I tried to stay as close to the current class implementations as possible and use existing APIs as much as I could (there's a notable exception - `bos_capability`, see the comment below).
If you feel like this would be a valuable addition, I'll clean it up a bit more and add documentation for it.
> WebUSB implementation

- cyw43/src/control.rs
With flags = 0 in PassphraseInfo, CYW firmware skips the PBKDF2 PSK derivation. This makes it possible avoid storing unhashed passwords.
The wpa_passphrase utility may be used to generate this PSK.
> cyw43: Add function to join WPA2 network with precomputed PSK.

- embassy-stm32/src/dac/mod.rs
The `DacChannel::new` (and `new_internal`) methods set HFSEL, (set the internal mode), and enable their channel, but the `Dac` two-channel version just creates the `DacChannel` without calling `new()`, so we need to set those properties appropriately.
> stm32: dac: fix new_internal not setting mode as documented

- embassy-stm32/src/timer/low_level.rs
When working with the low-level timer, it's often necessary to know the clock frequency that is fed into the timer, to correctly set values of ARR and CCR registers, in cases where the existing covenience methods are not sufficient.
(My use case is generating four one-shot pulses of different widths on the four timer channels to control an RC servo.)
> stm32/timer: add `low_level::Timer::get_clock_frequency()`

- embassy-net/Cargo.toml
As far as I can tell those are not used anymore.
> Removes some unused dependencies in embedded-net.

- embassy-net/src/tcp.rs
> impl ReadReady for tcp call can_recv() insted of may_recv()

- embassy-hal-internal/src/peripheral.rs
- embassy-stm32/src/ucpd.rs
Fix soundness issue introduced in a previous soundness fix https://github.com/embassy-rs/embassy/pull/2602 .
PeripheralRef must not implement DerefMut itself, but the blanket impl must still require DerefMut. Otherwise
you can create two instances of a driver on the same uart by using `&my_uart`.
> Fix PeripheralRef soundness issue allowing &T.

- examples/stm32h7rs/Cargo.toml
Current name clashes with "regular" stm32h7 thus generating cargo warning:
```
warning: skipping duplicate package `embassy-stm32h7-examples` found at ...
```
> stm32: examples: Use unique crate name for stm32h7rs examples

- examples/rp/Cargo.toml
- examples/rp/src/bin/interrupt.rs
By request, this example shows how you can use raw interrupt handlers alongside embassy.
The example also showcases some of the options available for sharing resources/data within the application.
> rp: Add raw interrupt handler example

- examples/rp/Cargo.toml
- examples/rp/src/bin/spi_sdmmc.rs
We've been getting quite a few questions regarding how to use embedded-sdmmc together with embassy-rp lately (there seems to be some confusion around how to make a SpiDevice), so thought i'd make a quick basic example of how to set it up.
Also shows how to reconfigure the underlying SPI bus to increase the SPI clock frequency after sd card initialization.
> rp: Add embedded-sdmmc example

- examples/rp/src/bin/usb_serial.rs
IMO the usb serial example would be more realistic in running the usb stack in an embassy task.
> refactor rp usb_serial example to use a task to run the usb

- embassy-usb-synopsys-otg/src/lib.rs
- examples/stm32f4/src/bin/eth.rs
- examples/stm32f4/src/bin/usb_ethernet.rs
- examples/stm32f4/src/bin/usb_hid_keyboard.rs
- examples/stm32f4/src/bin/usb_hid_mouse.rs
- examples/stm32f4/src/bin/usb_raw.rs
- examples/stm32f4/src/bin/usb_serial.rs
- examples/stm32f7/src/bin/eth.rs
- examples/stm32f7/src/bin/usb_serial.rs
- examples/stm32h7/src/bin/eth_client.rs
- examples/stm32h7/src/bin/eth_client_mii.rs
- examples/stm32h7/src/bin/usb_serial.rs
- examples/stm32h7rs/src/bin/i2c.rs
- examples/stm32l4/src/bin/usb_serial.rs
- examples/stm32u5/src/bin/usb_serial.rs
- **examples/stm32: reduce packet queue count to avoid OOM on smaller chips.**
- **embassy-usb-synopsys-otg: default vbus_detect to false.**
- **examples/stm32: do not enable vbus detect by default, it doesn't work on all boards.**
- **examples/stm32h7rs: add i2c example.**
> Fix misc example papercuts.

- embassy-rp/src/usb.rs
This implements endpoint stalling for `embassy-rp` - the current use-case being that Windows will stall a USB MSD implementation, possibly due to implementation error, or possibly while it's probing the device. This allows us to continue past the stall, rather than panicking.
Tested by running this on a pico implementing a MSD - interested to hear if there are other approaches to testing USB implementations (particularly stalls / error handling).
> rp: implement usb stall

- embassy-rp/src/clocks.rs
> In the start_xosc function, the frequency range is set twice. 

- examples/stm32g0/src/bin/i2c_async.rs
This example will help those having difficulties understanding how to bind interrupts on stm32g0 devices.
> stm32g0: add i2c_async example

- embassy-rp/src/flash.rs
The documented requirement for this marker trait are the same for the [blocking](https://docs.rs/embedded-storage/latest/embedded_storage/nor_flash/trait.MultiwriteNorFlash.html) and [async](https://docs.rs/embedded-storage-async/latest/embedded_storage_async/nor_flash/trait.MultiwriteNorFlash.html) versions so I assume it is fine to implement this even though the RP2040 doesn't support asynchronously writing to the flash.
> rp/flash: implement `embedded_storage_async::nor_flash::MultiwriteNorFlash`

- embassy-sync/CHANGELOG.md
- embassy-sync/src/channel.rs
- embassy-sync/src/priority_channel.rs
- embassy-sync/src/pubsub/mod.rs
Until now, only `Pipe` had all functions to return the capacity and amount of filling. This PR adds the missing functions to Channel, PriorityChannel and PubSubChannel so that all of them have a consistent API.
> Consistent functions for Channel, PriorityChannel and PubSubChannel to return capacity and filling

- embassy-embedded-hal/src/shared_bus/asynch/spi.rs
- embassy-embedded-hal/src/shared_bus/blocking/spi.rs
It's not particularly complicated, this allows to be more in line with other implementations like ExclusiveDevice which also has an u16 word size
> Make SpiDevice generic over Word size and implement u16 transfer

- README.md
- docs/modules/ROOT/pages/hal.adoc
- docs/modules/ROOT/pages/index.adoc
ch32-hal is at an early stage of development.
Supported chips are listed at https://github.com/ch32-rs/ch32-hal
An stm32-data clone for all the chips is at https://github.com/ch32-rs/ch32-data
> Add ch32-hal to HAL list, support WCH's CH32V family

- .vscode/settings.json
- embassy-usb-synopsys-otg/src/lib.rs
This restores the Send/Sync impls for EpState, which were incidentally removed in https://github.com/embassy-rs/embassy/pull/2881. This allows the Endpoints to be sent to tasks, e.g. as part of a custom class implementation.
Fixes #2957
> embassy-usb-synopsys-otg: impl Sync for EpState

- cyw43/src/runner.rs
- embassy-sync/CHANGELOG.md
- embassy-sync/src/pubsub/mod.rs
- embassy-sync/src/pubsub/publisher.rs
- embassy-sync/src/pubsub/subscriber.rs
Exposes the new length functions on the pubs and subs and seals the pubsubbehavior trait (which users shouldn't (need to) touch).
I guess there's more to clean up or at least things I'd have made different now, but there's nothing that really *needs* more work.
For posterity:
- I think it's weird that `DynSubscriber<T>` and `Subscriber<T>` both deref as `Sub<Channel, T>`.
- Same for publisher
- I'd make the shared functions into a trait and let each of the higher level types implement those traits
- This would be a breaking change, but likely one that doesn't break anyone
> Pubsub cleanup

- embassy-stm32/build.rs
- embassy-stm32/src/i2c/mod.rs
- embassy-stm32/src/i2c/v1.rs
- embassy-stm32/src/i2c/v2.rs
- embassy-stm32/src/i2s.rs
- embassy-stm32/src/macros.rs
- embassy-stm32/src/rcc/mod.rs
- embassy-stm32/src/spi/mod.rs
- examples/stm32h7/src/bin/i2c_shared.rs
- examples/stm32l4/src/bin/spe_adin1110_http_server.rs
- **stm32/rcc: add ClockEnableBit struct.**
- **stm32/spi: remove peripheral generic param.**
- **stm32/spi: check that the RCC enable bit is disabled on drop.**
- **stm32: use funcs for info/state, const for ENABLE_BIT.**
- **stm32/i2c: remove peripheral generic param.**
> stm32/i2c: remove peripheral generic param.

- embassy-sync/src/channel.rs
- embassy-sync/src/pipe.rs
- embassy-sync/src/priority_channel.rs
- embassy-sync/src/waitqueue/multi_waker.rs
Clippy issued some warnings mainly about the implementation of `Clone`. This PR fixes them by applying the suggested changes.
> embassy-sync: fixed some clippy warnings

- embassy-stm32/src/usart/mod.rs
CC #2875
I make Uart with Half-Duplex mode, `write` ~16 bytes, then call `blocking_flush`, then call `read_until_idle`. No other side, only pull up.
As result I get ~7 last bytes which was sent over `uart.write`.
I did a little research and found out that the TC flag works correctly. It this is confirmed by tests also.
> When the last data is written to the USART_TDR register, wait until TC = 1.
–When FIFO mode is disabled, this indicates that the transmission of the last frame
is complete.
–When FIFO mode is enabled, this indicates that both TXFIFO and shift register are
empty.
Possible it is errate, but I not found it within official errata.
Now I clear [cr1.re](https://github.com/embassy-rs/stm32-data-generated/blob/main/stm32-metapac/src/peripherals/usart_v4.rs#L81) flag before …
> Fix uart::flush with FIFO at Half-Duplex mode

- embassy-stm32/Cargo.toml
- embassy-stm32/src/hsem/mod.rs
- embassy-stm32/src/lib.rs
Requires https://github.com/embassy-rs/stm32-data/pull/450
> HSEM support for embassy-stm32

- README.md
- cyw43/README.md
> Remove "cargo install probe-rs", point users to probe.rs instead.

- embassy-rp/src/pwm.rs
- examples/rp/src/bin/interrupt.rs
This is based on the conversation on Element with @Dirbaio to the problem of being able to add different PWM stucts withing the same array.
https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$fJxGz19y7xLRKlmtc-wOyqP-IXiaZ5IPY5OxoWwwFL4?via=matrix.org&via=tchncs.de&via=grusbv.com
Essentially:
```rust
let mut pwm_config = Config::default();
// Initial PWM duty cycle (bightness) - Range 0.0 (0) to 1.0 (65535)
let duty_cycle = 0.5;
pwm_config.compare_b = (duty_cycle * u16::MAX as f32) as u16;
// (<LED ID>, <LED PIN>, <LED KIND>, <HANDLE>)
let leds = [
(
0,
0,
"pwm",
Pwm::new_output_a(slices.slice0, leds.led0, pwm_config),
),
(
1,
6,
"pwm",
Pwm::new_output_a(slices.slice1, leds.led1, pwm_config),
),
(
2,
7,
"pwm",
Pwm::new_output_a(slices.slice2, leds.led2, pwm_config),
),
(
3,
8,
"pwm", …
```
> Remove Generics from `embassy-rp` `Pwm` struct

- embassy-stm32/src/rcc/f247.rs
I'm working on a project with a bootloader that does it's things then jump to the main firmware, and I've got issues with the stm32 core locking up when the main firmware starts.
The issue is that both the bootloader and the main firmware are initializing the system clock to use a PLL (based on HSE clock).
When the main firmware starts, the core is already running using the PLL (setup by the bootloader), then the main firmware calls embassy_stm32::init() which setup the PLL by first turning it off (causing the CPU to stop running !!!) before setting it up and turning it on again.
With this patch, rcc::init() will first setup the core to run on the HSI clock, then do the whole clock setup, then switch the core to the requested clock (PLL, HSE...), and then turning off the HSI clock (if …
> stm32: ensure the core runs on HSI clock while setting up rcc

- embassy-stm32/src/rcc/l.rs
I have an STM32WLE5 module with no HSE, the official C demo code uses MSI range11. It worked with embassy about 1 year ago.  (ref: https://andelf.github.io/blog/2023/01/23/stm32wl-lora-with-rust-embassy/ )
Now after I porting the old code to the current embassy main branch, I got an error after BD is initiated:
```
ERROR probe_rs::architecture::arm::core::armv7m: The core is in locked up status as a result of an unrecoverable exception
```
The minimal reproduce code:
```rust
let mut config = embassy_stm32::Config::default();
{
use embassy_stm32::rcc::*;
config.rcc.msi = Some(MSIRange::RANGE48M);
}
let p = embassy_stm32::init(config);
```
After a year. So many new changes were merged. I had to look into the rcc part. The crash point is randomly located between LS init and FLASH setting. …
> Fix crash caused by using higher MSI range as sysclk on STM32WL

- examples/stm32l4/src/bin/can.rs
Hi,
Some notes:
1. I did my testing on an stm32l432kc device
2. I had to change the chip and target in the `.cargo/config.toml' to `thumbv7em-none-eabihf` and `STM32L432KCUx` (not checked in as doing so breaks other examples)
3. I had to change the embassy-stm32 feature from `stm32l4s5qi` to `stm32l432kc` in the `Cargo.toml` (same, not checked in as doing so breaks other examples)
4. I don't have a `stm32l4s5qi` device so there's no way for me to ensure this will work, but confidence is reasonably high
Hope this helps,
> Added a CAN example for the stm32l4

- embassy-sync/src/once_lock.rs
- embassy-sync/src/priority_channel.rs
- embassy-sync/src/pubsub/mod.rs
This PR fixes some typos in the documentation comments discovered by `typos-cli`.
> embassy-sync: fixed some documentation typos

- embassy-sync/CHANGELOG.md
- embassy-sync/src/channel.rs
- embassy-sync/src/priority_channel.rs
- embassy-sync/src/pubsub/mod.rs
- embassy-sync/src/pubsub/publisher.rs
- embassy-sync/src/pubsub/subscriber.rs
This PR adds a clear function to all channels that allows to delete all buffered elements. I'm not sure if this is a desired behaviour for the publishers and subscribers of the PubSubChannel, so request a change if there are concerns about it.
> embassy-sync: Add clear function to all channels

- embassy-stm32/src/adc/f1.rs
- embassy-stm32/src/adc/f3.rs
- embassy-stm32/src/adc/f3_v1_1.rs
- embassy-stm32/src/adc/g4.rs
- embassy-stm32/src/adc/mod.rs
- embassy-stm32/src/adc/v1.rs
- embassy-stm32/src/adc/v2.rs
- embassy-stm32/src/adc/v3.rs
- embassy-stm32/src/adc/v4.rs
- embassy-stm32/src/opamp.rs
- examples/stm32h7/src/bin/adc.rs
The main motivation for this was to allow for the use case of storing ADC channels in an array, which is difficult to do with the current API.
Summary of changes:
- Adds an `AdcChannel<T>` trait which contains a `fn setup` and `fn channel`. `fn channel` and `fn set_as_analog` is removed from `AdcPin`, and instead uses a supertrait. The logic for `set_as_analog` is moved to `fn setup`. This allows for a single `read` function for the ADC instead of having a separate `read_internal` function (in `g4.rs` and `v4.rs`)
- Places where an "internal channel" (like `Vref` or `Temperature`) implements `AdcPin` have been changed to implement `AdcChannel` instead.
- Adds the `AnyAdcChannel<T>` type, where `T` is an ADC instance. It implements `AdcChannel<T>`, which can be passed to `read`.
Even …
> stm32/adc: add AnyAdcChannel type

- embassy-stm32/src/usart/ringbuffered.rs
Closes https://github.com/embassy-rs/embassy/issues/2752
Unsatisfyingly, I don't know why this works or what has changed since the crates.io release. I have been poking at this for a while and I simply couldn't figure it out; I tried clearing sticky errors in all sorts of places but nothing worked. I would be interested if someone knows though.
It might also be valuable to test the min repro linked in the issue on some other chips as it might be a f2 specific thing.
> stm32 ringbuffered usart: don't teardown during reconfigure

- embassy-stm32/build.rs
- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
- examples/stm32h5/src/bin/usart_split.rs
- examples/stm32h7/src/bin/usart_split.rs
- examples/stm32h7rs/src/bin/usart_split.rs
- tests/stm32/src/bin/usart_rx_ringbuffered.rs
In Embassy, all driver structs (such as `UartRx` or `I2c`) are generic in the underlying peripheral. This has some disadvantages:
1. All higher-level drivers that wrap an underlying peripheral (for example, a driver for a gyroscope chip that wraps an `I2c` driver) must be generic in `T: BasicInstance`, which leads to a lot of clutter.
2. Code for the drivers and all higher-level code that uses them is duplicated for every instance of the peripheral. For example, if my code needs to work with two gyroscopes on two different I2C buses, all the code in the I2C driver and in the gyroscope driver will be duplicated.
3. It's not possible to specify the peripheral at runtime, the exact usage of all pins and peripherals [must be hard-coded](https://github.com/cbruiz/printhor/?tab=readme-ov-file#cu …
> stm32/usart: Remove BasicInstance generic

- embassy-stm32/src/gpio.rs
- embassy-stm32/src/macros.rs
Closes https://github.com/embassy-rs/embassy/issues/2942, where this was discussed in greater detail, along with alternatives.
Required for https://github.com/embassy-rs/embassy/pull/2943, so the correct config can be deduced from the registers.
> gpiov1: Do not call set_speed for AFType::Input

- embassy-stm32/src/can/bxcan/mod.rs
- embassy-stm32/src/can/bxcan/registers.rs
This PR allows you to enable FIFO scheduling of the transmit mailboxes. This can be quite important to ensure in-order delivery of data.
It also allows to avoid a weird gotcha between `flush_any()` and `try_write()`: when `flush_any()` completes, a call to `try_write()` may still report `TryWriteError::Full`. In one application I'm working on, this is very undesirable. I also updated the documentation, which previously said this could not happen.
The PR also relaxes the restriction for queuing frames in priority based scheduling mode. Previously, you could not queue a frame if another frame with equal **or higher** priority was already queued. This was more strict than necessary to work around the hardware scheduling limitation. The only thing that should be avoided is to have two …
> embassy_stm32: implement optional FIFO scheduling for outgoing frames

- embassy-rp/src/watchdog.rs
My first PR! As encouraged by @9names on Matrix, this is a PR to change `write()` calls to `modify()` when manipulating the rp2040's watchdog control register. Dumping out the registers after this change matches the expected behavior from the datasheet.
Previously, when calling a function like `watchdog.pause_on_debug()` or even `watchdog.start()` it would stomp on the register's previously set bits and potentially break the watchdog. If `start` was called after `pause_on_debug`, it would run but the bits set by `pause_on_debug` would be gone. Conversely, if `pause_on_debug` was called after `start`, it would also zero out the enable bit, thus pausing the watchdog (at least in terms of the behavior I've observed).
I've left the call to `write` in `trigger_reset` as is, because there is …
> Fix watchdog CTRL register getting overwritten

- embassy-stm32/src/gpio.rs
Simple addition to Flex to allow analog mode to be set. I need this bc the way I work with a comparator. Ideally this would be handled by a comparator driver but I didn't manage to write that.
A case could be made for exposing `set_as_disconnected` too which would do the same thing right now but be semantically different.
> add set_as_analog to stm32 gpio Flex

- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/fdcan.rs
- embassy-stm32/src/cryp/mod.rs
- embassy-stm32/src/dac/mod.rs
- embassy-stm32/src/dsihost.rs
- embassy-stm32/src/ltdc.rs
- embassy-stm32/src/rcc/f013.rs
- embassy-stm32/src/rtc/mod.rs
- embassy-stm32/src/rtc/v2.rs
- embassy-stm32/src/rtc/v3.rs
in chiptool pacs the register block struct is already a pointer, so
using pointers to it is redundant.
> stm32: remove pointer-to-pointer-to-registers.

- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/fdcan.rs
- embassy-stm32/src/cryp/mod.rs
- embassy-stm32/src/dac/mod.rs
- embassy-stm32/src/dsihost.rs
- embassy-stm32/src/ltdc.rs
- embassy-stm32/src/rcc/f013.rs
- embassy-stm32/src/rtc/datetime.rs
- embassy-stm32/src/rtc/low_power.rs
- embassy-stm32/src/rtc/mod.rs
- embassy-stm32/src/rtc/v2.rs
- embassy-stm32/src/rtc/v3.rs
- **stm32: remove pointer-to-pointer-to-registers.**
- **stm32/rtc: move lowpower stuff to a separate mod.**
> stm32/rtc: move lowpower stuff to a separate mod.

- embassy-stm32/src/can/bxcan/mod.rs
- embassy-stm32/src/can/bxcan/registers.rs
- examples/stm32f7/src/bin/can.rs
- tests/stm32/src/bin/can.rs
Remove generics from most of the BXCAN structs. Not removed from the initial struct that allows configuration at this stage but removed from the 'split' versions of the struct.
> Remove generics for BXCAN.

- embassy-stm32/Cargo.toml
- embassy-stm32/src/dma/util.rs
- embassy-stm32/src/i2s.rs
- embassy-stm32/src/lib.rs
- embassy-stm32/src/spi/mod.rs
- examples/stm32f4/src/bin/i2s_dma.rs
I added PoC support to the I2S driver for the `spi_v3`. This is not fully tested yet, it works for interfacing with the `tlv320aic32x4` codec, and it seems to be working fine from my limited testing. I took care to not change much from the configuration other than the necessary changes to make it work with the v3 versions. I also needed to add Full-Duplex support, so I changed the API, I expect that this will be iterated upon, so I see it mostly as a chance to talk about the interface. Not sure about the typestate pattern here, we could also do panicking read/write, but this seems safer.
> Add spi v3 & Full-duplex support to the I2S driver.

- embassy-stm32/src/can/bxcan/filter.rs
- embassy-stm32/src/can/bxcan/mod.rs
- embassy-stm32/src/can/bxcan/registers.rs
- examples/stm32f7/src/bin/can.rs
- tests/stm32/src/bin/can.rs
- tests/stm32/src/bin/can_common.rs
- tests/stm32/src/bin/fdcan.rs
Remove the rest of the generics in BXCAN. This covers the non-split Can and CanConfig structs.
> Remove more BXCAN generics.

- embassy-stm32/src/spi/mod.rs
- tests/stm32/src/bin/spi.rs
- tests/stm32/src/bin/spi_dma.rs
> stm32/spi: fix blocking_write on nosck spi.

- embassy-stm32/src/i2c/mod.rs
- embassy-stm32/src/i2c/v1.rs
- embassy-stm32/src/i2c/v2.rs
- embassy-stm32/src/spi/mod.rs
- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
This PR contains a bunch of small improvements related to driver initialization:
- Use `new_pin!` in I2C and buffered USART.
- Disconnect pins of I2C and USART on drop.
- Move initialization code into function that's not generic in `T`: I found that this slightly decreases code size.
Marked as draft because this PR builds on #3002.
> stm32: Make initialization of I2C and USART consistent with SPI

- embassy-net/src/tcp.rs
I need to know if queue is almost empty before sending low priority data.
> add send_queue and recv_queue to embassy-net

- embassy-sync/src/signal.rs
The tests all pass with this locally, and I've also tested it in a project using a `NoopRawMutex`.
Closes #3051
> embassy-sync: remove T: Send for Signal<M, T>

- embassy-net-wiznet/src/lib.rs
- examples/stm32f4/Cargo.toml
- examples/stm32f4/src/bin/eth_w5500.rs
This example takes into account the lower memory on the stm32f4. That
should prevent anyone wanting to use the w5500 on any stm from adapting
the w5500 example for the rp which uses a lot more RAM.
On chips with a low amount of ram it's easy to run out of ram. When
looking at the current docs for the State struct it is not easy to
see that these params can cause a lot of ram usage.
> Document w5500 State and add w5500 example for stmf4

- embassy-rp/src/i2c.rs
- embassy-rp/src/i2c_slave.rs
- embassy-rp/src/rtc/datetime_chrono.rs
- embassy-rp/src/rtc/datetime_no_deps.rs
- embassy-stm32/src/dsihost.rs
- embassy-stm32/src/i2c/mod.rs
- embassy-stm32/src/rng.rs
- embassy-stm32/src/sai/mod.rs
- embassy-stm32/src/spi/mod.rs
- embassy-stm32/src/tsc/mod.rs
- embassy-sync/src/pubsub/mod.rs
None of them these errors are `non-exaustative`, they are all small enough to be copy (I estimate none are larger than 4 bytes). All of them seem done and its not probable (to me) that large variants will be added in the future.
> Add Clone and Copy to Error types

- docs/pages/getting_started.adoc
- embassy-boot-stm32/Cargo.toml
- embassy-stm32/README.md
- examples/boot/bootloader/stm32/memory.x
This fixes a couple of typos, and adjusts memory range for bootloader example.
While the bootloader example is unlikely to be used alone - ./examples/boot/application/stm32h7/flash-boot.sh for example overwrites it temporarily with different file altogether, it might be less confusing to anyone wondering why the numbers don't match.
> fix docu typos, linker addr example

- embassy-rp/src/pwm.rs
It is confusing to read without. The corrected line reads like its 'b' pin counterpart (few lines below).
> Add missing word "pin" in rp pwm documentation

- embassy-executor/src/lib.rs
- embassy-executor/src/raw/waker.rs
Since https://github.com/rust-lang/rust/issues/96992 has stalled, to prevent potential unsoundness caused by transmuting to &WakerHack, we can use nightly waker_getters APIs by gating it behind nightly feature in embassy-executor without waiting for it to be stablized.
> use nightly waker_getters APIs

- ci-nightly.sh
- ci.sh
- embassy-executor/build_common.rs
- embassy-hal-internal/build_common.rs
- embassy-nrf/src/i2s.rs
- embassy-nrf/src/spim.rs
- embassy-nrf/src/spis.rs
- embassy-nrf/src/util.rs
- embassy-rp/src/dma.rs
- embassy-rp/src/spi.rs
- embassy-stm32/build_common.rs
- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/dma/gpdma.rs
- embassy-stm32/src/dma/mod.rs
- embassy-stm32/src/spi/mod.rs
- embassy-sync/build_common.rs
- rust-toolchain.toml
- **Update stable to Rust 1.79.**
- **Use raw slices .len() method instead of unsafe hacks.**
> Update to Rust 1.79

- examples/rp/src/bin/wifi_ap_tcp_server.rs
- examples/rp/src/bin/wifi_blinky.rs
- examples/rp/src/bin/wifi_scan.rs
- examples/rp/src/bin/wifi_tcp_server.rs
- tests/rp/src/bin/cyw43-perf.rs
probe-rs download 43439A0.bin --format bin --chip RP2040 --base-address 0x10100000
-->
Error: --format has been renamed to --binary-format. Please use --binary-format bin instead of --format bin
>  probe-rs download 43439A0.bin --format bin deprecated

- embassy-stm32/src/ucpd.rs
When using stm32g071b-disco as a PD interceptor i noticed especially GoodCrc packets got missed and sometimes corrupted packets were received. This PR seems to fix both issues :)
> Improve stm32 ucpd packet reception

- cyw43/src/fmt.rs
- embassy-boot-nrf/src/fmt.rs
- embassy-boot-rp/src/fmt.rs
- embassy-boot-stm32/src/fmt.rs
- embassy-boot/src/fmt.rs
- embassy-executor/src/fmt.rs
- embassy-futures/src/fmt.rs
- embassy-hal-internal/src/fmt.rs
- embassy-net-adin1110/src/fmt.rs
- embassy-net-driver-channel/src/fmt.rs
- embassy-net-enc28j60/src/fmt.rs
- embassy-net-esp-hosted/src/fmt.rs
- embassy-net-ppp/src/fmt.rs
- embassy-net/src/fmt.rs
- embassy-nrf/src/fmt.rs
- embassy-rp/src/fmt.rs
- embassy-stm32-wpan/src/fmt.rs
- embassy-stm32/src/fmt.rs
- embassy-sync/src/fmt.rs
- embassy-time/src/fmt.rs
- embassy-usb-dfu/src/fmt.rs
- embassy-usb-synopsys-otg/src/fmt.rs
- embassy-usb/src/fmt.rs
This makes location info in defmt logs point to the code calling the macro,
instead of always to fmt.rs as before. Fix works with nightlies
starting with today's, and stable 1.81+.
see previous discussion in #3065 #3068
> Add collapse_debuginfo to fmt.rs macros.

- embassy-stm32/src/gpio.rs
Fix what seems like a typo in the documentation of GPIO speed register values.
> docs(gpio): fix a typo regarding GPIO speed

- examples/stm32g0/src/bin/input_capture.rs
- examples/stm32g0/src/bin/pwm_complementary.rs
- examples/stm32g0/src/bin/pwm_input.rs
Add three `pwm` routines
`pwm_capture` is used to read the duty cycle, width and frequency of the input pwm.
`input_capture` is used to read the input edge frequency
`pwm_complementary` provides two sets of complementary pwm outputs with different duty cycles
> Add PWM examples for stm32g0

- embassy-time/src/lib.rs
- embassy-time/src/timer.rs
This allows writing
```rust
rx.read(&mut read_buf).with_timeout(Duration::from_millis(200)).await
```
rather than
```rust
with_timeout(Duration::from_millis(200), rx.read(&mut read_buf)).await
```
This looks nicer to me.
> implement with_timeout()/with_deadline() method style call on Future

- embassy-rp/src/adc.rs
- examples/rp/src/bin/adc_dma.rs
- tests/rp/src/bin/adc.rs
Adds "round robin" sampling so that multiple channels can be sampled at once.
Including a new example for how to use the ADC with DMA, for both single- and multichannel reads.
> rp: Add multichannel ADC

- embassy-rp/Cargo.toml
- embassy-rp/src/lib.rs
In a project I need a custom boot2 and embassy gets in the way.
This PR adds an option to let embassy not provide it.
This is an active choice a user has to make, so it doesn't get in the way of existing code and ease of setup.
> RP: add option to provide your own boot2

- embassy-rp/src/lib.rs
Dang, my last PR was a bit too quick. Got a warning for unused macro when boot2-none is activated.
So this fixes it.
> RP: Shut up missed warning boot2-none

- embassy-nrf/src/buffered_uarte.rs
- embassy-nrf/src/uarte.rs
- tests/nrf/Cargo.toml
- tests/nrf/src/bin/buffered_uart.rs
- tests/nrf/src/bin/buffered_uart_full.rs
- tests/nrf/src/bin/buffered_uart_halves.rs
- tests/nrf/src/bin/buffered_uart_spam.rs
- tests/nrf/src/bin/uart_halves.rs
- tests/nrf/src/bin/uart_split.rs
- tests/nrf/src/common.rs
- **nrf: fix wrong order configuring gpios.**
- **nrf/buffered_uart: take into account EASYDMA_SIZE. fixes nrf52832**
- **tests/nrf: generalize buffereduart tests for all chips.**
- **tests/nrf: add non-buffered uart tests.**
> nRF uart fixes, better tests.

- docs/pages/layer_by_layer.adoc
The struct is called ExtiInput, not ExtiButton.
> docs: Fix mention of ExtiInput

- embassy-rp/src/i2c.rs
- examples/rp/src/bin/i2c_async_embassy.rs
Previous i2c examples are using either blocking Embassy API or e-h traits, this example uses Embassy pub API directly, also loosens the requirement for passing specifically u8 or u16 to address a device.
> rp/i2c: add address flexibility and example

- embassy-nrf/CHANGELOG.md
- embassy-nrf/src/pwm.rs
HI everyone,
in an application I'm working on, I need a way to change the driving strength of the GPIO Pins.
Since I did find a `safe` way to do so on my side, I went implementing it here.
For the `SequencePwm` I extended the `Config` with the driving strength, whereas in the `SimplePwm` I added the function to adapt it similarly to the other parameters `set_max_duty`. I omitted the getters because personally I think that it's a "YAGNI".
I did not introduce a `SimpleConfig` because from the code it looks like not to be there intentionally, and I did not want to brake the API.
Happy to change any of this based on your feedback.
Cheers!
> feat(pwm): allow specifying OutputDrive for PWM channels

- embassy-stm32/src/i2c/v2.rs
The I2C master-write function was failing when executed immediately after an I2C read operation, requiring manual delays to function correctly. This fix introduces a check to ensure the I2C bus is free before initiating the write operation.
According to the RM0399 manual for STM32H7 chips, the BUSY bit (Bit 15 in the I2C ISR register) indicates whether a communication is in progress on the bus. The BUSY bit is set by hardware when a START condition is detected and cleared when a STOP condition is detected or when PE = 0.
This fix prevents the write operation from starting until the BUSY bit is cleared.
> Fix: Ensure I2C bus is free before master-write operation

- embassy-net/src/tcp.rs
Fix #3140 
Update `ReadReady` for `TcpReader` to match implementation for `TcpSocket`
Update `WriteReady` implementations to use `can_recv()` rather than `may_recv()`, since this will check that the transmit buffer is not full.
> Update `ReadReady` and `WriteReady` implementations

- embassy-stm32/src/dma/dma_bdma.rs
The half transfer irq needs to be enabled in order for the hardware to notify the waker when the transfer is at half. This is needed to ensure no overuns occur when using `ReadableDmaRingBuffer`'s `read_exact`. Otherwise we are only notified when the DMA has completed its cycle and is on its way to start overwriting the data. The docs in the dma_bdma buf module also seem to imply that the half transfer irq must be enabled for proper operation. The only consumers of the `ReadableDmaRingBuffer` api are the sai module and the `RingBufferedUartRx`. The former enables the irq manually when constructing the transfer options while the latter does not. This may also be the cause for #1441.
> Enables half transfer ir when constructing a ReadableDmaRingBuffer

- embassy-stm32/build.rs
- embassy-stm32/src/adc/mod.rs
- embassy-stm32/src/adc/ringbuffered_v2.rs
- embassy-stm32/src/adc/v2.rs
- examples/stm32f4/src/bin/adc_dma.rs
new PR, taking Dirbao's advice to make the DMA impl in a separate struct that consumes Adc<T> to make RingBufferedAdc<T>. Handling overrun similar to RingBufferedUart.
The API is therefore entirely disjoint from the original ADC API.
>  ring buffered adc v2

- embassy-net-wiznet/src/chip/mod.rs
- embassy-net-wiznet/src/chip/w5100s.rs
- embassy-net-wiznet/src/chip/w5500.rs
- embassy-net-wiznet/src/device.rs
- embassy-net-wiznet/src/lib.rs
- examples/rp/src/bin/ethernet_w5500_multisocket.rs
- examples/rp/src/bin/ethernet_w5500_tcp_client.rs
- examples/rp/src/bin/ethernet_w5500_tcp_server.rs
- examples/rp/src/bin/ethernet_w5500_udp.rs
- examples/stm32f4/src/bin/eth_w5500.rs
- tests/rp/src/bin/ethernet_w5100s_perf.rs
This performs a read from the Wiznet chips to check their respective version registers, returning an error if they mismatch.
Do note that this is largely untested because I'm trying to debug an issue with a chip at the moment, but it was asked that this gets PR'd in anyway since currently the initialization sequence only performs writes and no reads.
> wiznet: add version check to initialization sequence

- embassy-boot/src/boot_loader.rs
Uses a new feature in Rust 1.79 to get compile time asserts. It looks like it only works for assert! and not assert_eq!.
> make some embassy-boot asserts const

- embassy-stm32/src/tsc/mod.rs
- examples/stm32u5/src/bin/tsc.rs
First punt at contributing peripheral code, I hope it's close to where it needs to be.
Based off what I read in `rng.rs`, on the advice of @kkoppul2
Some questions I have:
- What, if anything, should happen to the existing `start_it` and `poll_for_acquisition` methods
- Is it okay that this _requires_ Irqs be linked up to use the TSC? Or should it be optional?
> Add async API to TSC

- embassy-nrf/src/radio/ble.rs
- The end event is not triggered by stop and might therefor never occur
- Clear the end_event after operation is done instead of disabled
> fix cancellation hanging on event never occuring

- embassy-stm32/build.rs
- embassy-stm32/src/adc/v3.rs
- embassy-stm32/src/adc/v4.rs
- examples/stm32g0/src/bin/adc_dma.rs
- examples/stm32h7/src/bin/adc_dma.rs
This PR is on top of https://github.com/embassy-rs/embassy/pull/3106 and adds also DMA support to STM32 ADC V3. Original PR added it to V4.
* https://github.com/embassy-rs/embassy/pull/3106
Tested on STM32G081.
> STM32 ADC v3 and V4 DMA support

- embassy-stm32/build.rs
Instead of this misleading message:
You now get a much more verbose message indicating what is going wrong
> Better panic message when peripheral clock is not enabled

- embassy-stm32/src/adc/g4.rs
- embassy-stm32/src/adc/ringbuffered_v2.rs
- embassy-stm32/src/adc/v2.rs
- embassy-stm32/src/adc/v3.rs
- embassy-stm32/src/adc/v4.rs
- examples/stm32f4/src/bin/adc.rs
- examples/stm32f4/src/bin/adc_dma.rs
- examples/stm32f7/src/bin/adc.rs
- examples/stm32g0/src/bin/adc.rs
- examples/stm32g0/src/bin/adc_dma.rs
- examples/stm32g0/src/bin/adc_oversampling.rs
- examples/stm32g4/src/bin/adc.rs
- examples/stm32h7/src/bin/adc.rs
- examples/stm32h7/src/bin/adc_dma.rs
- examples/stm32l4/src/bin/adc.rs
- examples/stm32u0/src/bin/adc.rs
- tests/stm32/src/bin/dac.rs
Unifies STM32 ADC `read` function naming.
Blocking reads will be named to `blocking_read` and async reads will be just `read`.
> stm32 adc: introduce blocking_read

- embassy-rp/src/uart/buffered.rs
error:
```
error[E0277]: the trait bound `BufferedUart<'_, UART0>: ReadReady` is not satisfied
```
@jamesmunns wanted to look at a pr
Handle with care, i have read the docs at https://docs.rs/embedded-io-async/latest/embedded_io_async/trait.ReadReady.html#tymethod.read_ready and this is my shot at it. But at my level of experience this may well be flawed -> draft for now
> Impl read ready for buffered uart in embassy rp

- embassy-usb/Cargo.toml
- examples/nrf52840/Cargo.toml
- examples/nrf5340/Cargo.toml
- examples/rp/Cargo.toml
- examples/stm32f4/Cargo.toml
- examples/stm32g4/Cargo.toml
- examples/stm32l5/Cargo.toml
Running `cargo build` in `examples/rp` gives the following error:
```
error[E0277]: the trait bound `usbd_hid_descriptors::MainItemKind: From<std::string::String>` is not satisfied
--> /home/julian/.cargo/registry/src/index.crates.io-6f17d22bba15001f/usbd-hid-macros-0.6.0/src/spec.rs:512:43
|
512 |             self.set_item(name, item_kind.into(), settings, bits, quirks);
|                                           ^^^^ the trait `From<std::string::String>` is not implemented for `usbd_hid_descriptors::MainItemKind`, which is required by `std::string::String: Into<_>`
|
= help: the trait `From<&str>` is implemented for `usbd_hid_descriptors::MainItemKind`
= help: for that trait implementation, expected `&str`, found `std::string::String`
= note: required for `std::string::String` to …
```
> Bump usbd-hid from 0.7.0 to 0.8.1 to fix compile errors in rp examples

- embassy-stm32/src/fmc.rs
This PR adds constructors for 13 bit address sdram
> stm32: Add 13bit address sdram constructors

- embassy-net/src/lib.rs
Added a missing closing angle bracket in the documentation.
> embassy-net: fix minor typo in doc

- embassy-stm32/src/tsc/mod.rs
- examples/stm32f3/src/bin/blocking-tsc.rs
- examples/stm32l0/src/bin/async-tsc.rs
- examples/stm32l0/src/bin/blocking-tsc.rs
- Examples of how to use blocking/polling TSC for stm32f303 and stm32l073.
- Example of how to use async TSC for stm32l073, inspired by https://github.com/embassy-rs/embassy/blob/main/examples/stm32u5/src/bin/tsc.rs.
I would have liked to add a corresponding async example for stm32f303, but I am having problems with registering the EXTI2_TSC interrupt with the usual `bind_interrupts!` macro, because I get an ldd conflict. My guess is that I get the conflict because of [this line in the exti.rs](https://github.com/embassy-rs/embassy/blob/6636a5835b27f82abea9000c9f3e93b4455b29c8/embassy-stm32/src/exti.rs#L312). I am quite new to Rust though, so it could be something else.
> add TSC examples

- embassy-rp/src/uart/buffered.rs
- embassy-rp/src/uart/mod.rs
- examples/rp/src/bin/uart_buffered_split.rs
- Add `split_ref` fn to `Uart` & `BufferedUart`, allowing a mutable reference split into RX & TX handles
- Change order of RX and TX handles in `BufferedUart::split()` fn, to streamline with other HALs & `Uart`
- Add `set_baudrate` to `BufferedUart` allowing runtime change of configured baudrate
> (embassy-rp): Add split_ref fn to uart, allowing a mutable reference split into RX & TX handles

- docs/pages/sharing_peripherals.adoc
- examples/rp/src/bin/shared_bus.rs
We get a lot of questions about how to use a shared bus with I2C and SPI devices, so here's an example for that
> Add example for shared I2C and SPI buses

- docs/pages/basic_application.adoc
- docs/pages/new_project.adoc
- docs/pages/nrf.adoc
- docs/pages/overview.adoc
- docs/pages/sharing_peripherals.adoc
- docs/pages/stm32.adoc
- docs/pages/time_keeping.adoc
This fixes some minor documentation link issues. Resolves problems where the links were still referencing the page they used to be on. It also fixes the master branch being renamed to main, so an interstitial is not shown on the Github side of things.
> Documentation Link Fixes

- cyw43/src/control.rs
- cyw43/src/lib.rs
> Fixing missing re-export

- embassy-stm32/src/flash/f1f3.rs
While not waiting for the BSY flag to clear works on STM32F103C8T6, it does not on APM32F103C8T6. Only one half-word gets written while the other one gets lost.
> embassy-stm32: wait for BSY flag to clear before flashing

- embassy-stm32/src/hsem/mod.rs
You could already enable and clear it, but you could never check which semaphore was activating the interrupt. This adds a function so you can check
> Add function to get the active HSEM interrupt

- embassy-sync/src/lazy_lock.rs
Using `union` can save more space.
And the `MaybeUninit<T>` will never drop the T, when dropping the `MaybeUninit<T>`.
Fixed it.
> embassy-sync: fix the data of LazyLock never drop

- examples/boot/bootloader/rp/memory.x
The bootloader region (`FLASH`) mentioned below overflows into the `BOOTLOADER_STATE` region by `0x100` bytes
```
0x10000100 + 24K = 0x10006100
```
https://github.com/embassy-rs/embassy/blob/32adddff9c7fc223853ada7e9ab5b7e06014a47c/examples/boot/bootloader/rp/memory.x#L3-L8
> Fix bootloader-rp's bootloader memory region overflow

- embassy-usb-synopsys-otg/src/lib.rs
Before, it would alloc the endpoint fine and then panic later due to out of range.
This ensures it falis at ep alloc time, and with a panic message that says
what's the actual problem: "no free endpoints available".
> usb-synopsys-otg: ensure ep alloc fails when endpoint_count < MAX_EP_COUNT.

- embassy-nrf/CHANGELOG.md
Rewrite CHANGELOG for better overview:
- Support for NRF chips:
- nrf51
- nrf9151
- Support for new peripherals:
- EGU
- radio - low-level support for IEEE 802.15.4 and BLE via radio peripheral
- Peripheral changes:
- gpio: Drop GPIO Pin generics (API break)
- pdm: Fix gain register value derivation
- pwm:
- Expose `duty` method
- Expose `pwm::PWM_CLK_HZ` and add `is_enabled` method
- Allow specifying OutputDrive for PWM channels
- Fix infinite loop
- spim:
- Reduce trace-level messages ("Copying SPIM tx buffer..")
- Support configuring bit order for bus
- Allow specifying OutputDrive for SPI pins
- Add bounds checks for EasyDMA buffer size
- Implement chunked DMA transfers
- uart:
- Add support for rx- or tx-only BufferedUart
- Implement splitting Rx/Tx
- Add support for handling RX …
> nrf: Rearrange CHANGELOG by features for better overview

- examples/stm32h755cm4/Cargo.toml
- examples/stm32h755cm7/Cargo.toml
Fixes cargo warnings:
```
warning: skipping duplicate package `embassy-stm32h7-examples` found at `.cargo/git/checkouts/embassy-9312dcb0ed774b29/46aa206/examples/stm32h755cm4`
warning: skipping duplicate package `embassy-stm32h7-examples` found at `.cargo/git/checkouts/embassy-9312dcb0ed774b29/46aa206/examples/stm32h7`
```
> Rename package for embassy-stm32h755cm4 and cm7 example

- embassy-nrf/src/buffered_uarte.rs
- embassy-nrf/src/gpio.rs
- embassy-nrf/src/wdt.rs
Watchdog and gpio ones are obvious, though maybe we could still keep the uarte warnings so someone has intention to look whether it's possible to refactor the ppi arguments into struct?
> nrf: Fix bunch of low-hanging clippy lint warnings

- cyw43/src/runner.rs
- examples/rp/Cargo.toml
> cyw43: make sure to yield if doing busy-polling for interrupts.

- embassy-nrf/src/saadc.rs
`saadc::ChannelConfig` does not implement the `Default` trait, so its documentation should not refer to it.  Modify the documentation to instead describe how the struct should be created and configured.
> nrf, doc: Don't refer to `Default` impl of `saadc::ChannelConfig`

- embassy-usb-synopsys-otg/src/otg_v1.rs
Adding the missing OTG core dma address registers; these are a prerequisite  for `usbh` support as well as improving async-ness on supported devices.
> Add OTG core DMA address registers

- embassy-stm32/src/low_power.rs
- embassy-stm32/src/rtc/low_power.rs
- embassy-stm32/src/rtc/v2.rs
This PR enables the `low-power` feature on STM32L4 devices by implementing the required traits and setting the correct `WakeupInterrupt` and `EXTI_WAKEUP_LINE`.
I have tested this on a NUCLEO-L452RE board with a program inspired by the `stm32l5/stop.rs` example. With `enable_debug_during_sleep = false` and the LED turned off, the current consumption drops down to around 3uA when the delays are large enough to allow STOP2 mode. Waking up works as well (normally, see below).
Both the RM0394 reference manual for STM32L4 devices and the AN4759 application note which is also mentioned in embassy-stm32's comments indicate that STM32L41/L42xxx devices use another RTC. Until now, I have not understood how the correct RTC implementation is chosen in embassy's build process, but I can see that the …
> Implement low-power feature for STM32L4 MCUs

- embassy-net/src/tcp.rs
If a remote connection crashes, the remote OS sends a packet with the RST flag set.
However, if the embassy_net TcpSocket then flushes, this blocks forever, as despite the socket state being `Closed`, there's data in the send queue, and thus the flush method keeps returning Poll::Pending.
My fix for this is to check if the state is `Closed`, and if so, the [`data_pending`](https://github.com/sammhicks/embassy/blob/e6f4db507d62178ddb05a4569a9f9352a25222e0/embassy-net/src/tcp.rs#L518) flag is not set, thus if `fin_pending` and `rst_pending` are both false, the flush completes.
This should possibly be fixed upstream, i.e. in `smoltcp`, by a tcp socket clearing its send queue if it's reset, but I'm not sure.
> net/tcp: fix flush() waiting forever if socket is reset with pending write data

- embassy-usb/src/descriptor.rs
- embassy-usb/src/lib.rs
USB device qualifier descriptor is useful when the device supports USB HS. It contains the information of the other speed mode. For example, if the device operates in HS mode, this descriptor contains information about how it could be operated in FS mode, and vice-versa.
> embassy-usb: add USB device qualifier descriptor

- embassy-net/Cargo.toml
Smoltcp supports mDNS but the feature was never used in embassy. Enabling it seems to be all what's required to resolve a `.local` address, in small local testing I did.
Should fix https://github.com/embassy-rs/embassy/issues/3177
cc @PhaestusFox
> feat(mdns): Enable mdns support through smoltcp

- embassy-stm32/build.rs
- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/dma/gpdma.rs
- embassy-stm32/src/lib.rs
- embassy-stm32/src/rcc/bd.rs
- embassy-stm32/src/rcc/c0.rs
- embassy-stm32/src/rcc/f013.rs
- embassy-stm32/src/rcc/f247.rs
- embassy-stm32/src/rcc/g0.rs
- embassy-stm32/src/rcc/g4.rs
- embassy-stm32/src/rcc/h.rs
- embassy-stm32/src/rcc/l.rs
- embassy-stm32/src/rcc/u5.rs
- embassy-stm32/src/rcc/wba.rs
- examples/boot/application/stm32wl/memory.x
- examples/stm32wl/memory.x
This commit addresses #3256 by disabling dma NVIC interrupt ~~configuration~~ enablement at startup.
Instead, per-channel NVIC interrupt ~~configuration~~ enablement is now done with the rest of the dma channel configuration.
This ensures that each core will only handle the interrupts of the DMA channels that it uses.
Successfuly tested on a complex STM32h745IIx project with ~20 peripherals and ~9 DMA1, DMA2, BDMA channels.
Potential issues:
- ~~Removal of `dma_priority` and `bdma_priority` from `Config`: This is now consistent with the rest of the peripherals. Maybe explicitely deprecate and suggest to manually set the priorities instead?~~ I kept the priority setup on both cores and only removed the enablement.
- build.rs script: I am not confident on the `ChannelInfo` build.rs fill …
> stm32: fix dma nvic issues on dual core lines

- embassy-stm32/src/usart/mod.rs
Half duplex UART requires the use of Open drain output with a pull up resistor. This modification has been tested and shown to work between two NUCLEOU545 boards. The verbage on the pin configuration is the same across the reference manuals for all of the chip families that support this behavior.
> Convert uart half_duplex to use user configurable IO

- embassy-rp/src/clocks.rs
RP2350 requires ticks to be started for timer to start counting. `picotool reboot` seems to do this automatically, but after next restart system timer wouldn't count at all.
This addresses my comments in https://github.com/embassy-rs/embassy/issues/3241
> Set up timer0 tick when initializing clocks

- embassy-stm32/src/can/bxcan/mod.rs
Running the bxcan driver's `enable().await` without having it connected to a CAN bus causes the `info` logs to bombard.
This removes the logging statements as they looked like remnants from the development of the driver.
> stm32: Fix log storm when no CAN is connected

- embassy-stm32/src/usb/otg.rs
- embassy-usb-synopsys-otg/src/lib.rs
This operates an ULPI PHY at full speed.
Useful for certain classes (e.g. USB audio 1.0) that are not meant to be used at high speed - or for saving some power.
> feat: Add support for a full-speed ULPI mode

- embassy-stm32/src/sai/mod.rs
The SAI peripheral (in receive mode) has a feature where it detects a mute condition, based on the repetition of the received sample value.
This adds support for reading that mute state.
> feat: add function to check if SAI is muted

- embassy-net/src/udp.rs
Added `recv_from_with` and `send_to_with`. These are conceptually similar to TCP's `read_with` and `write_with` functions.
An application can parse received datagrams directly out of the receive buffer or assemble a datagram of known-length directly into the send buffer.
> feat(embassy-net): add zero-copy UDP send/recv functions

- examples/rp/src/bin/bluetooth.rs
I guess this was copy-pasted from the wifi example.
> rp: add example code to flash bluetooth fw

- examples/nrf52840/src/bin/channel.rs
- examples/nrf52840/src/bin/channel_sender_receiver.rs
The LEDs on the nrf52840 DK are active low.
Documentation: https://docs.nordicsemi.com/bundle/ug_nrf52840_dk/page/UG/dk/hw_buttons_leds.html
Note, the LEDs on the Raspberry Pi Pico (2) are active high, no change is needed there.
> nrf52840: fix naming of LED states in examples

- embassy-boot/Cargo.toml
using default_features is deprecated in the 2024 edition per the compiler warning.
> Fix using default_features instead of default-features in embassy boot

- embassy-executor/Cargo.toml
- examples/wasm/Cargo.toml
Without that feature one will find import errors on opening the webpage, that are hard to debug. The feature was indirectly enabled in the wasm example, however the reason wasn't documented and thus it was easy to miss.
> Enable critical-section/std on wasm

- embassy-stm32/src/sai/mod.rs
Ensures that, when no external input is connected, the data line is in mute state, and no (spurious) clocks are received.
With a RaspberryPi 4 as a source (a few 10 Ohm of output resistance) in slave mode, the data line shows no signs of degradation. The pull-down is around 40 kOhm.
> SAI pull down clock and data lines in receive mode

- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/usart/ringbuffered.rs
This change is required to address an issue in the RingBufferedUartRx DMA handling and idle line detection.
When an IRQ wakes the `select` future, both inner futures (`dma` and `uart`) in the select are re-polled. Previously, the `dma` future was polled first. Since it can't check if it was woken for valid reasons (due to API limitations), it could end the select future without clearing the IDLE flag, which is handled in the `uart` future.
The proposed fix reverses the polling order, starting with the `uart` future. This allows proper checking and clearing of the IDLE flag before considering the DMA status, preventing scenarios where the flag remains set across multiple read operations.
Additionally, this PR enables the half-transfer IRQ for the DMA to help prevent data loss at high baud …
> fix(stm32): fix dma and idle line detection in ringbuffereduartrx

- embassy-usb/src/descriptor.rs
As discussed on the Matrix room, having a zero-length `bos_descriptor_buf` currently crashes the embassy-usb builder.
This should fix it, by checking for enough bytes in the buf, before taking any actions.
> Allow bos_descriptor_buf to be a zero-length slice

- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
Add function to send break character on STM32 USARTs.
Function is currently sync and first busy-waits until previous break has been sent (should be rare?, usart v3&v4 seems to have interrupt for sent break character).
Then sending break character is requested and it should be sent as soon as the current character is transmitted.
> stm32/usart: sending break character

- embassy-net/src/tcp.rs
Ran into this as I forgot to handle the Ok(0) return case and just kept reading. Documenting it here seemed the best way not to run into it again :)
> embassy-net/read document return value Ok(0)

- embassy-rp/src/flash.rs
- embassy-rp/src/lib.rs
- embassy-rp/src/rom_data/mod.rs
- embassy-rp/src/rom_data/rp2040.rs
- embassy-rp/src/rom_data/rp235x.rs
Many thanks to @thejpster for his work on the rom_data! 
Working around boot2 is currently a bit hacky for the rp235x, that will improve in upcoming rp235x flash pr.
Is there a better way to bring in the module docs for rom_data?
> rp: Import rom_data for the rp235x from rp-hal, don't use intrinsics on rp235x

- embassy-rp/src/flash.rs
- embassy-rp/src/lib.rs
- embassy-rp/src/otp.rs
- embassy-rp/src/rom_data/mod.rs
- embassy-rp/src/rom_data/rp2040.rs
- embassy-rp/src/rom_data/rp235x.rs
- examples/rp23/.cargo/config.toml
- examples/rp23/src/bin/flash.rs
- examples/rp23/src/bin/otp.rs
This PR depends on/contains #3287.
Direct mode reads are not supported (ie, reading the flash's jedec id or unique id).
The 2350 doesn't have a boot2 like the 2040, but it does have the concept of a xip setup function that could be customized. By default the bootrom searches for the attached flash chip and provides an xip setup func at the base of the bootram. That bootram is not executable, so it still needs to be copied to ram like boot2 would be.
Currently does not use inline assembly for write_flash_inner.
This pr also imports the OTP functions from rp-hal, and adds a couple helper functions to pull the random numbers written to the OTP by PI to make up for not being able to read the flash's unique id. Again, credit and many thanks to @thejpster for doing the real work for OTP.
Also …
> rp: 2350 flash write and OTP

- embassy-stm32/src/ucpd.rs
- examples/stm32g4/src/bin/usb_c_pd.rs
- tests/stm32/src/bin/ucpd.rs
Allow capturing (and distinguishing) non-SOP packets as well. The default configuration will just configure SOP packets. For ease of use the default receive function signature is unchanged as for PD sinks (which is likely the common usage) just SOP is enough so no need to differentiate.
> [UCPD] Add support for non-SOP packets

- embassy-stm32/src/adc/g4.rs
- embassy-stm32/src/adc/mod.rs
- examples/stm32g4/src/bin/adc_differential.rs
- examples/stm32g4/src/bin/adc_oversampling.rs
Add oversampling in regular mode .
Add adc differential use `pa0 `and `pa1`.
Verify no errors with `stm32g431cbu6`
> Add adc oversampling and adc differential for g4

- embassy-rp/src/gpio.rs
Does not handle using PIO with pins > 31, which is still broken.
> rp: Fix indexing for pins >31 on rp235xb

- embassy-boot/src/firmware_updater/asynch.rs
- embassy-boot/src/firmware_updater/blocking.rs
Fixes #3339
Always return signature error in verify_and_mark_updated when no signature features are enabled.
> fix(boot): return signature error when no features

- embassy-stm32/src/usb/usb.rs
- embassy-usb-synopsys-otg/src/lib.rs
- embassy-usb-synopsys-otg/src/otg_v1.rs
- embassy-usb/src/builder.rs
- embassy-usb/src/descriptor.rs
Adds support for ISO endpoints for both the STM32 OTG USB driver and the "regular" (newer?) USB driver.
> Add ISO endpoint support

- docs/pages/bootloader.adoc
- embassy-boot/Cargo.toml
- embassy-boot/src/lib.rs
Proposal for issue #3342, subject for discussion. Any feedback is welcome.
Allow compatibility with devices whose flash erase set bytes to 0x00 instead of 0xFF, using a new flash-erase-zero feature.
> boot: flash-erase-zero feature for compatibility with STM32L0x1 devices

- embassy-rp/src/uart/mod.rs
The same thing exists for rx-only, why not for tx-only?
> rp: add constructor for tx-only blocking UART

- embassy-rp/src/gpio.rs
- embassy-rp/src/pio/mod.rs
Disable pad isolation on any used pin.
Use GPIOBASE and offset pin bases if all pins are > 16, panic if some pins are < 16 and some are > 31
> rp: rp2350 pio pin fixes

- embassy-net-esp-hosted/src/control.rs
- embassy-net-esp-hosted/src/lib.rs
- embassy-net/src/lib.rs
- **net-esp-hosted: remove useless fn init.**
- **net-esp-hosted: set wpa3_supported=true.**
- **net: add all combinations of wait methods for link/config up/down.**
> net: add all combinations of wait methods for link/config up/down.

- embassy-boot/src/boot_loader.rs
- embassy-boot/src/firmware_updater/asynch.rs
- embassy-boot/src/firmware_updater/blocking.rs
- embassy-boot/src/lib.rs
- examples/boot/application/nrf/build.rs
- examples/boot/application/nrf/src/bin/a.rs
The revert state signals that a firmware revert has taken place, allowing the application to know if a firmware update attempt was reverted.
> Add revert state in embassy-boot

- embassy-stm32/src/eth/mod.rs
- examples/stm32f4/src/bin/eth_compliance_test.rs
This change adds the possibility to perform Ethernet compliance testing with STM32 systems when using a custom PHY struct to generate test patterns.
> embassy_stm32/eth: support compliance testing

- embassy-stm32/Cargo.toml
Hi there,
This is just a small fix to (correctly, hopefully) enable embassy-stm32 to be built without a time driver.
Without this, embassy-embedded-hal's default-on `time` feature will pull in embassy-time even without a `time-driver-xxx` specified, and the linker will fail to find the related time symbols.
This is a best-effort guess at the required fix, let me know if I need to change anything else!
> Correctly gate `time` feature of embassy-embedded-hal in embassy-stm32

- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/usart/ringbuffered.rs
This fixes the RingBufferedUartRx::read never being able to recover after an initial overrun error, due the the complete reset of the DMA channel, instead of a temporary pause.
Possibly related issues: #1441 #1427
> stm32: Fix RingBufferedUartRx hard-resetting DMA after initial error

- embassy-stm32/src/spi/mod.rs
Currently, when calling read() of the SPI bus, DMA always transmits u8 for the clocking bit, which will cause bus hang if SPI transfer size > 8bit. Use matching word size for TX DMA instead.
Tested on STM32G431CBU6.
A small example to reproduce this problem:
```rust
let mut spi_config = spi::Config::default();
spi_config.frequency = Hertz(1_000_000);
spi_config.mode = MODE_0;
let mut my_spi = spi::Spi::new(
p.SPI2, p.PB13, p.PB15, p.PB14, p.DMA1_CH5, p.DMA1_CH4, spi_config,
);
loop {
let mut buf = [0u16; 2];
my_spi.read(&mut buf).await.unwrap();
Timer::after_millis(300).await;
}
```
> stm32/spi: issue correct DMA word length when reading to prevent hang

- .gitignore
- embassy-stm32/src/can/fd/peripheral.rs
Currently the return value of `write` is broken, it never returns the previous dequeued frame even when present.
This happens because a slice of length 64 is always passed to Frame::new from within the `abort_pending_mailbox` function, causing `Frame::new` to return None.
The fix is to take a subslice of length `data_length` and pass that to `Frame::new`.
> Fix return value of `fdcan` `write`

- docs/pages/bootloader.adoc
The second command line suggested to generate firmware signature may not work:
`cat $SECRETS_DIR/message.txt | dd ibs=128 count=1 | xxd -p -r > $SECRETS_DIR/message.txt`
The output file is the same as the input file, so if the output file is created before `cat` reads its content, the result is an empty file. This happens using bash on ubuntu, can't tell if this can work using other interpreters.
> Fixed signature script in bootloader documentation

- embassy-rp/src/pwm.rs
Also fixes minor bug for 2040 where A pins didn't have their pull up/down enabled.
Fixes #3370
> rp23: Disable pad isolation on PWM A pins.

- examples/rp/src/bin/pio_stepper.rs
Simple 4 character change to fix an overflow that occurs when negating `i32::MIN`.
Overflow that occurs when negating `i32::MIN`.
This happens because a signed integer can hold one more negative number than it can positive numbers. So for an `i32` it's from `-2^31` to `2^31-1`. As a result, when `i32::MIN` (`-2^31`) is negated in the `step` impl, it becomes `2^31`, which is more than `i32::MAX` (`2^31-1`).
This would cause a panic in --dev and while it doesn't panic in --release, it causes an overflow which is confusing for a simple example.
change `i32::MIN` to `-i32::MAX` which is equivalent to `i32::MIN+1`
> Fixed overflow on `pio_stepper.rs`

- embassy-rp/src/clocks.rs
Value taken over from PICO-SDK https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_clocks/include/hardware/clocks.h#L163
> rp: Run RP235x at 150 MHz instead of 125

- ci.sh
- embassy-nxp/Cargo.toml
- embassy-nxp/src/gpio.rs
- embassy-nxp/src/lib.rs
- embassy-nxp/src/pac_utils.rs
- embassy-nxp/src/pint.rs
- examples/lpc55s69/.cargo/config.toml
- examples/lpc55s69/Cargo.toml
- examples/lpc55s69/build.rs
- examples/lpc55s69/memory.x
- examples/lpc55s69/src/bin/blinky_nop.rs
- examples/lpc55s69/src/bin/button_executor.rs
This pull request implements a simple embassy-lpc55 hal based on [`lpc55-pac`](https://github.com/lpc55/lpc55-pac). This PR only implements the GPIO driver and the PINT (pin interrupt) driver, which is, in turn, used internally to detect edge & level changes for input GPIO.
While there are many drivers that are yet to be implemented (most notably a time driver, which I want to tackle soon!), I'm going to limit this PR to GPIO and PINT. Despite the limited scope, there are some design decisions of which I am unsure about.
First, how should the hal be organized in terms of chip-specific details? I thought about making this hal similar to how `embassy-nrf` does it (each nrf family has a `.rs` file that creates the unique configuration, but the drivers are more or less identical). However, I …
> LPC: embassy-lpc55 hal base with gpio and pint driver

- embassy-executor-macros/src/lib.rs
- embassy-executor-macros/src/macros/main.rs
- embassy-executor/Cargo.toml
- embassy-executor/src/arch/spin.rs
- embassy-executor/src/lib.rs
Spin polls the raw executor and never sleeps. It is useful for disabling
any power features associated with wfi/wfe-like instructions.
When implementing support for the CH32V30x MCU, the wfi instruction
had issues interacting with the USB OTG peripheral and appeared to be
non-spec-compliant.
1. When sending a USB Data-in packet, the USB peripheral appears to be
unable to read the system main memory while in WFI. This manifests in
the USB peripheral sending all or partially zeroed DATA packets.
Disabling WFI works around this issue.
2. The WFI instruction does not wake up the processor when MIE is
disabled. The MCU provides a WFITOWFE bit to emulate the WFE instruction
on arm, which, when enabled, ignores the MIE and allows the processor to
wake up. This works around the non-compliant WFI …
> executor/spin: introduce an architecture agnostic executor

- embassy-sync/CHANGELOG.md
- embassy-sync/src/channel.rs
These functions are already present in the channel but not implemented in the sender and receiver structs.
> Add capacity, free_capacity, clear, len, is_empty and is_full functions to Channel::{Sender, Receiver}

- embassy-sync/CHANGELOG.md
- embassy-sync/README.md
- embassy-sync/src/priority_channel.rs
These functions were also missing here.
> Add `capacity`, `free_capacity`, `clear`, `len`, `is_empty` and `is_full` functions to `priority_channel::{Sender, Receiver}`

- embassy-stm32/src/i2c/mod.rs
In https://github.com/embassy-rs/embassy/pull/3006 it was changed, that i2c gpios are set to [`Pull::Down`](https://github.com/embassy-rs/embassy/pull/3006/files#diff-1b049bff4df5ffd83afbc0ca47e2fc15d4defdca34d546c1602f799e7a66b1baR86) instead of the previous [`Pull::None`](https://github.com/embassy-rs/embassy/pull/3006/files#diff-1b049bff4df5ffd83afbc0ca47e2fc15d4defdca34d546c1602f799e7a66b1baL138), when [`Config::scl_pullup`](https://github.com/embassy-rs/embassy/blame/456c226b29799f7db56ab60b0ae3d95cc7d6a32a/embassy-stm32/src/i2c/mod.rs#L72) is set to `false` (which is the default). 
I don't think this was an intended change and I can't think of a scenario, where a `Pull::Down` is needed for the I2C bus. 
This merge request changes it to be `Pull::None` again.
> stm32/i2c: disable pullup instead of pulling down

- embassy-net-ppp/Cargo.toml
- embassy-net/Cargo.toml
- embassy-net/src/dns.rs
- embassy-net/src/tcp.rs
- examples/nrf9160/src/bin/modem_tcp_client.rs
- examples/rp/Cargo.toml
- examples/rp23/Cargo.toml
- examples/std/src/bin/net_ppp.rs
- examples/stm32h5/Cargo.toml
- examples/stm32h7/Cargo.toml
- examples/stm32h7/src/bin/eth_client.rs
- examples/stm32h7/src/bin/eth_client_mii.rs
- examples/stm32h755cm4/Cargo.toml
- examples/stm32h755cm7/Cargo.toml
- examples/stm32h7rs/Cargo.toml
- examples/stm32l4/src/bin/spe_adin1110_http_server.rs
Depends on
- https://github.com/smoltcp-rs/smoltcp/pull/994
- https://github.com/drogue-iot/reqwless/pull/91
> Update smoltcp, embedded-nal-async to use the `core::net` IP addr types.

- embassy-rp/Cargo.toml
- embassy-rp/src/lib.rs
- embassy-rp/src/pio_programs/hd44780.rs
- embassy-rp/src/pio_programs/i2s.rs
- embassy-rp/src/pio_programs/mod.rs
- embassy-rp/src/pio_programs/onewire.rs
- embassy-rp/src/pio_programs/pwm.rs
- embassy-rp/src/pio_programs/rotary_encoder.rs
- embassy-rp/src/pio_programs/stepper.rs
- embassy-rp/src/pio_programs/uart.rs
- embassy-rp/src/pio_programs/ws2812.rs
- examples/rp/Cargo.toml
- examples/rp/src/bin/pio_hd44780.rs
- examples/rp/src/bin/pio_i2s.rs
- examples/rp/src/bin/pio_pwm.rs
- examples/rp/src/bin/pio_rotary_encoder.rs
- examples/rp/src/bin/pio_servo.rs
- examples/rp/src/bin/pio_stepper.rs
- examples/rp/src/bin/pio_uart.rs
- examples/rp/src/bin/pio_ws2812.rs
- examples/rp23/src/bin/pio_hd44780.rs
- examples/rp23/src/bin/pio_i2s.rs
- examples/rp23/src/bin/pio_onewire.rs
- examples/rp23/src/bin/pio_pwm.rs
- examples/rp23/src/bin/pio_rotary_encoder.rs
- examples/rp23/src/bin/pio_servo.rs
- examples/rp23/src/bin/pio_stepper.rs
- examples/rp23/src/bin/pio_uart.rs
- examples/rp23/src/bin/pio_ws2812.rs
This is something that's been mentioned a few times and so I decided to just go ahead and do it. The main motivation is to get more people using PIO and especially sharing programs so they see more testing and refinement. 
This pr makes one significant change to all the programs, a few minor changes on some, and adds basic documentation. The significant change is to introduce a <thing>Program struct to represent a specific LoadedProgram for the given driver. This way it's easy to re-use the loaded program for multiple state machines.
The HD44780 driver needs one program for setup and one to run, I suspect there is a way to only load the setup program temporarily, but I didn't investigate that. @pennae appears to have written the original, I'd appreciate input on that.
The I made the pwm …
> rp: Move pio programs into embassy-rp

- embassy-stm32/src/usart/mod.rs
This PR addresses an issue with half-duplex UART communication on STM32H7 (probably valid for all STM32s) where subsequent read cycles unexpectedly return both sent and received bytes, leading to potential data corruption. 
The fix involves disabling the transmitter (before enabling the receiver) after transmission flush in half-duplex mode.
> fix(stm32): disable transmitter during during half-duplex flush

- embassy-rp/build.rs
- embassy-rp/src/multicore.rs
> Enable FPU for RP235X Core1

- embassy-stm32/src/usart/mod.rs
- tests/rp/.cargo/config.toml
- tests/stm32/.cargo/config.toml
- tests/stm32/src/bin/usart.rs
- tests/stm32/src/bin/usart_dma.rs
1) It implement non-blocking `async flush` for UART by enable Transmission complete interrupt.
2) It consist fix for **half-duplex**: either **tx** or **rx** can be enabled one moment. The #3299 can be closed after merging it, because flush should get non-mutable reference. Flush should wait only, no more.
> Stm32: implement async flush for UART

- embassy-stm32/src/can/bxcan/registers.rs
Added RTR flag for transmit frame.
Previous version: remote frame will be sent as data frame with eight `0x00` bytes
Fixed issue from: https://github.com/embassy-rs/embassy/issues/3413
> add RTR flag if it is remote frame

- cyw43/src/lib.rs
The current implementation makes BtDriver and friends private, making it public will improve DX.
> cyw43: make bluetooth module public

- embassy-stm32/src/flash/h5.rs
- embassy-stm32/src/flash/mod.rs
This was based on the stm32h7 driver minus the flash bank logic and the fact that the h5 has secure and non secure flash.
The current implementation works, but may have some outstanding issues, like the secure registers and register lockouts, so it needs a bit more testing to be considered "ready". 
I've implemented this so I could do DFU on the stm32h5, and for that it works.
Any review is very much appreciated.
> Add STM32H5 flash driver

- embassy-net/src/tcp.rs
- embassy-net/src/udp.rs
This provides a `readable()` implementation for `UdpSocket`, as discussed on Matrix.
This API allows a library maintainer or the end user to wait / poll a socket to see if it is readable, without dequeuing any packet. This is useful for offloading packet processing in a different part of the application.
/cc @ivmarkov
> feat(embassy-net): Implement `wait_recv_ready()` + `wait_send_ready()` for UdpSocket and `wait_read_ready()` + `wait_write_ready()` for TcpSocket

- embassy-sync/Cargo.toml
- embassy-sync/src/pubsub/mod.rs
- embassy-sync/src/pubsub/publisher.rs
Corresponding to the `Stream` impl for `pubsub::Sub`.
Notable difference is that we need a separate adapter type to store the pending item, i.e. we can't `impl Sink for Pub` directly. Instead a method `Pub::sink(&self)` is exposed, which constructs a `PubSink`.
> embassy_sync: `Sink` adapter for `pubsub::Pub`

- embassy-rp/Cargo.toml
- embassy-rp/src/pwm.rs
- examples/rp/src/bin/pwm.rs
- examples/rp23/Cargo.toml
- examples/rp23/src/bin/pwm.rs
- examples/rp23/src/bin/pwm_tb6612fng_motor_driver.rs
• Update crate versions 
• Implement embedded-hal PWM traits 
• Add TB6612FNG motor driver example
I noticed the traits were not implemented when trying to construct tb6612fng for a hobby project. I tried my hand at implementing myself, but with a lot of AI help, so please have a good look!
I can confirm with oscilloscope that the PWM is what it is supposed to be, so it should work fine. Not so sure about this living alongside the existing implementation.
> embassy_rp: implement pwm traits from embedded_hal

- embassy-stm32/src/usart/buffered.rs
I've tested this on a STM32H5 and it works without issue.
The option to turn RTS into DE was added because it can be usefull to have this mapping since ST's own tools (like CubeMX) work as such, so the distinction between DE and RTS can an issue if for for example a hardware designer uses tools that do not apply this distinction; Also the fact that the official tooling do not apply this indicates the it may be actually just a naming difference, not a functional difference.
I did not add the same permutations required for the regular Async/Blocking uart but I can if it is required.
> STM32: Add BufferedUart::new permutations usefull for RS485

- examples/rp/src/bin/wifi_blinky.rs
Leading an intro to bare-metal Rust development on an RPi Pico W session next month and want to fix up the example code for the learners.
> update path to cyw43 firmware in `wifi_blinky.rs` comments

- docs/pages/faq.adoc
Someone came up with the need and the solution in ESP-land, it might be worth documenting just in case :)
> Explain how to keep the executor awake

- embassy-rp/src/pwm.rs
this PR allow independent controll of duty cycle for each channel in a pwm slice.
```rust 
let pwm_ab= Pwm::new_output_ab(p.PWM_SLICE3, p.PIN_6, p.PIN_7, pwm_conf.clone());
let (pwm_a,pwm_b)=pwm_ab.split();
pwm_a.set_duty_cycle(dutya);
pwm_b.set_duty_cycle(dutyb);
```
> Embassy-rp Split Pwm driver to allow separate duty cycle control of each channel.

- embassy-nrf/src/twim.rs
Adds support for the `embedded_hal(_async)::i2c::I2c::transaction()` method to the `Twim` peripheral in `embassy_nrf`.
The inherent `transaction` methods also take an additional `stop` parameter to allow the user to suspend the bus following a transaction. This allows for operations like reading a register from a peripheral, modifying it, then writing it back all in a single I2C transaction.
A few nRF chips (specifically the nrf52832, nrf5340, and nrf9120) lack the LASTRX_SUSPEND short. This means they can't automatically enter the suspend state after a read operation, which is needed for certain (uncommon) operation sequences. Therefore, a manual implementation of the short has been added to the interrupt handler for those chips.
Lastly, I discovered a case of UB related to copying write …
> Add support for transactions to Twim in embassy-nrf

- embassy-rp/src/spi.rs
Fixes an issue with rxonly spi instances in embassy_rs::spi. DMA reads still (apparently) require a tx_dma channel to function.
Commit simply adds a required tx_dma parameter to `spi::new_rxonly`. I've tested this on an RP2040, using a MAX31855.
> Fix `embassy_rp::spi::new_rxonly` not taking in required `tx_dma`

- embassy-usb-logger/src/lib.rs
- examples/rp/src/bin/usb_serial_with_handler.rs
This makes it a lot easier for someone to handle incoming data to a serial connection with `embassy-usb-logger`. It adds optional parameter to the `run`, `with_class`, and `with_custom_style` macros to accept a struct that implements RecieverHandler. 
An example of this has been added, but the interface looks like the below.
```Rust
struct Handler;
impl ReceiverHandler for Handler {
async fn handle_data(&self, data: &[u8]) {
if let Ok(data) = str::from_utf8(data) {
let data = data.trim();
// If you are using elf2uf2-term with the '-t' flag, then when closing the serial monitor,
// this will automatically put the pico into boot mode
if data == "q" || data == "elf2uf2-term" {
reset_to_usb_boot(0, 0); // Restart the chip
} else if data.eq_ignore_ascii_case("hello") {
log::info!("World!");
} …
```
> Add ReceiverHandler to logger

- embassy-net/src/raw.rs
- embassy-net/src/tcp.rs
Pretty much copy pasted the logic from #3368 for additional types, which are:
- `TcpReader::wait_read_ready()`
- `TcpWriter::wait_send_ready()`
- `RawSocket::wait_recv_ready()`
- `RawSocket::wait_send_ready()`
@ivmarkov Does this cover every type that could make use of readable / writable?
> Implement readable / writable types for TCP socket splits and raw sockets

- embassy-net/src/driver_util.rs
- embassy-net/src/lib.rs
- embassy-net/src/tcp.rs
- embassy-stm32/src/eth/v2/mod.rs
- disable multicast filtering out packets (which seems to be problematic especially in ipv6, which relies heavily on multicast) (edit: updated to be unconditional as requested)
- fix a couple clippy items, make logs slightly cleaner, using hex like for example wireshark
> embassy-net: disable multicast filtering

- embassy-rp/src/uart/mod.rs
I already implemented `embedded_io::Write` for `Uart<'d, T: Instance, Blocking>`, it makes sense to also implement it for this one.
> Also implement `embedded_io::Write` for `UartTx<'d, T: Instance, Blocking>`

- embassy-stm32/src/dma/ringbuffer/mod.rs
- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
I am unsure what `DmaUnsynced` means and need some help with that. For now I have added it as a separate variant for `uart::Error`. Since I do not know what it means it still needs documentation making this a draft.
> stm32/uart impl ReadReady for RingbufferdUart

- examples/rp/Cargo.toml
- examples/rp/src/bin/spi_display.rs
- examples/rp23/Cargo.toml
- examples/rp23/src/bin/spi_display.rs
I dont have the actual LCD to test and confirm the orientation will be OK. But I have another hardware with GC9A01 and tested it OK on #1660 that I will update once this PR is merged.
> Update example spi_display for RP/RP23 to use mipidsi instead of ST7789 crate

- embassy-executor/Cargo.toml
- embassy-executor/build.rs
- embassy-executor/build_common.rs
- embassy-executor/src/lib.rs
- embassy-executor/src/raw/waker.rs
As there is no nightly Xtensa-enabled compiler, we need embassy-executor to support APIs a bit further back.
> Detect and allow older nightlies

- embassy-sync/src/watch.rs
Add patch for the following issue: https://github.com/embassy-rs/embassy/issues/3417
Add a new_with() to embassy_sync::watch which accepts default data.
> embassy_sync::watch default values

- embassy-nrf/src/chips/nrf5340_app.rs
Added the high-speed SPIM4 for the nrf5340-app.
This peripheral has no slave version, nor it's shared as the other SERIALx peripherals.
> fix(nrf5340-app): added SPIM4 peripheral

- embassy-executor/Cargo.toml
- embassy-executor/build.rs
- embassy-executor/build_common.rs
- embassy-executor/src/lib.rs
- embassy-executor/src/raw/waker.rs
This ensures the executor compiles with all recent nightly versions,
including the stable-but-with-nightly-features-enabled xtensa rustc.
> executor: use WakerHack unconditionally even if `nightly` feature is enabled.

- embassy-executor/src/raw/waker.rs
Saves a whopping 44 bytes of text, yay.
> executor: compare vtable addr instead of contents.

- embassy-rp/src/uart/mod.rs
Between RP2040 and RP235x, the UART DREQ ID changed.
I replaced the hard-coded ones with the enum value defined in rp-pac.
> RP23: fix uart dreq number

- examples/rp/Cargo.toml
- examples/rp/src/bin/spi_gc9a01.rs
This PR is another example of rp spi display but using the generic mipidsi crate (https://github.com/almindor/mipidsi).
I used the GC9A01 round AMOLED display as I have thi one on hand.
Unfortunately the GC9A01 model has been added recently to mipidsi and is not in v0.7.1 tag (latest). So I use the git version for now.
> add spi_display with mipidsi example for rp pico

- embassy-stm32/src/sai/mod.rs
As per RM0468, p.2291:
This also adds a FIFO flush on SAI init, just like the ST HAL.
> Flush SAI FIFO on init and disable

- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/sai/mod.rs
- examples/stm32h7/src/bin/sai.rs
Previously, when starting the SAI (and its ring buffer + DMA channel), then writing data to the ring buffer later, the SAI DMA has already been running for some (undeterministic) amount of time. It only makes sense to start the DMA after there is already data in the transmit ring buffer present.
This PR disables `start` for SAI in transmit mode, and starts the DMA just after the transmit ring buffer was filled with an initial amount of data.
> Disallow SAI start without an initial write

- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/dma/ringbuffer/mod.rs
- embassy-stm32/src/sai/mod.rs
Below is a use case, where there is a `channel` that gets supplied with audio sample arrays to play on `sai`.
As soon as there is an overrun error, `sai` shall be dropped and freshly created, so that it doesn't play garbage.
```rust
let mut sai = make_a_new_sai();
let mut renew_sai = false;
loop {
if renew_sai {
renew_sai = false;
drop(sai);
sai = make_a_new_sai();
}
let channel_receive_fut = channel.receive();
let sai_error_fut = sai.write_error();
let samples = match select(channel_receive_fut, sai_error_fut).await {
Either::First(x) => x,
Either::Second(_) => {
renew_sai = true;
continue;
}
};
sai.write(&samples).await.unwrap();
}
```
> Add a function that waits for any SAI/ringbuffer write error

- embassy-stm32/src/rcc/bd.rs
This is needed for #3515 when the LPTIM is supposed to be clocked by the LSE.
> Enable user to choose to pass lse clock to peripherals

- embassy-stm32/build.rs
- embassy-stm32/src/lib.rs
- embassy-stm32/src/spdifrx/mod.rs
- examples/stm32h723/.cargo/config.toml
- examples/stm32h723/Cargo.toml
- examples/stm32h723/build.rs
- examples/stm32h723/memory.x
- examples/stm32h723/src/bin/spdifrx.rs
This adds support for the STM32 SPDIFRX peripheral.
Requires https://github.com/embassy-rs/stm32-data/pull/518
> Support for STM32 SPDIFRX

- embassy-stm32/Cargo.toml
- embassy-stm32/src/lib.rs
- examples/stm32h5/src/bin/adc.rs
This updates `stm32-metapac` to include changes enabling the ADC peripherals in the STM32Hxx family of parts. An example has also been added and was tested as working on an Nucleo-H533 dev board.
Fixes #2938
> STM32H5xx ADC

- embassy-sync/CHANGELOG.md
- embassy-sync/src/waitqueue/atomic_waker.rs
Multi-core systems might want to use different locks than a critical section. While AtomicWaker isn't too complex, I'm hoping we don't need to duplicate it.
> Generalize AtomicWaker

- embassy-stm32/Cargo.toml
- embassy-stm32/src/usb/otg.rs
- embassy-usb-synopsys-otg/src/lib.rs
- embassy-usb-synopsys-otg/src/otg_v1.rs
The RM says we have to process STUP (and therefore clear CNAK to start the data stage)
in the DOEPINT STUP interrupt. Seems doing it in RXFLVL when we receive the data is
too early. This makes it work consistently on all chips, so the quirk is no longer needed.
Fixes #3493
Fixes #3459
- **otg: fix build with defmt enabled.**
- **otg: improve trace logging, print bytes as hex.**
- **otg: fix corruption in CONTROL OUT transfers in stm32f4.**
> otg: fix corruption in CONTROL OUT transfers in stm32f4.       

- embassy-usb/src/class/mod.rs
- embassy-usb/src/class/uac1/class_codes.rs
- embassy-usb/src/class/uac1/mod.rs
- embassy-usb/src/class/uac1/speaker.rs
- embassy-usb/src/class/uac1/terminal_type.rs
- examples/stm32f4/Cargo.toml
- examples/stm32f4/src/bin/usb_uac_speaker.rs
- examples/stm32h5/src/bin/usb_uac_speaker.rs
Hello,
I implemented a UAC 1.0 device, but this required some extensions and fixes to the implementation of `embassy-usb`.
Some changes are taken from or inspired by https://github.com/embassy-rs/embassy/pull/2736.
Here is an example of where this is in use (still rough): https://github.com/blus-audio/firmware-rs
The feedback endpoint is not yet in use.
Features:
- Added usage type and synchronization type settings for endpoints. This is only relevant for isochronous endpoints.
- Added `extra_fields` that can be appended to an endpoint descriptor. This is required for UAC (e.g. `bRefresh` and `bSynchAddress` fields for UAC1.0)
- Added functionality for allocating endpoints and writing their descriptors separately. This is required, because in UAC1.0, the `synch` endpoint must follow the …
> feat(usb): Prepare `embassy-usb` for USB Audio, and add USB Audio Class 1.0 (playback only)

- embassy-stm32/src/low_power.rs
- embassy-stm32/src/rcc/bd.rs
- embassy-stm32/src/rtc/low_power.rs
- embassy-stm32/src/rtc/mod.rs
- embassy-stm32/src/rtc/v3.rs
Adding low-power support for the stm32u0. This PR depends on embassy-rs/stm32-data#540.
I can measure ~9uA for a blinky with 0.5Hz LED frequency. During stop the power consumption is ~2uA when the LED is off. The measurements are on my Nucleo-U083RC.
> low-power: add support for stm32u0

- embassy-stm32/Cargo.toml
- embassy-stm32/src/fmt.rs
- embassy-stm32/src/rcc/c0.rs
- embassy-stm32/src/rcc/f013.rs
- embassy-stm32/src/rcc/f247.rs
- embassy-stm32/src/rcc/g0.rs
- embassy-stm32/src/rcc/g4.rs
Add new feature `unchecked-overclocking` to disables all assertions during RCC register initialization.
> feat: Add new feature to enable overclocking

- embassy-stm32/Cargo.toml
- embassy-stm32/src/flash/u5.rs
This addresses the problem in https://github.com/embassy-rs/embassy/issues/3561
In the current implementation of `blocking_erase_sector` for U5 there is no selection of the flash bank that contains the page to be erased.
As a consequence, only pages in bank 1 can be erased.  If blocking_erase_sector is called for a page in bank 2, then the corresponding page in bank 1 is cleared.
The implementation mimics what has already implemented for H5.
This same problem has already been raised in the past, and exactly this fix has been proposed, but never implemented.  See here
https://github.com/embassy-rs/stm32-data/pull/464#issuecomment-2050792236
At the moment the bank swap is not supported
> STM32U5: Add flash bank selection when erasing a sector

- embassy-stm32/src/usart/mod.rs
Currently the `data_bits` field of STM32 USART configuration is ignored and the USART is always configured for an 8-bit word size.  This implements the actual selection of the word size and adds a 7-bit mode (usually seen in combination with parity and ASCII-only protocols).
> stm32/usart: Implement data bit selection

- embassy-usb-dfu/Cargo.toml
- embassy-usb-dfu/src/consts.rs
- embassy-usb-dfu/src/dfu.rs
This commit adds logging to embassy-dfu-usb which helps with debugging issues such as https://github.com/embassy-rs/embassy/issues/3536. It also cleans up a few repeated code blocks and avoid re-initialising the local buffer for every iteration.
> embassy-dfu-usb: Improve debuggability

- embassy-stm32/src/dma/ringbuffer/mod.rs
When using `write_immediate()` with data that is shorter than the capacity of the ring buffer, it should be shifted towards the end of the buffer. Then, when the next block of data is appended to the buffer, there is no gap between the first block and the second block.
> Right-align `write_immediate()` in ring buffers

- embassy-stm32/src/timer/complementary_pwm.rs
- embassy-stm32/src/timer/low_level.rs
- embassy-stm32/src/timer/simple_pwm.rs
With STM32 32 bits timers, the max_compare_value (AKA, ARR register) can currently be set greater than u16::MAX, which leads to the following assert!(max < u16::MAX as u32) in max_duty_cycle() when setting up a 1 kHz SimplePwm on 84 MHz MCU.
The issue is fixed by computing an appropriate prescaler value so that max_compare_value fits into 16 bits.
Note that with current code, the prescaler computation is pretty useless as it always returns 0 (unless you manage to overclock an STM32 above 4 GHz ? ;-) )
> stm32/timer: avoid max_compare_value >= u16::MAX

- embassy-rp/src/otp.rs
Part of #3241 efforts, add write counterparts to OTP read ECC word and read raw word functions. I feel like the OTP should be refactored to be more similar to other peripherals in embassy-rp, but this would serve as a temporary enhancement.
> RP235X Add OTP write functions

- embassy-usb/src/builder.rs
- embassy-usb/src/descriptor.rs
Allows a custom bcdusb version like 1.1 (0x011) but leaves the default to 2.0/2.1
> allow custom bcd usb version

- examples/rp/src/bin/pwm.rs
- examples/rp23/src/bin/pwm.rs
- examples/rp23/src/bin/pwm_tb6612fng_motor_driver.rs
desired frequency was off, much more precise result that way
> correct rp pwm dutycycle examples: desired frequency

- embassy-rp/src/spi.rs
- examples/rp/src/bin/spi_sdmmc.rs
- examples/rp23/src/bin/spi_sdmmc.rs
- **Add `set_config` method to RP SPI driver**
- **examples/rp: update sdmmc.**
> Add set_config method to RP SPI driver (rebased #3419)

- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
- examples/stm32l1/src/bin/usart.rs
As discussed in #1289 adding support to changing the baud rate for stm32 usart.
> stm32/usart: Changing baud rate

- docs/pages/faq.adoc
- embassy-boot-nrf/README.md
- examples/boot/bootloader/stm32wb-dfu/README.md
Enhances documentation for bootloader in various places:
- Improves STM32 embassy-usb-dfu example documentation with clearer setup and usage instructions
- Adds troubleshooting FAQ section for common bootloader failures
- Documents the integration between softdevice and embassy-boot-nrf
> docs: improve bootloader documentation

- embassy-nrf/src/nfct.rs
- **nrf/nfct: set correct frame delay timing.**
- **nrf/nfct: use the right error register for rx and tx.**
> nrf/nfct: two fixes

- tests/nrf/Cargo.toml
nrf52832 is pretty much full, but I don't see any reason for that to be the status quo.
This PR frees up memory so that https://github.com/embassy-rs/embassy/pull/3622 should be able to compile.
> Shrink task arena of nrf tests

- embassy-usb-dfu/src/dfu.rs
- examples/boot/bootloader/stm32wb-dfu/src/main.rs
This PR improves USB DFU support by documenting correct MSOS header usage in an example and by using the correct function headers in all cases.
> Improve USB DFU support

- embassy-net/src/lib.rs
This makes the [existing constructors of `embassy_net::Config`](https://docs.embassy.dev/embassy-net/git/default/struct.Config.html#impl-Config) `const`, so they can be used in a `const` context. I don't think this would hinder future evolution of the type or the constructors, and it would make these a little bit easier to use.
> fix(embassy-net): make the `Config` constructors `const`

- embassy-nrf/src/lib.rs
- embassy-nrf/src/reset.rs
This adds free function helpers for the Reset peripheral to `embassy-nrf` so that it's easier to handle the checking of reset reasons and controlling the network core without having to use the `pac` directly.
It collects the reset reasons under a bitflag so that it can be more easily checked in binaries, instead of constructing a massive if else.
e.g. of reset reasons
```rust
use embassy_nrf::reset::{self, ResetReason};
for reason in reset::read_reasons().iter() {
let reas = match reason {
ResetReason::RESETPIN => "Reset Pin",
ResetReason::DOG0 => "Application watchdog timer 0",
ResetReason::CTRLAP => "Application CTRL-AP",
ResetReason::SREQ => "Application soft reset",
ResetReason::LOCKUP => "Application CPU lockup",
ResetReason::OFF => "Wakeup from System OFF when wakeup is triggered by …
```
> nrf: Add RESET operations helpers for the nrf5340

- embassy-stm32/src/opamp.rs
This PR adds the ability to use following opamp/ADC combinations when the opamp is configured in external output mode.
These are documented in the STM32G4 reference manual but currently missing in Embassy.
- `OPAMP3` with `ADC1` (output pin is `PB1`)
- `OPAMP4` with `ADC1` (output pin is `PB12`)
- `OPAMP6` with `ADC2` (output pin is `PB11`)
> Add missing opamp external outputs for STM32G4

- embassy-stm32/src/rcc/f013.rs
Fixes #3651
Tested on STM32F072CB.
> STM32F0 fix using HSI48 as SYSCLK on devices with CRS

- embassy-nrf/src/lib.rs
- embassy-nrf/src/nfct.rs
- embassy-nrf/src/power.rs
Connect the existing HAL functions
> Add System Off and Wake on Field

- embassy-rp/src/pio_programs/i2s.rs
Originally, `PioI2sOut::new()` hard coded the system clock frequency as 125 MHz; this commit instead has the function use `crate::clocks::clk_sys_freq()` to support other clock frequencies.
> Rp fix pio i2s clock

- embassy-executor/src/raw/mod.rs
- embassy-executor/src/raw/run_queue_atomics.rs
- embassy-executor/src/raw/run_queue_critical_section.rs
- embassy-executor/src/raw/state_atomics.rs
- embassy-executor/src/raw/state_atomics_arm.rs
- embassy-executor/src/raw/state_critical_section.rs
Waker::wake previously used two critical sections on targets without atomic CAS.
- One to update the task state
- One to call `RunQueue::enqueue`
This PR refactors `State::run_enqueue` to take a closure instead of returning a boolean. The closure is called when we previously returned `true`. This change allows as to run the closure in a critical section, saving the cost of locking a second time.
> Only lock once to wake a task

- embassy-executor/CHANGELOG.md
- embassy-executor/Cargo.toml
- embassy-executor/src/raw/mod.rs
- embassy-executor/src/raw/state_atomics.rs
- embassy-executor/src/raw/state_atomics_arm.rs
- embassy-executor/src/raw/state_critical_section.rs
- embassy-executor/src/raw/timer_queue.rs
- embassy-executor/tests/test.rs
- embassy-time-driver/src/lib.rs
- embassy-time-queue-driver/src/lib.rs
- embassy-time-queue-driver/src/queue_integrated.rs
- embassy-time/Cargo.toml
- embassy-time/src/timer.rs
This PR places the mapping of a TQI to a queue the responsibility of the timer queue implementation. The existing drivers should be fine, because they use a single queue, multi-queue implementations need to handle some additional tasks.
> Remove special handling of integrated timer queues and items

- embassy-executor/Cargo.toml
- embassy-executor/src/raw/mod.rs
- embassy-executor/src/raw/state_atomics.rs
- embassy-executor/src/raw/state_atomics_arm.rs
- embassy-executor/src/raw/state_critical_section.rs
- embassy-executor/tests/test.rs
This PR sets `RUN_QUEUED` unconditionally, which results in a tiny perf win:
- ESP32-S3 (atomic CAS): `16652/100` to `15849/100` cycles.
- ESP32-S2 (critical section): `26641/100` to `25815/100` cycles.
Based on #3628
> Unconditionally set `RUN_QUEUED`

- embassy-executor/src/raw/mod.rs
- embassy-executor/src/raw/run_queue_atomics.rs
- embassy-executor/src/raw/run_queue_critical_section.rs
- embassy-executor/src/raw/state_atomics.rs
- embassy-executor/src/raw/state_atomics_arm.rs
- embassy-executor/src/raw/state_critical_section.rs
- embassy-executor/tests/test.rs
This PR replaces `poll_fn` to a more "inert" one, making it okay to poll `!SPAWNED` tasks. I guess this PR changes the trace output for awoken-exited tasks, but it's probably for the better.
ESP32-S3: cycle count goes from `15749/100` to `14745/100`
ESP32-S2: cycle count goes from `25815/100` to `24809/100`
> Allow polling exited tasks

- embassy-stm32/src/ospi/mod.rs
- embassy-stm32/src/qspi/mod.rs
- examples/stm32f7/src/bin/qspi.rs
- examples/stm32h7b0/src/bin/ospi_memory_mapped.rs
The naming convention is to prefix blocking functions with blocking. As both command implementations are blocking the async for the ospi implementation should also be dropped.
> stm32/(o|q)spi: command naming convention fix

- .github/ci/build-xtensa.sh
For compatibility reasons with the released esp-hal, we're reverting espup to install 1.82 by default. This PR ensures that the embassy CI survives this change.
> Force use 1.83 for Xtensa

- embassy-futures/src/select.rs
This add `is_x()` methods on all `EitherN` enums to more concisely check which future from a `SelectN` completed first, without accessing the value. 
I often use signals for canceling futures "from within" and it's not always needed to access the value of the future, only to know if the signal `wait` future completed first. This can of course also be achieved using `matches!`, `if-let` or `let-else`, but the methods added in this PR make this a bit more concise.
> Add is_x() methods for all EitherN enum variants

- embassy-boot-rp/src/lib.rs
This PR exposes the `embassy-boot` `BootLoader` `State` in `embassy-boot-rp` [identically to](https://github.com/embassy-rs/embassy/blob/main/embassy-boot-stm32/src/lib.rs#L14-L15) `embassy-boot-stm32`.
This is required to `embassy-usb-dfu` Detach.
> Expose `rp` bootloader state like `stm32`

- embassy-stm32/src/gpio.rs
- embassy-stm32/src/spi/mod.rs
This PR makes the slew rate/speed for SCK and MOSI configurable and changes the default speed to `Medium`.
> embassy-stm32: SPI slew rate configuration

- embassy-time-queue-driver/Cargo.toml
- embassy-time-queue-driver/src/lib.rs
- embassy-time/CHANGELOG.md
- embassy-time/Cargo.toml
Hopefully this can reduce breakages caused by the version bump. I believe we still have to release embassy-time as a major upgrade, but migration should be just a bit smoother.
HALs can still override these, as they can override the features set on ETQD - they are allowed to just do their own thing. But now the users really don't have to import ETQD.
> Add generic-queue-* features back to embassy-time

- embassy-stm32/src/ucpd.rs
- examples/stm32h5/src/bin/usb_c_pd.rs
Also adds USB PD resistor software trimming for H5
> STM32h5 UCPD example

- embassy-stm32/src/lib.rs
- SharedData is now repr C.
- The init flag is is now written with a known value as soon as possible. I'm not sure whether using the AtomicUsize this way is sound at all, but writing to it sooner at least gives less chance of things going wrong I guess.
> stm32: Improve dualcore safety

- embassy-nrf/src/lib.rs
- examples/nrf54l15/.cargo/config.toml
This unlocks debugger access to the application core, if it is also unlocked in UICR.
> nrf54l: Allow debug access from firmware side

- ci.sh
- embassy-usb/src/class/uac1/speaker.rs
- embassy-usb/src/types.rs
Trying to build embassy-usb before this fix:
```
cargo build --features log
Compiling embassy-usb v0.3.0 (/home/nine/vc/rust/embassy_fmt_fixes/embassy-usb)
error[E0277]: `[u8]` doesn't implement `Display`
--> src/class/uac1/speaker.rs:583:53
|
583 |                 endpoint_address, control_selector, data
|                                                     ^^^^ `[u8]` cannot be formatted with the default formatter
|
= help: the trait `Display` is not implemented for `[u8]`, which is required by `&[u8]: Display`
= note: in format strings you may be able to use `{:?}` (or {:#?} for pretty-print) instead
= note: this error originates in the macro `$crate::__private_api::format_args` which comes from the expansion of the macro `debug` (in Nightly builds, run with -Z macro-backtrace for more …
```
> embassy-usb: fix building with optional log feature

- embassy-time-driver/Cargo.toml
- embassy-time-driver/src/lib.rs
The ignored example had some compilation issues (when running `cargo test`).
> fix embassy-time-driver example

- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
- examples/stm32g0/src/bin/onewire_ds18b20.rs
The 1-Wire bus requires the ability to read data while transmission is in progress to detect if a sensor pulls the bus to a low level (logic 0).
This pull request adds a new enum `HalfDuplexReadback` with `Readback` variant that keeps receiver enabled during transmission. Half duplex can be newly created with `BufferedUart` (#3278). A simplified example, based on the RP example, has been added to demonstrate how to use this feature with the DS18B20 temperature sensor.
> stm32/usart: configurable readback for half-duplex to support 1-wire + ds18b20 example

- embassy-stm32/src/usb/usb.rs
I scoured the device datasheets of the following devices. *All* state a `t_STARTUP` of max 1µs.
- STM32U073x8/B/C
- STM32H503xx
- STM32G0B1xB/xC/xE
- STM32F722xx STM32F723xx
- STM32F405xx, STM32F407xx
- STM32F21xxx
- STM32C071x8/xB
- STM32L462CE STM32L462RE STM32L462VE
- STM32L053x6 STM32L053x8
- STM32F303xD STM32F303xE
- STM32F102x8, STM32F102xB
- STM32F072x8 STM32F072xB
I did not find any device with a differently specified `t_STARTUP`.
Here is an example:
> STM32: set USB initialization delay to 1µs

- embassy-stm32-wpan/Cargo.toml
- embassy-stm32-wpan/src/consts.rs
- embassy-stm32-wpan/src/lib.rs
- embassy-stm32-wpan/src/sub/ble.rs
- embassy-stm32-wpan/src/sub/sys.rs
- embassy-stm32-wpan/src/tables.rs
- examples/stm32wb/src/bin/gatt_server.rs
A large part of the current implementation has been reverse engineered from Application Note AN5289, and from consultation of the stm32_copro library.
Because of this, there may be a few inaccuracies in the doc comments that have been added.
> add documentation for the BLE feature of the embassy-stm32-wpan crate

- cyw43/src/control.rs
- cyw43/src/lib.rs
Exports the ScanType enum, which is needed to build the ScanOptions struct
> Fix ScanType enum export

- examples/nrf52840/src/bin/pwm_sequence_ws2812b.rs
Small documentation note to save the next person having to break out their Saleae to look at signal voltages
> Add note for nRF52840-dk board details

- embassy-stm32/Cargo.toml
- embassy-stm32/src/flash/g.rs
- embassy-stm32/src/flash/mod.rs
Integration of changes made in embassy-rs/stm32-data/pull/556: Addition of dual flash bank support for G0.
- Setting of bank select for erase bit in erase sector
- Waiting for both busy flags 
Would be nice to have some feedback on how to deal with the now diverging options/registers other than the conditional compilation
> embassy-stm32 support g0 second flash bank

- embassy-nrf/Cargo.toml
Hi there,
This is another small fix to hopefully enable embassy-nrf to be built without a time driver.
This should allow embassy-nrf to not pull in embassy-time if a time driver or time feature is not needed.
As far as I could tell the time feature of embassy-embedded-hal is used only for spi delays, and so those would become panics when embassy-nrf is built without a time feature. This isn't ideal, but a better implementation would probably involve a shared bus that takes a delay implementation, which would be a PR for another day :)
Rust features are hard to reason about so let me know if anything needs changing.
> Correctly gate `time` feature of embassy-embedded-hal in embassy-nrf

- embassy-stm32/Cargo.toml
- embassy-stm32/src/dts/mod.rs
- embassy-stm32/src/dts/tsel.rs
- embassy-stm32/src/lib.rs
- examples/stm32h5/src/bin/dts.rs
Only PCLK-driven operation is supported. Similarly, only software triggering is supported.
> stm32: Implement reads of DTS peripheral

- embassy-rp/src/gpio.rs
In case of OpenDrain Output, a Pull-Up resistor *MUST* be present on the signal. Usually it is a physical resistor on the board, but why not using the RP internal PU capability for it ? Could be handy for board with forgotten PU...
Note: Pull-Down is irrelevant here, so it is not proposed...
> `embassy-rp`: add `set_pullup()` for `OutputOpenDrain`

- embassy-stm32/src/can/bxcan/mod.rs
I want to split up my CAN interface on my STM32 to handle sending and receiving in different tasks. However I also want to be able to change the receive filters while the peripheral is split. Currently the `modify_filters` method is only available on the combined struct. This PR also makes it available on `BufferedCan`, `CanRx`, and `BufferedCanRx`.
From what I could tell from the reference manual and implementation, the filter registers are only used from the `MasterFilter` struct. So I think it should be fine to make them also accessible from the split off `Rx` half, since there is still only one struct that can access them.
> feat: STM32 Allow to modify the receiver filters from `BufferedCan`, `CanRx`, and `BufferedCanRx`

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- examples/stm32u0/src/bin/spi.rs
- examples/stm32u5/src/bin/blinky.rs
Before we'd generate all pins Px0..Px15 for each GPIOx port. This changes
codegen to only generate singletons for actually-existing pins.
(AFs were already previously filtered, so these non-existing pins were already mostly useless)
> stm32: generate singletons only for pins that actually exist.

- embassy-stm32/src/qspi/mod.rs
The current QSPI synchronous read function uses tcf!=1 and ftf!=1 as the polling condition. However, this condition fails when the transfer is complete and the FIFO is not full, as both tcf and ftf will be 0. This causes the read loop to block indefinitely, leaving data unread in the FIFO.
This PR resolves the issue by using the correct polling condition: tcf!=1 and flevel==0. This ensures the loop terminates only when the transfer is complete and the FIFO is empty.
Monitoring the flevel register during the read operation confirmed that it remained at 15 (FIFO_SIZE-1) when the issue occurred, validating the hypothesis.
> FIX: QSPI synchronous read operation hangs when FIFO is not full

- embassy-stm32/build.rs
- embassy-stm32/src/i2s.rs
Use the correct peripheral clock for calculating dividers.
> Fix STM32F4 I2S clock calculations

- ci.sh
- embassy-stm32/src/qspi/mod.rs
- examples/stm32l432/.cargo/config.toml
- examples/stm32l432/Cargo.toml
- examples/stm32l432/README.md
- examples/stm32l432/build.rs
- examples/stm32l432/src/bin/qspi_mmap.rs
This PR add `enable_memory_map`  for qspi HAL.
Included example is tested in the `stm32l432kcu6` device.
> feat: mmap mode for qspi and example

- embassy-stm32/src/flash/f1f3.rs
Fix for flash erase not working on STM32F3 series (tested on STM32F303K8 specifically).
STM32F3xx series also needs a wait of at least one clock cycle before reading the BSY bit during a flash erase - previously this was only applied to STM32F1xx series.
This was causing an erase failure due to the `wait_ready_blocking` not actually waiting until the erase operation is complete, and as a result the EOP bit was not set when checked.
> stm32: flash: fix flash erase on stm32f3xx series

- embassy-nrf/src/twim.rs
Similar to twis.rs they is no reason as far I can tell to stay in async_wait when an error occurs.
This helped to recover from some bus interference I had without putting with_timeout everywhere.
> nrf twim return errors in async_wait instead of waiting indefinitely 

- embassy-stm32/src/usb/usb.rs
Hi. For me embassy-stm32 does not compile for stm32f103 with log feature
It seems EndpointAddress does not implement LowerHex trait. I suggest simply replacing the call with debug.
Or I can create a PR with LowerHex and UpperHex implementations for EndpointAddress
> Fix unsupported trace! call for EndpointAddress

- embassy-sync/src/priority_channel.rs
Added remove_if to priority channel. This allows removing items from the queue if there is a match in the predicate.
You can also do this on a sender, receiver and the channel directly itself.
In my sample code I use the following:
```
let send_ble_queue = QUEUE_CHANNEL.sender();
send_ble_queue.remove_if(|i| { i.handle == handle && i.is_single_instance() });
```
This is for my issue here: https://github.com/embassy-rs/embassy/issues/3431
> Added remove_if to priority channel

- embassy-stm32/src/can/fd/peripheral.rs
I'm using dual-core STM32H747BI.
The issue is that this method simply wrongly negates its parameter. 
In RM0399, it's stated that TXP bit _enables_ pause. The function negates boolean argument, so `set_transmit_pause(false)` will inevitably enable pause.
RM0399, page 2679:
> stm32/can: fix wrong negation of fdcan set_transmit_pause function parameter

- embassy-stm32/src/cryp/mod.rs
- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/dma/gpdma.rs
- embassy-stm32/src/hash/mod.rs
- embassy-stm32/src/timer/low_level.rs
- embassy-stm32/src/timer/simple_pwm.rs
Currently `waveform_chx` function in  `SimplePwm` assume that all timer are 16-bit, which will cause some unexpected issue ( e.g. https://github.com/embassy-rs/embassy/issues/2522)
This PR add 32-bit timer support for waveform function by changing the input data from `&[u16]` to more general `&[u8]`, and use unsafe transmute to prepare `&[u16]` or `&[u32]` based on the timer size for DMA.
Approach in this PR is far from perfect. I think `constant generic type` may be a better solution, but will introduce significant changes to current timer HAL in `embassy-stm32`
> feat: Add 32-bit timer support for waveform function

- embassy-stm32/build.rs
With feature embassy-stm32/split-pa0, I got the error ``error[E0425]: cannot find value `pin_name` in this scope``.
> Fix issue with enabled split-pxy feature

- embassy-time/Cargo.toml
Current doc says if there's If no `generic-queue-*` feature is enabled, a default of 64 timers is used. But according to:
https://github.com/embassy-rs/embassy/blob/169f9c27aa33a279aad51a92b52fc047a54b82af/embassy-time-queue-utils/src/lib.rs#L5-L13
the `queue_integrated::Queue` is used in this case. So the default 64 timers actually do nothing:
https://github.com/embassy-rs/embassy/blob/169f9c27aa33a279aad51a92b52fc047a54b82af/embassy-time-queue-utils/src/queue_generic.rs#L112-L119
> doc: fix embassy-time doc

- embassy-rp/src/clocks.rs
In the RP2350 the watchdog tick generator was split from the main timer tick generator and now lives in the TICKS register block. Previously, embassy-rp enabled the TIMER0 tick generator but not the WATCHDOG tick generator. As a result the watchdog peripheral did not work as expected. This PR fixes this problem by enabling both tick generators inside the `init` function.
This also poses the more general question of whether the other tick generators should also be enabled during initialization.
> fix: enable RP2350 watchdog tick generator

- embassy-stm32/src/time.rs
fixes #3587 
> can you send a PR adding the Display impl, and an entry to ci.sh so this doesn't break again inthe future?
how should ci.sh be modified?
> stm32: impl Display for time::Hertz

- embassy-stm32/build.rs
- embassy-stm32/src/rcc/f013.rs
STM32F107 has a two more PLLs than F013, which means using `f013.rs` config options doesn't let us configure the entire RCC.
My use case is to use STM32F107 for ethernet with an external HSE. 
This PR adds a special case for F107 with a fuller RCC config.
> Full RCC support for STM32F107

- embassy-rp/Cargo.toml
Avoid docs.rs build failures like https://docs.rs/crate/embassy-rp/0.3.0/builds/1609962
> Set embassy-rp target in docs-rs metadata

- embassy-sync/src/channel.rs
- embassy-sync/src/priority_channel.rs
- embassy-sync/src/pubsub/mod.rs
- embassy-sync/src/zerocopy_channel.rs
Calling clear() on `Channel`, `PriorityChannel`, `PubSub`, `zerocopy_channel::Channel` should wake the wakers of senders, as receive() do.
> embassy-sync: fix clear() to wake senders

- embassy-rp/src/i2c.rs
- embassy-rp/src/i2c_slave.rs
There are some non-compliant devices that respond to reserved I2c addresses. rp2040 behaves sanely for these addresses, so let's just allow using them.
Closes #3809
> remove checks for reserved I2c addresses

- embassy-stm32/src/ucpd.rs
On STM32H5 (with GPDMA), I saw some USB PD reception appearing to be empty, when packets were arriving quickly back-to-back.
When calling `receive` on the UCPD driver, you would usually provide a buffer big enough to cover the biggest standard packet type (e.g. 30 byte). The DMA will store data in the buffer, until its number of transfers are reached, even if this means handling multiple UCPD requests.
It turns out that the DMA got two requests from the UCPD peripheral during one receive operation and advanced the memory pointer by itself. The UCPD driver did not stop the DMA after receiving a full message. Multiple messages ended up in the same buffer, concatenated.
This PR stops the DMA after receiving a packet, or a hard reset.
Tested with …
> Fix STM32H5 UCPD reception

- embassy-stm32/src/dma/dma_bdma.rs
- embassy-stm32/src/sai/mod.rs
In [sai/mod.rs](../blob/main/embassy-stm32/src/sai/mod.rs), modified `sai_v3_2pdm` and `sai_v3_4pdm` placement in the `#cfg[...]` conditional compilation statements to allow the corresponding L5 and H7 stm32 chips to use external SAI sync, as stated available in the ST reference manuals.
In [dma_bdma.rs](../blob/main/embassy-stm32/src/dma/dma_bdma.rs), added code to reset the complete_count variable defined in the global channel `STATE` defined in [dma/mod.rs](../blob/main/embassy-stm32/src/dma/mod.rs). For some reason re-creating a BDMA channel resets its global state, but re-creating a DMA channel does not, making BDMA peripherals like SAI4 recoverable after dropping their `Sai<'_, SAI4, W>` instance (like in #3205), but not DMA peripherals like SAI1 for example. One consequence of this …
> Allow stm32 H7 and L5 families to use external SAI sync & allow recovering after dropping a DMA channel

- embassy-stm32/src/eth/generic_smi.rs
- examples/stm32f4/src/bin/eth.rs
- examples/stm32f7/src/bin/eth.rs
- examples/stm32h5/src/bin/eth.rs
- examples/stm32h7/src/bin/eth.rs
- examples/stm32h7/src/bin/eth_client.rs
- examples/stm32h7/src/bin/eth_client_mii.rs
- tests/stm32/src/bin/eth.rs
Currently `GenericSMI` can't detect ethernet PHY address and will stuck in eternal loop if address is incorrect. This PR adds automatic detection by probing all addresses from 0 to 31 with fixed attempt count and delay. Automatic detection enabled if `GenericSMI` was created with address `0xFF`
> STM32: Option to detect Ethernet PHY address automatically

- embassy-stm32/src/eth/generic_phy.rs
- embassy-stm32/src/eth/mod.rs
- embassy-stm32/src/eth/v1/mod.rs
- embassy-stm32/src/eth/v2/mod.rs
- examples/stm32f4/src/bin/eth.rs
- examples/stm32f4/src/bin/eth_compliance_test.rs
- examples/stm32f7/src/bin/eth.rs
- examples/stm32h5/src/bin/eth.rs
- examples/stm32h7/src/bin/eth.rs
- examples/stm32h7/src/bin/eth_client.rs
- examples/stm32h7/src/bin/eth_client_mii.rs
- tests/stm32/src/bin/eth.rs
We shouldn't use `unsafe` to mark merely "dangerous" actions, only actions that
actually cause UB.
> stm32/eth: rename PHY->Phy, GenericSMI -> GenericPhy. Remove unneeded unsafes.

- embassy-net/src/udp.rs
If the udpsocket send methods are given a buffer larger than the udp payload buffer the methods loop await forever trying to send and getting `BufferFull`.
Check and early-return if udp::send methods receive a buffer too large to ever be sent.
smoltcp used to distinguish these but stopped [here](https://github.com/smoltcp-rs/smoltcp/commit/b7871e4e5704963e84b0a5eea04c4601162b4703#diff-528cd95c12007e0dd82ca1181897ed74a8e2dedfd8ca2d151d4f133f785023b2L82). I'm not sure why. You can still the the remnant in the now invalid comment for `smoltcp::socket::udp::Socket::send` mentioning `Truncate`. I don't know if it would be preferred to update smoltcp or leave the fix here in `embassy-net`.
> Return Truncate error instead of looping forever on udp send.

- embassy-net/src/udp.rs
Followup from https://github.com/embassy-rs/embassy/pull/3804
> Fix udp send pt2

- embassy-rp/src/adc.rs
The ADC channel offset and temperature sensor channel were only correct for RP2040 and RP235XA, this PR makes them also correct for RP235XB.
Based on [this table in the RP2350 datasheet](https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf#%5B%7B%22num%22%3A1067%2C%22gen%22%3A0%7D%2C%7B%22name%22%3A%22XYZ%22%7D%2C115%2C742.498%2Cnull%5D).
> Correct ADC channels for RP235XB

- docs/pages/getting_started.adoc
Replaces "hare" with "are" in "If you hare having issues when running `+cargo run --release+`, please check the following:"
> Fix typo in getting started docs

- embassy-time/src/timer.rs
This just adds a section about cancel safety to the embassy-time Ticker struct and the corresponding method to get a Future for the next tick. 
When looking at the source its quite clear that the Ticker is cancel safe, but it would be nice to have a note in the docs, so people don't have to think about it.
> Add cancel safety notes to Ticker

- embassy-stm32/src/rcc/f247.rs
A `TODO` in embassy-stm32/src/rcc/f247.rs notes the need to support PLLM and plli2s_src for f4 chips which support them; this commit aims to rectify that, though there may be more that must be done (e.g., I'm not sure if this applies only to f4 chips or extends to f7, etc.). See #3681.
> set PLLI2S M and SRC for f4 chips which support it

- embassy-nrf/src/lib.rs
The nRF52833 has an internal adjustable voltage regulator. This is very similar to the nRF52840 so this commit is just 3 lines to enable and reuse that code. Tested on a custom board.
> nRF52833: configure internal LDO

- embassy-time-driver/src/lib.rs
- embassy-time/src/instant.rs
A bit of ghidra-browsing revealed that embassy_time_driver::now is not always inlined, if ever - calling `embassy_time::Instant::now()` got compiled to 3 different calls in my application until it reached my implementation.
> Allow inlining on time driver boundary

- embassy-usb/src/class/cdc_ncm/mod.rs
It seems changed in Rust https://github.com/rust-lang/rust/pull/135003.
The compiler suggest to use `core::mem::copy_nonoverlapping`.
But that seems not exists so I used `core::ptr::copy_nonoverlapping` which is used in other parts in Embassy.
Replaced `core::intrinsics::copy_nonoverlapping` with the `core::ptr::copy_nonoverlapping`.
This fixed this warning.
```
Compiling embassy-usb v0.4.0 (embassy/embassy-usb)
warning: use of deprecated module `core::intrinsics`: import this function via `std::mem` instead
--> embassy/embassy-usb/src/class/cdc_ncm/mod.rs:17:23
|
17 | use core::intrinsics::copy_nonoverlapping;
|                       ^^^^^^^^^^^^^^^^^^^
```
> embassy-usb: fix `core::intrinsics` deprecate warning in nightly.

- embassy-executor/src/spawner.rs
Add more detail to Debug, Display and defmt::Format for SpawnError::Busy, to point users to the spawn_pool feature of tasks, as it can be unclear currently getting just an "Error - Busy" message at runtime.
> improve SpawnError::Busy message

- embassy-executor-macros/src/macros/main.rs
The current implementation of `embassy_executor::main` and generated code causes `clippy` to complain even when using an empty function (for demonstration purposes).
```
error: future cannot be sent between threads safely
--> src/main.rs:22:1
|
22 | #[embassy_executor::main]
| ^^^^^^^^^^^^^^^^^^^^^^^^^ future returned by `____embassy_main_task` is not `Send`
|
note: captured value is not `Send`
--> src/main.rs:23:15
|
23 | async fn main(_spawner: Spawner) {}
|               ^^^^^^^^ has type `embassy_executor::Spawner` which is not `Send`
= note: `*mut ()` doesn't implement `core::marker::Send`
note: captured value is not `Send`
--> src/main.rs:23:15
|
23 | async fn main(_spawner: Spawner) {}
|               ^^^^^^^^ has type `embassy_executor::Spawner` which is not `Send`
= note: `*mut …
```
> Disable clippy error around generated main function

- embassy-rp/src/lib.rs
- embassy-rp/src/multicore.rs
- **rp: Workaround "SIO spinlock stuck bug", reset PROC1 at boot.**
- **rp: make atomics work properly between cores in rp235x.**
closes #3839
> rp235x: fix atomics, fix SIO spinlock stuck bug, fix missing core1 reset.

- examples/stm32wba/.cargo/config.toml
The WBA55 Nucleo bardd officially replaces the WBA52.
Even if WBA52 SoC is still part of the ST CubeFW, the SW connectivity projects for WBA52 are no longer delivered.
WBA55 Nucleo board is now the reference entry board.
> Replace STM32WBA52CGUxT by STM32WBA55CGUx

- examples/rp/src/bin/interrupt.rs
- examples/rp/src/bin/spi_sdmmc.rs
- examples/rp23/src/bin/interrupt.rs
- examples/rp23/src/bin/spi_sdmmc.rs
This is now workarounded by embassy-rp itself.
> examples/rp: remove unneeded sio spinlock stuck bug workarounds.

- embassy-embedded-hal/Cargo.toml
- embassy-embedded-hal/src/shared_bus/asynch/spi.rs
Currently, if a transfer is dropped, the CS will stay in a low state, which seems to be undesired. This uses `OnDrop` to guarantee that CS will be high regardless what happens.
Note that it is currently still unsafe, at least for STM32, to drop an on-going SPI transfer. More investigation on this is TBD. Some suggestions on this would be nice, e.g., whether it's desired to implement cancel safety for SPI transfers.
> SpiDevice cancel safety: always set CS pin to high on drop

- embassy-rp/src/pio/mod.rs
Please consider a PR for embassy-rp to add some PIO functions that look to me to be missing:
ConfigPins::set_sideset_pins(), needed like set_set_pins and set_out_pins. (Is there a reason this isn't there that I haven't found yet?)
Several runtime StateMachine manipulations:
- addr() of running SM, only useful at a stall point but important for that reason
- tx_threshold() (user code could just save the last-set value I suppose)
- set_tx_threshold - I've found several PIO programs "out there" that need to manipulate thresholds.
- rx_threshold()
- set_rx_threshold()
- set_thresholds() - both at once, same value
Please review with extreme prejudice!
> Add PIO functions.

- examples/stm32wba/Cargo.toml
Following PR https://github.com/embassy-rs/embassy/pull/3852 , I forgot to update the dependency.
The WBA55 Nucleo board officially replaces the WBA52.
Even if WBA52 SoC is still part of the ST CubeFW, the SW connectivity projects for WBA52 are no longer delivered.
WBA55 Nucleo board is now the reference entry board.
> STM32 - Update Cargo.toml : replace STM32WBA52CGU by STM32WBA55CG

- docs/pages/best_practices.adoc
- docs/pages/layer_by_layer.adoc
- docs/pages/overview.adoc
Replaces: 
- 'safetly' with 'safety'
- `button.await_for_any_edge()` with `button.wait_for_any_edge()`
- 'Comparsion' with 'Comparison'
> Fix small typos in docs

- embassy-net/Cargo.toml
This is to fix the docs for the icmp module not being in the docs.
> fix: embassy-net icmp feature docs

- embassy-stm32/src/rtc/datetime.rs
- embassy-stm32/src/rtc/mod.rs
- examples/stm32g0/src/bin/rtc.rs
RTC driver does not read subsecond register. This PR fixes that and also adds microsecond field to `DateTime` struct.
> STM32: RTC subsecond support

- cyw43/src/control.rs
I searched the repo for other references, and none exist.  Being Rust, I am confident any breaking changes in existing source code clients will be obvious.
> Fix function name

- cyw43-pio/Cargo.toml
- cyw43-pio/src/lib.rs
- embassy-rp/Cargo.toml
- embassy-rp/src/pio/instr.rs
- embassy-rp/src/pio/mod.rs
- embassy-rp/src/pio_programs/hd44780.rs
- embassy-rp/src/pio_programs/i2s.rs
- embassy-rp/src/pio_programs/onewire.rs
- embassy-rp/src/pio_programs/pwm.rs
- embassy-rp/src/pio_programs/rotary_encoder.rs
- embassy-rp/src/pio_programs/stepper.rs
- embassy-rp/src/pio_programs/uart.rs
- examples/rp/Cargo.toml
- examples/rp/src/bin/pio_async.rs
- examples/rp/src/bin/pio_dma.rs
- examples/rp23/Cargo.toml
- examples/rp23/src/bin/pio_async.rs
- examples/rp23/src/bin/pio_dma.rs
- examples/rp23/src/bin/pio_rotary_encoder_rxf.rs
- tests/rp/Cargo.toml
- tests/rp/src/bin/pio_irq.rs
- tests/rp/src/bin/pio_multi_load.rs
- **rp/pio: move instructions to methods of the SM.**
- **rp: remove typo'd `feature` that was doing nothing.**
- **rp/pio: update pio-rs crate, reexport it so users don't get version mismatches.**
depends on https://github.com/rp-rs/pio-rs/pull/72
> rp/pio: update pio-rs, reexport, move instr methods to SM.

- ci.sh
- tests/rp/.cargo/config.toml
- tests/rp/Cargo.toml
- tests/rp/readme.md
- tests/rp/src/bin/adc.rs
- tests/rp/src/bin/dma_copy_async.rs
- tests/rp/src/bin/flash.rs
- tests/rp/src/bin/gpio.rs
- tests/rp/src/bin/gpio_async.rs
- tests/rp/src/bin/gpio_multicore.rs
- tests/rp/src/bin/i2c.rs
- tests/rp/src/bin/multicore.rs
- tests/rp/src/bin/pio_irq.rs
- tests/rp/src/bin/pio_multi_load.rs
- tests/rp/src/bin/pwm.rs
- tests/rp/src/bin/spi.rs
- tests/rp/src/bin/spi_async.rs
- tests/rp/src/bin/timer.rs
- tests/rp/src/bin/uart.rs
- tests/rp/src/bin/uart_buffered.rs
- tests/rp/src/bin/uart_dma.rs
- tests/rp/src/bin/uart_upgrade.rs
Some tests need more work.
* The adc test builds, but isn't set up correctly for the 2350 hardware yet.
* The multicore and gpio_multicore tests only work from flash, seems to be a probe-rs issue.
* The i2c and flash tests also only works from flash, these are probably bugs but I don't have time to run them down now.
* The 2350 gpio test skips anything with pull downs. I think these fail because of E9.
The float, bootsel, cyw43, and ethernet tests don't have 2350 equivalents. There's no reason to use the float romfuncs, use the FPU. Bootsel as a button isn't supported on the 2350 yet. The wifi and eth tests don't have appropriate hardware.
The i2c test has also been tweaked to run on one core.
Also, thanks 9names, without #3890 this would have been much uglier.
> Inital rp23 ci tests

- embassy-sync/src/channel.rs
I recently had a thought to gather all of my channels and do some funky Stream manipulations on them (debouncing mainly).
Would this be a useful addition?
> Add stream impl for embassy-sync Channels

- embassy-nrf/Cargo.toml
- embassy-nrf/src/chips/nrf5340_app.rs
- embassy-nrf/src/lib.rs
Previously, `config.lfclk_source` was ignored on the nRF5340. This configures the LFCLK and also enables the Synthesized and External*Swing sources. And since the LFXO pins are shared with GPIO (P0.00 and P0.01), I've added the `lfxo-pins-as-gpio` feature.
I've only been able to test the ExternalXtal source.
> nrf5340: configure LFCLK

- embassy-stm32/src/usart/buffered.rs
This fixes the following issue: https://github.com/embassy-rs/embassy/issues/3883
The function was tested and works as expected (in our case at least)
> fix: BufferedUartRx embedded_hal_nb::serial::Read impl

- embassy-rp/CHANGELOG.md
Starting prep for an `embassy-rp` release.
Before the next crates.io publish of `embassy-rp` we also need a new release of the pio crates - `embassy-rp` currently depends on a git rev of `pio-rs`. This will be blocked on https://github.com/rp-rs/pio-rs/pull/73
> rp: Add unreleased changes to changelog

- embassy-nrf/src/lib.rs
`ReghVoltage` is identical to `Reg0Voltage` so I'm not sure whether it'd be better to just reuse/reexport `Reg0Voltage`.
> nrf5340: add regh_voltage config

- embassy-nrf/src/lib.rs
config for the optional internal capacitors for the HFXO/LFXO on the nrf5340
> nrf5340: add internal capacitor config

- embassy-stm32/src/sai/mod.rs
I see compile errors using a recent git checkout of embassy with an stm32l431cb. Use the `from_bits` function instead.
```
error[E0603]: tuple struct constructor `Sloten` is private
--> /usr/local/cargo/git/checkouts/embassy-9312dcb0ed774b29/17301c0/embassy-stm32/src/sai/mod.rs:939:36
|
939  |                 w.set_sloten(vals::Sloten(config.slot_enable as u16));
|                                    ^^^^^^ private tuple struct constructor
|
::: /usr/local/cargo/git/checkouts/stm32-data-generated-cb34dad5f3150296/5ffbb82/stm32-metapac/src/chips/stm32l431cb/../../peripherals/sai_v2.rs:1523:23
|
1523 |     pub struct Sloten(u16);
|                       --- a constructor is private if any of the fields is private
|
note: the tuple struct constructor `Sloten` is defined here
--> …
```
> stm32: do not use private constructor

- cyw43-pio/src/lib.rs
- embassy-rp/src/pio/mod.rs
- embassy-rp/src/pio_programs/hd44780.rs
- embassy-rp/src/pio_programs/i2s.rs
- embassy-rp/src/pio_programs/ws2812.rs
- examples/rp/src/bin/pio_dma.rs
- examples/rp235x/src/bin/pio_dma.rs
Changes the dma_pull/push function signatures to give callers access to the byte swap flag for their DMA transfers.
> embassy-rp: pio: Add access to DMA engine byte swapping

- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
This resolves an issue whereby one is unable to use a `UartTx` and a `RingBufferedUartRx` in parallel in separate tasks.
Firstly, it changes `clear_idle_flag` to ONLY clear the idle flag as the name suggests it should. Currently, it clears ALL set flags including TC which is checked by `UartTx::flush`. If the TX and RX are being used in parallel, it is possible for the RX to clear the TC flag before the TX can check it, which causes `UartTx::flush` to hang forever.
Secondly, it adds a separate `tx_waker`, otherwise when TX and RX are used in parallel they contend for the currently lone `rx_waker` and can overwrite each others wakers, causing hanging.
> Fix STM32 UART: Add separate TX waker and only clear idle flag in RingBufferedUartRx

- embassy-stm32/src/can/bxcan/mod.rs
- embassy-stm32/src/can/common.rs
- embassy-stm32/src/can/enums.rs
- embassy-stm32/src/can/fdcan.rs
This is intended to fix these issues:
Fixes #3874 
Fixes #3610
Store a count of the number of senders and receivers in the state so that we only disable the buffered mode when the last one is dropped.
> STM32 CAN: Count senders and receivers so that we don't close down early.

- embassy-time/src/duration.rs
- embassy-time/src/instant.rs
When using `Instant::from_*` (except `from_ticks`), it is possible to overflow on the multiplication, which can cause a panic if debug checks are enabled, which procudes a panic like this:
```
[...]\embassy-time-0.4.0\src\instant.rs:41:20:
attempt to multiply with overflow
```
I've just hit this and for now the only workaround is to do some bounds on the input value checks before passing it to the `Instant::from_*` constructor, but it is a bit cumbersome to find the maximum allowed value. For this reason I'm proposing to add these helper constructors that use `checked_mul` and can fail gracefully on overflow.
> Add `Instant::try_from_*` constructor functions

- embassy-stm32/src/lptim/pwm.rs
- embassy-stm32/src/timer/simple_pwm.rs
Currently there is no way to specify either timer or lptimer pwm channel pin configuration. This PR adds the ability for specifying the pins output type, pull, and speed depending on the gpio version.
> Add ability to create STM32 timer channels with full pin configuration

- embassy-stm32/src/usb/usb.rs
Some issues existed in the ISO endpoint handling of this particular USB driver (e.g. used in STM32H5).
Prerequisite: ISO transfers on this driver are always double-buffered.
Upon initialization, the ISO IN endpoint was in `NAK` state. This is forbidden, as it can only be `VALID` or `DISABLED`.
This changes the ISO IN endpoint state to `VALID` after init.
Reading from ISO OUT endpoints was performed from the wrong buffer location. They are swapped in this PR.
Reading/writing ISO endpoints does not require changing the `EPR` register.
> Fix USB ISO IN EP stat and ISO OUT buffer order

- README.md
- docs/pages/hal.adoc
- docs/pages/overview.adoc
- embassy-usb/README.md
This PR introduces [py32-hal](https://github.com/py32-rs/py32-hal) and [musb](https://github.com/decaday/musb) to the documentation and README files.
[py32-hal](https://github.com/py32-rs/py32-hal) already supports portions of the py32 series and most peripherals.
py32-hal drawing significant inspiration from embassy-stm32 (licensed under MIT). It also has a companion repository akin to stm32-data: [py32-data](https://github.com/py32-rs/py32-data). (Many thanks to the embassy project for its pioneering work in embedded Rust!)
I’ve also implemented `embassy-usb-driver` for musb (USB2.0 IP) [here](https://github.com/decaday/musb), a widely adopted USB IP by manufacturers like TI, MediaTek, Puya, and others.
Additionally, I’ve updated the "Adding support for new hardware" section of …
> Add py32-hal and musb to docs and READMEs

- embassy-rp/src/clocks.rs
The FUNCSEL value for GPOUT/GPIN has changed from RP2340 to RP2350. Embassy has been using 0x08 for both chips, therefore the GPOUT example did not work on the Pico 2.
This PR now distinguishes the two chips and sets FUNCSEL to 0x09 for the RP2350.
See RP2340 (left) and RP2350 (right) datasheets:
> [RP235x] Fix wrong funcsel on RP2350 GPOUT/GPIN

- embassy-nrf/src/saadc.rs
I noticed that if the register of `SAADC` about channels does not clean or override by other analog input channel. The original pin's functionality will be influenced, which makes it difficult to reuse the pin for other purpose.
```rust
let p = embassy_nrf::init(Default::default());
{
let cfg = ChannelConfig::single_ended(unsafe { P0_29::steal() });
let saadc_config = saadc::Config::default();
let mut adc = Saadc::new(p.SAADC, Irqs, saadc_config, [cfg]);
adc.calibrate().await;
let mut buf = [0i16; 1];
adc.sample(&mut buf).await;
defmt::info!("ADC value: {}", buf[0]);
drop(adc);
}
let pin = Input::new(p.P0_29, Pull::Down);
let ch0 = InputChannel::new(p.GPIOTE_CH0, pin, InputChannelPolarity::Toggle);
ch0.wait().await;
```
The `ch0` never triggered unless I create another `SAADC` instance to …
> clean the SAADC's register while dropping

- embassy-mspm0/Cargo.toml
- embassy-mspm0/build.rs
- embassy-mspm0/src/lib.rs
- embassy-mspm0/src/time_driver.rs
Please merge https://github.com/embassy-rs/embassy/pull/3991 first
This should make it so that the `Peripherals` type and module get all the singletons. Including pins e.g. `I2C0_SCL`. I imagine a few corrections will be needed in the future to be fully consistent.
Generation for uart pin implementations is commented in the buildscript out since uart is still work in progress. Hopefully the blocking uart driver will be ready soon.
For timers and pins, the types themselves also get marked as only available when not using a time driver when generating docs for crates.io.
> mspm0: generate all singletons

- embassy-stm32/src/usb/usb.rs
- embassy-usb/src/class/uac1/speaker.rs
- Fixes errata, found for STM32H5: "During OUT transfers, the correct transfer interrupt (CTR) is triggered a little before the last USB SRAM accesses have completed. If the software responds quickly to the interrupt, the full buffer contents may not be correct."
A delay of 800 ns is recommended as a workaround.
- Fixes default mute state of the UAC1 class. For hosts that don't use the control interface (e.g. Android) there is no way to get the device out of mute.
> Small USB-related fixes

- embassy-rp/src/flash.rs
Previously the constant pointing at the base of the bootram was incorrectly called BOOTROM_BASE. According to the datasheet, the bootrom is a 32K region starting at ``0x00000000`` while the bootram is a 1K region of SRAM starting at ``0x400e0000``.
> rp: rename BOOTROM_BASE to BOOTRAM_BASE

- embassy-rp/src/adc.rs
This commit rearranges the `Adc::wait_for_ready` function to make sure that wakers are registered before the interrupt is enabled, and keeps enabling the interrupt until the ADC is ready.
It's not actually clear to me how this race condition materializes, but when running code from RAM on RP2350B I noticed that the waker is lost almost every single time. More investigation is needed to determine a root cause, but this patch seems to fix the issue. 
The datasheet is not entirely clear as to exactly when the IRQ fires. It only explicitly says that the IRQ is raised when the FIFO length reaches FCS_THRESH, but FCS_EN is never set by the ADC driver for one shot samples so it's not obvious to me why the FIFO IRQ is raised at all in this case.
Any insight would be appreciated.
> rp/adc: fix potential race condition

- embassy-stm32/src/rcc/c0.rs
- embassy-stm32/src/rcc/g0.rs
Resolves #3608, tested on a g031
> stm32: allow using LSI/LSE as SYSCLK on g0/c0

- embassy-stm32/src/i2c/v2.rs
The I2C peripheral needs to be disabled to change the timings register. This PR fixes the `SetConfig` implementation to disable the peripheral, set the timings, then re-enable it.
I took a glance at the v1 I2C implementation to see if this might be easy to add there, but that peripheral is sufficiently different that I did not feel comfortable changing it without a device to test on, which I don't have.
Fixes #3914.
> Fix SetConfig implementation for STM32 I2C v2

- embassy-executor-macros/src/macros/task.rs
- embassy-executor/src/lib.rs
- embassy-executor/tests/ui.rs
- embassy-executor/tests/ui/type_error.rs
- embassy-executor/tests/ui/type_error.stderr
Somehow, doing `<F, Fut> -> TaskPool<Fut>` is better than `<F> -> TaskPool<F::Fut>`. I also moved ~~all~~ some of the helper functions out of the macro and in to embassy_executor.
Before:
```
error[E0308]: mismatched types
--> tests/ui/type_error.rs:5:5
|
4 | async fn task() {
|                - help: try adding a return type: `-> i32`
5 |     5
|     ^ expected `()`, found integer
error[E0277]: the trait bound `Align<#[embassy_executor::task]>: _export::Alignment` is not satisfied
--> tests/ui/type_error.rs:3:1
|
3 | #[embassy_executor::task]
| ^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `_export::Alignment` is not implemented for `Align<#[embassy_executor::task]>`
|
= help: the following other types implement trait `_export::Alignment`:
Align<1024>
Align<1048576>
Align<128>
Align<131072> …
```
> Fix ugly compiler error from task macro

- embassy-stm32/src/adc/g4.rs
For reasons that I don't fully understand, ADC calibration fails on the STM32G4 when SYSCLK is too high.
The ADC calibration happens in two steps:
- single-ended calibration
- differential calibration
After the differential calibration is started, the blocking wait for `ADCAL` going to `0` never finishes.
Introducing a short delay between calibration steps fixes the issue.
Inspired by the solution from https://github.com/ChibiOS/ChibiOS/blob/master/os/hal/ports/STM32/LLD/ADCv3/hal_adc_lld.c#L160, which uses the same approach.
Also, power-up delay (waiting for ADVREG stability) has to be 20 us, as per the datasheet (was 10 us).
I have not found any relevant information in the RM, errata, or datasheet. ST examples that I found never calibrate both single-ended and differential back-to-back.
> Fix STM32G4 ADC calibration stability

- embassy-sync/src/blocking_mutex/mod.rs
This adds a `lock_mut` method to `blocking_mutex::Mutex` in order to get direct mutable access to the protected data. This removes the need for an extra `RefCell` when mutable access is needed. 
The method is marked `unsafe` because calling this method when the mutex is already locked causes UB. Other than that this implementation should be sound.
> embassy-sync: add `lock_mut` to `blocking_mutex::Mutex`

- embassy-executor/src/raw/mod.rs
- embassy-executor/src/raw/trace.rs
This is an extension of the `trace` interface that adds two new hooks:
1. `_embassy_trace_poll_start` - used to mark the time AFTER executor polling starts, but BEFORE task polling starts. This is usable for measuring overhead of the scheduler algorithm itself.
2. `_embassy_trace_task_end` - used to mark the end of a task, at the time of dropping the contained future and freeing the associated space.
I've also added quite a bit of docs.
EDIT: this is a breaking change, but fine because https://github.com/embassy-rs/embassy/pull/4033#issuecomment-2769199765
> [embassy-executor] Add two new `trace` hooks, improve docs

- embassy-mspm0/src/gpio.rs
The current assertion triggers when `pf` is 0 which is required for analog functions.
> mspm0: Fix `set_pf_unchecked()` assertion

- embassy-executor/src/arch/cortex_m.rs
- embassy-executor/src/raw/waker.rs
Just some intra-doc warnings I saw while working on other things.
We could potentially be looking for:
* `rustdoc::broken_intra_doc_links`
* `rustdoc::redundant_explicit_links`
in CI somehow (run rustdoc with `-D warnings`?) to avoid this.
> [embassy-executor]: Fix some intra-doc links

- embassy-rp/src/i2c.rs
- embassy-rp/src/i2c_slave.rs
This change ensures that wakers are registered PRIOR to checking status in i2c `wait_on` helpers.
> embassy-rp: defensive change to ensure wakers are registered

- embassy-executor/Cargo.toml
I tried using embassy-executor with esp-idf-hal (i.e. on std), but found that esp-idf-hal enables a feature of critical-section that is mutually exclusive to `critical-section/std`, that is enabled by embassy-executor when using `arch-std`. I therefore don't think that embassy-executor should automatically select the critical-section implementation and leave it to the hal to decide, just like #4048 suggests for embassy-time.
> embassy-executor: Don't enable critical-section/std for `arch-std`

- embassy-stm32/src/timer/input_capture.rs
- embassy-stm32/src/timer/low_level.rs
- embassy-stm32/src/timer/mod.rs
- embassy-stm32/src/timer/one_pulse.rs
- embassy-stm32/src/timer/qei.rs
This adds a one pulse mode timer driver. This allows creating an output pulse and/or interrupt after a trigger and a configurable delay.
I have only implemented external triggers as that is what I required. Similarly, I have not implemented output pins.
This was tested on an STM32H533RE.
> STM32: One pulse mode timer

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/lib.rs
- embassy-stm32/src/macros.rs
- embassy-stm32/src/xspi/enums.rs
- embassy-stm32/src/xspi/mod.rs
- examples/stm32h7rs/src/bin/xspi_memory_mapped.rs
This is based on an initial patch by @rickrogers-ionq . It works fine in single SPI mode in my (fairly brief) amount of testing, I haven't got octospi working yet (waiting for a datasheet for the flash part on the nucleo board).
I'm not sure if there's a better way to handle the NCS1/NCS2 switching in https://github.com/embassy-rs/embassy/commit/f094e34efd6c7d083937b11d388270325e4cc00c . When using a single chip, either NCS1 or NCS2 Pin can be provided, with CSSEL register set to the one being used. In future someone could add another interface to allow switching on the fly between two chips (the unused `ncs_alt`).
> stm32h7rs xspi 

- embassy-executor/Cargo.toml
- embassy-sync/Cargo.toml
> embassy-sync, executor/arch-wasm: don't select critical-section impl for std

- embassy-executor/src/raw/mod.rs
- embassy-executor/src/spawner.rs
This adds a way to get a unique id for an `Executor`, and another to get that id through a `Spawner`.
The id is just an `Executor`'s inner `SyncSpawner` ref-as-pointer-as-usize.
I'd argue that due to the inner `SyncSpawner` ref being `&static`, no two `Executor` instances can have the same id.
> embassy-executor: introduce `Executor::id()`, `Spawner::executor_id()`

- embassy-stm32/src/rcc/f247.rs
This PR adds the `external_i2s_clock: Option<Hertz>` field to the `rcc::Config` struct for the mentioned platforms.
If set, this value is used to calculate the PLL output frequencies and sets the external clock as the I2S PLL source. Otherwise, the HSI/HSE clock is selected.
> Fix I2S PLL source selection for F413/F423/F412

- ci.sh
- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
rebase and fix of #3952
- **fix(stm32): handle half-duplex in ringbuffered read**
- **Remove flaky test.**
> fix(stm32): handle half-duplex in ringbuffered read

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/sdmmc/mod.rs
- examples/stm32f4/src/bin/sdmmc.rs
- examples/stm32f7/src/bin/sdmmc.rs
- examples/stm32h7/src/bin/sdmmc.rs
- tests/stm32/src/bin/sdmmc.rs
I've added support for eMMC memory devices in `embassy-stm32` using the SDMMC peripheral.
I've confirmed that this code works correctly for basic initialization, reads, and writes on a device that I've previously been using under `stm32f4xx-hal`, using 1, 4, and 8 data lanes, each with several different operating frequencies up to 24MHz.
Note that I don't have any appropriate hardware to test:
- `gpio_v1` config
- `sdmmc_v2` config
- SD card regressions
> Support eMMC devices via SDMMC (STM32)

- embassy-rp/src/uart/mod.rs
rebase of #3933
Change the UART RX FIFO depth from 1/8 to 7/8.  This should allow for
buffered receipt of uart data with a lower IRQ load.
The PL011 fifo is pretty smart about the fifo, it has an automatic
timeout (which triggers an interrupt) of about 4 characters worth of
time, so setting this threshold doesn't affect the behavior of receipt
of a partially filled fifo.
This should not have any affect on the DMA mode, as the DMA will
generally drain the fifo as data becomes available.
The constraint for the fifo threshold should be determined by expected
interrupt latency.  The IRQ needs to be able to drain the fifo before it
fills.  As such, the proper threshold depends on system design and data
rate.  At full speed (7.8 Mbaud), the remaining 8 characters will come
in in about 10us, …
> embassy-rp: uart: Increase RX FIFO watermark

- embassy-executor-macros/src/lib.rs
- embassy-executor-macros/src/macros/main.rs
- embassy-executor/src/lib.rs
I ended up making a custom executor for the wch ch58x HAL. (ref https://github.com/embassy-rs/embassy/issues/4030)
When an architecture isn't selected, the embassy_executor::main macro is currently undefined, requiring the user or the HAL to define their own main function. While that is acceptable, I'd like to propose the ability to specify an executor in the macro.
Currently this PR does the bare minimum to allow an executor to be specified, but does not re-export the macro through embassy-executor as I'm not sure what the best way to handle architecture here is. I'm hoping someone can weigh in with a good direction to take this, or reject it outright before I give it too much time. Thanks!
> executor: add executor selection to #[embassy_executor::main]

- ci.sh
- embassy-mspm0/src/uart.rs
- tests/mspm0/.cargo/config.toml
- tests/mspm0/Cargo.toml
- tests/mspm0/build.rs
- tests/mspm0/memory_g3507.x
- tests/mspm0/src/bin/uart.rs
This also fixes a bug in the uart clock calculation where it could select an oversampling faster than what the hardware is providing.
Depends on https://github.com/embassy-rs/teleprobe/pull/29
> mspm0: add uart tests

- embassy-stm32/src/adc/c0.rs
- embassy-stm32/src/adc/g4.rs
- embassy-stm32/src/adc/u5_adc4.rs
- embassy-stm32/src/adc/v4.rs
- embassy-stm32/src/rcc/h.rs
- embassy-stm32/src/rcc/u5.rs
Some frequency variables were being logged with `variable.0` and some as `variable`.  This PR makes the style consistent as `frequency`.
> Frequency display is now consistent

- examples/boot/application/rp/Cargo.toml
This PR removes duplicated features ("arch-cortex-m" and "executor-thread") from the `embassy-executor` dependency in Cargo.toml.
> embassy-boot-rp-examples: Remove duplicate features in embassy-executor dependency

- embassy-executor/Cargo.toml
- embassy-executor/src/raw/mod.rs
Fixes the avr executor by exchanging the `core::sync::AtomicPtr` with `portable_atomic::AtomicPtr`
> Fix the avr executor

- embassy-stm32/src/can/frame.rs
Implemented the ability to take a changeable reference to data in a CAN frame.
There are no breaking changes.
Read more in issue #4075.
> [embassy-stm32] Capability to modify CAN frame data without copying.

- examples/rp/src/bin/usb_webusb.rs
- examples/rp235x/src/bin/usb_webusb.rs
Running the usb-webusb example for the rp235x causes the following panic:
```
0.000395 ERROR panicked at /home/user/.cargo/git/checkouts/embassy-c08a80187403f815/6919732/embassy-usb/src/builder.rs:179:13:
if composite_with_iads is set, you must set device_class = 0xEF, device_sub_class = 0x02, device_protocol = 0x01
└─ panic_probe::print_defmt::print @ /home/jdickert/.cargo/registry/src/index.crates.io-1949cf8c6b5b557f/panic-probe-1.0.0/src/lib.rs:104 
```
Since the classes and protocol are not set to the necessary values, I think the `composite_with_iads` should simply be set to false in this case.
Also made the change in the RP2340 example.
fixes #4050
> [RP] Fix missing config.composite_with_iads = false; in webusb example

- cyw43/src/events.rs
- cyw43/src/ioctl.rs
- cyw43/src/lib.rs
This allows using static_cell::ConstStaticCell for cyw43::State.
> cyw43: make State::new a const fn

- embassy-rp/src/trng.rs
Per discussion in https://github.com/embassy-rs/embassy/pull/3338/files#r2040704590 the Trng implementation satisfies the requirements for CryptoRng, so it is reasonable to implement this marker trait.
> embassy-rp: impl rand_core::CryptoRng for Trng

- examples/rp/src/bin/i2c_slave.rs
sda and scl were swapped twice. The code worked, but would be confusing trying to interface with pins externally.
> rp: i2c-slave example: fix twice-swapped sda/scl

- embassy-stm32/src/eth/v1/mod.rs
Much like PR #2465 already did for the STM32 V2 Ethernet peripheral, this patch implements the MII interface for the STM32 V1 Ethernet peripheral.
I tested the code on a custom STM32F207 board and I get a link and traffic flows from A to B. So at least for that version of the peripheral, it works. I don't have hardware for the `eth_v1a` version, but I consulted the appropriate datasheet of the SoC (I forgot which one it was - some F1xx I think) which contains this version of the MAC and set the pin modes as described, so that should work as well.
> Implement MII for STM32 V1 ethernet peripheral

- embassy-rp/src/pwm.rs
PWM input does not work on rp235xa. This PR fixes this by enabling input mode if using pwm in input mode
Test result with fix: Can confirm reading correct rate from generated function. Before fix reads 0Hz.
Have a good look before merging, the code is based on AI agent suggestion. I am especially unsure if the drop implementation is as it ought to be, we will be setting IE to false even if the PWM was never initialized as input. But I found no convincing way that i liked to read the way it is set up without introducing more code so I left it like it is proposed here.
Here is an excerpt from the rp2350 datasheet backing up the viability of the fix itself: Chapter 9.3, outlining changes wrt rp2040:
> Enable input mode for PWM pins on RP235x and disable it on drop

- ci.sh
- embassy-stm32/src/rtc/low_power.rs
- embassy-stm32/src/rtc/v2.rs
The low power feature did not compile for the stm32wb55.
Entering sleep is working, but I still have to check if there needs to be added some special handling for the CPU2.
> fix: stm32wb55 low power feature did not compile

- docs/pages/faq.adoc
Looks like a link was using markdown instead of asciidoc.
> Fix link in faq.adoc

- embassy-stm32/src/usb/otg.rs
I've been using a STM32F107RC for a project and I wanted to use the USB OTG that it has, but the core id that the microcontroller returned was 0x1000. I tested it out in the PCB and works.
Thanks
> Added USB core_id 0x1000 for STM32

- embassy-usb/src/class/cmsis_dap_v2.rs
- embassy-usb/src/class/mod.rs
Because why not. I managed to extract this from eprobe, and since I have two copies in my toys, I thought we might as well try and add it to embassy-usb.
> Add CMSIS-DAP driver

- embassy-stm32/build.rs
- embassy-stm32/src/opamp.rs
- examples/stm32f334/src/bin/opamp.rs
1. The current `buffer_ext` includes a `gain` parameter, which feels a bit odd to me, so I split it into two functions: `buffer_ext` without the `gain` parameter and `pga_ext` with the `gain` parameter.  
2. Added missing gain multipliers for `x32` and `x64`.  
3. Added support for `standalone_dac_int`, `standalone_dac_ext`, `standalone_int`, and `standalone_ext`.  
4. Introduced a calibration method.
> feat(embassy-stm32/opamp): Add some STM32G4 opamp usage

- examples/rp235x/src/bin/blinky.rs
The RP pico w 2 blinky example is currently called `blinky_wifi`. Updates the comment in `blinky.rs` to match that.
> Update blinky_wifi example name

- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
- examples/stm32g0/src/bin/onewire_ds18b20.rs
Allows pin configuration for cts, tx, rts and de pin in usart::Config. The configuration is applied in all Uart drivers.
Also I removed the now rendundant HalfDuplexConfig which I used as base for the pin config implementation.
> Stm32 usart: implement pin config for cts, tx, rts and de

- embassy-stm32/src/sdmmc/mod.rs
- tests/stm32/src/bin/sdmmc.rs
Hello, I have added multiple block read and write support for the STM32 SDMMC peripheral.
This essentially adds CMD18 (multiple block read), CMD25 (multiple block write) and CMD12 (stop transmission) and sets the transfer up correctly.
I've tested this on SDMMCv2 devices.
I've also updated the `block_device_driver` implementation so it now supports multiple block read/writes. I also believe there is a preexisting issue that the `block_address` does not take into consideration the partition start offset, but I'll wait for confirmation from someone before modifying that.
Please let me know what you think as this PR greatly improves the read/write speeds, I would love to see it merged asap.
Kind regards
> STM32 SDMMC multiple block read/write support

- embassy-stm32/src/hash/mod.rs
The HASH accelerator on STM32 microcontrollers can be used for HMAC if a key is provided. One significant use case of HMAC is as a PRF for the PBKDF2 algorithm, but this requires that the hashing state can be recursively "branched" multiple times.
Implementing `Clone` on `hash::Context` makes this use case possible.
> Derive `Clone` for `hash::Context`

- embassy-stm32/src/spi/mod.rs
The new SPI configuration applied when using SpiDeviceWithConfig did previously not get applied as the SPI had to be disabled and re-enabled for it to have an effect. This is implemented by this PR and should resolve the issue.
It has been tested and is working on an STM32U5 which displayed the same problem that the STM32H7 has as described in #2259.
Closes #2259
> Fix STM32H7 SpiDeviceWithConfig does not properly apply the config

- embassy-time/src/timer.rs
Using `async fn` for these functions causes the memory for `fut` to be double-allocated due to rust-lang/rust#62958. Switching to a manual implementation of the future prevents the double-allocation which may be significant if the future is large.
> Manually implement the future for `with_timeout`

- embassy-stm32/Cargo.toml
- embassy-stm32/src/adc/mod.rs
- embassy-stm32/src/adc/v3.rs
- embassy-stm32/src/opamp.rs
Some trivial enums have been removed from the OpAmp API in stm32-metapac, this PR updates the HAL accordingly.
> Update opamp code to current stm32-metapac

- embassy-rp/src/pio_programs/onewire.rs
- examples/rp/src/bin/pio_onewire.rs
I encountered some issues testing the current implementation that led me to spent some time rewriting it.
This new implementation has a couple of improvements over the current one:
- It does not block if there is no device present on the bus
- It allows for better control when to perform a reset. The reset also performs the presence detection.
- There is a implementation of the search algorithm, this allows you to find addresses of the connected devices.
- The clock is now actually calculated based on the sys clock frequency
The only downside in my opinion is the unsafe calls to make the pio jump to the right instruction. But they should be safe since the state machine is disabled when performing the jumps.
Tested this with 0, 1 and 2 devices connected using the example program.
> [embassy-rp] Rewrite PIO onewire implementation

- embassy-stm32/Cargo.toml
- embassy-stm32/src/adc/v4.rs
This is an adaption to https://github.com/embassy-rs/stm32-data/pull/597,
Oversampling ratio register is OVSR, not OSVR
> Fix set_ovsr typo, adaption to latest stm32-data-generated

- embassy-rp/src/trng.rs
Expands upon the the initial implementation of the RP2350 TRNG driver introduced in this PR: https://github.com/embassy-rs/embassy/pull/3338 by setting more secure defaults and gracefully handling self-test errors.
On my Pico 2 W with the default configuration, the provided TRNG example returns very low entropy output and skips all self-tests.
When self-tests are *enabled*, the async implementation hangs after the first autocorrelation error (the trng isn't reinitialized after reset) and the blocking implementation panics.
Default sample rate with self-tests disabled, it works but low quality output (notice the repeating bytes):
```
0.000465 INFO  Random bytes async [170, 170, 170, 82, 85, 85, 85, 85, 149, 82, 85, 169, 86, 165, 170, 170, 86, 165, 170, 180, 182, 116, 45, 165, 85, 90, 86, …
```
> RP2350 TRNG Error Handling

- embassy-stm32/src/can/bxcan/registers.rs
- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/frame.rs
- embassy-stm32/src/opamp.rs
Currently `data()` always returns an 8- or 64-byte slice, even though the actual CAN frame contains less data. The remaining bytes will be zero, so the user must check the frame DLC to see how many bytes were actually sent by the remote end. With this change the slice is the same length as was transmitted, with no extra bytes.
Additionally removed the `ClassicData::MAX_DATA_LEN` constant because almost all instances were using a hardcoded `8` anyway, and the `FdData` only ever uses `64` and doesn't have an equivalent `MAX_DATA_LEN`. Happy to make everything use `MAX_DATA_LEN` instead if that's preferred.
Finally fixed a missing cfg gate on a defmt call that broke the build on G4 without defmt feature.
> STM32 CAN: Make `data()` return correct length slice

- embassy-stm32/src/can/bxcan/registers.rs
- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/frame.rs
- embassy-stm32/src/opamp.rs
This PR is a clone of https://github.com/embassy-rs/embassy/pull/4109 but it fixes the remaining CI failure by just making raw_data function public. The alternative would be to feature select based on bxcan vs canfd however I don't see any great risk in making that function available. It might be more optimal in some use cases.
From 4109:
Currently data() always returns an 8- or 64-byte slice, even though the actual CAN frame contains less data. The remaining bytes will be zero, so the user must check the frame DLC to see how many bytes were actually sent by the remote end. With this change the slice is the same length as was transmitted, with no extra bytes.
Additionally removed the ClassicData::MAX_DATA_LEN constant because almost all instances were using a hardcoded 8 anyway, and the …
> Stm32 can data len

- README.md
use simpler markdown linking, minor grammar cleanup
>  chore: minor readme cleanup

- docs/pages/new_project.adoc
- docs/pages/project_structure.adoc
The [document](https://embassy.dev/book/#_project_structure) shows an example of `rust-toolchain.toml` with toolchain version `nightly-2023-08-19`. I think this can pick some other version than nightly to let the reader know Embassy can use the stable toolchain.
```toml
[toolchain]
channel = "nightly-2023-08-19" # <- as of writing, this is the exact rust version embassy uses
components = [ "rust-src", "rustfmt" ] # <- optionally add "llvm-tools-preview" for some extra features like "cargo size"
targets = [
"thumbv6m-none-eabi" # <-change for your platform
]
```
This pull request uses the same version as https://github.com/embassy-rs/embassy/blob/main/rust-toolchain.toml
> doc: Tweak the example `rust-toolchain.toml`

- embassy-sync/src/signal.rs
- embassy-sync/src/watch.rs
This is an attempt at clarifying the documentation around `Signal` and `Watch` after searching for a bug where `Signal` had been used instead of `Watch` with multiple consumers.
`Watch` was lacking any description of the generic parameter `N`, which is the number of receivers. I have added that at two places.
`Signal` was lacking the description from the top-level docs that it is intended for a _single_ consumer. The `wait` function was not explicit about taking the value from the signal (though it could be inferred since the Future returns  `T`).
Let me know if there is anything I can change to improve this PR. 
Also, maybe we could add some clarification on why Signal does not implement the Receiver like Watch does? Watch does seem to check how many consumers there are, while Signal …
> Clarify docs for signal and watch

- embassy-stm32/src/spdifrx/mod.rs
I got this clippy lint in `src/spdifrx/mod.rs`. I'm not very confident, but I guess the intention was `0b0010` instead of `0x0001`. This pull request fixes it by replacing it with `!= 0`.
```
error: incompatible bit mask: `_ & 2` can never be equal to `1`
--> src/spdifrx/mod.rs:226:16
|
226 |             if (*sample & (0x0002_u32)) != 0x0001 {
|                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#bad_bit_mask
= note: `#[deny(clippy::bad_bit_mask)]` on by default
```
> Fix clippy::bad_bit_mask

- examples/stm32h7/src/bin/sai.rs
This commit fixes the start sequence of the stm32h7 SAI example, ensuring the master subblock is started via `transmitter.write()` before first calling `receiver.read()` for the slave subblock. See #4165.
> Fix h7 SAI example start sequence

- embassy-usb-dfu/src/application.rs
- embassy-usb-dfu/src/dfu.rs
- embassy-usb-dfu/src/lib.rs
- examples/boot/application/stm32wb-dfu/src/main.rs
- examples/boot/bootloader/stm32wb-dfu/src/main.rs
Modify the `Reset` trait's `reset` function to return `()` instead of `!` and adds a `&self` parameter. This makes it easier to implement cleanup before resetting the whole chip.
I also tacked on a change to reset immediately if `WILL_DETACH` is set, instead of waiting for a USB reset from the host since the WinUSB driver isn't capable of generating this USB reset.
> embassy-usb-dfu: Modify Reset trait

- embassy-stm32/src/opamp.rs
The opamp was refactored in #4089 but I think there was a copy paste error.
The old code:
https://github.com/embassy-rs/embassy/blob/d41eeeae79388f219bf6a84e2f7bde9f6b532516/embassy-stm32/src/opamp.rs#L149-L156
When a gain was selected (which is now always true in the new function), the VmSel is 0x10 (PGA). But in the new code it was left on OUTPUT.
I was seeing weird ADC values and this fixes it.
> Stm32: Fix opamp copy pasta mistake

- embassy-usb-driver/Cargo.toml
- embassy-usb-driver/src/lib.rs
- embassy-usb/Cargo.toml
- embassy-usb/src/class/cdc_acm.rs
Implement embedded-io-async Read and Write traits for USB CDC ACM.
For the Receiver side, this requires being able to buffer a received packet if the caller doesn't read the entire length in one go, so a separate `BufferedReceiver` is created for this.
> Implement embedded-io-async traits for USB CDC ACM

- examples/rp235x/src/bin/pio_rotary_encoder_rxf.rs
The current example code shows negative values as `u32` as shown below. This pull request fixes it by simply casting to `i32`.
```
0.000395 INFO  Count: 7
└─ pio_rotary_encoder_rxf::____embassy_main_task::{async_fn#0} @ src\bin\pio_rotary_encoder_rxf.rs:109
1.000447 INFO  Count: 0
└─ pio_rotary_encoder_rxf::____embassy_main_task::{async_fn#0} @ src\bin\pio_rotary_encoder_rxf.rs:109
2.000466 INFO  Count: 0
└─ pio_rotary_encoder_rxf::____embassy_main_task::{async_fn#0} @ src\bin\pio_rotary_encoder_rxf.rs:109
3.000485 INFO  Count: 4294967295
└─ pio_rotary_encoder_rxf::____embassy_main_task::{async_fn#0} @ src\bin\pio_rotary_encoder_rxf.rs:109
4.000509 INFO  Count: 4294967295
└─ pio_rotary_encoder_rxf::____embassy_main_task::{async_fn#0} @ src\bin\pio_rotary_encoder_rxf.rs:109
5.000533 INFO …
```
> Fix `rotary_encoder_rfx` example to handle negative values

- embassy-rp/src/clocks.rs
- embassy-rp/src/pio_programs/clock_divider.rs
- embassy-rp/src/pio_programs/hd44780.rs
- embassy-rp/src/pio_programs/mod.rs
- embassy-rp/src/pio_programs/rotary_encoder.rs
- embassy-rp/src/pio_programs/stepper.rs
- examples/rp/src/bin/overclock.rs
- examples/rp/src/bin/overclock_manual.rs
- tests/rp/src/bin/overclock.rs
This PR introduces the ability to initialize the rp2040 with other frequencies than 125Mhz. A user can either use a higher level API to achieve a setting or set the PLL manually. See the two new examples for more details.
Should close #3919 
Disclosure for Review:
I have used AI Agents to help me code this and my level of experience is limited, most of what I touched I learned as I went. 
The agent I fed with the Pi Pico SDK as well as the datasheet, in the datasheet I tried to make sure I read up on all the things touched to see if i spot discrepancies. Those I found, I corrected.
I have tested:
- compile for rp2040
- compile for rp235x
- run blinky on both
- look for hardcoded 125Mhz throughout the HAL, fix that
- run my examples
- run a few of the other rp examples to see if i …
> RP: rp2040 overclocking

- embassy-rp/src/uart/buffered.rs
- embassy-rp/src/uart/mod.rs
- examples/rp/src/bin/sharing.rs
- examples/rp/src/bin/uart_buffered_split.rs
- examples/rp/src/bin/uart_unidir.rs
- examples/rp235x/src/bin/sharing.rs
- examples/rp235x/src/bin/uart_buffered_split.rs
- examples/rp235x/src/bin/uart_unidir.rs
- tests/rp/src/bin/uart.rs
- tests/rp/src/bin/uart_buffered.rs
- tests/rp/src/bin/uart_dma.rs
Inspired by how it is done in embassy-stm32, removed the instance from the Uart and BufferedUart implemenations. This makes it easier to make code that can run on all instances of the uart peripheral since that code no longer needs to be generic over the Instance.
> [embassy-rp] Remove <T: Instance> from Uart and BufferedUart

- embassy-nrf/src/chips/nrf5340_app.rs
- embassy-nrf/src/chips/nrf5340_net.rs
- embassy-nrf/src/ipc.rs
- embassy-nrf/src/lib.rs
This is a heavily reworked version of #3658.
I added the PPI task/event, and made each IPC event its own struct that can be handled independently.
> nrf5340: Add IPC peripheral

- embassy-stm32/src/lib.rs
- embassy-stm32/src/rcc/mod.rs
I had a need to configure an external clock generator and then switch to it which means I needed to call init and then configure RCC.
After som input from the matrix chat this is what I came up with.
Not sure if this makes sense, and I did not find any test so I have not added tests.
Might make sense to add an example but as a meaningful example would require a specific external clock generator I am unsure how to proceed but it would be possible to add:
```rust
#[embassy_executor::main]
async fn main(_spawner: Spawner) {
let p = embassy_stm32::init(Default::default());
// Configure the external clock here
let mut config = Config::default();
{
use embassy_stm32::rcc::*;
config.rcc.hse = Some(Hse {
freq: mhz(8),
mode: HseMode::Bypass,
});
config.rcc.pll = Some(Pll {
src: PllSource::HSE, …
```
> Add function to allow re-init rcc config for stm32

- embassy-rp/src/clocks.rs
- examples/rp/src/bin/overclock.rs
- examples/rp/src/bin/overclock_manual.rs
- examples/rp235x/src/bin/overclock.rs
- tests/rp/src/bin/overclock.rs
After overclocking for rp2040 got enabled, this adds convenient overclocking for rp235x.
**Maintainer Note**:
Unlike for the rp2040 there is no manufacturer support for running on higher frequency or higher core voltage. Meaning 
this is out of specs for now and in case this is considered too risky, please do not merge this!
**Reviewer Note**:
+ AI usage only for syntax help on setting registers, rest is hand-rolled
+ Add Core Voltage options for rp235x, add brownout detection values for rp235x
+ Add rp235x branch for this to `init()`
+ Add fn `core_voltage()` to retrieve the value from register instead of reading it from the config and update examples accordingly
+ Add one rp235x example
+ Add test branch for rp235x
+ some documentation changes
> RP235x overclocking

- ci.sh
So that when I do local `ci.sh` runs std examples get built on my aarch64-unknown-linux-gnu machine.
> ci: build std examples on aarch64-unknown-linux-gnu (local)

- embassy-stm32/src/lib.rs
This adds support for doc comments in the `bind_interrupts` macro, allowing them to be better documented.
**Example usage:**
```rust
bind_interrupts!(
/// Interrupt handlers
struct Irqs {
/// An interrupt handler for device x
USART3 => BufferedInterruptHandler<USART3>;
/// An interrupt handler for device y
USART2 => BufferedInterruptHandler<USART2>;
}
);
```
**Questions for reviewer**
Does this break any existing code or introduce issues? This has been working fine for me, but macros can be fun.
> Interrupt Doc Comments

- embassy-hal-internal/src/macros.rs
- embassy-hal-internal/src/peripheral.rs
- embassy-nxp/Cargo.toml
- embassy-rp/src/adc.rs
- embassy-rp/src/gpio.rs
this doesn't cover every `struct` & co. in `embassy-rp`, but at least it adds those needed for `Adc` and `adc::Channel`.
> rp: add missing `Debug` and `defmt::Format` `derive`s for ADC

- embassy-rp/src/pwm.rs
Adresses #3615, appling a fix written by @vivi202 (I can take no credits!)
I could not reproduce the issue, but the reasoning behind the fix seems plausible. I tested the change by setting up and dropping Pwm, which to me behaves as expected.
After setting up and 50% duty cycle:
After dropping:
> pwm: enable pull-down resistors for pins in Drop implementation

- embassy-stm32/src/rng.rs
This disables the RNG in the CR::RNGEN register and calls `rcc::disable` to possibly disable the corresponding clock if the refcount goes to zero. Using the "low-power" feature, I have verified that this allows to enter STOP2 mode again after the RNG has been dropped.
> Impl Drop for stm32 Rng

- embassy-rp/src/pio_programs/i2s.rs
- examples/rp/src/bin/pio_i2s.rs
- examples/rp235x/src/bin/pio_i2s.rs
The `PioI2sOutProgram` had a fixed 16bit sample depth, but that isn't reflected in the types name or the documentation.
The `PioI2sOut` output driver on the other hand accepts a `bit_depth` argument.
This was previously only used to calculate the clock frequency, while no other values than 16 made any sense.
This MR implements setting the sample bit-depth by setting it to scratch register `Y`, from where it is read by the PIO program. 
Also the channel argument is removed, since only 2 channels are supported.
> embassy-rp: Make bit-depth of I2S PIO program configurable

- embassy-usb-dfu/src/application.rs
- embassy-usb-dfu/src/dfu.rs
- examples/boot/application/stm32wb-dfu/src/main.rs
- examples/boot/bootloader/stm32wb-dfu/src/main.rs
This PR makes it possible to provide function level msos GUIDs to usb_dfu. This helps to ensure that composite DFU devices automatically get assigned the WinUSB driver on Windows.
> [embassy-usb-dfu] support function level WinUSB GUIDs

- embassy-mspm0/src/gpio.rs
- embassy-mspm0/src/int_group/l12xx.rs
Dumb mistake pretty much, should fix CI explosions.
> mspm0: add gpio handlers to l122x/l110x

- examples/std/README.md
- examples/std/tap.sh
I have been getting familiar with networking using the **std examples** and I have put together a comprehensive documentation to guide a user to run the network related std examples.
I have also corrected a the tap.sh file since it looks like the original intention was to give ownership to the `tap99` to the current user but effectively was giving ownership to `root`. This way the examples can be run, and debug, with the unprivileged user credentials.
Please consider adding this changes. to the repository and thanks all the contributors and maintainers!
> Adding documentation to network std examples

- embassy-nrf/src/chips/nrf5340_net.rs
- embassy-nrf/src/lib.rs
App core doesn't have a TEMP peripheral.
> nrf: Enable TEMP driver for nrf5340-net

- ci.sh
Since we are merging code without these tests running, it makes sense to disable them until the physical board can be checked.
> chore: temporarily disable pico tests

- embassy-stm32/src/crc/v1.rs
- embassy-stm32/src/crc/v2v3.rs
* Corrects spelling and grammar errors in documentation.
* Removes non-v1 code from v1-only source file.
* Adds 'read' operation for v2/v3, to be consistent with v1.
* Removes 'reset' from the v2/v3 'reconfigure' operation to match the documentation (the only user is the 'new' function which already issues a reset).
> stm32: Improvements to CRC HAL.

- embassy-rp/src/pio_programs/ws2812.rs
Some ws2812 (aka neopixel) devices have an additional white led. The current pio program does not support these and can cause weird shifting issues due to using only 24 bits on the FIFO config threshold. Add an optional program that supports this white led, and supports using `smart_led::RGBW<u8>`
See [this repository](https://github.com/MatrixSenpai/ripple/blob/6dcf3a26aa6b17bc549177ae20b9e43c298fc95e/binary/src/ws2812/pio.rs#L50-L94) for the original working implementation.
> Support RGBW on PioWs2812

- embassy-sync/src/channel.rs
- embassy-sync/src/priority_channel.rs
Add support for peeking into the front of the channel if the value implements Clone. This can be useful in single-receiver situations where you don't want to remove the item from the queue until you've successfully processed it.
> feat: add support for channel peek

- embassy-stm32/src/rcc/bd.rs
- embassy-stm32/src/rcc/c0.rs
- embassy-stm32/src/rcc/f013.rs
- embassy-stm32/src/rcc/f247.rs
- embassy-stm32/src/rcc/g0.rs
- embassy-stm32/src/rcc/g4.rs
- embassy-stm32/src/rcc/h.rs
- embassy-stm32/src/rcc/hsi48.rs
- embassy-stm32/src/rcc/l.rs
- embassy-stm32/src/rcc/u5.rs
- embassy-stm32/src/rcc/wba.rs
Currently, the only way of instantiating an `embassy_stm32::rcc::Config` is through the `Default` trait, which makes it not instantiable from `const` contexts.
This PR introduces a `const` `embassy_stm32::rcc::Config::new()` constructor.
- This PR is better reviewed commit by commit: each commit targets one STM32 (sub-)family, except for the first one which *also* introduces a `const` constructor for `Hsi48Config` and `LsConfig`. I can easily split that first commit or, on the opposite, squash all this PR's commits into a single one if you prefer.
- Please do check that this PR is complete and that I didn't forget an STM32 family or some feature-gated field. I did do a basic sanity check by grepping for `::default(` in `embassy-stm32/src/rcc` (the remaining seems irrelevant to this PR). …
> feat(stm32): provide a `const` constructor on `rcc::Config`

- embassy-stm32/src/can/common.rs
- embassy-stm32/src/can/fd/peripheral.rs
- embassy-stm32/src/can/fdcan.rs
The FDCAN driver was using a static function to hand out &mut State internally. Generally, care was taken to only access this from within a critical section or Interrupt. The interrupt case is an issue, if some code decided to [de]configure the buffering mode from a higher priority interrupt level than the CAN interrupt. This seems unlikely, anyway... 
This change was proposed by @DrTobe in: https://github.com/embassy-rs/embassy/pull/4223
This required: https://github.com/embassy-rs/embassy/pull/4265 as a dependency. Which also points us to the fact that buffered mode was unsound if the Channel was constructed with a Raw mutex. The first commit in this series blocks that.
This patch has been tested on STM32G431 boards, mainly with the buffered mode.
> Use a critical section mutex in CAN Fdcan driver.

- embassy-stm32/src/usb/usb.rs
Many thanks Dario for finding it!
When using CDC ACM sometimes a packet would contain data of the *next* packet after it.
This seems to solve the issue.
> STM32 USB: Read data before register update

- embassy-sync/Cargo.toml
- embassy-sync/src/lazy_lock.rs
- embassy-sync/src/once_lock.rs
- embassy-sync/tests/ui.rs
- embassy-sync/tests/ui/sync_impl/lazy_lock_function.rs
- embassy-sync/tests/ui/sync_impl/lazy_lock_function.stderr
- embassy-sync/tests/ui/sync_impl/lazy_lock_type.rs
- embassy-sync/tests/ui/sync_impl/lazy_lock_type.stderr
- embassy-sync/tests/ui/sync_impl/once_lock.rs
- embassy-sync/tests/ui/sync_impl/once_lock.stderr
This pull request introduces changes to ensure stricter `Sync` trait implementations for `LazyLock` and `OnceLock` types in the `embassy-sync` crate. It also adds regression tests to verify these changes and prevent incorrect usage of these types with non-`Sync` data. Additionally, a new dependency (`trybuild`) is added for compile-time testing.
* [`embassy-sync/src/lazy_lock.rs`](diffhunk://#diff-cd31bb3d341607967bd756da8f3d44ab3106dc08d38c7b4ec235230b584c2723L34-R39): Updated the `Sync` implementation for `LazyLock` to require both `T` and `F` to implement `Sync`.
* [`embassy-sync/src/once_lock.rs`](diffhunk://#diff-e8478b2fa15a8e88ebb2d2ea0faecdfc7223d2c3b8c5ccc0ce631aa432d74939L45-R45): Updated the `Sync` implementation for `OnceLock` to require `T` to implement `Sync`.
* …
> Fix sync bounds on LazyLock and OnceLock

- docs/index.adoc
This requires installing the [rouge gem](https://docs.asciidoctor.org/asciidoctor/latest/syntax-highlighting/rouge/), but it gives some basic syntax highlighting.
Assuming it already runs fine on your machine prior to this commit, you just need to run `gem install rouge` and add `:source-highlighter: rouge` to `index.adoc`
I noticed a couple problems other than this, like the build script complaining about missing files, but seemingly still building fine without images. I did however have to replace this file because it doesn't seem to exist in the repo:
https://github.com/embassy-rs/embassy/blob/206a324cf4d612122356fb350b4a3b56391d6f20/docs/pages/overview.adoc?plain=1#L68C1-L73C1
> Add syntax highlighter

- examples/boot/application/rp/src/bin/a.rs
The write method is given the full aligned buffer to write to flash even though it may not be fully populated. This change ensures only what has been read is written to flash. Preventing potential corrupted firmware and additional flash wear.
> Only write to the flash what was read from the file

- embassy-stm32/src/sdmmc/mod.rs
I've had the chance to test `embassy-stm32`'s eMMC support on an STM32L562 microcontroller, which works with `#[sdmmc_v2]`. I'm not sure if it's a behavior specific to that or the particular eMMC chip used, but I found that `Sdmmc` initialization would hang after sending the `SWITCH` command (used by `modify_ext_csd`). This is caused by an `R1b`-type response that took longer to clear the busy status than supported by the microcontroller's default timeout configuration. The immediately following `embassy-stm32` code wouldn't check or clear the timeout error flag, so it got stuck waiting for a completion that would never occur.
To solve this I've added a new `set_datatime` call into `init_internal`, prior to any `R1b` commands or datapath transactions. Furthermore, since values written to …
> [sdmmc] Set `datatime` during initialization

- embassy-stm32/src/hsem/mod.rs
The current STM32 HSEM driver is broken on at least one platform I've tried (STM32H755) due to a couple of bugs:
- the peripheral wasn't enabled at the RCC level
- the core ID detection was broken: the match cases are correct, but it's missing a right-shift on the mask
> embassy-stm32: fix HSEM initialization and core detection

- embassy-rp/src/rom_data/mod.rs
This removes the `//!` doc comment markers from the [`rom_data`][rd] module documentation strings, as these appear in the generated output when using the `#[doc(...)]` attribute.
[rd]: https://docs.embassy.dev/embassy-rp/git/rp2040/rom_data/index.html
> embassy-rp: fix rom_data documentation format

- embassy-stm32/src/can/bxcan/mod.rs
- embassy-stm32/src/can/common.rs
- embassy-stm32/src/can/enums.rs
- embassy-stm32/src/can/fdcan.rs
As mentioned https://github.com/embassy-rs/embassy/pull/4223, this is a proposal for using RAII for the reference counting of alive sender/receiver/transceiver instances.
Note, this is a draft PR, and also includes https://github.com/embassy-rs/embassy/pull/4271 as a dep.
@DrTobe
> Fdcan use RAII for reference counting.

- embassy-stm32/src/lib.rs
Resolves #4333 
Fixes a regression that prevented conditional items from being used in the bin_interrupts macro
> Allow conditional items in bind_interrupts macro

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/opamp.rs
The new code implements the corresponding traits for the common opamp pin naming scheme of all families, which is VINPx/VINMx and adapts the opamp driver to new opamp IP version numbers.
The same pin must not be used for multiple channels for the same opamp. For example, if VINM0 and VINM1 of the same opamp were assigned to the same pin, the channel would not be unique, meaning that the traits would be implemented in a conflicting manner.
> Adapt to new opamp pin naming scheme and opamp IP version numbers

- ci.sh
- embassy-stm32/Cargo.toml
- embassy-stm32/src/rtc/mod.rs
Added the following
- new devices (a.k.a. features) from `stm32-data`
- within `ci.sh`: attempt to build 2 `stm32wba6[2|5]` devices
- handled a default rtc implementation if the generated peripherals didn't match the mapping.
- handled a new generated peripheral `rtc_v3c0` recently introduced to `stm32-data-generated`
> Added STM32WBA6XXX devices as features

- ci.sh
- examples/stm32h723/src/bin/spdifrx.rs
The STM32H723 SPDIF RX example was not yet adapted to the new `Peri` API and thus failed to compile. This PR remedies that.
> [stm32h723]: fix spdifrx example

- examples/stm32h7rs/src/bin/xspi_memory_mapped.rs
- Cleans up the SPI and OPI commands to match the datasheet for the flash used on the Nucleo board
- Creates a separate impl for OPI operations
This has been tested on an STM32H7S3 nucleo board.
Unfortunately, the datasheet for the flash chip used on the nucleo board is not public however I was able to get access to it in order to get this example fixed up to match the datasheet.
> STM32H7RS Examples: Add OPI functionality to the XSPI example

- embassy-stm32/src/timer/pwm_input.rs
- examples/stm32f1/src/bin/pwm_input.rs
- examples/stm32f4/src/bin/pwm_input.rs
- examples/stm32g0/src/bin/pwm_input.rs
Some timers don't support PWM Input mode. 
See below for STM32G4 RM0440:
And PWM Input is usable only with CH1 and CH2 on all families.
> embassy-stm32: Rename PWM Input constructors, add warning on usable timer peripherals

- examples/rp/Cargo.toml
- examples/rp235x/Cargo.toml
To avoid confusion around build profile tweaks (see #4346), remove optimisation/lto changes and just enable generation of debug symbols for release profiles.
Also add a comment explaining that it is intentional so it is less likely to be seen as a mistake in the examples.
> Minimise build profile tweaking in rp/rp235x examples

- embassy-mspm0/src/gpio.rs
`get_output_level()` was attempting to read the input buffer, which is currently disabled by this HAL when a pin is configured as an `Output`, resulting in a constant logical low reading. After fixing this I noticed that the equivalent input reading logic was inverted. This PR fixes both issues.
> mspm0: Fix inverted GPIO logic

- embassy-stm32/src/qspi/enums.rs
- embassy-stm32/src/qspi/mod.rs
- examples/stm32f7/src/bin/qspi.rs
- examples/stm32h742/src/bin/qspi.rs
- examples/stm32l432/src/bin/qspi_mmap.rs
I noticed the sample shifting configuration for the stm32 QSPI driver is missing as `QUADSPI.cr().sshift()` is always set to `false` on initialization [here](https://github.com/embassy-rs/embassy/blob/main/embassy-stm32/src/qspi/mod.rs#L123). 
This PR adds the sample shifting option found in the STM32 CubeIDE to the existing embassy-stm32 QSPI Config.
> embassy-stm32: Added sample shifting to qspi config

- embassy-mspm0/Cargo.toml
- embassy-mspm0/build.rs
- embassy-mspm0/src/dma.rs
- embassy-mspm0/src/gpio.rs
- embassy-mspm0/src/lib.rs
- examples/mspm0g3507/.cargo/config.toml
- tests/mspm0/Cargo.toml
- tests/mspm0/build.rs
- tests/mspm0/memory_g3519.x
- tests/mspm0/src/bin/dma.rs
- tests/mspm0/src/bin/uart.rs
Add a DMA driver for mspm0. So far only implement features available on all (basic) channels. copying slices is also not implemented yet nor anything related to source/destination stride. 
~~A few things pending before this is ready to review~~
> mspm0: add dma driver

- embassy-executor/src/spawner.rs
- examples/nrf52840/src/bin/self_spawn_current_executor.rs
It's unsound with manually-created Contexts, see https://github.com/embassy-rs/embassy/issues/4379
> executor: mark Spawner::for_current_executor() as unsafe.

- embassy-embedded-hal/CHANGELOG.md
- embassy-embedded-hal/release.toml
- embassy-executor/CHANGELOG.md
- embassy-executor/release.toml
- embassy-futures/CHANGELOG.md
- embassy-futures/release.toml
- embassy-net-driver-channel/CHANGELOG.md
- embassy-net-driver-channel/release.toml
- embassy-rp/CHANGELOG.md
- embassy-rp/release.toml
- embassy-time-driver/CHANGELOG.md
- embassy-time-driver/release.toml
- embassy-time/CHANGELOG.md
- embassy-time/release.toml
- embassy-usb-driver/CHANGELOG.md
- embassy-usb-driver/release.toml
- embassy-usb/CHANGELOG.md
- embassy-usb/release.toml
- release/bump-dependency.sh
see the individual commit messages for further details.
what this PR does for the affected crates:
* it adds changelog entries for the new releases
* it adds release automation using [`cargo-release`](https://crates.io/crates/cargo-release)
* it fixes `release/bump-dependency.sh` (inadvertently created backup files, leading to lots of untracked files)
what this PR does *not* do:
* it does *not* run `release/bump-dependency.sh` for the crates (should only be done after the release of each crate)
* it does *not* enter a version number or release date in `CHANGELOG.md` (now taken care of by `cargo-release`)
* it does *not* prepare a new release for `embassy-sync`: while there were already new commits again there was just a release a few days ago so it's probably not yet needed?
* it does …
> prepare release for `embassy-rp` & dependencies

- embassy-nrf/src/gpio.rs
Fixes a mistake that misconfigures the drive pins for the nrf54l I notice while working on the support for the nrf54l.
> Fixing the nrf54l drive configuration bug

- embassy-executor/src/raw/trace.rs
Tasks that are spawned after starting SystemViewer were not named. This change ensures that tasks spawned while SystemViewer is running will be properly named, too.
> embassy-executor: rtos-trace: fix task naming for new tasks

- examples/rp235x/memory.x
According to [datasheet](https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf) (page 31), the base addresses specified as SRAM4 and SRAM5 in the example linker script should actually be SRAM8 and SRAM9.
There are 10 SRAM banks on the chip with the following base addresses:
- 0x20000000: SRAM_BASE
- 0x20000000: SRAM_STRIPED_BASE
- 0x20000000: SRAM0_BASE
- 0x20040000: SRAM4_BASE
- 0x20080000: SRAM_STRIPED_END
- 0x20080000: SRAM8_BASE
- 0x20081000: SRAM9_BASE
- 0x20082000: SRAM_END
If the example linker script is not incorrect, please share the reason as I haven't been able to find out why it's set that way.
> RP2350: Correct SRAM8 and SRAM9 base addresses in example memory.x

- embassy-nrf/src/usb/mod.rs
- embassy-rp/src/usb.rs
- embassy-stm32/src/usb/otg.rs
- embassy-stm32/src/usb/usb.rs
- embassy-usb-driver/src/lib.rs
- embassy-usb-synopsys-otg/src/lib.rs
- embassy-usb/src/builder.rs
- embassy-usb/src/class/cdc_acm.rs
- embassy-usb/src/class/cdc_ncm/mod.rs
- embassy-usb/src/class/cmsis_dap_v2.rs
- embassy-usb/src/class/hid.rs
- embassy-usb/src/class/midi.rs
- embassy-usb/src/class/uac1/speaker.rs
- examples/rp/src/bin/usb_raw_bulk.rs
- examples/rp/src/bin/usb_webusb.rs
- examples/rp235x/src/bin/usb_webusb.rs
This PR adds an optional `ep_addr` to all USB endpoint allocation methods. If a method receives`None`, the old incremental allocation behavior applies.
This enables developers to select a specific endpoint index, enabling implementation and emulation of devices where endpoints are hardcoded (e.g. FTDI USB-to-serial adapters).
I am still testing this on the various platforms that I have on hand, just wanted to get this open for discussion re: modifying these interfaces; there are a few places where this parameter doesn't necessarily need to be exposed (we can default to `None`).
> Make USB endpoint allocator methods accept an optional `EndpointAddress`

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/adc/adc4.rs
- embassy-stm32/src/adc/mod.rs
- embassy-stm32/src/rcc/wba.rs
- examples/stm32wba/src/bin/adc.rs
This adds ADC support for the WBA series, using the already existing ADC4 support for the U5 series.
This was tested on a WBA55CG. 
There are probably some simplifications to be made, but this at least works.
I haven't tested the u5 after these changes because I don't own one.
> Adds ADC4 for STM32WBA series

- embassy-rp/src/i2c.rs
i've split this in two commits since i'm not sure if you want to take the second one (enabling the warning without adding all the derives - on the other hand, if i'd add them then i'd turn it into a `deny`)
> Add `derive(Debug)` for `embassy_rp::i2c::I2c`

- embassy-stm32/Cargo.toml
- embassy-stm32/src/eth/v1/mod.rs
AFIO_MAPR.SWJ_CFG must be written as 0b111 to leave its value unchanged.
> STM32F107: Fix inadvertent re-configuration of the SWJ/JTAG pins when activating the (R)MII interface

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/ipcc.rs
Fixes https://github.com/embassy-rs/embassy/issues/4421 by exposing rfwkpsel in `ClockMux`
~~Depends on https://github.com/embassy-rs/stm32-data/pull/643~~ Merged
~~Depends on https://github.com/embassy-rs/stm32-data/pull/648~~ Merged
> stm32wb: Add rfwkpsel to ClockMux

- ci.sh
- embassy-stm32/src/rtc/low_power.rs
- embassy-stm32/src/rtc/mod.rs
- embassy-stm32/src/rtc/v3.rs
- Added low-power feature for STM32WBA65RI build in ci.sh
- RTC APB registers are different in STM32WBA6 than in STM32U5 so the embassy RTC low-power function calls had to be changed.
> Added RTC low-power support for STM32WBA

- embassy-stm32/src/adc/v3.rs
https://cdn.sparkfun.com/assets/1/6/c/b/b/STM32WB55xx_Reference_Manual.pdf @ 16.4.29 - oversampling is configured using the same registers as on G0 and U0 (except OVSE -> ROVSE for regular oversampling mode)
Requires https://github.com/embassy-rs/stm32-data/pull/647
> stm32: Enable regular oversampling for ADC v3

- .vscode/settings.json
- ci.sh
- embassy-nxp/Cargo.toml
- embassy-nxp/build.rs
- embassy-nxp/src/chips/mimxrt1062.rs
- embassy-nxp/src/gpio/rt1xxx.rs
- embassy-nxp/src/lib.rs
- examples/mimxrt1062-evk/.cargo/config.toml
- examples/mimxrt1062-evk/Cargo.toml
- examples/mimxrt1062-evk/build.rs
- examples/mimxrt1062-evk/src/bin/blinky.rs
- examples/mimxrt1062-evk/src/bin/button.rs
- examples/mimxrt1062-evk/src/lib.rs
Depends on #4419
The examples in this case are designed for the IMXRT1060-EVK.
The same chip is used in the Teensy 4.0/1, but that will probably get its own set of examples due to some differences such as the FCB and how it is flashed.
> nxp: Add mimxrt1062 support 

- embassy-embedded-hal/src/adapter/blocking_async.rs
As discussed in https://github.com/embassy-rs/embassy/pull/2910#issuecomment-2637965968, this changes `BlockingAsync` to rely on v1.0 `embedded-hal` traits to provide the implementations of `I2c` and `SpiBus`, instead of the v0.2 traits. This makes `BlockingAsync` usable on types that only implement the v1.0 traits, like `esp_hal::spi::master::Spi` [since v0.23.0](https://github.com/esp-rs/esp-hal/blob/main/esp-hal/CHANGELOG.md#removed-4).
I do not think it is possible to keep the implementations relying on the v0.2 traits at the same time, possibly because of https://github.com/rust-lang/rust/issues/20400.
BREAKING CHANGE: this is a breaking change as this would not work anymore if the inner type only implements the v0.2 traits.
---
Feel to push to this PR branch as needed.
> feat(embedded-hal)!: rely on v1.0 traits for `BlockingAsync`

- examples/stm32wb/src/bin/gatt_server.rs
Closes #3563 - this is necessary to prevent locking up after a certain number of events.
> stm32/wb: Add memory manager to GATT example

- embassy-stm32/src/rcc/u5.rs
> U5: Enable MSI auto calibration and compute frequencies

- embassy-stm32/src/lptim/timer/mod.rs
This pull request adds new methods to manage and interact with timer interrupts in the `embassy_stm32::lptim::timer::Timer` implementation. These changes provide functionality to enable, disable, check, and clear timer interrupts assuming that the default interrupt for `LPTIMx` timers should be the auto-reload match interrupt.
Enhancements to timer interrupt management:
* [`embassy-stm32/src/lptim/timer/mod.rs`](diffhunk://#diff-5c9e3bc25433dd27a2ad3d6db1bbdec1e4a111e98e2beeed28a4c0c585b21ab1R85-R109): Added methods `enable_interrupt`, `disable_interrupt`, `is_interrupt_enabled`, `is_interrupt_pending`, and `clear_interrupt` to provide comprehensive control and status checks for timer interrupts.
> Add helper methods for the low-power interrupt timer.

- embassy-stm32/src/timer/complementary_pwm.rs
The counter handles the ARR value differently depending on the counting mode. This is described in section  38.3.2 in RM0433. In center aligned mode the counter never reaches the AAR value so a CCR value equal to ARR will result in 100 % duty cycle.
> Get max duty off by one for Center-aligned mode

- embassy-rp/src/lib.rs
Updated the MPU region enablement logic in the `install_stack_guard` function to correctly set the region limit by using the stack bottom address plus 256 minus one, ensuring proper memory protection configuration.
- See Table 235 MPU_RLAR Register in [RP2350 documentation](https://datasheets.raspberrypi.com/rp2350/rp2350-datasheet.pdf) (Page 195)
- See Section 4.5 MPU_RLAR in [armv8m MPU documentation](https://www.scribd.com/document/414130259/Armv8m-Architecture-Memory-Protection-Unit-100699-0100-00-En) (Page 4-33)
> Embassy RP: RP235x Fix MPU region enablement in stack guard installation

- embassy-stm32/src/dac/mod.rs
Just added a method to create a DAC in NormalExternalUnbuffered mode.
> feat(stm32): Add DAC::new_unbuffered method.

- embassy-stm32/Cargo.toml
- embassy-stm32/src/i2c/v2.rs
originally from #4316
- removed defmt:: and explicit defmt cfg checks
- rebased
closes #4316
This fixes an issue where the slave interface would time out when the
master goes from a short write to a read (e.g. when accessing memory
registers) with a START signal between. The previous implementation
would expect the full buffer length to be written before starting to
listen to new commands.
This also adds debug trace printing which helped during implemention and
testing.
Places error checking into a function inspired from a C implementation
of HAL.
> fix: stm32 i2c slave blocking r/w

- docs/pages/layer_by_layer.adoc
proposed fix for #4226, re. https://github.com/embassy-rs/embassy/issues/4226#issuecomment-2908772500
> Update layer_by_layer.adoc to clarify PAC limitations

- embassy-net/Cargo.toml
- embassy-net/src/lib.rs
This PR adds some missing `defmt` derives to `embassy-net` so that IP address and other configuration can more easily be inspected.
> Add `embassy-net` `defmt` derives for config structs

- embassy-net/src/lib.rs
This PR adds missing equality comparison traits to some of the `embassy-net` `Config`-related structs, enabling config change detection routines ("detect user switch from DHCP to static configuration in the web UI.")
> Add missing `PartialEq` and `Eq` trait derives to `embassy-net` config structs

- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/rcc/wba.rs
- embassy-stm32/src/usb/otg.rs
- examples/stm32wba/src/bin/pwm.rs
The RCC HAL for WBA devices had support for HSE and HSI but not for the PLL. That support has been added due to the recent additions in `stm32-data` that added the PLL enums. With that in place a new addition is the inclusion of sanity checks for the PLL VCO generated frequency (it'll panic just like in the U5 HAL). That aside there's also the addition of the PLLFRACN fractional multiplier. That has also been added. The frequency asserts also take this PLLFRACN into account.
A timer example has also been added showcasing this new support for the PLL.
> Added support for PLL as a clock source on STM32WBA

- embassy-embedded-hal/src/shared_bus/asynch/i2c.rs
Removing the `'static` lifetime requirement for the shared i2c bus.
> fix: remove static lifetime requirements from i2c shared bus.

- embassy-rp/src/clocks.rs
It doesn't seem like there's any working option for low power modes on the rp235x.
The dormant_sleep() function is enabled in the rp2040, and disabled in the rp235x with a conditional compilation flag.  The datasheet for the rp2350(page 489) says that the state is still supported.
removing the flag and enabling the necessary dependencies for it seemed like the low hanging fruit.
I tried it on my project (https://github.com/Nicholas-L-Johnson/flip-card) and it works well, with 1/10 of the power usage compared to just .await-ing everything, and wakes as expected on GPIO high signal.
> removed the rp2040 flag from the dormant function

- embassy-sync/src/waitqueue/multi_waker.rs
In 3081ecf301a54f8ed3d0f72350dd21f8ac9e1b18 `register` was changed to clear the buffer when it's full, but the docs weren't updated.
> embassy-sync: Update `MultiWakerRegistration::register` docs

- embassy-nxp/Cargo.toml
- embassy-nxp/src/lib.rs
- embassy-nxp/src/time_driver/rtc.rs
- examples/lpc55s69/Cargo.toml
- examples/lpc55s69/README.md
- examples/lpc55s69/src/bin/blinky_embassy_time.rs
I implemented the embassy time diver using the RTC peripheral.
For now, we are using the lpc55-pac for RTC. Later that will be switched out for the nxp-pac one.  :)
@george-cosma please review. :D
> feat: add RTC time driver

- embassy-nrf/src/chips/nrf54l15_app.rs
- embassy-nrf/src/lib.rs
- embassy-nrf/src/rramc.rs
- examples/nrf54l15/Cargo.toml
- examples/nrf54l15/src/bin/nvmc.rs
Adding basic support for RRAMC to nrf54l15 (nrf54l15-app-s only). Exposed as Nvmc for downstream compatibility. 
I am submitting this as a Draft PR as I am unsure how it fits with [4393](https://github.com/embassy-rs/embassy/pull/4393).
> nrf54l15 Rramc (Nvmc) support

- embassy-stm32/src/i2c/config.rs
- embassy-stm32/src/i2c/mod.rs
- embassy-stm32/src/i2c/v1.rs
- embassy-stm32/src/i2c/v2.rs
- embassy-stm32/src/i2s.rs
- embassy-stm32/src/spi/mod.rs
- examples/stm32f4/src/bin/i2c.rs
- examples/stm32f4/src/bin/i2c_async.rs
- examples/stm32f4/src/bin/i2c_comparison.rs
- examples/stm32f4/src/bin/i2s_dma.rs
- examples/stm32g0/src/bin/i2c_async.rs
- examples/stm32g4/src/bin/i2c_slave.rs
- examples/stm32h5/src/bin/i2c.rs
- examples/stm32h7/src/bin/camera.rs
- examples/stm32h7/src/bin/i2c.rs
- examples/stm32h7/src/bin/i2c_shared.rs
- examples/stm32h7rs/src/bin/i2c.rs
- examples/stm32l4/src/bin/i2c.rs
- examples/stm32l4/src/bin/i2c_blocking_async.rs
- examples/stm32l4/src/bin/i2c_dma.rs
- examples/stm32l4/src/bin/spe_adin1110_http_server.rs
- examples/stm32u0/src/bin/i2c.rs
- examples/stm32u5/src/bin/i2c.rs
Fixes [#4510](https://github.com/embassy-rs/embassy/issues/4513)
Also did a little bit cleanup to unify naming for config params.
> embassy-stm32: Add frequency and gpio speed to Config for i2c and i2s

- embassy-stm32/src/timer/complementary_pwm.rs
- embassy-stm32/src/timer/low_level.rs
The idle state is determined by the MOE, OSSI, OSSR, OISx and OISxN bits according to the 334 in the RM0433 Reference manual. This PR adds interfaces for controlling these bits.
The set_output_idle_state method, controlling OISx and OISxN, sets the idle state as inverted as both channels are configured with the same polarity in set_polarity method and idle state can't be that both are active.
> Add methods for idle-state control in STM32 Complementary PWM

- embassy-stm32/src/i2c/v2.rs
This PR fixes a bug where subsequent blocking I2C reads would fail with a timeout.
The read_internal function, which uses Stop::Automatic, was returning before the STOP condition was actually complete on the bus. This created a race condition where the next transaction would start while the bus was still busy.
The fix is to call wait_stop() at the end of the read. This ensures the transaction is fully terminated and the bus is idle before the function returns.
Fixes #4540
> fix stm32 i2c: wait for STOP flag in blocking read to terminate read transaction

- .github/workflows/changelog.yml
Based on similar workflow for esp-hal.
This requires pull requests to add changelog entries to modules that are touched, unless the skip-changelog label is set.
> chore: add changelog enforcement

- embassy-nrf/src/pwm.rs
Tiny change to make `embassy-nrf` ready for future `nrf-pac` updates (e.g. nrf54 updates). Since the release of `nrf-pac` in Jan 2025, `chiptool` has been updated to make the inner integer in Newtypes private. `LoopCnt(n)` will thus break when the pacs are updated in the future with new versions of `chiptool`. `LoopCnt::from_bits(n)` is already supported and currently used in the `pwm` module.
> Use from_bits with LoopCnt

- embassy-stm32/src/vrefbuf/mod.rs
VREFBUF has TRIM values at known memory locations.
This PR updates the new VREFBUF implementation to provide proper support for its initialization.
Any feedback is welcome 😄
> Added VREFBUF-TRIM manual write. Known errata

- embassy-time/src/delay.rs
Modify `async fn` to return `impl Future`.
`async { xx.await }` is not zero cost, so such invalid packaging should be avoided without affecting correctness.
> Optimize embedded_hal_async::delay::DelayNs impl

- embassy-rp/CHANGELOG.md
- embassy-rp/src/i2c.rs
- embassy-rp/src/i2c_slave.rs
- examples/rp/src/bin/i2c_blocking.rs
- Example updated to demonstrate enabling internal pullups
- Add `sda_pullup` and `scl_pullup` fields to I2C Config
> Add configurable internal pullups for rp i2c

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/xspi/mod.rs
If a previous command used alternate bytes and the next command does not have them the alternate bytes need to be turned off.
> STM32 XSPI: Disable alternate bytes if not requested

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/adc/v3.rs
- examples/stm32h5/src/bin/adc_dma.rs
Tested on an STM32H533RE. Documentation of other chips has been reviewed to ensure compatibility, but not extensively.
I can make a similar change for other ADC versions, but I don't have the hardware to test it.
> stm32/adc/v3: allow DMA reads to loop through enabled channels

- embassy-stm32/src/sai/mod.rs
WB MCKDIV has a width of 6 bits (RM0434 Rev 14, p. 1269).
> stm32/sai: fix WB MCKDIV

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/sai/mod.rs
These values should clearly be made independent, at least in the WB55 microcontroller (and so I suspect in all the others) since NODIV implies no divider between the master clock and the bit clock, but it does NOT imply no divider between the SAI clock and the master clock. Quoting from the WB55 reference manual (RM0434 Rev 14, p. 1219):
> #### Clock generator programming when NODIV = 1
> When MCKDIV is different from 0, the frequency of the bit clock (SCK\_x) is given in the
> formula below:
> $`F_{SCK\_x} = F_{MCLK\_x} = \frac{F_{sai\_x\_ker\_ck}}{MCKDIV}`$
Tests I have performed with the WB55 show you can use `NODIV = 1` with `MCKDIV != disabled` and still get valid configurations and correct clock frequencies.
I'm not entirely sure about integrating this change though since CubeMX …
> stm32/sai: make NODIV independent of MCKDIV

- embassy-sync/CHANGELOG.md
- embassy-sync/src/signal.rs
Dropping wakers is a recipe for hangs, as was discovered on [matrix](https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$l_xv_ruxW4G3yWKAC6g2cVQYZiCBqcfY_9204R9lo4c?via=matrix.org&via=beeper.com&via=mozilla.org).
Might be worth deprecating and removing the method altogether since `try_take` has the same effect.
> embassy-sync: Don't drop wakers in Signal::reset

- embassy-executor/CHANGELOG.md
- embassy-executor/src/raw/mod.rs
- embassy-executor/src/raw/state_atomics.rs
- embassy-executor/src/raw/state_critical_section.rs
This PR walks back a bit on #4244, which PR turned out to be a small perf hit on ESP32-S2, ESP32-S3 and possibly more.
> Fix perf regression on ESP32-S2/S3

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/usb/usb.rs
A busy loop has been added for when the "time" feature is not enabled.
Fixes #4610
> fix: stm32/usb: Fixed STM32H5 build requiring time feature

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/i2c/v2.rs
When a slave responds with a NACK in blocking I²C master mode, all subsequent transmissions send only the address followed immediately by a STOP.
This happens because the current implementation sets I2C_CR2.STOP = 1 whenever any error (including a NACK) occurs.
According to the reference manual: "If a NACK is received: […] a STOP condition is automatically sent […]"
As a result, the STOP bit is already set when the next transmission starts.
This bug was not triggered until #4454 was merged.
> stm32/i2c: fix failure of subsequent transmissions after NACK

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/timer/complementary_pwm.rs
Add independent polarity setters to complementary_pwm. Previously, set_polarity updated both main and complementary outputs together. These new functions let users modify the main or complementary output separately, supporting use cases where only one output’s polarity should change.
> Add timer set polarity functions for main and complementary outputs in complementary_pwm

- embassy-rp/src/lib.rs
- embassy-rp/src/psram.rs
- embassy-rp/src/qmi_cs1.rs
- examples/rp235x/src/bin/psram.rs
This pull request adds support for the QMI CS1 peripheral, and then uses that support to implement further support for the APS6404L PSRAM as QMI Memory 1.
I have tried to keep the code as general as foreseeable for other forms of PSRAM. The code is presumably general enough to handle using a second serial NOR flash instead of a PSRAM, but I imagine a PSRAM is a much more common use case.
> feat(embassy-rp): RP2350 - Add support for QMI CS1, and for APS6404L PSRAM

- embassy-stm32/CHANGELOG.md
- embassy-stm32/Cargo.toml
- embassy-stm32/build.rs
- embassy-stm32/src/adc/mod.rs
- embassy-stm32/src/i2s.rs
- embassy-stm32/src/lib.rs
- embassy-stm32/src/sai/mod.rs
- embassy-stm32/src/spi/mod.rs
- examples/stm32h7/src/bin/sai.rs
- examples/stm32h723/src/bin/spdifrx.rs
- **stm32/sai: update for new metapac, simplify cfgs.**
- **stm32: peri_v1_bar now enables cfgs peri_v1 and peri_v1_bar.**
- **stm32/spi: update for new version numbering, add i2s support for all versions.**
> stm32: add i2s support for all versions, cleanup spi/i2s/sai versions.

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/ospi/mod.rs
Rebase of #4581
- **OSPI RAM Support**
- **Separate DQS functions**
- **Updated changelog**
- **changelog formatting**
> stm32: OSPI ram support

- embassy-stm32/src/adc/v1.rs
Some STM32 MCUs feature an internal temperature sensor which is connected to a ADC channel. 
It seems that in `adc/v1.rs`, the `AdcChannel` implementation for `Temperature` is using channel 16. However, for STM32L0-series MCUs it seems the internal temperature sensor is consistently connected to `ADC_IN18`. 
_(excerpt from https://www.st.com/resource/en/datasheet/stm32l011d4.pdf)_
While looking through the datasheets, I realized that STM32L0x0-series (value line) seems _not_ to feature a temperature sensor, however I was not sure how to handle this. STM32L0x1 (access line), STM32L0x2 (USB) and STM32L0x3 (USB & LCD) comprise the temperature sensor. 
This MR suggest to rely on a compile-time `cfg` to select the channel used for measuring the temperature.
> embassy-stm32: Fix temperature ADC channel for STM32L0 series

- embassy-usb-driver/CHANGELOG.md
- embassy-usb-driver/src/lib.rs
instead of always transferring only USB packets, add a provided method to transmit an entire data block by using a simple loop construct.
> feat: add helper to read/write full transfer blocks

- embassy-rp/CHANGELOG.md
- embassy-rp/src/pio_programs/i2s.rs
- examples/rp235x/src/bin/pio_i2s_rx.rs
Mostly following the same format as the PioI2sOutput struct and related structs/implementations, I have implemented an I2S controller and receiver (e.g. for use with an I2S microphone, INMP441 in my case) for the RP235x family using PIO and created an example binary for it.
> Add PioI2sIn, PioI2sInProgram, and example binary

- embassy-net-wiznet/CHANGELOG.md
- embassy-net-wiznet/src/chip/mod.rs
- embassy-net-wiznet/src/chip/w5100s.rs
- embassy-net-wiznet/src/chip/w5500.rs
- embassy-net-wiznet/src/chip/w6100.rs
- embassy-net-wiznet/src/device.rs
Tested with this device:
https://docs.wiznet.io/Product/iEthernet/W6100/w6100-evb-pico2
I've introduced a new register `SOCKET_INTR_CLR` as the W6100 (and presumably later devices) use a _different_ register to clear the socket interrupt. See `Sn_IRCLR` on page 61:
https://docs.wiznet.io/img/products/w6100/w6100_ds_v105e.pdf
On previous driver implementations (W5100/W5500) this register address is simply a duplicate of `SOCKET_INTR`.
Weirdly the MAC filter does not operate like the W5500 as having it turned on will stop DHCP working. I've left the MAC filter disabled but this does not affect the operation of this device (although it will cause more noise on the SPI bus).
For this reason I would still consider this driver experimental however I would like to start the conversation of …
> Add Wiznet W6100 driver

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/hspi/mod.rs
- embassy-stm32/src/ospi/enums.rs
- embassy-stm32/src/ospi/mod.rs
- embassy-stm32/src/qspi/enums.rs
- embassy-stm32/src/qspi/mod.rs
- embassy-stm32/src/xspi/enums.rs
- embassy-stm32/src/xspi/mod.rs
Hi!
I'm in the middle of improving the error handling in OSPI and noticed this detail that makes the API tiny bit more cumbersome than it needs to be.
One can't use the same config for more than one transfer because read/write methods take it by ownership and `TransferConfig` doesn't implement `Clone` neither `Copy`.
This PR unifies what we derive for all config structs in all SPI implementations in `embassy-stm32` to `Clone`, `Copy` and `defmt::format` if the `defmt` feature is enabled.
It'd be best if could also change the read/write methods to merely borrow `TransferConfig`. None of them really need the ownership so it's just a question of changing the function signatures. However that would be a breaking change. Let me know if that's a desirable change and I'll be happy to submit a …
> Unify derivation of Clone, Copy and defmt::format for all *SPI configs

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/ospi/mod.rs
Currently, trying to write a buffer longer than `0xFFFF` panics here:
https://github.com/embassy-rs/embassy/blob/ec117e3b08e329c0d713dcd493822fbb547eb5aa/embassy-stm32/src/dma/gpdma/mod.rs#L612
Support writing longer buffers in OSPI by chunking them and dispatching multiple DMA transfers.
This requires slight participation from the CPU on every 64kB boundary. A more performant approach would be setting up a LinkedList DMA, but that's a bigger change. We may try to do that in a separate PR later.
We have successfully tested this on STM32U5AZJ.
cc @bschwind
> embasy-stm32: Allow large OSPI DMA writes with chunking

- embassy-mspm0/CHANGELOG.md
- embassy-mspm0/build.rs
- embassy-mspm0/src/adc.rs
- embassy-mspm0/src/lib.rs
- examples/mspm0g3507/src/bin/adc.rs
- examples/mspm0l1306/src/bin/adc.rs
Adding the adc implementation:
- Reading a single channel, blocking and asynchronously
- Reading a sequence of channels, only asynchronously (the interface from [here](https://github.com/embassy-rs/embassy/blob/a6cd24907aa43a8178a16b0db3d6b376f67f7540/embassy-stm32/src/adc/v3.rs#L411) )
I tested the implementation before my L1306 board broke with the dev boards for MSPM0G3507 and MSPM0L1306.
> MSPM0: add adc implementation

- cyw43/CHANGELOG.md
- cyw43/src/control.rs
Update doc comment to clarify that Control::join() can be used to join
networks using the provided options, not only open networks.
> docs(cyw43): clarify Control::join() docs

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/rcc/c0.rs
Include `Hsi48Config` in the RCC config struct to provide support for USB CRS (similar to [STM32G0](https://github.com/embassy-rs/embassy/blob/main/embassy-stm32/src/rcc/g0.rs)). These changes were tested with an STM32C071G8 and an STM32C071KB and appear to work well.
> USB CRS sync support for STM32C071

- embassy-stm32/CHANGELOG.md
- embassy-stm32/Cargo.toml
- embassy-stm32/src/rcc/bd.rs
- embassy-stm32/src/rtc/low_power.rs
- embassy-stm32/src/rtc/mod.rs
- embassy-stm32/src/rtc/v2.rs
It also includes improvements in accuracy of the l412 and l422 RTC register map.
I have tested the changes locally and can confirm that the RTC is now working on L4P5.
> stm32-metapack: Corrects the RTC register map for l4p and l4q.

- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/timer/qei.rs
- tests/stm32/src/bin/afio.rs
This is basically #3728 (thanks to [leehambley](https://github.com/leehambley) for getting it started) but with individually configurable pulls for each encoder channel, and based on a more recent embassy commit.
Related to #3721
> Allow configuring the pull up/down resistors and Qei mode for the Qei peripheral

- embassy-hal-internal/src/atomic_ring_buffer.rs
- embassy-stm32/CHANGELOG.md
- embassy-stm32/src/usart/buffered.rs
- embassy-stm32/src/usart/mod.rs
- embassy-stm32/src/usart/ringbuffered.rs
Add a new option to control the behaviour of `BufferedUartRx` and `RingBufferedUartRx`.
Currently, `BufferedUartRx` returns as soon as _any_ data is available in the buffer, even just a single byte, while `RingBufferedUartRx` returns either when line idle is detected or when the DMA internal buffer half-full or full position is written over.
In my case it's useful to have `BufferedUartRx` wait for more data so I can process larger packets (and typically complete packets due to the line idle), but in other cases it's useful for `RingBufferedUartRx` to return eagerly to reduce latency. This change allows choosing either behaviour and makes the two types consistent.
For `BufferedUartRx` the modification is fairly straightforward; `RingBuffer` gains `is_half_full()`, the interrupt handler …
> STM32: USART: Add `eager_reads` config option

- docs/pages/embassy_in_the_wild.adoc
Yet another maker project for the "in the wild" section: https://github.com/1-rafael-1/air-quality-monitor
Is feature-complete and built & works well to remind me of airing my room when working from home.
> Add Air Quality Monitor project to Embassy in the Wild page

- embassy-nrf/CHANGELOG.md
- embassy-nrf/src/chips/nrf54l15_app.rs
- embassy-nrf/src/lib.rs
- embassy-nrf/src/radio/ieee802154.rs
- examples/nrf5340/src/bin/nrf5340dk_internal_caps.rs
Apparently, this is the way to set the internal HFXO capacitor value for the nrf5340dk. I also see it setting various undocumented registers for SAADC, COMP, TEMP, RADIO, etc.
Does the same thing as https://github.com/zephyrproject-rtos/hal_nordic/blob/2c0fd06a98bb9b89ac234b75b2c217742f0df1ba/nrfx/mdk/system_nrf5340_application.c#L97-L109.
Also adds the option to explicitly disable internal capacitors to override the TRIMCNF values.
> nrf: apply FICR.TRIMCNF values

- embassy-mspm0/CHANGELOG.md
- embassy-mspm0/src/gpio.rs
`OutputOpenDrain` pins always read as `LOW` even after `set_high()`.
(You can reproduce this by reverting e84f90178099a8326413ff39176d8e2d2b372dd6 and then running `cargo run --bin gpio_mode` on an MSPM0L1306 launchpad)
**Root causes:**
1. Input buffer (`INENA`) was disabled, preventing reads
2. Output driver (`DOE`) was not enabled, preventing active pull-down
Modified `Flex::set_as_input_output()` in `gpio.rs`:
**1. Enable input buffer** (line 159):
```rust
pincm.modify(|w| {
w.set_pf(GPIO_PF);
w.set_hiz1(true);
w.set_pc(true);
w.set_inena(true); // Changed from false
});
```
**2. Enable output driver** (lines 162-165):
```rust
// Enable output driver (DOE) - required for open-drain to drive low
self.pin.block().doeset31_0().write(|w| {
w.set_dio(self.pin.bit_index(), true);
});
```
- …
> [mspm0] fix open-drain config
