embassy-rs/embassy

embassy-nrf/Cargo.toml
embassy-nrf/src/lib.rs
embassy-nrf/src/uarte.rs
embassy/src/util/signal.rs
examples/src/bin/buffered_uart.rs
examples/src/bin/uart.rs

Outstanding work
* Example code
* Make it generic so it works with UART0, UART1, UARTx…
* Add and review documentation
* Is `stop()` on the `ReceiveFuture` best practice?
* Allow concurrent send and receive, `&mut self` prevents that. Possible solution: Split into RX and TX parts, each with `&mut self`
* Coexistance with current uarte code (especially the ISR). Maybe there is a better way than cargo features to select between them.

(low power) UARTE implementation

---

embassy-macros/src/lib.rs

#[task]
pub async fn run(mut param: Param) {}
warning: variable does not need to be mutable

Fix warnings for tasks that take mutable parameters

---

embassy-nrf/src/uarte.rs
embassy-nrf/src/util/mod.rs
embassy/src/util/signal.rs

I did more testing and current consumption measurements on the UARTE peripheral.
Details of each improvement is described in the commit messages.
There have been three major current consumption improvements:
* Do not spin when stopping a receive future (1st 6mA peak is gone)
* Low power wait when dropping RX futures (2nd 6mA peak is gone)
* Do not try to disable receiver or transmitter when it is disabled already ("tail" of the first falling edge)
before
after
Code for the power consumption test sequence:
``` rust
#[task]
async fn run(mut led: Pin<Output<PushPull>>, mut uart: uarte::Uarte<pac::UARTE0>) {
let mut buf = [0; 8];
Timer::after(Duration::from_millis(500)).await;
buf.copy_from_slice(b"bootboot");
uart.send(&buf).await.unwrap();
loop {
// Wait for data.
// Receive ends when the …
```

UARTE power optimization and improvements

---

embassy-stm32f4/src/serial.rs

This issue occurred because the change occurred immediately before the stm32f4 pull request was merged. I still need to test on hardware.

fix set_handler context

---

embassy/src/gpio.rs
embassy/src/lib.rs

A very common usage for "pin interrupts" is IRQ lines of external chips. With the current GPIOTE this is not very well abstracted, since a driver would need to take ownership of the GPIOTE peripheral *plus* the irq pin.
The solution is for GPIOTE (and EXTI for stm32, etc) to have an API that creates "pin wrappers" for single pins that implement the proposed traits. This way users can wrap mutiple pins and then hand them out to different driver crates.
A driver crate could use an interrupt pin like this:
```rust
loop { 
pin.wait_for_low();
// retrieve whatever events the chip has for us via i2c/spi/etc
}
```
These are separate traits because different hardware supports different features. For example, nrf's GPIOTE PORT event can't wait for edges, only for high/low, while GPIOTE channels …

RFC: GPIO WaitForFoo traits

---

embassy-macros/src/lib.rs

The raw enum values are not always equal to the interrupt number
fixes #23

Fix IRQ numbers

---

embassy-stm32f4/src/exti.rs
embassy-stm32f4/src/lib.rs

This is a draft PR for the EXTI interrupt handler (similar to GPIOE on nrf). Notes about EXTI:
> In section one (GPIOs) we have 16 interrupt lines. They are line0 to line15 and they also represent pin number. This means, PA0 is connected to Line0 and PA13 is connected to Line13.
> 
> You have to know that PB0 is also connected to Line0 and PC0 also and so on. This is for all pins on board, All Px0 (where x is GPIO name) pins are connected to Line0 and let’s say all Px3 are connected to Line3 on the Interrupt channel.
> 
> All pins with same number are connected to line with same number. They are multiplexed to one line.
> 
> IMPORTANT: You can not use two pins on one line simultaneously:
> 
> PA0 and PB0 and PC0 and so on, are connected to Line0, so you can use only one pin at one time to …

Add EXTI interrupt handler for GPIO pins

---

.vscode/settings.json
embassy-macros/src/lib.rs
embassy-nrf-examples/src/bin/buffered_uart.rs
embassy-nrf-examples/src/bin/executor_fairness_test.rs
embassy-nrf-examples/src/bin/gpiote.rs
embassy-nrf-examples/src/bin/gpiote_port.rs
embassy-nrf-examples/src/bin/multiprio.rs
embassy-nrf-examples/src/bin/qspi.rs
embassy-nrf-examples/src/bin/rtc_async.rs
embassy-nrf-examples/src/bin/rtc_raw.rs
embassy-nrf-examples/src/bin/uart.rs
embassy-nrf/src/rtc.rs
embassy-stm32f4-examples/src/bin/exti.rs
embassy-stm32f4-examples/src/bin/serial.rs
embassy/src/executor/mod.rs
embassy/src/executor/raw.rs
embassy/src/executor/run_queue.rs
embassy/src/executor/timer.rs
embassy/src/executor/timer_queue.rs
embassy/src/executor/waker.rs
embassy/src/interrupt.rs
embassy/src/lib.rs
embassy/src/time/traits.rs
embassy/src/util/signal.rs
test-build.sh

- It was possible to call run() reentrantly from within a task (soundness issue)
- it's now possible to spawn futures across threads (SendSpawner, #37)

Executor API V2.

---

embassy-stm32f4/src/exti.rs

Bit should be cleared when created. This caused problems in my application, but I had to have the RTC fixed to see it.

stm32f4: exti: clear interrupt pending bit

---

embassy-nrf-examples/.cargo/config
embassy-nrf-examples/Cargo.toml
embassy-nrf-examples/src/bin/buffered_uart.rs
embassy-nrf-examples/src/bin/multiprio.rs
embassy-nrf-examples/src/bin/qspi.rs
embassy-nrf-examples/src/bin/rtc_raw.rs
embassy-nrf-examples/src/bin/uart.rs
embassy-nrf-examples/src/example_common.rs
embassy-nrf/Cargo.toml
embassy-stm32f4-examples/.cargo/config
embassy-stm32f4-examples/Cargo.toml
embassy-stm32f4-examples/src/example_common.rs
embassy-stm32f4/Cargo.toml
embassy/Cargo.toml

mostly to go along with the same update to nrf-softdevice (because {:x} is awesome)

update defmt and defmt-rtt to 0.2.0

---

embassy-nrf-examples/src/bin/spim.rs
embassy-nrf/src/lib.rs
embassy-nrf/src/spim.rs

I'm trying out a new way to wait for completion like this:
- Task enables `intenset.end` and starts transfer
- interrupt fires. Handler disables it with `intenclr.end` and wakes the async task
- task checks `events_end`.
This is nearly equivalent to using a Signal, except we're using the `events_end` register itself to store the "done" flag instead of moving it from there into the Signal. This is better than a Signal because:
- Signals use a critical section to work. (Since we're using PeripheralMutex a non-Sync signal could work)
- Signals are 12 bytes, a waker is just 8 bytes.

nrf: add spim

---

embassy-traits/src/delay.rs
embassy-traits/src/lib.rs
embassy/src/executor/timer.rs
embassy/src/lib.rs
embassy/src/time/duration.rs

There needs to be a generic timer trait that is not tied to embassy for other libraries to depend on.

add delay trait

---

embassy-nrf-examples/Cargo.toml
embassy-nrf/Cargo.toml
embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/qspi.rs
embassy-nrf/src/spim.rs
embassy-nrf/src/uarte.rs

Use the `psel_bits()` method to reduce #[cfg] clutter

Update `nrf-hal` to v0.12.1

---

embassy-stm32f4/src/lib.rs
embassy-stm32f4/src/qei.rs
embassy-traits/Cargo.toml
embassy-traits/src/lib.rs
embassy-traits/src/qei.rs

This one may be a little too specific, but in my application I use a knob as a control, and wait for it to move up or down to adjust a menu. The 'async' qei trait allows the user to wait until the encoder has moved up or down a certain number of rotations.

add qei trait and impl

---

embassy-stm32f4/src/exti.rs

This is necessary for being able to use a pin as both `async` input and output. Another option would be to `impl embedded_hal::digital::v2::*` for `ExtiPin`.

embassy-stm32f4: Add embedded_hal::digital::v2::* for ExtiPin

---

Cargo.toml
ci.sh
embassy-stm32l0/Cargo.toml
embassy-stm32l0/src/exti.rs
embassy-stm32l0/src/fmt.rs
embassy-stm32l0/src/interrupt.rs
embassy-stm32l0/src/lib.rs

Made possible with #48, tested to work on my `stm32l072`. It's quite similar to `embassy-stm32f4` so far, with some changes because of differences between `stm32l0xx-hal` and `stm32f4xx-hal`.

Add stm32l0 support for ExtiPin futures

---

embassy-extras/src/peripheral.rs
embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/qspi.rs
embassy-nrf/src/spim.rs

Change 1: Remove `free()`. Simplifies code significantly, since now it's no longer possible for it to be in "freed" state. 
The free() pattern works really badly with pinned data anyway: you can't take owned Self because that would mean moving self.
The need for free() should go away once we figure out how to create drivers that borrow the peripherals, so you'll be able to simply drop the driver to recover access to the owned peripherals.
Change 2: separate `register_interrupt()` method. It's the driver's responsibility to call it. This allows more code size, because drivers may call `with` in codepaths where they know the interrupt is already registered, which saves the check.

Simplify PeripheralMutex

---

embassy-stm32/src/exti.rs
embassy-stm32f4-examples/src/bin/exti.rs

stm32: fix exti impl. to require dp.SYSCFG.constrain()

---

embassy-traits/src/delay.rs
embassy/src/executor/timer.rs

Adds documentation and a couple inline examples for the remainder of `embassy::time`
Relates to #60

Document remainder of embassy::time

---

embassy-macros/Cargo.toml
embassy-macros/src/lib.rs
embassy-nrf/Cargo.toml
embassy-stm32/Cargo.toml
embassy-stm32/src/lib.rs
embassy-stm32f4-examples/Cargo.toml
embassy-stm32f4-examples/src/bin/rtc_async.rs
embassy/src/executor/mod.rs
embassy/src/lib.rs

Example:
```rust
use defmt::panic;
use embassy;
use embassy::executor::Spawner;
use embassy::task;
use embassy::time::{Duration, Timer};
use embassy_stm32f4;
use embassy_stm32f4::hal;
#[task]
async fn run1() {
loop {
info!("BIG INFREQUENT TICK");
Timer::after(Duration::from_ticks(32768 * 2 as u64)).await;
}
}
#[task]
async fn run2() {
loop {
info!("tick");
Timer::after(Duration::from_ticks(13000 as u64)).await;
}
}
#[embassy::main(use_hse = 48)]
async fn main(spawner: Spawner) {
let (dp, clocks) = embassy_stm32f4::Peripherals::take().unwrap();
spawner.spawn(run1()).unwrap();
}
```
This provides an initial implementation that works with the standard clock configuration. The API can be set now and later refined.

add embassy::main

---

Cargo.example.toml

The device-specific stm HALs no longer exist as they were merged into `embassy-stm32`.
This PR removes references to them in the example workspace toml

Purge outdated references

---

embassy-extras/src/macros.rs

Ensures that, after the first call to `take()`, we can't take the peripherals again.

Mark peripherals as taken

---

embassy-macros/Cargo.toml
embassy-macros/src/lib.rs
embassy-std/Cargo.toml

When building a generic macro that should work on both cortex-m and std alike, having a main macro that works on std is kind of useful.

Add std version of embassy::main

---

embassy-stm32/src/f4/mod.rs
embassy-stm32/src/f4/spi.rs
embassy-stm32/src/lib.rs

Notes:
- read must wait for spi interrupt as well as dma interrupt. If NAK signal occurs, then spi interrupt will fire.
- read_write reads and writes at the same time.

stm32: add draft spi trait

---

embassy-macros/src/chip/nrf.rs
embassy-macros/src/chip/rp.rs
embassy-macros/src/chip/stm32.rs
embassy-macros/src/lib.rs
embassy-macros/src/path.rs

This allows crates depending on embassy that wants to use a different
module path to do so for the 'task' and 'main' macros, by passing the
parameter 'embassy_prefix'. The prefix defaults to '::', which will
retain the existing behavior.

Add embassy_prefix attribute parameter to task and main macros

---

embassy-nrf-examples/src/bin/gpiote_port.rs
embassy-nrf-examples/src/bin/qspi.rs
embassy-nrf-examples/src/bin/spim.rs
embassy-nrf-examples/src/bin/uart.rs
embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/gpiote.rs
embassy-nrf/src/qspi.rs
embassy-nrf/src/spim.rs
embassy-nrf/src/uarte.rs
embassy-stm32-examples/src/bin/exti.rs
embassy-stm32/src/exti.rs
embassy-stm32/src/f4/serial.rs
embassy-stm32/src/f4/spi.rs
embassy-traits/src/delay.rs
embassy-traits/src/flash.rs
embassy-traits/src/gpio.rs
embassy-traits/src/i2c.rs
embassy-traits/src/spi.rs
embassy-traits/src/uart.rs
embassy/src/executor/timer.rs

Many people have reported struggling with putting pinned drivers in their structs. Pin has lots of usability issues:
- It doesn't integrate well with the borrow checker. For example it doesn't automatically reborrow, so you have to use `.as_mut()`.
- It's "infectious": if a struct contains something pinned, you have to make it pinned too, all the way to the topmost allocation.
- There's no good story on how to do pin projections: you either have to use unsafe, or use the bloated `pin-project`, or the incomplete `pin-project-lite`.
This PR attempts to remove Pin by moving the irq-accessible state from the driver structs to `static`s, so driver struct instances can be moved around freely.

Remove Pin

---

embassy-traits/src/lib.rs
embassy/src/lib.rs

the const_fn feature was split into const_fn_trait_bound and const_fn_unsize: https://github.com/rust-lang/rust/pull/84310
I'm not sure why the CI wasnt failing as the rust change was merged a few weeks ago.

Fix build on the latest nightly

---

.github/workflows/rust.yml
rust-toolchain.toml

The changes are:
*   setup a rust-toolchain file using the modern format: https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file
*   removed toolchain specification from github actions config so that it will fall back to the toolchain file: https://github.com/actions-rs/toolchain
I hope my CI changes do what I think they should... I cant really test them locally.
Dependent on: https://github.com/embassy-rs/embassy/pull/166
This change could be controversial so I'm happy to discuss it.
The advantages I see here are:
*   CI doesnt break due to nightly regressions or breaking changes.
*   Developers work on a common nightly, preventing differences between nightlies from causing hard to track down issues.
*   Users have a documented nightly version that embassy supports, and …

Use rust-toolchain.toml for developers and CI

---

embassy-extras/src/ring_buffer.rs
embassy-nrf-examples/src/bin/blinky.rs
embassy-nrf-examples/src/bin/buffered_uart.rs
embassy-nrf-examples/src/bin/executor_fairness_test.rs
embassy-nrf-examples/src/bin/gpiote_channel.rs
embassy-nrf-examples/src/bin/ppi.rs
embassy-nrf-examples/src/bin/pwm.rs
embassy-nrf-examples/src/bin/qspi.rs
embassy-nrf-examples/src/bin/spim.rs
embassy-nrf-examples/src/bin/timer.rs
embassy-nrf-examples/src/bin/uart.rs
embassy-nrf-examples/src/bin/uart_idle.rs
embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/gpio.rs
embassy-nrf/src/pwm.rs
embassy-nrf/src/qspi.rs
embassy-nrf/src/saadc.rs
embassy-nrf/src/spim.rs
embassy-nrf/src/twim.rs
embassy-nrf/src/uarte.rs

I was wary of removing the unused fields, but I couldnt see any problem with doing so as the `embassy_nrf::peripherals::*` dont have drop impls.

Fix all warnings on embassy-nrf + embassy-nrf-examples + embassy_extras

---

embassy-rp-examples/src/bin/button.rs
embassy-rp-examples/src/bin/uart.rs
embassy-rp/build.rs
embassy-rp/src/dma.rs
embassy-rp/src/lib.rs
embassy-rp/src/pll.rs
embassy-std-examples/src/bin/serial.rs
embassy-std-examples/src/bin/tick.rs

Pulls the warning fixes out of https://github.com/embassy-rs/embassy/pull/190
I'm landing these separately as the namespaced-features addition is fairly contentious
This still leaves a warning unfixed when compiling embassy without defmt. e.g. when compiling embassy-std-examples.

Fix all warnings on embassy-rp and embassy-rp-examples and embassy-std-examples

---

embassy-stm32-examples/.cargo/config.toml
embassy-stm32-examples/memory.x
embassy-stm32-examples/src/bin/blinky.rs
embassy-stm32-examples/src/bin/button.rs
embassy-stm32-examples/src/bin/button_exti.rs
embassy-stm32-examples/src/bin/spi.rs
embassy-stm32-examples/src/bin/usart.rs
embassy-stm32-examples/src/bin/usart_dma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/dma/v2.rs
embassy-stm32/src/exti.rs
embassy-stm32/src/lib.rs
embassy-stm32/src/pac/regs.rs
embassy-stm32/src/rng.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/spi/v1.rs
embassy-stm32/src/usart/v1.rs

I used the STM32F429ZITx chip as the cargo.toml uses stm32f429zi but there also seems to be a STM32F429ZIYx not sure what the difference would be..

Fix warnings for embassy-stm32 and embassy-stm32-examples and add .cargo/config.toml + memory.x

---

embassy-nrf/src/spim.rs

With https://github.com/rust-embedded/embedded-hal/pull/126 merged we can now exhaustively match on the SPI mode

match on SPI mode

---

embassy/src/interrupt.rs

Allows the compiler to figure out bounds for wrapper code of owned
peripherals and interrupts.
Example: https://gist.github.com/timokroeger/f025ef590557f1cd6c2e9c7ab30442d2

Add `Unborrow` trait bound for `Interrupt`

---

embassy-nrf/src/spim.rs
embassy-nrf/src/twim.rs
embassy-traits/src/i2c.rs

firstly, I have very little idea of what i'm doing here, trying to puzzle things together.
This PR adds async twim (by implementing the I2c trait) for embassy-nrf. This is based on the nrf-hal version of twim, and the embassy async spim implementation.

nrf async twim

---

README.md

Let me know if there is a specific board the rp and stm32 examples are designed for and I can that it in.

Improve examples section of readme

---

embassy-stm32/src/dac/mod.rs
embassy-stm32/src/rcc/mod.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/spi/v1.rs
embassy-stm32/src/spi/v2.rs
embassy-stm32/src/spi/v3.rs
stm32-metapac/build.rs

Adds RccPeripheral trait and a macro table for peripherals implementing clock enable and reset for a given peripheral

RccPeripharal + generate SPI clock enable

---

embassy-stm32/src/rng.rs
stm32-metapac/build.rs

Alternative approach that should handle split registers better by inferring register names from register file and doing a sanity check that it matches the peripheral clock name.

Infer enable and reset registers based on RCC registry file

---

embassy-macros/src/chip/stm32.rs
embassy-stm32/src/clock.rs
stm32-metapac/gen/src/lib.rs

* Moves the tim2-specific code into macro which always uses TIM2
* For peripherals without clock specified, attempt to locate enable and
reset registers in the RCC block matching the peripheral name. This
could be useful for peripherals where deducing the clock name might
not be feasible, but it remains to be tested with more chip families
to see if it is sufficiently accurate.

Enable timer clock in RCC on timer start

---

embassy-stm32/gen.py

On my Mac, the CSafeLoader seems to be unavailable in the pyyaml package. 
With this change, CSafeLoader is still used if available, but otherwise it now falls
back to SafeLoader.﻿

Make gen.py work without CSafeLoader

---

embassy-net/src/lib.rs
embassy-net/src/stack.rs
examples/std/src/bin/net.rs
examples/stm32h7/src/bin/eth.rs

By having the user pass in the resources, we can make them generic, this way the user can choose the size of the individual resources.

net: Make the user pass in the StackResources in init

---

embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/timer.rs
embassy-nrf/src/uarte.rs

Resolves #189 
This is a fairly low-level driver, just providing a safe wrapper over the peripheral with the addition of waiting for a CC register's COMPARE event to be fired.

Add an nRF Timer driver

---

embassy-nrf/Cargo.toml
embassy-nrf/src/chips/nrf52805.rs
embassy-nrf/src/chips/nrf52810.rs
embassy-nrf/src/chips/nrf52811.rs
embassy-nrf/src/chips/nrf52820.rs
embassy-nrf/src/chips/nrf52832.rs
embassy-nrf/src/chips/nrf52833.rs
embassy-nrf/src/chips/nrf52840.rs
embassy-nrf/src/lib.rs
embassy-nrf/src/rng.rs
examples/nrf/Cargo.toml
examples/nrf/src/bin/rng.rs

Resolves #187
Like the stm32 driver, this has both a non-blocking and blocking API, and implements `rand_core::RngCore` for the blocking API.

Add an nRF RNG driver

---

embassy-macros/src/chip/stm32.rs

We will need to change this eventually to accept a specific timer, since there are still chips that have neither TIM2 or 3.

STM: Change embassy main to use TIM3 instead of TIM2

---

embassy-stm32/src/adc/mod.rs
embassy-stm32/src/adc/v3.rs
examples/stm32h7/src/bin/blinky.rs
examples/stm32h7/src/bin/dac.rs
examples/stm32h7/src/bin/eth.rs
examples/stm32h7/src/bin/usart.rs
examples/stm32l4/src/bin/adc.rs
examples/stm32l4/src/bin/dac.rs

I suspect deleting `fn calibrate` isn't the right option, did we maybe forget to call it somewhere? or maybe this code is just super WIP?

fix stm32 warnings

---

embassy/Cargo.toml
embassy/src/lib.rs
embassy/src/util/mod.rs
embassy/src/util/mpsc.rs
embassy/src/util/mutex.rs
examples/nrf/src/bin/mpsc.rs

An MPSC inspired by Tokio and Crossbeam. The MPSC targets the mutexes we presently have i.e. those for single-core processors at this time. That said, the design is agnostic and should be able to target multi-core processors. 
The allocation of the channel’s buffer is inspired by the const generic parameters that Heapless provides.
Sample usage as per a new "mpsc" example:
```rust
enum LedState {
On,
Off,
}
static CHANNEL: Forever<Channel<WithNoThreads, LedState, 1>> = Forever::new();
#[embassy::task(pool_size = 1)]
async fn my_task(sender: Sender<'static, WithNoThreads, LedState, 1>) {
loop {
let _ = sender.send(LedState::On).await;
Timer::after(Duration::from_secs(1)).await;
let _ = sender.send(LedState::Off).await;
Timer::after(Duration::from_secs(1)).await;
}
}
#[embassy::main]
async …
```

Multi Producer Single Consumer channel

---

embassy-stm32/src/dbgmcu/mod.rs
embassy-stm32/src/lib.rs
examples/stm32f4/src/bin/spi.rs
examples/stm32h7/src/bin/usart_dma.rs
stm32-metapac-gen/src/lib.rs

Includes the addition of a `dbgmcu!(...)` macro table which currently takes
the form of
(cr, $fn_name:ident)
where `$fn_name` is something like `set_dbgsleep_d1` etc.
The method is unsafe, since it's performing unsafe PAC operations.
Two examples modified to demonstrate its usage.

Add a `Dbgmcu` struct capable of enabling all relevant DBGMCU.cr fields.

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs

I have only tested the USART DMA example.
Any thoughts?
Code size USART DMA:
```
before (atomics)
text    data     bss     dec     hex filename
8804      48    1464   10316    284c usart_dma
after (interrput flags)
text    data     bss     dec     hex filename
8784      48    1464   10296    2838 usart_dma
```

STM32 DMA/BDMA: Use interrupt flags instead of atomics

---

examples/stm32l4/Cargo.toml
examples/stm32l4/src/bin/adc.rs
examples/stm32l4/src/bin/blinky.rs
examples/stm32l4/src/bin/button.rs
examples/stm32l4/src/bin/button_exti.rs
examples/stm32l4/src/bin/dac.rs
examples/stm32l4/src/bin/spi.rs
examples/stm32l4/src/bin/spi_dma.rs
examples/stm32l4/src/bin/usart.rs
examples/stm32l4/src/bin/usart_dma.rs

- Use only embassy, no legacy pac/hal.
- use embassy::main macro

stm32/examples: cleanup L4

---

examples/nrf/.cargo/config.toml
examples/rp/.cargo/config.toml
examples/stm32f4/.cargo/config.toml
examples/stm32l0/.cargo/config.toml
examples/stm32l4/.cargo/config.toml
examples/stm32wb55/.cargo/config.toml

Previously the cargo configurations of all of the example projects had
`build-std = ["core"]`, which forces compilation of `core` as a
code-size optimisation. However, this is strictly unnecessary and will
currently break for users who do not use `rustup` directly (e.g. nix
users).

examples: Drop build-std = ["core"]

---

embassy/src/util/mpsc.rs

Instead of using inferred types for send() and recv(), introduce future types allowing them to be more easily wrapped in other types without `Box` or other unstable features.
I think this change should be sound:
* For send(), sender is already Sync + Send, and there is only a syntactic change.
* For recv(), the added lifetime argument should ensure that only 1 RecvFuture can be created at a time or else the borrow checker will complain. Moreover, making RecvFuture Send + Sync should be safe because there can exist only 1, and it also locks the underlying channel_cell.
@huntc ^^

Introduce future types

---

embassy-hal-common/src/peripheral.rs
embassy-hal-common/src/usb/mod.rs
embassy-hal-common/src/usb/usb_serial.rs
embassy-nrf/src/buffered_uarte.rs
embassy-stm32/src/eth/v2/mod.rs
examples/nrf/src/bin/buffered_uart.rs
examples/stm32h7/src/bin/eth.rs

Fixes #323 
- Refactor PeripheralMutex so it borrows a state instead of storing it inside itself. This guarantees the state won't move, so Pin is no longer needed.
- Update all uses
- nrf BufferedUarte
- stm32h7 eth
- hal-common usb

PeripheralMutex: Remove Pin

---

stm32-metapac-gen/src/lib.rs

The number has different meanings depending on family:
stm32f0: RCC_APB2ENR - APB peripheral clock enable register 2    CLOCK: APB1
stm32f4: RCC_APB2ENR - RCC APB2 peripheral clock enable register CLOCK: APB2
Ignore the clock number and search all registers for a matching enable bit.

metapac: Improve enable bit search

---

embassy-macros/src/lib.rs

Fixes #18
Syn considers doc comments to be attributes, so forwarding those fixes the issue.
It's probably a good idea to forward most attributes anyway.

Forward attributes to generated task function

---

embassy-macros/src/lib.rs
embassy-stm32/src/rcc/f4/mod.rs
embassy-stm32/src/rcc/h7/mod.rs
embassy-stm32/src/time_driver.rs
embassy/src/executor/mod.rs
examples/nrf/src/bin/blinky.rs
examples/nrf/src/bin/gpiote_port.rs
examples/nrf/src/bin/mpsc.rs
examples/nrf/src/bin/qspi.rs
examples/nrf/src/bin/qspi_lowpower.rs
examples/nrf/src/bin/rng.rs
examples/nrf/src/bin/spim.rs
examples/nrf/src/bin/twim.rs
examples/nrf/src/bin/twim_lowpower.rs
examples/stm32f4/src/bin/blinky.rs
examples/stm32f4/src/bin/button.rs
examples/stm32f4/src/bin/usart.rs
examples/stm32f4/src/bin/usart_dma.rs
examples/stm32h7/src/bin/blinky.rs
examples/stm32h7/src/bin/usart.rs
examples/stm32l0/src/bin/blinky.rs
examples/stm32l0/src/bin/button.rs
examples/stm32l4/src/bin/blinky.rs
examples/stm32l4/src/bin/button.rs
examples/stm32l4/src/bin/spi_dma.rs
examples/stm32l4/src/bin/usart.rs
examples/stm32wb55/src/bin/blinky.rs

Unfortunately errors from `embedded_graphics` and `core` doesn't provide
the necessary instances currently.

examples: Consistently use unwrap! in favor of .unwrap()

---

embassy-hal-common/src/ring_buffer.rs
embassy-stm32/Cargo.toml
embassy-stm32/src/usart/mod.rs
embassy-stm32/src/usart/v2.rs
examples/stm32l0/Cargo.toml
examples/stm32l0/src/bin/usart_irq.rs

* Implementation based on nRF UARTE, but simplified to not use DMA to
avoid complex interaction between DMA and USART.
* Implementation of AsyncBufRead and AsyncWrite traits
* Some unit tests to ring buffer

Add IRQ-driven buffered USART implementation for STM32 v2 usart

---

embassy-stm32/Cargo.toml
embassy-stm32/src/bxcan.rs
embassy-stm32/src/can/bxcan.rs
embassy-stm32/src/can/mod.rs
embassy-stm32/src/lib.rs
examples/stm32f4/Cargo.toml
examples/stm32f4/src/bin/can.rs

Ready to review
~~Example code not working yet.~~
https://github.com/stm32-rs/stm32f1xx-hal/pull/215#issuecomment-629356701 might be related

CAN support with bxcan crate

---

embassy-stm32/src/eth/v2/mod.rs

Source-Address-Filtering is not helping the board to receive packets.
For unknown reasons, the Receive-All is required, when in theory
it should not be required. Until we figure it out, follow the
stm32h7xx-hal example of setting RA=true.

Don't set SAF=true, do set RA=true for Ethernet.

---

embassy-stm32/src/eth/v2/mod.rs

Previously the MACA0 register was written LR and then HR, but the value across both registers only updates when LR is written, so only a partial MAC address was being configured in the core. Presumably this is why destination filtering was failing and the RA (receive all) bit needed to be set.
With this reordering of the writes, the correct MAC address is loaded into the MAC core, and so the RA bit is no longer required.
Tested on an H745ZI nucleo board.

STM32H7: Ethernet: Disable RA in MAC filtering, fix order of MACA0 register writes

---

embassy-stm32/src/rcc/wl5x/mod.rs
embassy-stm32/src/subghz/cad_params.rs
embassy-stm32/src/subghz/hse_trim.rs
embassy-stm32/src/subghz/mod.rs
embassy-stm32/src/subghz/mod_params.rs
embassy-stm32/src/subghz/ocp.rs
embassy-stm32/src/subghz/op_error.rs
embassy-stm32/src/subghz/pa_config.rs
embassy-stm32/src/subghz/packet_params.rs
embassy-stm32/src/subghz/packet_status.rs
embassy-stm32/src/subghz/packet_type.rs
embassy-stm32/src/subghz/pkt_ctrl.rs
embassy-stm32/src/subghz/pmode.rs
embassy-stm32/src/subghz/pwr_ctrl.rs
embassy-stm32/src/subghz/rf_frequency.rs
embassy-stm32/src/subghz/rx_timeout_stop.rs
embassy-stm32/src/subghz/sleep_cfg.rs
embassy-stm32/src/subghz/smps.rs
embassy-stm32/src/subghz/standby_clk.rs
embassy-stm32/src/subghz/stats.rs
embassy-stm32/src/subghz/status.rs
embassy-stm32/src/subghz/tcxo_mode.rs
embassy-stm32/src/subghz/tx_params.rs
embassy-stm32/src/subghz/value_error.rs

* Import changes in stm32wl-hal for the subghz peripheral
* Add method for enabling LSI clock (required for RNG)

Updates to WL5x

---

embassy-stm32/src/can/bxcan.rs
embassy-stm32/src/eth/v2/mod.rs
embassy-stm32/src/gpio.rs
embassy-stm32/src/i2c/v1.rs
embassy-stm32/src/spi/v1.rs
embassy-stm32/src/usart/v1.rs
embassy-stm32/src/usart/v2.rs

Small adjustment to 'set_as_af' interface. Mostly just to remove the dependency on the raw GPIO registers in i2c.

Small adjustment to 'set_as_af' interface

---

embassy-stm32/src/gpio.rs

A race condition exists when configuring pins into a peripheral's AF.
In the case of usart_v1 on a stm32f446RE, this causes an erroneous `0xF8` byte to be written to the usart's TX pin during startup.
This PR fixes the race condition by only configuring the pin into AF mode at the end of the configuration.
Minimal falsifying example:
```rs
#![no_std]
#![no_main]
#![feature(type_alias_impl_trait)]
/*
Module declartions
*/
// stuff used across binaries
#[path = "../example_common.rs"]
mod example_common;
use example_common::*;
/*
Includes
*/
use embassy::executor::Spawner;
use embassy::traits::*;
use embassy_stm32::usart::{Config, Uart};
use embassy_stm32::Peripherals;
#[embassy::main]
async fn main(_spawner: Spawner, p: Peripherals) {
info!("Hello World!");
let config = Config::default(); …
```

Fix: erroneous behavior of pins  being configured into AF

---

embassy-traits/src/i2c.rs

This trait makes the parallel with `embedded_hal::i2c::WriteIter`.
It allows to fetch bytes to write from an Iterator rather than requiring an allocation for an array.
It is provided as an extra Trait to avoid breaking existing implementations of `embassy_traits::i2c::I2c`.

Add the `embassy_traits::i2c::WriteIter` trait

---

embassy/src/blocking_mutex/mod.rs
embassy/src/channel/mpsc.rs
embassy/src/executor/spawner.rs

There are still 3 warnings (below)
```
Documenting embassy v0.1.0 (embassy)
warning: unresolved link to `channel`
--> src/channel/mpsc.rs:241:22
|
241 |     /// [`channel`]: channel
|                      ^^^^^^^ no item named `channel` in scope
|
= note: `#[warn(rustdoc::broken_intra_doc_links)]` on by default
= help: to escape `[` and `]` characters, add '\' before them like `\[` or `\]`
warning: unresolved link to `Task::spawn`
--> src/executor/raw/mod.rs:105:12
|
105 | /// with [`Task::spawn()`], which will fail if it is already spawned.
|            ^^^^^^^^^^^^^ no item named `Task` in scope
warning: public documentation for `spawn` links to private item `Executor::spawn`
--> src/executor/raw/mod.rs:156:17
|
156 |     /// cause [`Executor::spawn()`] to return the error.
| …
```

docs: fix some `cargo doc` warnings

---

.github/workflows/rust.yml
embassy-net/src/stack.rs
embassy-nrf/Cargo.toml
embassy-nrf/src/chips/nrf5340_app.rs
embassy-nrf/src/chips/nrf5340_net.rs
embassy-nrf/src/gpio.rs
embassy-nrf/src/gpiote.rs
embassy-nrf/src/lib.rs
embassy-nrf/src/ppi/dppi.rs
embassy-nrf/src/ppi/mod.rs
embassy-nrf/src/ppi/ppi.rs

Thanks to @diondokter's work on DPPI this was quite easy! :) 
TODO:

nrf: add initial nrf5340 support

---

embassy-stm32/build.rs
embassy-stm32/src/rcc/h7/mod.rs
examples/stm32h7/src/bin/mco.rs

This PR adds an abstraction over STM32 RCC feature called MCO (Microcontroller Clock Output). The clock output can bind to several clock sources and then can be scaled using a prescaler.
Given that from the embassy ecosystem the RCC is generaly invisible to the user, the MCO was implemented as a separate peripheral bound to the pin where the clock should appear.

Add MCO peripheral.

---

embassy-nrf/src/pwm.rs
examples/nrf/src/bin/pwm_sequence_ppi.rs

More PWM yak shaving. I was going to do some safe pwm ppi events stuff but I just dont think it fits this api design.. ppi is just very low level, im not sure how safe it will be in general
* first we should probably have borrows of handlers for ppi with lifetime of the peripheral?  hal does https://github.com/nrf-rs/nrf-hal/blob/eb4ba6ae4204c7f58fc968e57b2995df15f5ac77/nrf-hal-common/src/pwm.rs#L714-L716
* in general having access to tasks can put the state in some configuration the api doesnt understand anymore. for `SequencePwm` ideally id hand you back either only seq_start0 or seq_start1 because youd only use one based on if your `Times` is even or odd.. but again we only know that with this api AFTER start has been called. I dont think were ready for typestates
SO I figured why not …

Pwm ppi events

---

.vscode/settings.json
embassy-stm32/src/lib.rs
embassy-stm32/src/pwm/mod.rs
examples/stm32g4/Cargo.toml
examples/stm32g4/src/bin/pwm.rs

Here is a first-cut at implementing PWM support for STM32 targets via the TIM peripherals. Currently this only contains pin configuration for the STM32G0 but it would be straightforward to extend to other platforms.

STM32: Add PWM support

---

embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/uarte.rs
examples/nrf/src/bin/buffered_uart.rs
examples/nrf/src/bin/uart.rs

The constructors themselves are not strictly unsafe. Interactions with DMA can be generally unsafe if a future is dropped, but that's a separate issue. It is important that we use the `unsafe` keyword diligently as it can lead to confusion otherwise.
I've also provided some rationale re. the usage of [Uarte] vs [BufferedUarte].

Remove unsafe from nRF uarte and improve doco with rationale

---

embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/uarte.rs

Applies the Nordic workaround found in the `Uarte` for the nRF9160 and nRF5340 to the `BufferedUarte`.

Applies the Uarte patch

---

embassy-hal-common/src/ring_buffer.rs
embassy-hal-common/src/usb/usb_serial.rs
embassy-net/src/tcp_socket.rs
embassy-nrf/src/buffered_uarte.rs
embassy-stm32/src/usart/mod.rs
embassy/src/io/std.rs
embassy/src/io/traits.rs
embassy/src/io/util/flush.rs
embassy/src/io/util/mod.rs
embassy/src/io/util/split.rs
examples/nrf/src/bin/buffered_uart.rs

As per Tokio and others, this commit provides a `poll_flush` method on `AsyncWrite` so that a best-effort attempt at wakening once all bytes are flushed can be made.

Provides AsyncWrite with flush

---

embassy-nrf/src/gpio.rs
embassy-nrf/src/gpiote.rs
examples/nrf/src/bin/gpiote_port.rs
examples/nrf/src/bin/wdt.rs

`PortInput` is just a dumb wrapper around `Input`, it has no reason whatsoever to exist. This PR moves the `wait_for_x` functionality to `Input` directly.
It also adds it to `FlexPin` for completeness and consistency with `Input`.
(The reason `PortInput` exists is a while ago `GPIOTE` was an owned singleton that you had to initialize, so `PortInput::new()` would require it to enforce it's been initialized. This doesn't apply anymore now that GPIOTE is "global")

nrf/gpiote: remove PortInput, move impls to Input/FlexPin.

---

embassy-stm32/src/spi/mod.rs
embassy-stm32/src/spi/v1.rs
embassy-stm32/src/spi/v2.rs
embassy-stm32/src/spi/v3.rs

Notable changes:
- `SPE` is now disabled before `TXDMAEN` and `RXDMAEN` are disabled. This is the "mandatory" sequence for v2 and v3 (and maybe v1 as well, but I can't find it in the reference manual).
- v1's `write_dma_u8` now waits for idle and disables `TXDMAEN` after the transfer is complete, just like everything else.

Incrementally merge STM32 SPI versions, Part 3

---

embassy-nrf/src/uarte.rs
examples/nrf/src/bin/uart_split.rs

A new `split` method is introduced such that the Uarte tx and rx can be used from separate tasks. An MPSC is used in an example to illustrate how data may be passed between these tasks.
The approach taken within the `Uarte` struct is to split into tx and rx fields on calling `Uarte::new`. These fields are returned given a call to `Uarte::split`, but otherwise, if that call isn't made, then the API remains as it was before.
Here's a snippet from a new example introduced:
```rust
#[embassy::main]
async fn main(spawner: Spawner, p: Peripherals) {
// ...
let uart = uarte::Uarte::new(p.UARTE0, irq, p.P0_08, p.P0_06, NoPin, NoPin, config);
let (mut tx, rx) = uart.split();
// ...
// Spawn a task responsible purely for reading
unwrap!(spawner.spawn(reader(rx, s)));
// ...
// Continue reading in …
```

Introduces split on the nRF Uarte

---

embassy-nrf/src/uarte.rs

I noticed lots of logging which really slows things down and is not useful outside of a debugging context, hence set to trace.

Set Uarte log levels to trace

---

docs/modules/ROOT/examples/basic/src/main.rs
embassy-nrf/src/gpio.rs
embassy-nrf/src/gpiote.rs
examples/nrf/src/bin/blinky.rs
examples/nrf/src/bin/mpsc.rs
examples/nrf/src/bin/spim.rs

Add infallible inherent methods, so that users don't have to import a trait, or `.unwrap()`.
This implements Input and Output using FlexPin, to avoid some code duplication.

nrf/gpio: add infallible inherent methods, remove some duplication.

---

embassy-stm32/src/dac/v2.rs

Previously disable_channel enabled rather than disabled the requested
channel due to an apparent copy-paste error. Refactor to eliminate this
sort of issue by construction.

stm32/dac: Fix disable_channel

---

embassy-stm32/src/usart/mod.rs

#526 seems to suggest that it will be rewritten for DMA support, but I am not sure how to implement it and the port was quite straightforward, so here it is. It might be immediately useful before DMA version will be implemented
Note that I have not tested this on v2 hardware

Port buffered uart to v1 stm32 hardware

---

examples/stm32f7/src/bin/usart_dma.rs

This small PR adds the USART DMA write an example for the STM32F7. The example has been tested on a Nucleo-f767zi board.
Output from `DEFMT_LOG=info cargo run --bin usart_dma`
```
Running `probe-run --chip STM32F767ZITx target/thumbv7em-none-eabihf/debug/usart_dma`
(HOST) INFO  flashing program (108 pages / 108.00 KiB)
(HOST) INFO  success!
────────────────────────────────────────────────────────────────────────────────
0 INFO  Hello World!
└─ usart_dma::__cortex_m_rt_main @ src/bin/usart_dma.rs:39
1 INFO  wrote DMA
└─ usart_dma::main_task::task::{generator#0} @ src/bin/usart_dma.rs:31
```

USART DMA example for the STM32F7

---

embassy-stm32/src/adc/f1.rs
embassy-stm32/src/adc/mod.rs
embassy-stm32/src/rcc/f1/mod.rs
embassy-stm32/src/rcc/mod.rs
examples/stm32f1/Cargo.toml
examples/stm32f1/src/bin/adc.rs

Add an ADC implementation for F1 based chips. Primarily tested using ADC1, proper functionality for ADC2 probably needs some extra work as it's mainly a slave and can't e.g. measure vrefint by itself.
Needs https://github.com/embassy-rs/stm32-data/pull/115

Initial ADC support for on STM32F1xx 

---

embassy-stm32/Cargo.toml
embassy-stm32/src/usart/mod.rs
embassy-traits/Cargo.toml
embassy-traits/src/adapter.rs
embassy-traits/src/lib.rs
examples/stm32l4/src/bin/i2c_blocking_async.rs
examples/stm32l4/src/bin/spi_blocking_async.rs
examples/stm32l4/src/bin/usart_blocking_async.rs

This allows writing drivers relying on async traits, while still
functioning with implementations that already implement the embedded-hal
traits.

Add adapter for implementing async traits for blocking types

---

embassy-nrf/src/rng.rs
examples/nrf/src/bin/rng.rs

Unsafe is not required here given that all futures are required to live longer than their global peripheral instances. There are other occurrences of unsafe being used on new that should be removed. I started to do that but then went down a bit of a rabbit hole. Therefore, just confining this PR to what I'm currently exposed to.

Remove unsafe from new on RND

---

embassy-nrf/src/uarte.rs

This PR allows `event_endtx` to be used outside of the `Uarte` itself. As a consequence, PPI can be used to drive tasks given the end of transmission on the Uarte. This is particularly useful for situations like RS485 where a GPIO may be required to be set to high when transmitting, then cleared when done. A non-PPI approach can cause a delay in the clearing of this GPIO as other Embassy tasks might become scheduled. Not clearing the GPIO in a timely manner can be problematic.
Here's an example of our usage with this change:
```rust
let uarte_tx_enable = OutputChannel::new(
p.gpiote_ch,
Output::new(p.uarte_tx_enable_pin, Level::Low, OutputDrive::Standard),
OutputChannelPolarity::Set,
);
let mut ppi = Ppi::new_one_to_one(p.ppi_ch, uarte.event_endtx(), uarte_tx_enable.task_clr()); …
```

Makes the uarte endtx event available

---

ci.sh
embassy-stm32/Cargo.toml
embassy-stm32/build.rs
embassy-stm32/src/rcc/mod.rs
embassy-stm32/src/time_driver.rs
examples/stm32f0/Cargo.toml
examples/stm32f1/Cargo.toml
examples/stm32f3/Cargo.toml
examples/stm32f4/Cargo.toml
examples/stm32f7/Cargo.toml
examples/stm32g0/Cargo.toml
examples/stm32g4/Cargo.toml
examples/stm32h7/Cargo.toml
examples/stm32l0/Cargo.toml
examples/stm32l1/Cargo.toml
examples/stm32l4/Cargo.toml
examples/stm32wb55/Cargo.toml
examples/stm32wl55/Cargo.toml

Most of the time you don't care which one gets used, so this is easier! :) 
It also helps for building docs for all chips, it reduces the feature changes needed.

stm32: add `time-driver-any` cargo feature that automatically picks one.

---

embassy-nrf/src/pwm.rs
examples/nrf/src/bin/pwm_sequence.rs
examples/nrf/src/bin/pwm_sequence_ppi.rs

Sequences are now passed in via the start method to avoid having to stop the PWM and restart it. Sequences continue to be constrained with the same lifetime of the Pwm struct itself. The pwm_sequence example has been extended to illustrate multiple sequences being passed around.

Permit many sequences to be passed

---

embassy-nrf/src/pwm.rs
examples/nrf/src/bin/pwm_sequence.rs
examples/nrf/src/bin/pwm_sequence_ppi.rs

I had introduced a small bug in my last PR where I assigned the sequence before stopping the PWM. I now stop the PWM before doing that now.
Also, corrected a math comment.

Stop PWM before assigning the new sequence

---

embassy-stm32/src/dma/mod.rs
embassy-stm32/src/i2c/v2.rs

The Senseair Sunrise CO2 sensor expects a wake-up packet in the form of (START, address, STOP), which looks like a `write(addr, &[])`, but this assertion prevents sending that.
I'm not sure why the assertion is there. Sending empty packets works fine in my limited testing, at least.

stm32/i2c: allow empty writes

---

embassy-stm32/build.rs
embassy-stm32/src/rcc/f3.rs

The rcc code was taken from stm32-rs which uses 'x' features, but embassy uses features with full chip names.
Add these 'x' wildcards as cfgs and use them in rcc. They will be useful for USB #580 too.
---
I don't have any F3 boards, so this is not tested. But the original cfg clearly doesn't look right…

stm32f3: fix nonexistent cfg tests

---

embassy-nrf/src/pwm.rs
examples/nrf/src/bin/pwm_double_sequence.rs
examples/nrf/src/bin/pwm_sequence.rs
examples/nrf/src/bin/pwm_sequence_ppi.rs
examples/nrf/src/bin/pwm_sequence_ws2812b.rs

I've permitted the PWM sequences to be mutated on stopping the PWM by associating them with a new  `SingleSequencer` structure. This is so that we can perform effects on the LEDs (and other use-cases, I'm sure!). The example has been updated to illustrate the use of this by flashing a WS2812B LED.
There's also a `Sequencer` structure for more sophisticated PWM interactions, along with a `pwm_double_sequence`  example to illustrate.
These changes should make it possible to attain all of the nRF PWM functionality available.

PWM WS2812B example and flexible sequence config

---

embassy-rp/src/spi.rs
embassy-rp/src/uart.rs
embassy-stm32/src/crc/v1.rs
embassy-stm32/src/crc/v2v3.rs
embassy-stm32/src/dac/mod.rs
embassy-stm32/src/dac/v2.rs
embassy-stm32/src/dcmi.rs
embassy-stm32/src/gpio.rs
embassy-stm32/src/i2c/v1.rs
embassy-stm32/src/pwm/mod.rs
embassy-stm32/src/pwm/pins.rs
embassy-stm32/src/pwm/simple_pwm.rs
embassy-stm32/src/rng.rs
embassy-stm32/src/sdmmc/v2.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/subghz/mod.rs
embassy-stm32/src/usart/mod.rs
examples/stm32g4/src/bin/pwm.rs
examples/stm32h7/src/bin/camera.rs
examples/stm32h7/src/bin/dac.rs
examples/stm32h7/src/bin/low_level_timer_api.rs
examples/stm32h7/src/bin/pwm.rs
examples/stm32l4/src/bin/dac.rs

The idea behind OptionalPin has a few problems:
- you need to impl the signal traits for NoPin which is a bit weird https://github.com/embassy-rs/embassy/blob/master/embassy-stm32/src/dcmi.rs#L413-L416
- you can pass any combination of set/unset pins, which needs checking at runtime  https://github.com/embassy-rs/embassy/blob/master/embassy-stm32/src/dcmi.rs#L130
The replacement is to do multiple `new` constructors for each combination of pins you want to take.

stm32: Remove OptionalPin

---

docs/modules/ROOT/pages/basic_application.adoc

Add an example documenting the config param based on help I got in the matrix chat.
Because the example is very short and incompatible with the other example code I just included it inline.

Document #[embassy::main(config = ...)]

---

embassy/Cargo.toml
embassy/src/fmt.rs
embassy/src/time/instant.rs

Add the feature defmt-timestamp-uptime. Enabling it adds a timestamp of the number of seconds since startup next to defmt log messages using `Instant::now`.

Add feature defmt-timestamp-uptime

---

embassy/src/time/duration.rs
embassy/src/time/instant.rs
embassy/src/time/mod.rs

For example, `as_micros`, `from_micros` now are noops if tick rate is 1MHz.
See: https://godbolt.org/z/fE1bf3ecP

time: optimize math by reducing fractions at compile time. 

---

embassy-stm32/build.rs
embassy-stm32/src/dcmi.rs
embassy-stm32/src/i2c/mod.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/traits.rs
embassy-stm32/src/usart/mod.rs
stm32-metapac-gen/src/lib.rs

Continuation of work from #601

stm32: move dma trait impls from macrotables to build.rs

---

ci.sh
embassy-stm32/src/can/bxcan.rs
embassy-stm32/src/gpio.rs
embassy-stm32/src/usart/mod.rs
tests/stm32/.cargo/config.toml
tests/stm32/Cargo.toml
tests/stm32/src/bin/gpio.rs
tests/stm32/src/bin/spi_dma.rs
tests/stm32/src/bin/usart.rs
tests/stm32/src/bin/usart_dma.rs

- Fix 2 bugs in GPIOv1 configuration
- Add stm32f1 to HIL so that this doesn't regress again.

stm32f1: fix input GPIO AFs, add to HIL.

---

embassy-stm32/src/lib.rs

- Fix build when no DBGMCU is present (wl55 cm0 core)
- Fix multicore 2nd core having the wrong NVIC.

stm32 misc fixes

---

embassy-stm32/Cargo.toml
embassy-stm32/build.rs
embassy-stm32/src/time_driver.rs

I am not sure what the effect of reducing the number of alarms will be, but these are the only timers I have available on my board.

stm32: Add support for using TIM12 and TIM15 as time driver

---

embassy-stm32/src/rcc/g0.rs

This is the follow-on to my PR against stm32-data that added new register enums for the G0. I have updated the G0 RCC module to use those new enums.
I have also fixed an issue with the calculation of the AHB clock rate. 32 is not available as an AHB prescaler. The sequence jumps from 16 to 64. The original bit shifting math did not account for this gap. I have replaced it with a `match` instead.

Use new stm32-data registers and fix AHB clock calculation

---

embassy-stm32/src/can/bxcan.rs
examples/stm32f4/src/bin/can.rs

* Do not use wildcard reexport for `bxcan`
* `cfgs` to fix `bxcan` implementation for devices with "CAN1" but no "CAN2" peripheral

`bxcan` improvements

---

embassy-nrf/src/saadc.rs
examples/nrf/src/bin/saadc_continuous.rs

Starting the sampling task prior to starting the SAADC peripheral can lead to unexpected buffer behaviour with multiple channels. We now provide an init callback at the point where the SAADC has started for the first time. This callback can be used to kick off sampling via PPI.
We also need to trigger the SAADC to start sampling the next buffer when the previous one is ended so that we do not drop samples - the major benefit of double buffering.
Given these additional tasks, we now simplify the API by passing in the TIMER and two PPI channels.
As a bonus, we provide an async `calibrate` method as it is recommended to use before starting up the sampling.
The example has been updated to illustrate these new features along with the simplified API.
The changes here have been tested on my …

Fix nRF Saadc continuous sampling

---

embassy-stm32/build.rs
embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/mod.rs
examples/stm32l4/src/bin/spi_dma.rs
tests/stm32/src/bin/spi_dma.rs
tests/stm32/src/bin/usart_dma.rs

Previously, every dma interrupt handler called the same `on_irq`
function which had to check the state of every dma channel.
Now, each dma interrupt handler only calls an `on_irq` method for its
corresponding channel or channels.

stm32: Refactor DMA interrupts

---

embassy-nrf/src/lib.rs
embassy-nrf/src/spim.rs
embassy-nrf/src/twim.rs
embassy-nrf/src/uarte.rs
embassy-nrf/src/util.rs

As discussed, this PR makes the following changes:
- Ignore pointer location of zero-length slices (fixes #631)
- Change default functions so they copy the tx buffer if it does not reside in RAM
- Introduce new variants for `write`, `transfer`, and their blocking versions which fails instead of copying
- Add documentation about the motivation behind all these variants
Remaining TODOs:
@Dirbaio it probably makes sense for you to review it now before I "copy" over the changes to the other two peripherals.

Skip EasyDMA slice location check for empty slices and copy data if necessary

---

embassy-stm32/src/usart/mod.rs

This is a quick fix to make `Uart` futures implement `Send`.
Previously they were `!Send`, because pointer to the data register was held across an await point. Simple rearrange fixes the issue.

Make UART futures Send

---

embassy-stm32/src/adc/v2.rs
embassy-stm32/src/adc/v3.rs
embassy-stm32/src/dac/v2.rs
embassy-stm32/src/i2c/v1.rs
embassy-stm32/src/i2c/v2.rs
embassy-stm32/src/usart/mod.rs

Add reset on initialization to peripherals that did not have it before. This fixes problems when same peripheral is reinitialized at runtime multiple times.
Some exceptions:
- ADC: all ADCs share a single reset
- DCMI: does reset before enable - couldn't find anything about the order in the reference manual. Just keep it if it works?
I also fixed safety issues where global RCC registers where accessed without critical section.

Reset peripherals on enable

---

embassy-stm32/src/gpio.rs

All GPIO functions are monomorphized (per pin). Inlining these make the ROM smaller when using opt-level="z"

Inline GPIO functions

---

embassy-nrf/src/usb.rs
embassy-usb/src/builder.rs
embassy-usb/src/class.rs
embassy-usb/src/control.rs
embassy-usb/src/driver.rs
embassy-usb/src/lib.rs
examples/nrf/src/bin/usb/cdc_acm.rs
examples/nrf/src/bin/usb/main.rs

Added functionality to #657 to allow classes to handle their own EP0 control requests. This was needed for an HID class implementation I'm working on. It a fairly substantial change so review would be much appreciated.

Add support for USB classes handling control requests.

---

stm32-metapac/build.rs

PR #665 made stm32-metapac rebuild when the chip definition was changed.
Though it used the lowercase version of the chip name as a filename which probably worked fine on windows with its case-independent filesystem, but was causing constant rebuilds on linux

Convert chip name to upper case to fix rebuilds

---

embassy-usb/src/builder.rs
embassy-usb/src/control.rs
embassy-usb/src/lib.rs
examples/nrf/src/bin/usb/cdc_acm.rs
examples/nrf/src/bin/usb/main.rs

This removes the buffer from UsbDevice for control_in requests and lets the ControlHandler provide it's own buffer or a static buffer for the response.

async usb stack: Let ControlHandler's provide the control_in buffer

---

embassy-stm32/src/time_driver.rs

Previously timer overflow interrupts were not firing correctly, because Update Interrupt Enable (UIE) was not set.
The timers still worked somewhat correclty, because overflow was handled together with other interrupts.

Fix STM32 timer interrupt bug

---

embassy-nrf/src/usb.rs
embassy-usb/src/control.rs
embassy-usb/src/lib.rs

With these changes I have a working HID class. 🎉
The HID `ControlHandler` needs to respond to some `RequestType::Standard` control requests, so I moved the handling for `GET_STATUS`, `GET_INTERFACE` and `SET_INTERFACE` into the `ControlHandler` with default implementations so we can route all control requests with a `Recipient::Interface` to the `ControlHandler`.
The `embassy-nrf::ControlPipe` implementation also needed some work to support control out requests with more than one data packet.

Async usb bug fixes

---

embassy/src/util/mod.rs
embassy/src/util/select_all.rs

Here's a no-std compatible version of `select_all`. It's not quite as useful as the original because it requires an array of Unpin futures to be pre-constructed instead of taking an iterator (which could return `Pin<Box<_>>` in `std`). And, of course, you don't get a `Vec` of the unfinished futures returned at completion. Still, I think it's cleaner than a long cons of select calls.
I'll leave it up to you whether this is sufficiently general purpose to include in Embassy or not.

no_std version of `futures::future::select_all`

---

embassy-nrf/src/usb.rs
embassy-usb-serial/src/lib.rs
embassy-usb/src/driver.rs
embassy-usb/src/lib.rs
examples/nrf/src/bin/usb_serial.rs

For protocols where the endpoint stream is stateful, it will be necessary for endpoint tasks to handle bus reset events. We should also avoid enabling endpoints until the host has set the device configuration.
This PR adds a `set_configured()` method to the `driver::Bus` trait to allow the driver to enable/disable endpoints in response to SET_CONFIGURATION control requests.
It also adds a `Disabled` error to both `WriteError` and `ReadError` which should be returned from `EndpointIn::write()` or `EndpointOut::read()` if the endpoint is disabled during the call.
Finally, it adds an `Endpoint::wait_enabled()` method to allow clients to wait for the device to be configured and the endpoint(s) enabled.

Add basic device state handling for endpoints.

---

embassy-usb-hid/src/lib.rs
examples/nrf/src/bin/usb_hid_keyboard.rs

This adds `ready()` methods to `ReportReader` and `ReportWriter` to wait for their respective endpoints to be enabled. It also adds a `use_report_ids` argument to `ReportReader::run()` to control whether the first byte of reports should be used as the report ID passed to the callback or not. This is needed for full consistency with control request reports.
Finally, it includes a couple of robustness improvements to `ReportReader`:
First, it properly resets the report offset on bus reset or a disabled error.
Second, it now handles superfluous zero-length-packets. MacOS appears to send zero-length-packets even when the report is maximum size. Even worse it can interleave the ZLPs with data packets (e.g. REPORT REPORT ZLP ZLP). This is now handled properly.

embassy-usb-hid bug fixes

---

embassy/src/lib.rs
embassy/src/mutex.rs
examples/nrf/src/bin/mutex.rs

What it says on the tin :) 
It allows sharing data between tasks when you want to `.await` stuff while holding it locked.

Add async Mutex.

---

embassy-nrf/src/lib.rs
embassy-rp/src/lib.rs
embassy-stm32/src/lib.rs
examples/stm32h7/Cargo.toml
examples/stm32h7/src/bin/low_level_timer_api.rs

Removes the need to depend on embassy-hal-common in the case of developing custom peripheral drivers.

Reexport unborrow macro in HALs

---

embassy-nrf/src/usb.rs
embassy-usb/src/builder.rs
embassy-usb/src/driver.rs
embassy-usb/src/lib.rs
examples/nrf/src/bin/usb_hid_keyboard.rs
examples/nrf/src/bin/usb_hid_mouse.rs
examples/nrf/src/bin/usb_serial.rs
examples/nrf/src/bin/usb_serial_multitask.rs

As discussed, this prevents the 1ms blocking wait in the nrf USB driver.
I also found an issue with `ControlPipe::accept_in` returning an error when a setup packet is received immediately after `data_in` completes (before the future is polled). That's now fixed.

Async-ify Driver::enable and UsbDeviceBuilder::build

---

embassy/src/channel/channel.rs
embassy/src/channel/mod.rs

The automatic derive clone does not work because RawMutex is not Clone.

Add back support for cloning sender/receiver

---

embassy-nrf/src/saadc.rs

Adds support for the VDDHDIV5 ADC input on newer nrf chips.

Add saadc::VddhDiv5Input

---

embassy-nrf/src/usb.rs
embassy-usb-hid/src/lib.rs
embassy-usb-serial/src/lib.rs
embassy-usb/src/control.rs
embassy-usb/src/driver.rs
examples/nrf/src/bin/usb_serial.rs
examples/nrf/src/bin/usb_serial_multitask.rs

Originally #698, got overwritten in a rebase I think.

Unify ReadError and WriteError into EndpointError

---

embassy-stm32/src/rcc/l4.rs
embassy-stm32/src/rcc/l5.rs
examples/stm32l4/src/bin/rng.rs

- added an assert so it panics if pll48div is not 48Mhz
- added MSI as a clock source for PLL
- removed hsi48 option for MCUs mentioned in l4 rcc presentation
- copied some code from l4 to l5, but don't have a way of testing it.

add more clock options for l4 and l5

---

embassy-usb-hid/src/lib.rs
embassy-usb/src/control.rs
examples/nrf/src/bin/usb_hid_keyboard.rs
examples/nrf/src/bin/usb_hid_mouse.rs

Following the discussion from #720  and [matrix](https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$PcPr8E_JbodEPuUUKI2PzIC9sx7nF3y0kV2T5O4UWj8?via=matrix.org&via=converser.eu&via=braun-odw.eu), this is a second take on simplifying the HID API.
Split into a separate PR so it can be reviewed separately.
See individual commit messages for details.
cc @alexmoon

USB HID: simplify API

---

embassy-usb-hid/src/lib.rs
embassy-usb-serial/src/lib.rs
embassy-usb/src/builder.rs
embassy-usb/src/descriptor.rs
embassy-usb/src/lib.rs
examples/nrf/src/bin/usb_hid_keyboard.rs
examples/nrf/src/bin/usb_hid_mouse.rs
examples/nrf/src/bin/usb_serial.rs
examples/nrf/src/bin/usb_serial_multitask.rs

usb: improved descriptor building API
The same API call allocates interfaces/endpoints/etc and writes their descriptors.
This means less API calls, and less possibility to screw things up.
DescriptorWriter is now private.

USB: New builder API 

---

embassy-nrf/Cargo.toml
embassy-nrf/src/qspi.rs
examples/nrf/src/bin/qspi.rs
examples/nrf/src/bin/qspi_lowpower.rs

* Adds implementations of embedded-storage and embedded-storage-async
for QSPI
* Add blocking implementations of QSPI
* Use blocking implementation in new() and embedded-storage impls
* Use async implementation in embedded-storage-async impls
* Add FLASH_SIZE const generic parameter
* Own IRQ in Qspi instance to disable it on drop.

Add embedded-storage trait impls for QSPI

---

embassy-nrf/Cargo.toml
embassy-nrf/src/usb.rs
embassy-usb-hid/src/lib.rs
embassy-usb-serial/src/lib.rs
embassy-usb/src/builder.rs
embassy-usb/src/control.rs
embassy-usb/src/descriptor.rs
embassy-usb/src/descriptor_reader.rs
embassy-usb/src/driver.rs
embassy-usb/src/lib.rs
embassy-usb/src/types.rs

Currently altsetting handling is left to classes, which is annoying because they have to enable/disable the EPs themselves from the ControlHandler. This PR builds the handling into embassy-usb core.
TODO: actually enable/disable the endpoints on SET_INTERFACE.

usb: builtin handling of interface alternate settings

---

embassy-macros/src/macros/task.rs
rust-toolchain.toml

Fixes a new opaque type error in the task macro.
Full error is "opaque type's hidden type cannot be another opaque type from the same scope".
This got disallwed by the lazy-TAIT PR: https://github.com/rust-lang/rust/pull/94081
Sadly there's now some weird type inference errors with pre-lazy-TAIT
nightlies, so support for those is dropped.

Update Rust nightly.

---

embassy-net/src/tcp_socket.rs
embassy-usb-ncm/Cargo.toml
embassy-usb-ncm/src/fmt.rs
embassy-usb-ncm/src/lib.rs
examples/nrf/Cargo.toml
examples/nrf/src/bin/usb_ethernet.rs
examples/nrf/src/bin/usb_hid_keyboard.rs
examples/nrf/src/bin/usb_hid_mouse.rs
examples/nrf/src/bin/usb_serial.rs
examples/nrf/src/bin/usb_serial_multitask.rs

TODO:
I won't add the `embassy-net` driver to `embassy-usb-ncm` for now because `embassy-net` buffer management will likely be refactored soon, so there's not much point to it.

WIP: USB CDC NCM (Ethernet over USB)

---

embassy/src/executor/arch/cortex_m.rs
embassy/src/executor/spawner.rs
examples/nrf/src/bin/self_spawn_current_executor.rs

This is needed to spawn non-Send tasks in an InterruptExecutor, after the fixes in #730 .
@matoushybl could you check if this works for your use case?

executor: Add `Spawner::for_current_executor`.

---

embassy-macros/src/macros/task.rs
embassy/src/executor/raw/mod.rs
embassy/src/executor/spawner.rs

This allows send-spawning (spawning into an executor in another thread) tasks if their args are Send. Previously this would require the entire future to be Send.
--
When send-spawning a task, we construct the future in this thread, and effectively
"send" it to the executor thread by enqueuing it in its queue. Therefore, in theory,
send-spawning should require the future `F` to be `Send`.
The problem is this is more restrictive than needed. Once the future is executing,
it is never sent to another thread. It is only sent when spawning. It should be
enough for the task's arguments to be Send. (and in practice it's super easy to
accidentally make your futures !Send, for example by holding an `Rc` or a `&RefCell` across an `.await`.)
Luckily, an `async fn` future contains just the args when …

executor: allow Send-spawning of tasks if their args are Send.

---

docs/modules/ROOT/pages/bootloader.adoc
embassy-boot/boot/src/lib.rs
embassy-boot/nrf/src/lib.rs
embassy-boot/stm32/src/lib.rs
embassy-boot/stm32/src/main.rs
examples/boot/nrf/src/bin/a.rs
examples/boot/stm32l0/src/bin/a.rs
examples/boot/stm32l1/src/bin/a.rs
examples/boot/stm32l4/src/bin/a.rs
examples/boot/stm32wl/src/bin/a.rs

* Less generics on bootloader. Keep PAGE_SIZE as a common multiple of
DFU and ACTIVE page sizes.
* Document restriction
* Add unit tests for different page sizes

Allow using separate page sizes for state and dfu

---

embassy-stm32/src/rcc/f2.rs
embassy-stm32/src/rcc/mod.rs
examples/stm32f2/src/bin/pll.rs

- minor changes to make the F2 RCC API a bit more flexible
- low-level PLL config with assertions based on datasheet specs. It shouldn't be very difficult to later add a "reverse API" where you pass the clocks you want to a function and it generates a `PLLConfig` struct for you
- PLL API tested on my custom board with 12 MHz HSE as source for PLL to generate max clocks for SYSCLK/AHB/APB/APB1/PLL48
- the example *should* work but is untested since I don't have the Nucleo board :disappointed:

Add PLL config support for F2

---

embassy/src/executor/raw/mod.rs

This commit removes the else branch in `TaskStorage::spawn`, and returns
explicitly from the if statement's branch, similar to what
[TaskPool::spawn](https://github.com/embassy-rs/embassy/blob/85c0525e01c52bbb85c7b93600a60837ee7b87dc/embassy/src/executor/raw/mod.rs#L235-L243) does.

Use explicit return statement TaskStorage::spawn

---

embassy-stm32/src/rcc/f7.rs

Fixes a typo in clock calculations, see: https://github.com/stm32-rs/stm32f7xx-hal/blob/aaf2034cab697577e6f4fc6079fc7e4691d7ad9d/src/rcc.rs#L347

Allow maximal clock for F7 HCLK

---

embassy-rp/src/gpio.rs

This commit implements a suggestion for the method `is_set_low` which is
currently a `todo`, by reading last value written to `GPIO_OUT`.

Implement Output::is_set_low for embassy-rp

---

embassy-stm32/src/rcc/f3.rs
embassy-stm32/src/usart/mod.rs

Using embassy on STM32 Discovery board showed problems with
- USART with parity
- Clock settings (CFGR) when using PLL and prescaler
- Flash ACR settings
This PR attempts to fix these

Stm32 fixes

---

examples/nrf/src/bin/usb_serial.rs
examples/nrf/src/bin/usb_serial_multitask.rs

Windows shows `error 10` when using CDC ACM on non composite devices.
Workaround is to use IADS:
https://developer.nordicsemi.com/nRF_Connect_SDK/doc/1.9.1/kconfig/CONFIG_CDC_ACM_IAD.html#help

Make usb_serial examples work on windows

---

embassy-nrf/src/usb.rs
embassy-usb/src/driver.rs
embassy-usb/src/lib.rs

nrf/usb: fix control out transfers getting corrupted due to ep0rcvout sticking from earlier.

---

embassy-rp/src/gpio.rs

This commit implements drop for embassy-rp gpio Output which is
currently a `todo`.

Impl drop for embassy-rp gpio Output

---

embassy-rp/src/gpio.rs

The commit adds new lines between the SIO functions which at least for
me improves readability and is consistent with the other methods in the
trait.

Add new lines between SIO methods

---

embassy-rp/src/gpio.rs

This commit adds open-drain support for embassy-rp by adding a new type
named `embassy_rp::gpio::OutputOpenDrain`.

Add open-drain support for embassy-rp

---

embassy-nrf/src/buffered_uarte.rs
embassy-stm32/src/usart/buffered.rs
examples/nrf/src/bin/buffered_uart.rs
examples/stm32f4/Cargo.toml
examples/stm32f4/src/bin/usart_buffered.rs

The `AsyncBufRead` implementation for `BufferedUart` was removed in https://github.com/embassy-rs/embassy/pull/752, this PR reimplements it from `embedded-io`. This allows reading `BufferedUart` without copying slices.

Reimplement BufRead for BufferedUart

---

embassy-stm32/src/rcc/g0.rs

STM32G0 SYSCLK can be sourced from PLLRCLK. Given that the HSI runs at 16 MHz and the HSE range is 4-48 MHz, the PLL is the only way to reach 64 MHz. This commit adds `ClockSrc::PLL`.
The PLL sources from either HSI16 or HSE, divides it by `m`, and locks its VCO to multiple `n`. It then divides the VCO by `r`, `p`, and `q` to produce up to three associated clock signals:
* PLLRCLK is one of the inputs on the SYSCLK mux. This is the main reason the user will configure the PLL, so `r` is mandatory and the output is enabled unconditionally.
* PLLPCLK is available as a clock source for the ADC and I2S peripherals, so `p` is optional and the output is conditional.
* PLLQCLK exists only on STM32G0B0xx, and exists only to feed the MCO and MCO2 peripherals, so `q` is optional and the output is …

stm32: g0: add PLL clock source

---

embassy-net/Cargo.toml
embassy-net/src/lib.rs
embassy-net/src/tcp.rs

I found these useful while implementing the TcpClient traits for embedded-nal-async:
https://github.com/drogue-iot/drogue-device/blob/shared-tcp-stack/device/src/drivers/tcp/smoltcp.rs
Once e-n-a PR is merged, I might add the above client to embassy-net if you think it makes sense.

Embassy net improvements

---

embassy-hal-common/src/peripheral.rs
embassy-nrf/src/buffered_uarte.rs
embassy-stm32/src/eth/v1/mod.rs
embassy-stm32/src/eth/v2/mod.rs
embassy-stm32/src/usart/buffered.rs
examples/stm32f4/src/bin/usart_buffered.rs

Following the project's decision that  "leak unsafe" APIs are not marked as "unsafe",
update PeripheralMutex to accept non-'static state without unsafe.
Fixes #801 
bors r+

common/PeripheralMutex: remove unsafe API.

---

embassy/src/channel/mod.rs
embassy/src/channel/mpmc.rs
embassy/src/channel/signal.rs
examples/nrf/src/bin/channel.rs
examples/nrf/src/bin/channel_sender_receiver.rs
examples/nrf/src/bin/uart_split.rs
examples/nrf/src/bin/usb_ethernet.rs
examples/nrf/src/bin/usb_hid_keyboard.rs
examples/stm32f3/src/bin/button_events.rs
examples/stm32h7/src/bin/signal.rs
examples/stm32h7/src/bin/usart_split.rs
examples/stm32l5/src/bin/usb_ethernet.rs

I've renamed the channel module for the MPMC as `mpmc`. There was a previous debate about this, but I feel that the strategy here avoids importing `channel::channel`. The change leaves `signal::Signal`, but I think that's ok. It is all a bit subjective of course. The bottom line for me is that I really like the term `mpmc` - it means something to me and aligns with broader naming e.g. in Tokio.

Rename channel to mpmc

---

README.md
embassy/src/blocking_mutex/mod.rs
embassy/src/blocking_mutex/raw.rs
embassy/src/channel/mpmc.rs
embassy/src/channel/signal.rs
embassy/src/executor/raw/mod.rs
embassy/src/lib.rs
embassy/src/mutex.rs
embassy/src/util/steal.rs
embassy/src/waitqueue/waker.rs

This also includes the README.md in the toplevel crate documentation, fixing a few formatting issues with it as well. 
Please review the mutex in detail in case I've misunderstood/missed a few things there.

Document remaining public APIs in embassy crate

---

embassy/Cargo.toml
embassy/src/executor/arch/riscv32.rs
embassy/src/executor/mod.rs
embassy/src/time/mod.rs

- ~~Moves the default Interrupt implementation into a cortex_m specific module~~
- Adds a RISCV32 executor based on [osobiehl](https://github.com/osobiehl)'s work in [esp32c3 mess work](https://github.com/osobiehl/riscv-embassy-mess-work)
(FYI esp implementation of embassy traits etc, is being developed [here](https://github.com/esp-rs/esp-hal/tree/feature/embassy))
[bonus ascii cinema](https://asciinema.org/a/500857 )

Preliminary RISCV support

---

embassy/src/channel/pubsub/publisher.rs

All other publish methods don't require mut

Fixed a pubsub mutability inconsistency

---

embassy/src/executor/arch/xtensa.rs
embassy/src/executor/mod.rs
embassy/src/lib.rs

Based on the work in #804.
I hope non-upstream target support is acceptable :).

Preliminary Xtensa support

---

embassy-stm32/src/pwm/mod.rs
embassy-stm32/src/pwm/simple_pwm.rs
examples/stm32f4/src/bin/pwm.rs

Advanced timers have additional BDTR register, which has a global output enable bit and it is disabled by default.
Also added an example for F4, but it will only work once https://github.com/embassy-rs/stm32-data/pull/149 is merged. We can also move it to some other chip, but I don't have anything else to test on atm.

Fix PWM for advanced timers

---

examples/boot/application/stm32h7/Cargo.toml

Use correct chip family name for example

---

embassy-embedded-hal/src/shared_bus/blocking/i2c.rs
embassy-embedded-hal/src/shared_bus/blocking/spi.rs

Adds impls for the old embedded-hal v0.2 traits for usability until the ecosystem catches up with EH1.
Also added some basic examples in docs of how the shared buses can be set up.

Blocking shared bus EH 0.2 impls + example docs

---

embassy-stm32/src/rcc/f0.rs
embassy-stm32/src/rcc/f1.rs
embassy-stm32/src/rcc/f2.rs
embassy-stm32/src/rcc/f3.rs
embassy-stm32/src/rcc/f4.rs
embassy-stm32/src/rcc/f7.rs
embassy-stm32/src/rcc/g0.rs
embassy-stm32/src/rcc/g4.rs
embassy-stm32/src/rcc/h7.rs
embassy-stm32/src/rcc/l0.rs
embassy-stm32/src/rcc/l1.rs
embassy-stm32/src/rcc/l4.rs
embassy-stm32/src/rcc/l5.rs
embassy-stm32/src/rcc/u5.rs
embassy-stm32/src/rcc/wb.rs
embassy-stm32/src/rcc/wl.rs
embassy-stm32/src/wdg/mod.rs
examples/stm32f4/src/bin/wdt.rs

Allow specifying `IndependentWatchdog` timeout as `Duration` instead of prescaler value.
Since IWDG is clocked from LSI, which differs between families, I standardized HSI/LSI definitions in RCC and used that.

Implement IWDG timeout calculation

---

embassy-nrf/src/gpio.rs
embassy-rp/src/gpio.rs
embassy-stm32/src/gpio.rs

This reduces boilerplate code from:
```rs
if config.pin_high {
pin.set_high()
} else {
pin.set_low()
}
```
to
```rs
pin.set_level(config.pin_high.into());
```

Add more convenience GPIO functions

---

embassy-stm32/src/flash/f4.rs
embassy-stm32/src/flash/mod.rs
examples/stm32f4/src/bin/flash.rs

This discontinuous flash sector layout is too cursed and I left some mistakes in last PR. Erasing last sector did not work and it wasn't possible to erase between memory banks for 1MB dual-bank devices. So I changed the erase function to iterate over memory addresses (which is continuous) instead of sector numbers.
It should also be possible to implement erase across memory banks for H7, but it requires special handling for write too. I don't have an H7 to test now so left it as is.
I wasn't sure how to add tests to `embassy-stm32` and it seems that there are none, except for `subghz`, but no test runner? Anyway, I tested the `get_sector` on playground: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=13b59339fe6c70a3249e6183e81f869e
Also fixed erase alignment …

F4 flash fixes

---

embassy-embedded-hal/src/shared_bus/asynch/i2c.rs
embassy-embedded-hal/src/shared_bus/asynch/spi.rs
embassy-embedded-hal/src/shared_bus/blocking/i2c.rs
embassy-embedded-hal/src/shared_bus/blocking/spi.rs
embassy-embedded-hal/src/shared_bus/mod.rs

I think the current naming is a bit odd, the EH traits are organized as "Bus" vs "Device", and XxxBusDevice is a Device (not a Bus, not both)
@kalkyl

Rename XXBusDevice to XXDevice.

---

embassy-nrf/src/usb.rs

PowerUsb must be constructed through `new()` so that it sets up the IRQ.
It must have at least one private field, otherwise user code can construct
it directly with `PowerUsb{}`.

nrf/usb: prevent user code from constructing a PowerUsb directly.

---

embassy-stm32/src/pwm/simple_pwm.rs
examples/stm32f4/src/bin/pwm.rs
examples/stm32g4/src/bin/pwm.rs
examples/stm32h7/src/bin/pwm.rs

550da471be7b56927b50b5955a6de0916ebe6b1f previously refactored the STM32
PWM logic in such a way to preclude use of non-contiguous channels (e.g.
channel 2 but not channel 1). Refactor it yet again to yet again allow
this sort of usage.

embassy-stm32/pwm: Generalize channel selection

---

embassy-embedded-hal/Cargo.toml
embassy-embedded-hal/src/shared_bus/mod.rs
embassy-nrf/Cargo.toml
embassy-stm32/Cargo.toml

`defmt::unwrap!()` should now work with shared buses. I tested it only with I2C as I don't have SPI in the target project.

Add defmt support to embassy-embedded-hal errors

---

embassy-stm32/src/adc/v2.rs
embassy-stm32/src/adc/v3.rs
embassy-stm32/src/adc/v4.rs
examples/stm32h7/src/bin/adc.rs

This smooths out a few rough edges with ADC:
- Make `Resolution::to_max_count()` pub for all ADC versions. Useful if performing conversion manually.
- `VREF` and `VREFINT` were convoluted. `VREF` is an external voltage reference used for all ADC conversions and it is exposed as a separate pin on large chips, while on smaller ones it is connected to `VDDA` internally. `VREFINT` is an internal voltage reference connected to one of the ADC channels and can be used to calculate unknown `VREF` voltage.
- Add a separate `VREF_DEFAULT_MV`, equal to 3.3V, which is the usual supply voltage and should work for most simple cases.
- For an external voltage reference `set_vref()` can be used to set a known precise voltage.
- If no voltage reference is present, `VREFINT` calibration can be used to …

Improve ADC configuration options

---

embassy/src/executor/raw/mod.rs

Since rust 1.61, the required const features are availabe on stable rust

Remove separation of stable vs. nightly implementations in executor/raw

---

embassy-executor/src/executor/raw/mod.rs
embassy-executor/src/executor/raw/run_queue.rs
embassy-executor/src/executor/raw/waker.rs

Fixes a few MIRI errors due to loosely mixing `&TaskStorage<F>` and `&TaskHeader`. References "downgrade" the provenance. `TaskHeader` is smaller, so once you have a `&TaskHeader` you can't use pointer casts to access the whole `TaskStorage<F>`. This fixes it by always keeping the raw pointer around, which doesn't downgrade provenance.
The error was: 
```
[dirbaio@mars std]$ MIRIFLAGS=-Zmiri-disable-isolation cargo miri run --bin tick
Finished dev [unoptimized + debuginfo] target(s) in 0.05s
Running `/home/dirbaio/.rustup/toolchains/nightly-2022-07-13-x86_64-unknown-linux-gnu/bin/cargo-miri target/miri/x86_64-unknown-linux-gnu/debug/tick`
error: Undefined Behavior: trying to reborrow <12349> for SharedReadWrite permission at alloc2[0x30], but that tag does not exist in the borrow stack …
```

executor: miri fixes

---

embassy-net/src/tcp.rs

It's just an implementation detail to share code between Socket, Reader, Writer. It wasn't supposed to be public.

net: make TcpIo private.

---

ci.sh
embassy-futures/README.md
embassy-futures/src/lib.rs
embassy-sync/README.md
embassy-sync/src/lib.rs
embassy-sync/src/signal.rs
embassy-time/README.md
embassy-time/src/lib.rs

Attempting to add doc modules that don't have any warnings to CI for at least 1 target + feature combination. Hopefully doesn't add to much CI time but catches bugs.

Fix warnings after crate split

---

embassy-executor/Cargo.toml
embassy-time/Cargo.toml
examples/wasm/Cargo.toml
examples/wasm/README.md

This fixes the WASM support which was failing due to missing
critical-section implementation. This also upgrades the bindgen
dependency and ensures that tooling works.

Enable 'std' feature on critical-section for WASM

---

embassy-nrf/src/ppi/mod.rs

- Feature-gate DPPI-only stuff that should be feature-gated
- Fix unsoundness due to Task/Event ptr being public: this meant you could construct a Task/Event with an arbitrary pointer and then safely call `Ppi::new_*` which would blindly write to it. Now you have to go through `Task/Event::new_unchecked` which is unsafe, with the right safety contract.

nrf: PPI fixes

---

embassy-executor/Cargo.toml
embassy-macros/Cargo.toml
embassy-macros/src/macros/cortex_m_interrupt_take.rs

Add "rtos-trace-interrupt" feature flag on embassy-macros and enable it
for embassy-executor, to ensure that the interrupt::take! macro can be
used without depending on embassy-executor.

Ensure interrupt::take works without embassy-executor

---

embassy-nrf/src/saadc.rs

Ensures that nRF saadc sampling is stopped and is awaited prior to exiting the two sampling methods. Not doing so causes a potential power drain and the potential for dropped buffer writes when having finished continuous sampling.

Ensure that the sampling is stopped

---

embassy-nrf/src/gpiote.rs
embassy-nrf/src/spim.rs
embassy-nrf/src/twim.rs
embassy-nrf/src/uarte.rs
embassy-rp/src/uart.rs
embassy-stm32/src/exti.rs
embassy-stm32/src/i2c/v2.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/usart/mod.rs
embassy-time/src/delay.rs

Old code used `cfg_if!` because rustc still parses code inside disabled cfg's, and Rust stable at that time couldn't parse the new GAT where-clause location. This is not the case anymore.
bors r+

Do not use cfg_if for embedded-hal-async feature gates.

---

embassy-boot/README.md
embassy-boot/boot/src/lib.rs
embassy-boot/nrf/src/lib.rs
embassy-boot/stm32/src/lib.rs
examples/boot/application/nrf/src/bin/a.rs
examples/boot/application/stm32f3/src/bin/a.rs
examples/boot/application/stm32f7/src/bin/a.rs
examples/boot/application/stm32h7/Cargo.toml
examples/boot/application/stm32h7/flash-boot.sh
examples/boot/application/stm32h7/src/bin/a.rs
examples/boot/application/stm32l0/src/bin/a.rs
examples/boot/application/stm32l1/src/bin/a.rs
examples/boot/application/stm32l4/src/bin/a.rs
examples/boot/application/stm32wl/src/bin/a.rs
examples/boot/bootloader/nrf/src/main.rs
examples/boot/bootloader/stm32/src/main.rs

* Remove the need for generic const expressions and use buffers provided in the flash config.
* Extend embedded-storage traits to simplify generics.
* Document all public APIs
* Add toplevel README
* Expose AlignedBuffer type for convenience.
* Update examples

Remove generic const expressions from embassy-boot

---

docs/modules/ROOT/pages/runtime.adoc

This commit replaces `embassy::main` with `embassy_executor::main` in the
runtime documentation page.
Refs: https://embassy.dev/dev/runtime.html

Use embassy_executor::main in runtime.adoc

---

embassy-executor/Cargo.toml

This commit suggests adding `critical-section/std` to the std feature as
without this a link time error is generated:
```console
cargo r --bin main
Updating git repository `https://github.com/embassy-rs/embassy`
Updating crates.io index
Compiling embassy-executor v0.1.0 (https://github.com/embassy-rs/embassy?branch=master#50af13d4)
Compiling embassy-macros v0.1.0 (https://github.com/embassy-rs/embassy?branch=master#50af13d4)
Compiling embassy-time v0.1.0 (https://github.com/embassy-rs/embassy?branch=master#50af13d4)
Compiling embassy-exploration v0.1.0 (/home/danielbevenius/work/rust/learning-rust/embassy)
error: linking with `cc` failed: exit status: 1
|
= note: "cc" "-m64" "/tmp/rustcSRodQD/symbols.o" "/home/danielbevenius/work/rust/learning-rust/embassy/target/debug/deps/main-1832a61515 …
```

Add critical-section/std to std feature

---

embassy-sync/src/signal.rs

This makes behavior consistent with `WakerRegistration`. It allows canceling `wait` in one task and then calling `wait` in another. If two tasks are `wait`ing concurrently the signal will be received by only one of them, randomly.

sync/signal: wake old waker on overflow instead of panicking.

---

embassy-sync/src/mutex.rs

Similar to the methods on std Mutex, these methods allow accessing the underlying data without locking the mutex when you have exclusive access to it.

Add .into_inner() and .get_mut() to Mutex

---

embassy-boot/boot/src/lib.rs
examples/boot/bootloader/nrf/src/main.rs
examples/boot/bootloader/stm32/src/main.rs

Compiler will infer a different lifetime for BootFlash than for the borrowed flash, which makes it require more type annotations than if it was just owning the type. Since it doesn't really matter if it owns or borrows in practical use, change it to own so that it simplifies usage.

Remove BootFlash borrow

---

embassy-nrf/src/buffered_uarte.rs

The drop method in `BufferedUarte` was prone to hanging indefinitely and also didn't actually disable the peripheral. I mostly copied over the drop method from `Uarte` with some modifications since `BufferedUarte` could have a transmit lasting indefinitely.

Implement proper `Drop` for `BufferedUarte`

---

embassy-sync/src/signal.rs
examples/nrf/src/bin/usb_hid_keyboard.rs
examples/stm32h7/src/bin/signal.rs
examples/stm32wl/src/bin/subghz.rs

The `RawMutex` parameter is deliberately chosen to be the second one, so as it can take as a default `CriticalSectionRawMutex`. This way backwards compatibility is preserved, and users utilizing the `critical-section` crate everywhere can just continue to use the more ergonomic single-generic-parameter version of Signal.
I'm thinking we should probably do the same for `Channel`, and move the `RawMutex` parameter as the last one in the list, with a `CriticalSectionRawMutex` being its default. But that's a backwards-incompatible change of course.

Parameterize Signal with RawMutex

---

embassy-boot/boot/src/lib.rs

Also add a split `prepare_update` + `write_firmware` API, to allow for an optimized update API at the exchange of added complexity. 
The old API is left in place to allow users to choose the complexity level that fits their needs.

(embassy-boot): add blocking API to FirmwareUpdater

---

examples/boot/application/stm32f7/src/bin/a.rs
examples/boot/application/stm32h7/src/bin/a.rs

The new FirmwareWriter is useful in particular for these architectures due to the large erase sector size.

Use firmware writer in stm32{f7, h7} example app

---

ci.sh
tests/rp/Cargo.toml

rp: enable time-driver in Cargo.toml instead of ci.sh

---

embassy-stm32/src/usart/buffered.rs

Context:
On STM32, BufferedUart is not splittable into Rx and Tx part like the non buffered version. On embassy-nrf, a RefCell is used to make BufferedUarte splittable.
Description:
This PR add the possibility to split BufferedUart into Rx and Tx without adding breaking changes.
Hope somebody find it useful

Rework STM32 BufferedUart internals so we can split into Rx and Tx like embassy-nrf

---

embassy-nrf/Cargo.toml
embassy-nrf/src/usb.rs
embassy-rp/Cargo.toml
embassy-rp/src/usb.rs
embassy-stm32/Cargo.toml
embassy-stm32/src/usb/usb.rs

usb: make HALs depend only on embassy-usb-driver.

---

embassy-rp/src/clocks.rs
embassy-rp/src/i2c.rs
embassy-rp/src/lib.rs
embassy-rp/src/uart/mod.rs

This PR adds both blocking and DMA based async implementations of I2C master.
Both E-H 0.2 & E-H 1.0 abstractions are implemented as well.
- Do we need an I2C interrupt handler (for transfer done, abort & error handling?) (async only)
- Do we need to add some automatic attempt at unblocking an I2C bus in case of failures (see ref: https://github.com/fivdi/pico-i2c-dma/blob/7ebfd553f3ce5b5b210d53102b0ecca158172633/src/i2c_dma.c#L116-L142)
- Should I add `vectored_{read, write}` implementations?

(embassy-rp): Add I2C master implementation

---

embassy-sync/src/pubsub/mod.rs
embassy-sync/src/pubsub/publisher.rs
embassy-sync/src/pubsub/subscriber.rs

- Futures in pub & sub are now awaited instead of returned
- Added functions for reading how many messages are available
This helps people get better compiler diagnostics. For example, I forgot to call await on a future and the compiler didn't complain.
This also helps with making some decisions based on the state of the channels.

Small pubsub improvements

---

embassy-usb-driver/src/lib.rs

Alternative fix for #989 , see comment there for rationale.
bors r+

usb: remove all "Direction as u8" casts.

---

embassy-stm32/src/flash/mod.rs
examples/boot/application/stm32f3/src/bin/a.rs
examples/boot/application/stm32f7/src/bin/a.rs
examples/boot/application/stm32h7/src/bin/a.rs
examples/boot/application/stm32l0/src/bin/a.rs
examples/boot/application/stm32l1/src/bin/a.rs
examples/boot/application/stm32l4/src/bin/a.rs
examples/boot/application/stm32wl/src/bin/a.rs
examples/boot/bootloader/stm32/src/main.rs
examples/stm32f3/src/bin/flash.rs
examples/stm32f4/src/bin/flash.rs
examples/stm32f7/src/bin/flash.rs
examples/stm32h7/src/bin/flash.rs
examples/stm32l0/src/bin/flash.rs
examples/stm32l1/src/bin/flash.rs
examples/stm32wl/src/bin/flash.rs

Instead, perform the unlocking and locking automatically on erase and write operations.
This makes the `embedded-storage` abstraction actually useable in libraries, while still keeping the flash peripheral locked the majority of the time.

(embassy-stm32): remove flash lock/unlock public API from stm32 flash

---

embassy-stm32/src/adc/mod.rs
embassy-stm32/src/adc/v2.rs
embassy-stm32/src/adc/v4.rs
examples/stm32f4/src/bin/adc.rs

Internal channel reading was broken on adc_v2, because `Adc::read()` requires gpio pin trait, which was not implemented by `VrefInt`, `Temperature`, `Vbat`. The required configuration bits `tsvrefe`, `vbate` were not enabled either. This PR makes it a bit closer to how adc_v4 works.
While at it, I also changed adc_v2 to use `RccPeripheral` instead of permanently enabling all ADCs.

Fix internal channels for adc v2

---

embassy-nrf/src/uarte.rs
examples/nrf/src/bin/uart_idle.rs

This PR removes some of the code duplications for `UarteWithIdle` at the slight expense of requiring a split when using idle processing. As the nRF example illustrates though given the LoC removed, this expense seems worth the benefit in terms of maintenance, and the avoidance of copying over methods. My main motivation for this PR was actually due to the `event_endtx` method not having been copied across to the idle-related code.
Tested the uart_idle example on my nRF52840-dk, and from within my app. Both appear to work fine.

Removes some of the code duplication for UarteWithIdle

---

embassy-stm32/src/flash/h7.rs

The stm32h7xx-hal uses only the ordering barrier, while the CubeMX uses the DSB and ISB instructions, to be on the safe side, both are used here.
Without the barrier, the PG bit is not set, when the writes are being done, resulting in an error.

Add memory barriers to H7 flash driver to mitigate PGSERR errors

---

embassy-nrf/src/chips/nrf52810.rs
embassy-nrf/src/chips/nrf52811.rs
embassy-nrf/src/chips/nrf52833.rs
embassy-nrf/src/chips/nrf52840.rs
embassy-nrf/src/chips/nrf9160.rs
embassy-nrf/src/lib.rs
embassy-nrf/src/pdm.rs
examples/nrf/src/bin/pdm.rs

PDM microphones have a long startup phase, therefore the driver samples continuously and only switches the target buffer if the user requests sampling.

PDM microphone support for nrf

---

embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs
examples/stm32f3/src/bin/usart_dma.rs
examples/stm32f4/src/bin/usart.rs
examples/stm32f4/src/bin/usart_buffered.rs
examples/stm32f4/src/bin/usart_dma.rs
examples/stm32f7/src/bin/usart_dma.rs
examples/stm32h7/src/bin/usart.rs
examples/stm32h7/src/bin/usart_dma.rs
examples/stm32h7/src/bin/usart_split.rs
examples/stm32l0/src/bin/usart_dma.rs
examples/stm32l0/src/bin/usart_irq.rs
examples/stm32l4/src/bin/usart.rs
examples/stm32l4/src/bin/usart_dma.rs
tests/stm32/src/bin/usart.rs
tests/stm32/src/bin/usart_dma.rs

@guillaume-michel I rebased #1011 for you and then noticed you don't have the "allowed maintainers to push" option so I had to open a new PR. 
bors r+

stm32: Add support for read_until_idle on UART - rebase

---

embassy-stm32/Cargo.toml
embassy-stm32/src/i2c/mod.rs
embassy-stm32/src/i2c/timeout.rs
embassy-stm32/src/i2c/v1.rs
embassy-stm32/src/i2c/v2.rs
embassy-stm32/src/lib.rs
embassy-stm32/src/subghz/timeout.rs
embassy-stm32/src/subghz/tx_params.rs
examples/stm32f4/src/bin/i2c.rs
examples/stm32h7/src/bin/i2c.rs

This is an alterrnative to #1022 as discussed there.
Timeouts are implemented using suggested `check_timeout: impl Fn() -> Result<(), Error>` function, which does not depend on `embassy-time` by default and is a noop for regular I2C.
This also adds `time` feature like in `embassy-nrf` to enable `embassy-time` dependencies. While at it, I also gated some other peripherals that depend on `embassy-time`, notably `usb` and (partially) `subghz`.
`TimeoutI2c` is currently only implemented for i2cv1, because i2cv2 has additional complications:
- Async methods still use a lot of busy waiting code in between DMA transfers, so simple `with_timeout()` will not work and it will have to use both types of timeouts. It could probably be rewritten to replace busy waits with IRQs, but that's outside the …

Implement I2C timeouts, second attempt

---

embassy-stm32/src/adc/f1.rs
embassy-stm32/src/adc/v2.rs
embassy-stm32/src/adc/v3.rs
embassy-stm32/src/adc/v4.rs
examples/stm32f1/src/bin/adc.rs
examples/stm32f4/src/bin/adc.rs
examples/stm32f7/src/bin/adc.rs

The current conversion utilities are confusing and a bit of a footgun. (Two out of the three examples got it wrong! They didn't measure vref at all, so all the conversions are completely wrong if vcca isn't 3.3v)
I think we should eventually have some sort of conversion utilities in the HAL, but for now I think it is best to just remove it and let the users do their own math.
cc @chemicstry

stm32/adc: Remove voltage and temperature conversions

---

embassy-stm32/src/adc/f1.rs
embassy-stm32/src/adc/mod.rs
embassy-stm32/src/adc/resolution.rs
embassy-stm32/src/adc/sample_time.rs
embassy-stm32/src/adc/v2.rs
embassy-stm32/src/adc/v3.rs
embassy-stm32/src/adc/v4.rs

Noteworthy changes:
- Fixed a few typos in the `SampleTime`s
- `set_resolution` now writes directly to the configuration register. This also fixed a bug in v3 where the resolution was changed while `ADEN` is enabled, which the datasheet says isn't allowed.

stm32/adc: Misc refactoring

---

embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs

This PR follows #1031 and #987 and add missing constructors with hardware flow control.
It also factor general UART configuration like word size, parity, ... used in `Uart`, `UartRx`, `UartTx` and `BufferedUart`.

stm32/usart: Add missing constructor with hardware flow control

---

embassy-stm32/src/usart/mod.rs

on STM32, when setting USART `detect_previous_overrun = true`, the idle flag is not cleared and could result in premature end of the `read` method.
This PR fixes that.

stm32/usart: Fix bug where USART idle flag could end a `read` prematuraly

---

examples/stm32wl/src/bin/uart_async.rs

Dear Embassy Team,
here i propose an additional async uart pass-through example for the STM32WL.
Because im quite new to Rust, is there something like **interfaces**?
The code: 
```
mut usart1: Uart<
'static,
embassy_stm32::peripherals::USART1,
embassy_stm32::peripherals::DMA1_CH3,
embassy_stm32::peripherals::DMA1_CH4,
>,
mut usart2: Uart<
'static,
embassy_stm32::peripherals::LPUART1,
embassy_stm32::peripherals::DMA1_CH5,
embassy_stm32::peripherals::DMA1_CH6,
>,
```
is quite ugly in my opinion. I would like to allow any Type of DMA and USART/UART as argument. Is this possible somehow?
Im open to any feedback.
With love,
Mia

Add uart async task example

---

stm32-metapac-gen/Cargo.toml
stm32-metapac-gen/src/lib.rs

This makes stm32-metapac-gen over twice as fast. A full run on my desktop goes from about six and a half seconds to about three seconds. Suprisingly, it also reduces the fresh compile time by almost a second.

stm32-metapac-gen: Use `serde_json` to parse json files

---

embassy-stm32/src/eth/v2/mod.rs

MMC interrupts can cause firmware hangup - refer to: https://github.com/stm32-rs/stm32h7xx-hal/issues/275 for more information
Fixes #594

Disable MMC interrupts

---

embassy-usb-logger/Cargo.toml
embassy-usb-logger/README.md
embassy-usb-logger/src/lib.rs
examples/rp/Cargo.toml
examples/rp/src/bin/usb_logger.rs

* Add embassy-usb-logger which allows logging over USB for any device implementing embassy-usb
* Add example using logger for rpi pico

feat: embassy-usb-logger and example for rpi pico

---

embassy-stm32/src/adc/v3.rs

using the CHSELR register in sequence mode does not support ADC channels above 14. Also, it seems like the sequencer itself wasn't being used anyway, so I turned it off (maybe the whole block from L72..L76 could be removed?) and used a bit shift.

stm32g0: Fix ADC for channels above 14

---

embassy-nrf/src/lib.rs

Uarte is enabled by default on the nrf9160, which is both bad for power consumption and renders the other "shared" peripherals unusable. This might be an SPM bug, but had the same issue with all pre-compiled SPM:s available out there, so adding this fix until we figure out.

embassy-nrf: Default disable UARTE (nrf9160)

---

embassy-nrf/src/gpiote.rs

Adding these changes enables us to define a channel using a mutable reference to `GPIOTE_CH(n)`, similar to how we can do with other drivers. So instead of using:
```rust
let p = embassy_nrf::init(config);
let freq_in = InputChannel::new(
p.GPIOTE_CH0,
Input::new(&mut p.P0_19, embassy_nrf::gpio::Pull::Up),
embassy_nrf::gpiote::InputChannelPolarity::HiToLo,
);
```
we can use:
```rust
let p = embassy_nrf::init(config);
let freq_in = InputChannel::new(
&mut p.GPIOTE_CH0,
Input::new(&mut p.P0_19, embassy_nrf::gpio::Pull::Up),
embassy_nrf::gpiote::InputChannelPolarity::HiToLo,
);
```
therefore not giving ownership to GPIOTE_CH0.

GPIOTE InputChannel with mutable reference.

---

embassy-executor/Cargo.toml
embassy-executor/src/lib.rs
embassy-macros/Cargo.toml
embassy-macros/src/lib.rs
embassy-macros/src/macros/main.rs

Apply heuristics using target_arch, target_os and target_family to determine which variant of the entry point to use.

refactor: autodetect macro variant

---

embassy-executor/Cargo.toml

Otherwise the non-raw executor and the macros don't show up.

executor: enable features for docs.rs

---

embassy-hal-common/src/atomic_ring_buffer.rs
embassy-hal-common/src/lib.rs
embassy-rp/Cargo.toml
embassy-rp/src/uart/buffered.rs
embassy-rp/src/uart/mod.rs
tests/rp/src/bin/uart_buffered.rs

This gets rid of another PeripheralMutex usage.
Extracted out of #980

rp/uart: use lockfree ringbuffer.

---

embassy-rp/Cargo.toml
embassy-rp/src/clocks.rs
embassy-rp/src/lib.rs

This has the potential to not be random, but it should not be an issue if default clock settings are used.

rp: Add an RngCore impl based on ROSC.RANDOMBIT

---

embassy-stm32/src/usart/buffered.rs

This PR enables fifo for buffered uart where it is available. This should hopfully get rid of some overrun errors. I tried it in my application where it worked, but more intensive testing is probably required.

stm32: Enable fifo for buffered uart

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/lib.rs

This adds very basic support for specifying priority for DMA interrupts. Unfortunately, the patch now doesn't allow for specifying different priorities for DMA1/DMA2, or BDMA1/BDMA2, which I didn't know how to support.

stm32: Add basic support for DMA priority settings

---

embassy-stm32/src/flash/h7.rs

This PR simplifies erasing sectors on the H7, which was buggy.

stm32: Fix H7 unaligned erase

---

examples/stm32f0/.cargo/config.toml
examples/stm32f0/Cargo.toml
examples/stm32f0/src/bin/blinky.rs

Hi, I have added **blinky** example for `stm32f0` and tested with Nucleo board `STM32F091RC`.
- Can I add more example for stm32f0?

Added blinky example for stm32f0

---

embassy-net/README.md

examples/std/src/bin/net.rs connects to TCP port 8000, you need to have something listening there. For example nc -l 8000
Besides, need to add `-- --static-ip` becuase `nc` not support DHCP.

fix net README.md

---

embassy-rp/Cargo.toml
embassy-rp/src/gpio.rs
embassy-rp/src/lib.rs
embassy-rp/src/pio.rs
embassy-rp/src/pio_instr_util.rs
embassy-rp/src/relocate.rs
examples/rp/Cargo.toml
examples/rp/src/bin/pio_async.rs
examples/rp/src/bin/pio_dma.rs

This is a driver for the two PIOs in the Pico. I've tried using the type system to get as much compile time checks as possible. There is asynchronous support for FIFOs an Irqs. No DMA support yet. There's an example that shows how to use the driver asynchronously.

Rpi Pico PIO driver

---

embassy-nrf/src/uarte.rs

It's a perfectly fine thing to do, should be just a noop. Erroring is really annoying when you're writing a payload to uart that might be zero-length or not.
bors r+

nrf/uart: do not error on zero length transfers.

---

examples/rp/src/bin/adc.rs

modify RP2040 adc example to get inside biased bipolar diode voltage,
then convert this temperature sensor data into Celsius degree,
according to chapter 4.9.5. Temperature Sensor in RP2040 datasheet.

add convert_to_celsius function in the adc module

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/gpdma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/spi/mod.rs

This PR fixes two bugs:
* It fixes #1095 by ensuring that pin speed is VeryHigh for all spi versions. I am on stm32f429 which seems to be spi_v1, and it also needs the VeryHigh pin speed. Otherwise bit errors on the "last bit in every byte" can happen.
* It also fixes a lifetime bug for the tx buffer when sending "write_repeated". The issue can be seen when doing spi.write where the clock byte changes during a transmission because the buffer handled to the dma must live throughout the entire transfer.

Fix two SPI bugs for stm32

---

embassy-rp/src/spi.rs

The SPI definitions lack the pins which are not accessible on the pico (but are so e.g. on the stamp).

Add missing SPI pins

---

embassy-nrf/src/gpio.rs

This simply adds the Clone and Copy derive traits on embassy_nrf::gpio::Level.

Add Clone & Copy on embassy_nrf::gpio::Level

---

embassy-usb/src/class/cdc_acm.rs

* Remove unused call management descriptor
* Set flag for supported capabilities
The rp `usb_serial` example still works with windows hosts.

USB serial (CDC-ACM) improvements

---

embassy-boot/nrf/src/lib.rs
embassy-nrf/src/wdt.rs
examples/boot/application/nrf/README.md
examples/boot/application/nrf/memory-bl.x
examples/boot/application/nrf/memory.x
examples/boot/application/nrf/src/bin/a.rs
examples/boot/bootloader/nrf/memory-bm.x
examples/boot/bootloader/nrf/memory.x
examples/boot/bootloader/nrf/src/main.rs

Per commits:
* By passing WDT config around we can control it more easily and promote sharing it between files.
* The memory layout of the s140 crept into a number of memory files, which can cause confusion (well, it did for me!).
* Obtaining the current WDT config is useful so that we do not have to duplicate configurations around the place. A constructor method has been introduced that attempts to return the current running WDT config from the WDT peripheral. The bootloader example has also been updated to show how the watchdog can be obtained and used.

Wdt config changes

---

embassy-rp/src/uart/mod.rs
examples/rp/src/bin/uart_unidir.rs

As discussed with @henrik-alser on Matrix. I also added an example, feel free to remove it if it's too much.

rp2040: add {tx,rx}-only constructors to UART

---

ci.sh
examples/boot/application/nrf/Cargo.toml
examples/boot/application/nrf/README.md
examples/boot/application/nrf/memory-bl-nrf91.x
examples/boot/application/nrf/memory-nrf91.x
examples/boot/application/nrf/src/bin/a.rs
examples/boot/application/nrf/src/bin/b.rs
rust-toolchain.toml

* Add nRF91 as target in CI builds
* Add example linker scripts for nrf91
* Make less nRF52 assumptions example config
* Add llvm-tools-preview required for cargo objcopy example

feat: compile bootloader examples for nRF91

---

.github/workflows/rust.yml
embassy-boot/boot/Cargo.toml
embassy-boot/boot/src/lib.rs
examples/boot/application/nrf/Cargo.toml
examples/boot/application/nrf/README.md

This PR provides a method to verify that firmware has been SHA-512 hashed and signed with a private key given its public key. The implementation provides both [`ed25519-dalek`](https://github.com/dalek-cryptography/ed25519-dalek/blob/main/Cargo.toml) and [`salty`](https://github.com/ycrypto/salty) as the signature verifiers. Either of the `ed25519-dalek` and `ed25519-salty` features is required to enable the functionality from `embassy-boot`.
The `verify_and_mark_updated` method is used in place of `mark_updated` when signing is used via its feature. This avoids the accidental omission of validation where it has been declared as required at compile time. It also keeps the parity of calls at the same number to the previous situation.
The PR permits other types of signature verifiers in the …

Support codesigning in the firmware updater

---

embassy-nrf/src/saadc.rs
embassy-stm32/src/i2c/v2.rs
embassy-stm32/src/usart/mod.rs

Prior to this commit, the onDrop function was being dropped immediately and not on exiting the Saadc sampling methods.
A few other places have been corrected also.
Thanks to Peter Hansen for pointing out this issue.

Stop sampling when exiting the Saadc methods

---

embassy-stm32/src/usb_otg/usb.rs
examples/stm32f4/Cargo.toml
examples/stm32f4/src/bin/usb_ethernet.rs

This fixes a couple of usb otg bugs that surfaced with `usb_ethernet` example from nrf:
- Properly implemented `Endpoint::wait_enabled()`
- Return `EndpointError::Disabled` when neccessary in `Endpoint::write()`

stm32 usb otg bug fixes

---

embassy-rp/src/gpio.rs

This allows set_high() etc to be inlined, toggling pins should be much faster.

rp gpio: make pin_bank() inline

---

ci.sh
embassy-stm32/Cargo.toml
embassy-stm32/src/sdmmc/mod.rs

- Renamed feature to `embedded-sdmmc`.
- Move embedded-sdmmc fork repo to the embassy-rs org.
- Remove unused features in the fork
- Fix impl in embassy-stm32
- Add to CI so it doesn't break again.
bors r+

fix embedded-sdmmc integration.

---

embassy-stm32/src/rcc/wb.rs

- fix prescaler not divided which incorrectly set prescaler divided by 3
Issue: #1137

Fix rcc prescaler for wb55 HCLK1

---

embassy-net/src/device.rs

As title says. Fixes `embassy-net` not compiling when feature `proto-ipv6` is enabled.

IPv6 has no checksum

---

examples/nrf52840/Cargo.toml
examples/nrf5340/Cargo.toml

Fixed nRF examples crates' names: they had the same names and they were conflicting during compilation (Cargo warning).

nRF examples crates names

---

embassy-usb/src/builder.rs

This adds (basic) support for isochronous endpoints. In theory, isochronous endpoints have guaranteed bandwidths and are supposed to adhere to strict timings. But it seems that nothing bad happens if you don't follow the specs closely in this regard. Better handling could also still be added in the future.

usb: allow adding isochronous endpoints

---

embassy-usb/src/builder.rs
embassy-usb/src/class/cdc_acm.rs
embassy-usb/src/class/cdc_ncm/mod.rs
embassy-usb/src/class/hid.rs

This is a breaking change to embassy-usb's API.

USB: allow setting the interface string for interface alt settings

---

embassy-lora/src/sx127x/mod.rs

After a transmission, two receive windows Rx1 and Rx2 are opened for one second each, one right after the other, after a fixed delay (for example 5s). The Rx window offset is added to the starting date of each window and the Rx window duration represents the maximum delay we will wait for an incoming message before declaring that a timeout occurred.
A value of -500ms for the offset and 800ms for the duration means that instead of having Rx1 = [5000, 6000[ and Rx2 = [6000, 7000[ we get Rx1 = [4500, 5300[ and Rx2 = [5500, 6300[. We only cover 30% of the expected windows.
The maximum time a SX127x can take before the Rx side is ready is TS_HOP + TS_RE = 50µs + 2.33ms. Using 3ms for the offset and 1003ms for the duration will give much better time windows: Rx1 = [4997, 5997[ and Rx2 = [5997, …

LoRa/SX1276: adjust Rx window offset and duration

---

embassy-lora/src/stm32wl/mod.rs
embassy-lora/src/sx126x/mod.rs

Those timings open Rx time windows covering 99.7% of the one expected
by the antenna while allowing 3ms for the Rx subsystem to start listening.

LoRa timings for SX126x/STM32WL

---

embassy-stm32/src/gpio.rs

This PR implements a `degrade` method on the STM32 GPIO structs `Flex`/`Input`/`Output`/`OutputOpenDrain`. This allows, for example, transforming some `Input<T>` to an `Input<AnyPin>`.

stm32 gpio implement degrade to AnyPin

---

embassy-stm32/src/usart/mod.rs

According to RM0351 Rev 9 (L4) and RM0399 Rev 3 (H7):
baud = (256 * clock) / LPUARTDIV

stm32/usart: fix LPUART clock multiplier

---

embassy-usb/Cargo.toml
embassy-usb/src/builder.rs
embassy-usb/src/lib.rs
embassy-usb/src/msos.rs
examples/nrf52840/Cargo.toml
examples/nrf52840/src/bin/usb_serial_winusb.rs

This is an alternate API for #1152 based on the work of @mattico. By switching to a writer-style API instead of a builder API some compile-time guarantees are lost, but it integrates better into the usb `Builder` and makes an api that can be used by USB device class implementations.
It also adds a feature flag so there is zero cost to the MS OS descriptors for devices that don't need to use them.
I've added an example based on `usb_serial` which tells Windows to use the generic `WinUSB` driver instead of the serial port driver for the device.
Comments are welcome. It would be nice to see either this or #1152 merged as my project is going to require the MS OS Descriptors soon.

USB: Add MS OS Descriptors (alternate implementation)

---

embassy-stm32/src/spi/mod.rs

Fixes #1094 
There are some proposed solutions in #1094 
> Keep the DMA transaction open across calls to read/write
This may be problematic if the user changes bus settings between calls, and also the reference manual says the chip should not be placed into low power mode while SPI is enabled
As already described, this is problematic and against reference manual recommendation
>    Set the CLK (and maybe MOSI) pins as pull-down on setup (or pull-up, depending on config - and this would need to be updated if the user modified the config)
This is less good than driving the pin to the correct value, but may be better than nothing
That is also my preferred solution. See below citation from reference manual.
>    Document this and require users fix it themselves (add a pull-up/down resistor - …

STM32 SPI: Set clk-pin pull-up/-down to match spi clock polarity

---

embassy-stm32/src/rng.rs

This PR fixes a problem where the device gets locked in case of rng errors.
The PR also includes a hack for stm32wl based devices where the more complicated RNG peripheral can get stuck on seed errors.

stm32/rng Fix rng generation lock-up

---

embassy-time/src/duration.rs

I found myself doing things like this
```rust
let rate_us = 1_000_000 / rate_hz;
let mut ticker = Ticker::every(Duration::from_micros(rate_us));
```
Several times, and figured it was worth adding a little convenience function to handle that. This also makes the calculation const, which is a nice little upside. The compiler might have been doing that already, but this makes sure. 
Speaking of const, would it be better to give hz as a float? Obviously we'd want to avoid that at runtime since many targets don't have a fpu, but if it's at compile time that doesn't matter and a float may be more ergonomic.

Time: Add from_hz function for Duration.

---

embassy-stm32/src/rcc/wl.rs

fix "prescaler none" which incorrectly set "prescaler divided by 3"
Issue: #1168

Fix rcc prescaler for wl55 HCLK1

---

embassy-rp/src/gpio.rs

Allows you to wite a cleaner state change detector. Example:
```rs
let mut button_state: Level = Level::Low;
let mut prev_button_state: Level = button_state;
loop {
button_state = button.get_level();
if prev_button_state != button_state {
led.set_level(button_state);  // Takes ownership of button_state. 
}
prev_button_state = button_state; // Can't be done since the ownership has been moved.
// Adding Clone makes this code possible
}
```

Add clone to embassy_rp::gpio::Level

---

examples/stm32wb/memory.x

cortex-m-rt 0.7.2 now enforces the stack is 8-byte aligned. Stack is placed at `ORIGIN(RAM) + LENGTH(RAM)` by default, which wasn't 8-byte-aligned. See https://github.com/rust-embedded/cortex-m/discussions/469
ST trims 8 bytes from start of RAM, and uses the whole 192kb, so let's just copy that:
https://github.com/STMicroelectronics/STM32CubeWB/blob/bceb1dae09f912eae47fba059251d499ba32f4ca/Drivers/CMSIS/Device/ST/STM32WBxx/Source/Templates/gcc/linker/stm32wb55xx_flash_cm4.ld#L48
bors r+

examples/stm32wb: fix linker script.

---

embassy-rp/src/pio.rs
examples/rp/src/bin/pio_async.rs
examples/rp/src/bin/pio_dma.rs

Renames "PioPeripherial" to "PioPeripheral" (without the second i).

Fix a typo in "PioPeripheral"

---

embassy-lora/src/sx126x/mod.rs

Lora: sx126x: Change timing window to match values found experimentally.

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/gpdma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/sdmmc/mod.rs
examples/stm32f4/src/bin/sdmmc.rs

This fixes writes on sdmmc v1 (SDIO). I'm pretty sure I tested writes in #669, but maybe I was just lucky or I just forgot.
There were two problems:
- Writes require DMA FIFO mode, otherwise SDIO FIFO is under/overrun depending on sdio/pclk2 clock ratio.
- Hardware flow control is broken for sdmmc v1 (I checked F1 and F4 erratas). This causes clock glitches above 12 MHz and results in write CRC errors.

stm32/sdmmc: Fix SDIOv1 writes

---

examples/stm32wb/memory.x

They're used to communicate from the app to ST's OTA bootloader. See AN5247. 
This bootloader is optional, must be flashed by the user, and requires changing the FLASH start address as well, so the current memory regions still require modifications to use it. Therefore there's no point in reserving these words.
Thanks @adamgreig for investigating the purpose.
bors r+

examples/stm32wb: do not reserve words at start of RAM.

---

ci.sh
embassy-nrf/Cargo.toml
embassy-nrf/src/chips/nrf52805.rs
embassy-nrf/src/chips/nrf52810.rs
embassy-nrf/src/chips/nrf52811.rs
embassy-nrf/src/chips/nrf52820.rs
embassy-nrf/src/chips/nrf52832.rs
embassy-nrf/src/chips/nrf52833.rs
embassy-nrf/src/chips/nrf52840.rs
embassy-nrf/src/chips/nrf5340_app.rs
embassy-nrf/src/lib.rs
embassy-nrf/src/nvmc.rs

- APPROTECT enable/disable. Notably this fixes issues with nrf52-rev3 and nrf53 from locking itself at reset.
- Use NFC pins as GPIO.
- Use RESET pin as GPIO.
NFC and RESET pins singletons are made available only when usable as GPIO, for compile-time checking.
TODO: test

nrf: add support for UICR configuration.

---

embassy-net/src/tcp.rs

Implements flush for TcpSocket by checking the send queue. 
Flushing is implemented by checking if smoltcp's send_queue/tx_buffer is empty. The flush is completed when all outstanding octets are acknowledged. Smoltcp wakes the send waker [here](https://docs.rs/smoltcp/latest/src/smoltcp/socket/tcp.rs.html#1712) when ACKs are processed and data is removed from the send buffer. So we can re-check in our flush implementation, if the buffer is now empty.
fixes #1223

embassy-net: Implement flush for TcpSocket

---

embassy-stm32/src/dma/dma.rs

DMA interrupts must be acknowledged by writing to the DMA_{L,H}IFCR
register.
Writing to the CR register is unnecessary as the channel (EN bit) is
disabled by hardware on completion of the transfer.

stm32/dma: fix spurious transfer complete interrupts

---

embassy-stm32/src/sdmmc/mod.rs
examples/stm32f4/src/bin/sdmmc.rs
examples/stm32f7/src/bin/sdmmc.rs

This implements proper clock configuration for sdmmc based on chip family, because `RccPeripheral::frequency()` is almost always incorrect. This can't be fixed in PAC, because sdmmc uses two clock domains, one for memory bus and one for sd card. `RccPeripheral::frequency()` usually returns the memory bus clock, but SDIO clock calculations need sd card domain clock. Moreover, chips have multiple clock source selection bits, which makes this even more complicated. I'm not sure if it's worth implementing all this logic in `RccPeripheral::frequency()` instead of cfg's in sdmmc.
Some chips (Lx, U5, H7) require RCC updates to expose required clocks. I didn't want to mash everything in a single PR so left a TODO comment. I also left a `T::frequency()` fallback, which seemed to work in H7 case …

stm32/sdmmc: Implement proper clock configuration

---

embassy-time/src/duration.rs

I chose microseconds for the conversion as the lowest resolution that embassy provides. A new Error-type did not seem that useful but I can add one, if necessary.

embassy-time: Implement conversions to/from core::time::Duration for embassy-time::Duration

---

embassy-time/src/timer.rs

Small QOL change so you don't have to add a direct dependency on futures-util to use the Ticker

embassy-time: add async tick() method to Ticker

---

embassy-stm32/src/eth/mod.rs
embassy-stm32/src/lib.rs

`PacketQueue` is pretty big, so I added a method to initialize it without requiring an allocation on the stack (which could in fact overflow). Before this PR, the only solution would be to declare a `PacketQueue` instance as a `static mut`, while now one could for example have a `Box<MaybeUninit<PacketQueue<...>>>` and then use `init()` on it.
Ideally, the same work would need to be done for all those structures that own big arrays which could overflow the stack.

`PacketQueue::init()`

---

embassy-stm32/src/spi/mod.rs

Need to clear the rx fifo before enabling rx dma.

stm32/spi: fix occasional data corruption

---

embassy-stm32/src/eth/mod.rs

Quick fix for a bug introduced in my previous PR #1247.

FIx `PacketQueue::init()`

---

embassy-cortex-m/src/executor.rs
examples/nrf52840/src/bin/multiprio.rs
examples/stm32f0/Cargo.toml
examples/stm32f0/src/bin/multiprio.rs
examples/stm32f3/src/bin/multiprio.rs
examples/stm32f4/src/bin/multiprio.rs

Preparation for #1224.
InterruptExecutor can't easily use the new interrupt binding system. The problem is the context pointer, I don't see an easy way to get it to the interrupt handler. I don't want to add a `context` pointer to all interrupts in the new system.
Use manual interrupt handlers for now. We can add a nicer macro on top of the current API later.
(Interestingly, the reason this is not an issue in HALs is  because the impls are made by macros, so each irq handler can be gen'd with its own static state, because the HAL knows all the interrupts that exist. Not the case in embassy-cortex-m though...)

cortex-m/executor: don't use the owned interrupts system.

---

embassy-hal-common/src/atomic_ring_buffer.rs

Extracted out of #1208. Since I don't think that'll end up using the ringbuf in the end, I've separated it.
This allows the ringbuf to be filled up to `N` instead of just `N-1`, using some fun tricks on the indices. 
The advantage is better performance: Before, the first write would fill N-1 bytes, The second would write just the 1 byte left before wrapping, then N-2. Then 2, then N-3, and so on. This would result in more smaller chunks, so worse perf. This problem is gone now.
bors r+

common: allow atomic ringbuf to fill up to N instead of just N-1.

---

README.md

I can also add some examples if you think that is a good idea, but I don't want to add any maintenance burden in doing so; of course, I am more than happy to maintain the examples myself.

docs: add esp-hal

---

embassy-rp/src/gpio.rs

When using gpio pin changes for things like peripheral interrupts these debug! calls flood defmt, making it difficult to find what you're actually looking for.

Swap debug! for trace! in rp gpio

---

examples/rp/Cargo.toml
examples/rp/src/bin/ws2812-pio.rs

This example also uses a pio program compiled at runtime, rather than one built at compile time. There's no reason to do that, but it's probably useful to have an example that does this as well.

Example using the PIO to drive WS2812 aka Neopixel RGB leds

---

embassy-executor/Cargo.toml
embassy-executor/src/raw/mod.rs
embassy-executor/src/raw/waker_turbo.rs
embassy-sync/Cargo.toml
embassy-sync/src/waitqueue/atomic_waker.rs
embassy-sync/src/waitqueue/atomic_waker_turbo.rs
embassy-sync/src/waitqueue/mod.rs
embassy-sync/src/waitqueue/waker_registration.rs

This is a `core` patch to make wakers 1 word (the task pointer) instead of 2 (task pointer + vtable). It allows having the "waker optimization" we had a while back on `WakerRegistration/AtomicWaker`, but EVERYWHERE, without patching all crates.
Advantages:
- Less memory usage.
- Faster.
- `AtomicWaker` can actually use atomics to load/store the waker, No critical section needed.
- No `dyn` call, which means `cargo-call-stack` can now see through wakes.
Disadvantages:
- You have to patch `core`...
- Breaks all executors and other things that create wakers, unless they opt in to using the new `from_ptr` API.
How to use:
- Run this shell script to patch `core`. https://gist.github.com/Dirbaio/c67da7cf318515181539122c9d32b395
- Enable `build-std`
- Enable `build-std-features = …

Turbo-wakers :rocket: 

---

embassy-stm32/build.rs
embassy-stm32/src/rcc/f4.rs
embassy-stm32/src/rcc/l4.rs
examples/stm32f4/src/bin/mco.rs
examples/stm32l4/src/bin/mco.rs

Add MCO support for L4 and F4 as already done in F7. 
When the 'HSI' source is selected as MCO source, 'HSI' is activated (`set_hsion(true)`) . This is done to operate the MCO in case 'MSI' is chosen as the clock source for the CPU. The same applies to PLL, etc.

Add MCO support for L4 and F4 families

---

embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs
examples/stm32f4/src/bin/usart_buffered.rs
examples/stm32l0/src/bin/usart_irq.rs

New implementation is very similar to the implementation of embassy-nrf & embassy-rp. 
Also adds embedded-hal traits to bufferedUart.
**NB**: Still needs testing on actual hardware

(embassy-stm32): rework bufferedUart to get rid of PeripheralMutex

---

embassy-stm32/src/pwm/complementary_pwm.rs
embassy-stm32/src/pwm/mod.rs
examples/stm32f4/src/bin/pwm_complementary.rs

This implements complementary PWM with dead time on many supported targets. The specific dead-time programming functions are passed through directly to the user, which is a bit ugly but the best compromise I could reach for now.

stm32/pwm: add complementary pwm

---

embassy-rp/src/gpio.rs

A while ago `OutputOpenDrain` was made to implement `InputPin`, something that allowed drivers for various one-wire protocols to be written, but it's been lacking a `Wait` implementation — something that's needed to write async versions of these drivers.
This commit also adds `get_level()` to `OutputOpenDrain`, since `is_high()` and `is_low()` were already implemented, but `get_level()` itself was missing.

feat(rp): add `Wait` impl to `OutputOpenDrain`

---

embassy-stm32/src/i2c/v2.rs

While tinkering with I2C on a NUCLEO-H723ZG, I noticed that when trying to communicate with a non-existent device you do receive a proper NACK error, but afterwards any future communications with any device no longer works as expected.
The use case is auto-detection of devices, in this case a series of Adafruit 24LC32 I2C EEPROM boards.
On closer inspection with a logic analyzer, I observed that after the NACK, any data bytes sent out by the board to the devices are just zeros. Even though the embassy code specifies the correct data in `set_txdata` in `write_internal`. Something seems to be going wrong with the controller or buffers on the board itself.
Then I noticed what seems to be a logic error in `flush_txdr`, which is called when issuing a NACK.
After flipping the if statement, I2C …

fix I2C controller problems after NACK

---

examples/stm32h5/Cargo.toml

This uses the correct package name for the `stm32h5` example.
Fixes #1349

Fix duplicate package name `embassy-stm32h7-examples`

---

embassy-executor/src/arch/riscv32.rs

embassy_executor::main was missing for riscv targets.

re-export main_riscv macro as main for riscv arch.

---

embassy-stm32/src/rcc/f2.rs

This PR fixes a typo in the derivation of the PLLP divisor for the STM32F2 family.
Fixes #1357

Fix typo in derivation of PLLP divisor for STM32F2 family

---

embassy-stm32/src/time.rs

This PR makes `Hertz` associated functions `hz()`, `khz()`, `mhz()` and their unassociated variants `const`, allowing `Hertz` to be used more easily in constant values:
```rust
const FREQ1: Hertz = Hertz::khz(120);
const FREQ2: Hertz = mhz(1);
```
This follows the pattern used for similar types such as `Duration` and `Instant`, from `embassy-time/src/duration.rs` and `embassy-time/src/instant.rs`, respectively.
https://github.com/embassy-rs/embassy/blob/ba8cafb20c2458a2016c7db3efd91d718f1a91b6/embassy-time/src/duration.rs#L44-L47
https://github.com/embassy-rs/embassy/blob/ba8cafb20c2458a2016c7db3efd91d718f1a91b6/embassy-time/src/instant.rs#L29-L34

Make Hertz constructors `const`

---

embassy-executor/src/raw/run_queue.rs

Only the head pointer needs to be atomic. The `RunQueueItem` pointers are only loaded and stored, and never concurrently

Executor: Replace unnecessary atomics in runqueue

---

embassy-rp/src/intrinsics.rs

rp2040-hal adds division intrinsics using the hardware divider unit in the SIO, as does the pico-sdk itself. using the hardware is faster than the compiler_rt implementations, and more compact too.
since embassy does not expose the hardware divider in any way (yet?) we could go even further an remove the state-saving code rp2040-hal needs, but that doesn't seem to be worth it.

rp: add division intrinsics

---

embassy-stm32/build.rs
embassy-stm32/src/dcmi.rs
embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/dmamux.rs
embassy-stm32/src/dma/gpdma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/i2c/v2.rs
embassy-stm32/src/lib.rs
embassy-stm32/src/qspi/mod.rs
embassy-stm32/src/sdmmc/mod.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/traits.rs
embassy-stm32/src/usart/mod.rs

- The shared `Channel` trait is not scaling well.
- It has methods for oneshot, double-buffered, circular...
- Double-buffered, circular is not implementable in GPDMA as written.
- There's already runtime panics saying "this is not supported in BDMA/GPDMA"
- #1150 adds more stuff for circular mode
- We'd like to support the fancy new GPDMA linked lists, but that's a completely different API.
- Shared `Channel` trait makes it hard to implement `AnyChannel`, because H7 has a mix of DMA+BDMA
- `AnyChannel` would be useful to remove the `TXDMA, RXDMA` generics on drivers.
So this refactor does:
- Different `Channel` trait for DMA/BDMA/GPDMA.
- Different "driver" for each DMA use case. Currently there's `Transfer` for one-shot transfers, in the future there'll be `CircularTransfer` etc.
- The …

stm32/dma: refactor

---

embassy-rp/src/uart/mod.rs

Same PR as before, except this now works :) 
There was a minor hiccup in the UartRx code where the rx pin got passed as the tx argument, so the invert settings didn't get applied. With this fix, my local setup at least is happily reading inverted uart data.

Add ability to invert UART pins, take 2

---

embassy-rp/src/float/add_sub.rs
embassy-rp/src/float/cmp.rs
embassy-rp/src/float/conv.rs
embassy-rp/src/float/div.rs
embassy-rp/src/float/functions.rs
embassy-rp/src/float/mod.rs
embassy-rp/src/float/mul.rs
embassy-rp/src/lib.rs
tests/rp/.cargo/config.toml
tests/rp/Cargo.toml
tests/rp/src/bin/float.rs

rp-hal has done this very well already, so we'll just copy their entire impl again. only div.rs needed some massaging because our sio access works a little differently, everything else worked as is.
includes a minor bit of refactoring to make it easier to check which bits we've copied from rp2040-hal and which we haven't.

rp: hook up softfloat intrinsics to bootrom

---

embassy-stm32/src/i2c/v2.rs

This change addresses two races:
1. It removes the `chunks_transferred` state variable that is modified inside the interrupt. Analysis of the code reveals that the only time the waker can be woken is when `chunks_transferred` is incremented. Therefore, waking is enough to signal the `poll_fn` that the `chunks_transferred` has incremented. Moving to `remaining_len` clarifies the code, since there is no need to track how many chunks are remaining.
2. It moves the start of the transfer until after the waker is registered, which could theoretically occur if the clock speed is very low, but probably never would even if this wasn't fixed.
There is another race that I noticed: between writes the waker may not yet be registered. In that case, the code would simply be stuck and the `poll_fn` would …

stm32/i2c: fix races when using dma.

---

embassy-rp/src/intrinsics.rs

Commit [7a682ec](https://github.com/embassy-rs/embassy/commit/7a682ec02af50026d31296ce5cac6383580f5e55#diff-f121955242a67342004444b26214e5d1d591c3182dcd0fedf4329ad472cd1200) may break compilation if also using `rp2040-hal`. It seems that the rp2040-hal does have a feature flag for [disabling intrinsics](https://github.com/rp-rs/rp-hal/blob/2c9921cdc578bfcbd5c6e0eb0085bb91f9a7e229/rp2040-hal/src/sio.rs#L323), but I still cannot seem to compile with that enabled. Adding these flags fixes it for me.

embassy-rp : Fix for division intrinsics clashing with rp2040-hal

---

examples/boot/application/stm32f7/.cargo/config.toml

Just a minor thing: `-v` option does not work with probe-rs-cli

fix stm32f7 example runner command for probe-rs-cli

---

embassy-rp/src/uart/buffered.rs
embassy-rp/src/uart/mod.rs
examples/rp/src/bin/uart_unidir.rs
tests/rp/src/bin/uart.rs
tests/rp/src/bin/uart_buffered.rs
tests/rp/src/bin/uart_dma.rs

neither of these reported errors so far, which is not ideal. add error reporting to both of them that matches the blocking error reporting as closely as is feasible, even allowing partial receives from buffered uarts before errors are reported where they would have been by the blocking code. dma transfers don't do this, if an errors applies to any byte in a transfer the entire transfer is nuked (though we probably could report how many bytes have been transferred).

rp: report errors from buffered and dma uart receives

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/dma/ringbuffer.rs
embassy-stm32/src/usart/mod.rs
embassy-stm32/src/usart/rx_ringbuffered.rs
tests/stm32/Cargo.toml
tests/stm32/src/bin/usart_dma.rs
tests/stm32/src/bin/usart_rx_ringbuffered.rs
tests/stm32/src/example_common.rs
tests/utils/Cargo.toml
tests/utils/src/bin/saturate_serial.rs

This PR replaces #1150. Comparing to that PR, this one has the following changes:
* The implementation now aligns with the new stm32 dma module, thanks @Dirbaio!
* Calls to `read()` now returns on either 1) idle line, or 2) ring buffer is at most half full. This is different from the previous pr, which would return a lot of 1 byte reads. Thank you @chemicstry for making me realize that it was actually not what I wanted. This is accomplished using half-transfer completed and full-transfer completed interrupts. Both seems to be supported on both dma and bdma.
The implementation still have the issue mentioned here: https://github.com/embassy-rs/embassy/pull/1150#discussion_r1094627035
Regarding the todos here: https://github.com/embassy-rs/embassy/pull/1150#issuecomment-1513905925. I have …

feat(stm32): Add DMA based, ring-buffer based rx uart, v3

---

embassy-rp/src/gpio.rs
embassy-rp/src/lib.rs
embassy-rp/src/multicore.rs
tests/rp/src/bin/gpio_multicore.rs

InputFuture could not wait for edges without breaking due to a broken From impl, but even if the impl had been correct it would not have worked correctly because raw edge interrupts are sticky and must be cleared from software. also replace critical sections with atomic accesses, and do nvic setup only once.

rp: fix gpio InputFuture and inefficiencies

---

embassy-rp/src/pio.rs
examples/rp/src/bin/pio_async.rs
examples/rp/src/bin/pio_dma.rs
examples/rp/src/bin/pio_hd44780.rs
examples/rp/src/bin/ws2812-pio.rs

another round of bugfixes for pio, and some refactoring. in the end we'd like to make pio look like all the other modules and not expose traits that provide all the methods of a type, but put them onto the type itself. traits only make much sense, even if we added an AnyPio and merged the types for the member state machines (at the cost of at least a u8 per member of Pio).

rp pio, round 2

---

embassy-stm32/src/spi/mod.rs
examples/stm32wl/src/bin/lora_lorawan.rs
examples/stm32wl/src/bin/lora_p2p_receive.rs
examples/stm32wl/src/bin/lora_p2p_send.rs

For STM32WL, simplify configuration for the use of SUBGHZSPI to perform LoRa operations.  Use Rx/Tx DMA on SPI to enable async functionality.

Handle SUBGHZSPI as async

---

embassy-stm32/src/spi/mod.rs
examples/stm32wl/src/bin/lora_lorawan.rs
examples/stm32wl/src/bin/lora_p2p_receive.rs
examples/stm32wl/src/bin/lora_p2p_send.rs

Determine SUBGHZSPI PCLK3 within new_subghz(), controlled by the stm32wl feature.

Simplify SUBGHZSPI configuration

---

embassy-rp/src/pio.rs
embassy-rp/src/pio_instr_util.rs
embassy-rp/src/relocate.rs
examples/rp/Cargo.toml
examples/rp/src/bin/pio_async.rs
examples/rp/src/bin/pio_dma.rs
examples/rp/src/bin/pio_hd44780.rs
examples/rp/src/bin/ws2812-pio.rs

this should hopefully be the last entry in this series. after this we'll have a reasonably safe interface to pio, both for configuration and at runtime. pio now looks very much like the other peripherals (though not exactly, seeing how state machines can't be constructed from a config but only have it applied to them later). the generated code for `StateMachine::set_config` is still larger than we'd like (almost 300 bytes at Oz), but it's a great step up in safety from the previous interface at approximately the same code space cost.

rp pio IV (the voyage home)

---

.github/workflows/doc.yml
.github/workflows/rust.yml

The following updates are performed:
* update [`actions/cache`](https://github.com/actions/cache) to v3
* update [`actions/checkout`](https://github.com/actions/checkout) to v3
Still using the outdated actions will generate several warnings in CI runs, for example in https://github.com/embassy-rs/embassy/actions/runs/4917900672:
> Node.js 12 actions are deprecated. Please update the following actions to use Node.js 16: actions/checkout@v2, actions/cache@v2. For more information see: https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12/.
The PR will get rid of those warnings.

Update GitHub Actions CI

---

embassy-rp/src/watchdog.rs

rp/watchdog: fix overflow if period is longer than 4294 seconds.

---

embassy-rp/src/pio.rs
embassy-rp/src/pwm.rs
examples/rp/src/bin/pio_async.rs
examples/rp/src/bin/pio_dma.rs
examples/rp/src/bin/pio_hd44780.rs
examples/rp/src/bin/pwm.rs
examples/rp/src/bin/ws2812-pio.rs

It was intended to allow changing baudrate on shared spi/i2c. There's no advantage in using it for PWM or PIO, and makes it less usable because you have to have `embassy-embedded-hal` as a dep to use it.
bors r+

rp: don't use SetConfig trait in PWM and PIO.

---

embassy-executor/src/arch/xtensa.rs

This PR is another go at trying to do something with #1449. The commit was part of the previous attempt but mistakenly discarded as I still experienced lockups. However, after further testing, it looks like that lockup is caused by something else.
This is a manual, "cpu-local" critical section impl that should be good enough on dual-core CPUs, although the implementation still contains `SIGNAL_WORK_THREAD_MODE` which is absolutely not correct on dual-core. This approach was chosen because:
- not taking the global lock technically allows the second core to run
- wrapping the signal read and the sleep in a critical section prevents a race condition that would cause the CPU to sleep longer than ideal if an interrupt hits after reading, but before sleeping.

Work around xtensa deadlock, take 2

---

embassy-rp/src/adc.rs
embassy-rp/src/i2c.rs
embassy-rp/src/interrupt.rs
embassy-rp/src/uart/buffered.rs
embassy-rp/src/uart/mod.rs
embassy-rp/src/usb.rs
examples/rp/src/bin/adc.rs
examples/rp/src/bin/i2c_async.rs
examples/rp/src/bin/uart_buffered_split.rs
examples/rp/src/bin/uart_unidir.rs
examples/rp/src/bin/usb_ethernet.rs
examples/rp/src/bin/usb_logger.rs
examples/rp/src/bin/usb_serial.rs
tests/rp/src/bin/uart_buffered.rs
tests/rp/src/bin/uart_dma.rs
tests/rp/src/bin/uart_upgrade.rs

both of the uart interrupts now check a flag that only the dma rx path ever sets (and now unsets again on drop) to return early if it's not as they expect. this is ... not our preferred solution, but if bind_interrupts *must* allow mutiple handlers to be specified then this is the only way we can think of that doesn't break uarts.

rp: remove take!, add bind_interrupts!

---

embassy-rp/src/clocks.rs
embassy-rp/src/rtc/mod.rs
examples/rp/src/bin/gpout.rs

vastly reduce the code size of initial clock config (over 700 bytes saved!), at the cost of about 48 bytes of ram used to store the frequencies of all clocks in the system. also stop exporting unstable pac items for clock config, fix a few settings that were out of spec, and add missing features (most notably gpin source information).

rp: continue clock rework

---

embassy-macros/src/lib.rs
embassy-macros/src/macros/main.rs

In [esp-hal](https://github.com/esp-rs/esp-hal) we use our own custom runtime crate, [esp-riscv-rt](https://github.com/esp-rs/esp-riscv-rt). This PR adds the ability to optionally specify an entry macro when using `embassy_executor::main`. The following forms are both accepted:
```rust
#[embassy_executor::main] // uses `riscv_rt::entry` by default
async fn main() {}
#[embassy_executor::main(entry = "esp_riscv_rt::entry")]
async fn main() {}
```
I attempted to get this working without needing to quote the entry macro argument, however I was not able to get this working. Based off some reading I did this may not be possible, however I am rather inexperienced with proc macros. Happy to change this if anybody has any insight.

Allow for an optional user-defined entry macro when targeting RISC-V

---

examples/rp/src/bin/pio_ws2812.rs

Went to actually use this code and found two issues:
* The config for the pins got dropped in the shuffle. 
* I found that when using more than one ws2812, only the first would get data. I'm pretty sure the data was shifted out before the task got back to push the next word. So now the fifo gets filled, then we wait.

rp: Pin fix, improve fifo handling

---

embassy-boot/boot/src/firmware_updater.rs
embassy-boot/nrf/src/lib.rs
embassy-boot/rp/src/lib.rs
embassy-boot/stm32/src/lib.rs

It seems as if the arm compiler can does not care about whether the bootloader symbols are undefined if the default() function is never used. The x64 compiler does care however, so this change ensures that we can instantiate the types from tests.

Protect default implementations for FirmwareUpdater and BootLoader

---

embassy-embedded-hal/Cargo.toml
embassy-embedded-hal/src/adapter.rs
embassy-embedded-hal/src/adapter/blocking_async.rs
embassy-embedded-hal/src/adapter/mod.rs
embassy-embedded-hal/src/adapter/yielding_async.rs

This PR calls `yield_now()` for long blocking `NorFlash` read and erase operations.
The motivation for this change is to allow for other tasks on the same executor to get something done between these long running operations, for example a task that feeds a watchdog. This will allow the watchdog to have a timer relative to e.g. one sector erase, instead of all sector erase.

Add YieldingAsync adapter

---

embassy-stm32/build.rs
embassy-stm32/src/flash/common.rs
embassy-stm32/src/flash/f0.rs
embassy-stm32/src/flash/f3.rs
embassy-stm32/src/flash/f4.rs
embassy-stm32/src/flash/f7.rs
embassy-stm32/src/flash/h7.rs
embassy-stm32/src/flash/l.rs
embassy-stm32/src/flash/mod.rs
embassy-stm32/src/flash/other.rs

This PR has the following fixes:
* Ensure that `FlashRegion` instances can only be created within the embassy-stm32 crate.
* Remove `Drop` trait for `AltFlashLayout`, as it is hard to use, as one cannot take the individual regions out from the struct. Instead of going back to single bank mode on `Drop`, we instead transition to single bank mode when calling `Flash::into_regions()`.
* Add missing `otp_region` to the dual bank layout and implement `NorFlash` for the alternate regions.

stm32: Minor fixes in flash regions for F4 dual bank layout

---

embassy-embedded-hal/src/flash.rs
embassy-embedded-hal/src/lib.rs

This PR adds a `ConcatFlash` utility that can be used to concatenate two `NorFlash` flashes. This is especially useful when concatenating multiple flash regions with unequal erase size.

Add ConcatFlash utility

---

.github/workflows/rust.yml
ci.sh

The oidc token is only valid for 5min, builds are starting to fail because HIL tests take more than 5 min and we only obtain it once at start.
Instead of fixing it, let's remove it. My hope for OIDC was to allow running HIL tests on PRs from forks if the author is in a list of trusted users. However GHA simply doesn't give the ID token to PRs from forks. :shrug: Same limitation as with static tokens. So it's useless complexity, let's kill it.

ci: replace openid connect with static secret.

---

embassy-net/src/tcp.rs
examples/std/src/bin/tcp_accept.rs

This lets callers ensure that the reset packet is sent to the remote host. Otherwise there isn't a way to wait for the smoltcp stack to send the reset.
Requires changes to smoltcp to wake after the reset has been sent, see https://github.com/smoltcp-rs/smoltcp/compare/master...mkj:smoltcp:abort-wake
This commit also adds a "TCP accept" demo of the problem. Without the `.await` for abort() it gets dropped before the RST packet is emitted.

embassy-net: Make TcpSocket::abort() async

---

embassy-rp/src/uart/mod.rs

Uart/UartTx currently implements `embedded_hal_02::serial::Read<u8>` and `embedded_hal_02::blocking::serial::Write<u8>` but not `embedded_hal_02::serial::Write<u8>`.
This implements the missing `embedded_hal_02::serial::Write<u8>` to allow use of Uart with crates that expect this interface, such as [defmt_serial](https://docs.rs/defmt-serial/latest/defmt_serial/).

rp: Implement embedded_hal::serial::Write for Uart/UartTx

---

embassy-stm32/src/flash/asynch.rs
embassy-stm32/src/flash/common.rs
embassy-stm32/src/flash/f0.rs
embassy-stm32/src/flash/f3.rs
embassy-stm32/src/flash/f4.rs
embassy-stm32/src/flash/f7.rs
embassy-stm32/src/flash/h7.rs
embassy-stm32/src/flash/l.rs
embassy-stm32/src/flash/other.rs

I wasted yesterday trying to get this to work. It seems that erase operations does not work when in db1m mode. The erase operations, both bank and sector, runs and completes without any error flags being set. It also takes expected amount of time, but the flash is not actually erased.
I found [this](https://community.st.com/s/question/0D50X00009XkWrASAV/is-it-possilbe-to-checkand-may-be-writethe-db1m-option-byte-from-the-firmware-i-am-using-an-stmf4427ig-1mb-with-double-bank-via-db1m-option-byte) on the topic, at it seems that one have to reset the mcu for the change to take effect, so it does not make any sense to have it as runtime configurable.

Remove ability to, during runtime, set alt layout - it does not work.

---

embassy-nrf/src/buffered_uarte.rs
embassy-nrf/src/timer.rs

Solve the issue where power consumption stays high after dropping BufferedUarte

Disable ppi group in BufferedUarte drop

---

examples/.cargo/config.toml

Currently release builds of the examples don't report the location of defmt log lines:
```
0.000000 DEBUG rcc: Clocks { sys: Hertz(8000000), apb1: Hertz(8000000), apb1_tim: Hertz(8000000), apb2: Hertz(8000000), apb2_tim: Hertz(8000000), ahb1: Hertz(8000000) }
└─ <invalid location: defmt frame-index: 13>
0.000030 INFO Hello World!
└─ <invalid location: defmt frame-index: 5>
```
With this change, they log their location just like in debug:
```
0.000000 DEBUG rcc: Clocks { sys: Hertz(8000000), apb1: Hertz(8000000), apb1_tim: Hertz(8000000), apb2: Hertz(8000000), apb2_tim: Hertz(8000000), ahb1: Hertz(8000000) }
└─ [snipped]\...\embassy-clone\embassy\embassy-stm32\src\fmt.rs:125
0.000030 INFO Hello World!
└─ src\bin\blinky.rs:14
```

Add [profile.release] debug = true to all examples

---

embassy-net-w5500/Cargo.toml
embassy-net-w5500/README.md
embassy-net-w5500/src/device.rs
embassy-net-w5500/src/lib.rs
embassy-net-w5500/src/socket.rs
embassy-net-w5500/src/spi.rs
examples/rp/Cargo.toml
examples/rp/src/bin/ethernet_w5500_multisocket.rs
examples/rp/src/bin/ethernet_w5500_tcp_client.rs
examples/rp/src/bin/ethernet_w5500_tcp_server.rs
examples/rp/src/bin/ethernet_w5500_udp.rs

This merges https://github.com/embassy-rs/embassy-net-w5500 into the main repo.
Motivation: the cyw43 repo depends on embassy crates like embassy-rp, embassy-net. It's always somewhat behind and needs periodic work for updating it for breaking changes.
By integrating it into the main repo, the person doing the breaking changes is in charge of updating everything, so no more playing catch up.

Merge embassy-net-w5500 into main repo

---

embassy-sync/src/pipe.rs

Hello, old _try_write_with_context_ function only write minimum available size to pipe, some data will be lost from user.
It can workaround by user side base on return bytes from write(buf).await, but it's complex.
This patch will wait until all bytes are written to pipe.

sync/pipe: write all user data to pipe

---

embassy-net/src/tcp.rs

The `may_recv` function returned True when the socket was open, but had no pending data. The smoltcp `can_recv` function instead only returns True when there is pending data.

Added can_recv for TcpSocket

---

embassy-usb-logger/src/lib.rs

https://github.com/rust-lang/log/issues/567

usb-logger: fix breakage in log 0.4.19

---

examples/rp/src/bin/button.rs
examples/rp/src/bin/wifi_blinky.rs

I got a RP Pico W and wanted to verify it's function. The only easy output is a LED, but it has moved from the standard PR Pico. I also spent some time to discover how the button was connected, only to find that button.rs use a normal GPIO.
- Add rp/src/bin/wifi_blinky.rs for easy beginners start.
- Document external button.in rp/src/bin/button.rs.

Add wifi_blinky.rs for easy beginners start.

---

embassy-stm32/src/rcc/g4.rs
examples/stm32g4/Cargo.toml
examples/stm32g4/src/bin/pll.rs
examples/stm32g4/src/bin/usb_serial.rs

This PR adds onto https://github.com/embassy-rs/embassy/pull/1532 and I believe it completes https://github.com/embassy-rs/embassy/issues/1198 by supporting the rest of the PLL functionality. 
This also adds a USB Serial example for the G4 that uses the other PLL output to ensure it is working correctly. 
This has been tested on a custom STM32G473 board that I have.
@cstlaurent I made a few tweaks to the API you had created to add the other output configurations here. These changes align much closer with the API used for the H5 PLL config.

Feature/stm32g4 pll enhancements - Add PLL support for the P and Q outputs for G4 series chips

---

embassy-stm32/src/usart/buffered.rs

This fixes the main issue in #1556 on STM32F4 where the interrupt flags are not always cleared, leading to a continuous ISR loop. It does not address the potential race conditions:
1. The overflow interrupt can occur independently of RXNE, however on v1 we need to read DR to clear the OVE flag. A character could arrive after checking SR, but before reading DR to clear OVE. There is no way of disabling OVE without also disabling RXNE as they are both controlled by RXNEIE. 
2. The idle interrupt has a similar issue, although it can be disabled independently by IDLEIE. This allows us to disable the interrupt until the next character is received, which gets around the race condition, however in my testing this lead to worse performance in the typical use case (more overflows when receiving …

Ensure idle & ove flags are cleared in BufferedUart ISR on STM32

---

ci.sh
embassy-boot/boot/src/firmware_updater/asynch.rs
embassy-boot/boot/src/firmware_updater/blocking.rs
embassy-boot/boot/src/firmware_updater/mod.rs
embassy-boot/boot/src/lib.rs
examples/boot/application/nrf/Cargo.toml
examples/boot/application/nrf/src/bin/a.rs
examples/boot/application/rp/Cargo.toml
examples/boot/application/rp/src/bin/a.rs
examples/boot/application/stm32f3/Cargo.toml
examples/boot/application/stm32f3/src/bin/a.rs
examples/boot/application/stm32f7/Cargo.toml
examples/boot/application/stm32f7/src/bin/a.rs
examples/boot/application/stm32h7/Cargo.toml
examples/boot/application/stm32h7/src/bin/a.rs
examples/boot/application/stm32l0/Cargo.toml
examples/boot/application/stm32l0/src/bin/a.rs
examples/boot/application/stm32l1/Cargo.toml
examples/boot/application/stm32l1/src/bin/a.rs
examples/boot/application/stm32l4/Cargo.toml
examples/boot/application/stm32l4/src/bin/a.rs
examples/boot/application/stm32wl/Cargo.toml
examples/boot/application/stm32wl/src/bin/a.rs

Prevent accidental revert when using firmware updater
This change prevents accidentally overwriting the previous firmware before
the new one has been marked as booted.
Add firmware updater examples to CI
CI was not building the a.rs application due to the requirement of b.bin
having been built first. Add a feature flag to examples so that CI can
build them including a dummy application.
Update a.rs application examples so that they compile again.
I was tempted to give a go at adding the magic buffer to FirmwareUpdater type but decided against it for now and will probably raise a separate PR for that.

Prevent bootloader revert and add missing examples to CI

---

embassy-macros/Cargo.toml
embassy-macros/src/lib.rs
embassy-macros/src/macros/main.rs
embassy-macros/src/macros/task.rs
examples/nrf52840/src/bin/self_spawn.rs

This PR relaxes `pool_size` to allow arbitrary expressions. Unfortunately, this also means that the attribute now accepts arbitrary paths, meaning the attribute may cause compile errors not constructed by syn/darling/embassy (e.g. use of undeclared module, etc.).
The intent of this PR is to allow controlling both the pool size, and the length of some global resource array with the same constant.

Allow arbitrary expressions as `task(pool_size)`

---

embassy-rp/src/usb.rs
embassy-stm32/Cargo.toml
embassy-stm32/src/rcc/l0.rs
embassy-stm32/src/usb/usb.rs
embassy-stm32/src/usb_otg/usb.rs
embassy-sync/src/pipe.rs
examples/stm32f4/src/bin/usb_ethernet.rs
examples/stm32f4/src/bin/usb_serial.rs
examples/stm32f7/src/bin/usb_serial.rs
examples/stm32g4/src/bin/usb_serial.rs
examples/stm32h7/src/bin/usb_serial.rs
examples/stm32l4/src/bin/usb_serial.rs
examples/stm32u5/src/bin/usb_serial.rs

fixes #1365 
fixes #1442 
TODO:

stm32/otg: implement VBUS detection, misc fixes so plug/unplug works.

---

embassy-net/src/lib.rs

So, I don't actually know for a fact if this works, but since the constructor seems to only initialize arrays, I don't see a reason why not. CI shall tell us :)

Make StackResources::new() const

---

embassy-hal-common/src/peripheral.rs
embassy-stm32/src/dac/mod.rs

Otherwise you can create multiple drivers on the same singleton like this:
```rust
let mut input = Input::new(&pin, Pull::None);
let mut output = Output::new(&pin, Level::Low, Speed::Low);
input.is_high();
output.set_high();
input.is_high();
output.set_high();
```
Thanks @pennae for reporting.

hal-common: require DerefMut for peripherals, not just Deref.

---

embassy-stm32/src/fmc.rs

We only had support for 16-bit modules on bank 2.

Add stm32 FMC support for bank 1 16-bit RAM

---

embassy-nrf/src/spim.rs

I updated to the newest nightly today (yay, let else formatting!), but embassy-nrf stopped compiling. Apparently the compiler now cares about lifetime annotation in the SPIM embedded-hal-async trait implementations.
<details>
<summary>Error</summary>
```txt
error: `impl` item signature doesn't match `trait` item signature
--> /home/dion/.cargo/git/checkouts/embassy-9312dcb0ed774b29/99b4ea7/embassy-nrf/src/spim.rs:524:67
|
524 |           async fn transfer(&mut self, rx: &mut [u8], tx: &[u8]) -> Result<(), Error> {
|                                                                     ^^^^^^^^^^^^^^^^^ found `fn(&'1 mut spim::Spim<'d, T>, &'2 mut [u8], &'3 [u8]) -> impl futures::Future<Output = Result<(), spim::Error>>`
|
::: /home/dion/.cargo/registry/src/index.crates.io-6f17d22bba15001f/em …
```

Fix nrf spim nightly error

---

embassy-time/src/queue_generic.rs

`QUEUE_SIZE` is not correct if feature is `generic-queue-64`

time: fix queue size

---

embassy-stm32/build.rs
embassy-stm32/src/rcc/mod.rs

This allows the UB time-travel optimization to propagate clock frequencies.

stm32/rcc: allow const-propagation

---

embassy-stm32/src/usb_otg/usb.rs

It was implemented only for writes.

stm32/otg: implement `EndpointError::Disabled` for reads.

---

embassy-rp/src/adc.rs
embassy-rp/src/gpio.rs
examples/rp/src/bin/adc.rs
tests/rp/src/bin/adc.rs

- don't require an irq binding for blocking-only adc
- abstract adc pins into an AnyPin like interface, erasing the actual peripheral type at runtime.
- add pull-up/pull-down functions for adc pins
- add a test (mostly a copy of the example, to be honest)
- configure adc pads according to datasheet
- drop embedded-hal interfaces. embedded-hal channels can do neither AnyPin nor pullup/pulldown without encoding both into the type
incorporates #1286, which seems to cause no problems. should not interfere with other drivers because during pin drop we reset the IE/OD bits to defaults.

rp/adc: rewrite the module

---

embassy-stm32/src/rcc/h7.rs

The STM32H7 reference manual (RM0433) specifies PLL output frequency with these formulas:
`F_ref_ck = F_pll_src / DIVM`
`F_vco = F_ref_ck * DIVN`
`F_pll_p_ck = F_vco / (DIVP+1)`
... where `F_pll_p_ck` is the output of the PLL postdivider P.
Expanding this and solving for `F_vco`, we get:
`F_vco = F_pll_p_ck * (DIVP+1)`
i.e. `vco_ck = output * pll_x_p`
But the formula in the H7 RCC is incorrectly specified as `vco_ck = output + pll_x_p`.  Therefore asking for a PLL output frequency of 80 MHz causes `vco_ck` to be calculated as `80000005`, which is nonsense (you cannot actually realize a VCO frequency of 80000005 with only integer multipliers), and leads to a panic as `vco_ck` is out of range.
With this fix, asking for a PLL output frequency of 80 MHz with a PLL source clock of 16 MHz …

Correctly calculate target VCO frequency from multipliers

---

embassy-time/Cargo.toml

I'm using only the `embassy-time` crate in a `std` context and I found that it wouldn't link without this change. The link error I got is as such:
```
= note: /usr/bin/ld: /home/james/Repositories/ethercrab/target/debug/deps/libembassy_time-91c1a3c881edf7b5.rlib(embassy_time-91c1a3c881edf7b5.embassy_time.ac31f442-cgu.7.rcgu.o): in function `embassy_time::timer::schedule_wake':
/home/james/.cargo/registry/src/index.crates.io-6f17d22bba15001f/embassy-time-0.1.1/src/timer.rs:172: undefined reference to `_embassy_time_schedule_wake'
/usr/bin/ld: /home/james/Repositories/ethercrab/target/debug/deps/libembassy_time-91c1a3c881edf7b5.rlib(embassy_time-91c1a3c881edf7b5.embassy_time.ac31f442-cgu.11.rcgu.o): in function `critical_section::release': …
```

Enable `critical-section/std` when using `std` feature of `embassy-time`

---

embassy-rp/src/clocks.rs
embassy-rp/src/rtc/datetime_no_deps.rs
embassy-rp/src/rtc/mod.rs
embassy-rp/src/watchdog.rs
examples/rp/src/bin/rtc.rs

- RTC example.
- Remove start time from Rtc::new() for more flexibility.
- Not reset RTC in Clock::init().
- Rename to Rtc from RealTimeClock to match STM32 implementation.
- Add missing set_/get_scratchN to watchdog for reboot safe data.
- Add save/restore to RP2040 Rtc.

RP2040 Rtc update with example 

---

embassy-rp/src/usb.rs

I'm not sure if this is also needed elsewhere, but currently on rp2040 the device gets stuck if the usb suspends because Bus::poll will always yield Ready(Suspended)

rp: Check intrstatus before signalling suspended

---

embassy-stm32/src/rcc/wl.rs
embassy-stm32/src/rtc/v3.rs
examples/stm32wl/.cargo/config.toml
examples/stm32wl/Cargo.toml
examples/stm32wl/src/bin/rtc.rs

Sets up options and RCC clocks for STM32WL RTC module.
Adds rcc configuration option to enable the APB RTC enable.
Add rtc example for STM32WL
Corrects compiler in examples/stm32wl... this processor does not support hardware floating point.

Enable RTC on STM32WL chips

---

examples/rp/Cargo.toml
examples/rp/src/bin/usb_hid_keyboard.rs

This PR includes a port of the usb_hid_keyboard.rs example from the nrf52840, with several modifications. I've omitted the hardware VBUS detector implementation as it doesn't seem to be available in embassy-rp.
Also, the remote_wakeup functionality has been disabled due to issues encountered with bus resets following suspensions. This issue led to the disabling of remote_wakeup—though I'm currently unsure if this is an issue specific to the Pico, Windows, or my particular setup.
In its current state, the example waits for a high input signal on pin 16, and then simulates pressing the 'a' key until a low signal is detected. The dependency on usbd-hid in Cargo.toml is necessary for handling KeyBoard reports.

Add usb-hid keyboard example for rp pico.

---

embassy-net/src/lib.rs

While it is possible to configure both, IPv4 and IPv6, it isn't possible to use both at the same time because the IP address was always set as the first element

Make dual-stack work in embassy-net

---

embassy-stm32/src/usart/mod.rs

Add an option to swap RX and TX. Tested on STM32U575ZITx on a board with swapped tx/rx pins.

stm32/uart: add swap_rx_tx

---

embassy-rp/src/adc.rs

the adc constantly pulls a small but significant amount of current while the hardware is enabled. this can have quite an effect on sleeping devices that also use the adc.

rp: disable adc hardware on Adc drop

---

embassy-stm32/src/dac/mod.rs
examples/stm32f4/Cargo.toml
examples/stm32f4/src/bin/dac.rs
examples/stm32h7/src/bin/dac.rs
examples/stm32l4/src/bin/dac.rs

Currently the DAC examples don't work on F4 or L4, because the DAC driver defaults to enabling the trigger (useful for DMA) but doesn't set the trigger selection, so it's left at the reset value of 0 for `TIM6`. The examples then try to software trigger each new value, but as the DAC isn't configured for software trigger, nothing happens.
One option is to change the trigger selection from `TIM6` to `SOFTWARE`, but as this disables the channel you then have to re-enable it, and since we just trigger immediately after writing each word, it's more sensible to just disable the trigger.
On the H7, in _theory_ the example would work as-is, because the default value for the trigger selection is `SOFTWARE`. However, the PAC is wrong for the H7 and puts the trigger enable bit TEN into the trigger …

stm32: Fix DAC examples

---

embassy-stm32/Cargo.toml
embassy-stm32/src/dac/mod.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/sdmmc/mod.rs

Based on the PRs https://github.com/embassy-rs/embassy/pull/1676 and https://github.com/embassy-rs/embassy/pull/1677, this adds DAC v3 (available in stm32-metapac v13, https://github.com/embassy-rs/stm32-data/pull/223) for the STM32H7 and some others that previously had no support for DMA in the DAC implementation.

Add DAC v3

---

embassy-stm32/src/can/bxcan.rs
examples/stm32f4/src/bin/can.rs

This PR implements async enable for bxcan.
Using the default enable from bxcan library can lead to infinite loops if there is a hardware problem (i.e. canbus shorted to VCC, or faulty transceiver).
Unfortunatelly, bxcan seems to only have interrupt for entering sleep mode, but not for leaving (SLAK = 0) so I used `yield_now()`.

stm32/can: bxcan async enable

---

embassy-stm32/src/ipcc.rs
embassy-stm32/src/rcc/mod.rs
embassy-stm32/src/rcc/wb.rs
tests/stm32/src/bin/wpan_ble.rs
tests/stm32/src/bin/wpan_mac.rs

This moves the bulk of the rcc configuration out of the ipcc module, and also frontloads clock computation.

stm32/rcc: move rcc logic from ipcc

---

examples/nrf-rtos-trace/Cargo.toml
examples/nrf52840-rtic/Cargo.toml
examples/nrf52840/Cargo.toml
examples/nrf5340/Cargo.toml
examples/rp/Cargo.toml
examples/std/Cargo.toml
examples/stm32c0/Cargo.toml
examples/stm32f0/Cargo.toml
examples/stm32f1/Cargo.toml
examples/stm32f2/Cargo.toml
examples/stm32f3/Cargo.toml
examples/stm32f7/Cargo.toml
examples/stm32g0/Cargo.toml
examples/stm32g4/Cargo.toml
examples/stm32l0/Cargo.toml
examples/stm32l1/Cargo.toml
examples/stm32l4/Cargo.toml
examples/stm32l5/Cargo.toml
examples/stm32u5/Cargo.toml
examples/stm32wb/Cargo.toml
examples/stm32wl/Cargo.toml
examples/wasm/Cargo.toml

This makes rtt output work right when using `cargo run` in release mode.
Debug was already enabled for release builds in some of the examples but not all.

Added debug=2 in release profile to all examples.

---

embassy-lora/Cargo.toml
examples/nrf52840/Cargo.toml
examples/rp/Cargo.toml
examples/stm32l0/Cargo.toml
examples/stm32wl/Cargo.toml

Use lora-phy v1.2.1 rather than a patch.
Remove unnecessary dependencies for embassy-lora.
Place the embassy-lora dependency on rust-lorawan behind the time feature so that users of embassy-lora have the option to not pull in rust-lorawan.

Use lora-phy v1.2.1; modify embassy-lora dependencies

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/ringbuffer.rs

Add a STM32/DMARingBuffer::read_exact helper
This provides a helper function with an async implementation, that
will only return (or error) when it was able to read that many bytes,
sleeping until ready.
Additionally, corrected the documentation for Ringbuffer functions to use
"elements" instead of "bytes" as the types were already generic over the
word/element size.
This is in reference to #1604.
Adding this helper function is right on the edge of what felt acceptable to me to duplicate, rather than refactor. I'm fine with this being merged as is, but it feels like there's a better way and I'm just not experienced enough to know what is best, especially in a project other people develop and use.
<details>
<summary>Implementation Choices</summary>
I started down the path of refactoring …

Add a STM32/DMARingBuffer::read_exact helper

---

embassy-stm32/src/usart/mod.rs

I am 80% sure this is the right fix because it correctly outputs the frequency in most cases. However, I don't really understand this code completely at this point, so I may have go this wrong.

stm32/usart: fix error msg for lptim

---

embassy-rp/src/lib.rs
embassy-rp/src/multicore.rs

fix up an incorrectly placed bit in the stack guard mpu setup, and allow installing stack guards for core0 as well. that'll allow using dedicated sram for the core0 stack without losing overflow protection entirely.

Rp stack guards

---

embassy-stm32/src/can/bxcan.rs

- Implemented non-async `try_read`/`try_write` methods.
- Implemented `flush_all()`, `flush_any()` methods for waiting on TX mailbox state.
- Implemented `wait_for_data()` method for waiting on RX frames without removing them from queue.
- Reduced code duplication by using `CanRx`/`CanTx` methods in non-split `Can`.

stm32/can: implement more convenience methods

---

cyw43-pio/src/lib.rs
embassy-rp/src/lib.rs
embassy-rp/src/pio.rs
embassy-rp/src/relocate.rs
examples/rp/src/bin/pio_async.rs
examples/rp/src/bin/pio_dma.rs
examples/rp/src/bin/pio_hd44780.rs
examples/rp/src/bin/pio_uart.rs
examples/rp/src/bin/pio_ws2812.rs
tests/rp/src/bin/pio_irq.rs
tests/rp/src/bin/pio_multi_load.rs

this removed the RelocatedProgram construction step from pio uses. there's not all that much to be said for the extra step because the origin can be set on the input program itself, and the remaining information exposed by RelocatedProgram can be exposed from LoadedProgram instead (even though it's already available on the pio_asm programs, albeit perhaps less convenient). we do lose access to the relocated instruction iterator, but we also cannot think of anything this iterator would actually be useful for outside of program loading.

rp: relocate programs implicitly during load

---

embassy-boot/rp/src/lib.rs
embassy-rp/Cargo.toml
embassy-rp/src/flash.rs
examples/boot/application/rp/src/bin/a.rs
examples/rp/src/bin/flash.rs
tests/rp/src/bin/flash.rs

This adds an async mode to RP flash operations.  This mode requires a DMA channel but can utilize the background best effort read mechanism.  This mechanism avoids stalling actual code execution from XIP as well as avoiding filling the cache with flash data (that's going to RAM anyway).  Write and erase remain blocking, however.
See the [Pico SDK Example](https://github.com/raspberrypi/pico-examples/blob/master/flash/xip_stream/flash_xip_stream.c) and  section (2.6.3.4) of the manual.

rp: add async flash

---

embassy-stm32/src/i2c/timeout.rs

I don't love having another lifetime in the type signature but I needed this to be able to create a local TimeoutI2c within a function which operates on a passed in `&mut I2c<>`.
Another option would be to have `TimeoutI2c` own the `I2c` and fully wrap it, exposing all methods.

TimeoutI2c: allow ref to live shorter than peripheral

---

embassy-stm32/src/rcc/f2.rs

With a significant enough HSE input frequency, the VCO clock calculation will overflow a u32. Therefore, we must use the inner value and cast to u64 in this specific case to ensure the mul isn't clipped before applying the divider.
FYI the input source on my board is a 25mhz external crystal.

stm32f2 PLL overflow with crystal

---

embassy-stm32/src/rtc/v2.rs

Also ensure the pwr is enabled before trying to initialize. For the F2 series, this is in a separate clock control register which has to be enabled.

stm32f2: Avoid resetting RTC backup domain

---

embassy-stm32/src/i2s.rs
embassy-stm32/src/spi/mod.rs
examples/stm32f3/src/bin/spi_dma.rs
examples/stm32f4/src/bin/spi.rs
examples/stm32f4/src/bin/spi_dma.rs
examples/stm32g0/src/bin/spi_neopixel.rs
examples/stm32h7/src/bin/spi.rs
examples/stm32h7/src/bin/spi_dma.rs
examples/stm32l0/src/bin/lora_cad.rs
examples/stm32l0/src/bin/lora_lorawan.rs
examples/stm32l0/src/bin/lora_p2p_receive.rs
examples/stm32l0/src/bin/lora_p2p_send.rs
examples/stm32l0/src/bin/spi.rs
examples/stm32l1/src/bin/spi.rs
examples/stm32l4/src/bin/spi.rs
examples/stm32l4/src/bin/spi_blocking_async.rs
examples/stm32l4/src/bin/spi_dma.rs
tests/stm32/src/bin/spi.rs
tests/stm32/src/bin/spi_dma.rs

This will move stm32-spi frequency settings from function parameters to config, see #1682.
Tested on NUCLEO-F303K8, not tested for #[cfg(any(spi_v3, spi_v4, spi_v5))] variant.

Move frequency to SPI config

---

embassy-stm32/Cargo.toml
embassy-stm32/src/rng.rs
examples/stm32f4/src/bin/eth.rs
examples/stm32f4/src/bin/usb_ethernet.rs
examples/stm32f7/src/bin/eth.rs
examples/stm32h5/src/bin/eth.rs
examples/stm32h5/src/bin/rng.rs
examples/stm32h7/src/bin/eth.rs
examples/stm32h7/src/bin/eth_client.rs
examples/stm32h7/src/bin/rng.rs
examples/stm32l0/src/bin/lora_lorawan.rs
examples/stm32l4/src/bin/rng.rs
examples/stm32l5/src/bin/rng.rs
examples/stm32l5/src/bin/usb_ethernet.rs
examples/stm32wl/src/bin/lora_lorawan.rs
examples/stm32wl/src/bin/random.rs

- fix missing NVIC RNG interrupt enable
- add conditioning sequence for RNGs that support it
- add recovery from noise-source/seed error according to reference manual
- speed up polling of data by `await`ing only if there is no more data available
note: requires https://github.com/embassy-rs/stm32-data/pull/209

STM32: RNG update

---

examples/stm32h7/.cargo/config.toml

Accidently commited one file too many in  #1705 :/ Sorry.
This reverts part of commit 937a63ce28beee87ae78756ecf8377f465b8cf9d

Fix probe-rs chip type in stm32h7 example

---

ci.sh
cyw43/src/lib.rs
embassy-net-driver-channel/src/lib.rs
embassy-net-driver/Cargo.toml
embassy-net-driver/src/lib.rs
embassy-net-esp-hosted/src/lib.rs
embassy-net-w5500/src/lib.rs
embassy-net/src/lib.rs
embassy-stm32-wpan/src/mac/driver.rs
embassy-stm32/src/eth/mod.rs
embassy-usb/src/class/cdc_ncm/embassy_net.rs
examples/std/src/tuntap.rs

(I'm sorry for the PR-spam. I'm trying to get the "finished" things we have cleaned up, atomic and mergeable.)
This allows a net::Driver to be an IEEE802.15.4 device.
I wrote this in two stages.
1. Added `ieee802154_address()` to the trait
2. Merged `ethernet_address()` and `ieee802154_address` into `hardware_address()`.
This allows the community (mainly @Dirbaio, cc @xoviat) to decide which way is better. HardwareAddress means we have a bunch of match-statements at runtime, for a property that's typically known at compile time (but that's the case anyway with smoltcp, currently), but it's a lot more compact and future proof. It's a (big-ish) breaking change, however.
CI will probably complain, but I'll clean that up after a decision on the above is taken :-)

Expose IEEE802.15.4 address in Driver

---

embassy-net/Cargo.toml

The IEEE802.15.4 features weren't showing up on embassy.dev.

Enable IEEE802.15.4 doc building

---

embassy-stm32/src/rcc/l4.rs

According to the reference manual RM0394, section 5.1.4, Backup domain Access:
To make changes to the RTC registers, you first need to enable the power interface clock by setting the PWREN bits.
This is missing from the current code and the program will hang on while !RCC.csr().read().lsirdy() {} every time on my STM32L431.
Adding the line to set the bit fixes the issue.

LSE requires setting PWREN bit on STM32L4

---

ci.sh
ci_stable.sh
embassy-rp/Cargo.toml
embassy-rp/src/clocks.rs
embassy-rp/src/gpio.rs
embassy-rp/src/i2c.rs
embassy-rp/src/pio.rs
embassy-rp/src/pwm.rs
embassy-rp/src/spi.rs
embassy-rp/src/uart/mod.rs

qspi gpio interrupts simply would not have worked, at all. this alone has us suspect that nobody uses qspi pins for anything other than qspi, so we'll make the qspi gpio implementations optional as well to avoid the mostly-unnecessary overhead they come with. this does seem like much of a downside, anyone using qspi pins for gpio must already acknowledge this by using a different boot2 config.

rp: fix qspi gpio interrupts, make qspi gpio optional

---

embassy-stm32/src/i2c/timeout.rs
embassy-stm32/src/i2c/v2.rs

I think it's fine as is but there are two things I thought about:
1. Wrapping `async fn`s like this might create some bloat. I'm not sure what the best practice is, but this is simplest and I expect LTO to handle it.
2. These timeouts are currently only checked inside of busy-wait loops inside the I2C implementation. If it is waiting for a DMA transfer to complete, for example, the timeout expiry won't interrupt that. We could use something like [embassy_time::with_timeout](https://docs.embassy.dev/embassy-time/git/default/fn.with_timeout.html#) to stop polling when the timeout expires but I'm not sure if that would leave the peripheral in an invalid state or something.

stm32: add async timeout functions to I2c and TimeoutI2c

---

examples/stm32f334/Cargo.toml

Fixes this warning on `cargo update` etc:
warning: skipping duplicate package `embassy-stm32f3-examples` found at `/home/adam/.cargo/git/checkouts/embassy-9312dcb0ed774b29/a40daa9/examples/stm32f3`

Fix package name for stm32f334-examples

---

tests/rp/src/bin/adc.rs

GP29 is connected to the cyw43 SCK pin. cyw43 is selected by default (due to rp2040 pins being input/pulldown by default), so the wifi chip is always selected and watches the SCK pin. this little bit of load on the SCK pin is enough to disturb the 300k voltage divider used for VSYS sensing, making the test flaky.

rp: fix adc test flakiness

---

embassy-rp/src/clocks.rs

this is "generic" in that it doesn't require the user to set up anything specific to go to dormant sleep, unlike the C sdk which requires clock sources to be configured explicitly and doesn't much care about PLLs. we will instead take a snapshot of the current clock configuration, switch to a known clock source (very slow rosc, in this case), go to sleep, and on wakeup undo everything we've done (ensuring stability of PLLs and such).
tested locally, but adding tests to HIL seems infeasible. we'd need at least another pico or extensive modifications to teleprobe since dormant-sleep breaks SWD (except to rescue-dp), neither of which is feasible at this point. if we *did* want to add tests we should check for both rtc wakeups (with an external rtc clock source) and gpio wakeups.

rp: add generic dormant-sleep functionality

---

embassy-boot/boot/src/firmware_updater/asynch.rs
embassy-boot/boot/src/firmware_updater/blocking.rs
embassy-boot/boot/src/firmware_updater/mod.rs
embassy-boot/boot/src/lib.rs
embassy-boot/nrf/src/lib.rs
embassy-boot/rp/src/lib.rs
embassy-boot/stm32/src/lib.rs
examples/boot/application/nrf/src/bin/a.rs
examples/boot/application/rp/src/bin/a.rs
examples/boot/application/stm32f3/src/bin/a.rs
examples/boot/application/stm32f7/src/bin/a.rs
examples/boot/application/stm32h7/src/bin/a.rs
examples/boot/application/stm32l0/src/bin/a.rs
examples/boot/application/stm32l1/src/bin/a.rs
examples/boot/application/stm32l4/src/bin/a.rs
examples/boot/application/stm32wl/src/bin/a.rs

* Allow manipulating state without accessing DFU partition.
* Provide aligned buffer when creating updater to reduce potential wrong parameters passed.

Refactor firmware updater

---

embassy-usb-logger/src/lib.rs

This allows normal linux terminal emulators, like screen or picocom to be used with the usb_logger. Without this, calling `tcsetattr` with `TCSAFLUSH` will hang.

Make usb-logger read and discard input data

---

embassy-sync/src/channel.rs
embassy-sync/src/pipe.rs

See #1759 
This removes an implicit T: Copy bound on these types

embassy-sync: manual Copy impls for channel and pipe

---

embassy-stm32/src/gpio.rs

Following some discussion in Matrix after a very long debugging session today, I figured these notes might help others who are coming from firmware environments other than Embassy that treat pins as persistent across the lifetime of the firmware's execution (e.g. ST's own HAL layer in C/C++).

stm32: add note about Output/OutputOpenDrain drop behavior

---

embassy-time/src/timer.rs

The `Ticker` stream never stops yielding values and can thus be marked as fused. This makes it more versatile to use in situations where a fused stream is required (such as `select_biased!`), without having to resort to `StreamExt::fuse()`.

Mark `Ticker` stream as fused

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/ringbuffer.rs

this has less savings than the other pr, but does not impact performance in a way that the compiler can't optimize

stm32/dma: consolidate ringbuf

---

embassy-executor/CHANGELOG.md
embassy-executor/Cargo.toml

I think it's okay to have this as a point release, as it only seems to contain a bunch of fixes and a new API.

Executor: prepare 0.2.1 release

---

embassy-boot/nrf/src/lib.rs
embassy-boot/rp/src/lib.rs
embassy-boot/stm32/src/lib.rs
examples/boot/bootloader/nrf/src/main.rs
examples/boot/bootloader/rp/src/main.rs
examples/boot/bootloader/stm32/src/main.rs

This refactoring of the chip specific bootloader creates the internal boot instance and aligned buffer in the prepare stage, so that they are automatically dropped after. This unlocks a use case where peripherals owning the flash need to be Drop'ed before load() happens.

boot: release flash after prepare and refactor api

---

embassy-stm32/src/rcc/wl.rs

Seems the RTC clock source is never set for stm32-wl, and creating a new `Rtc` instance will hang (at least using LSI). This PR sets the RTC clock source similar as for stm32-wb.

stm32-wl: set RTC clock source on RCC init

---

embassy-stm32/src/rcc/l4.rs

Fixes https://github.com/embassy-rs/embassy/issues/1778

stm32l4: set pwren in rcc regardless of clock source

---

embassy-boot/rp/src/lib.rs
embassy-rp/src/flash.rs
examples/boot/application/rp/src/bin/a.rs
examples/rp/src/bin/flash.rs
tests/rp/src/bin/flash.rs

- Needed for consistency with other drivers.
- Having two `new()` functions sometimes resulted in 'multiple applicable methods' errors.

rp/flash: change naming to `blocking_*`, `new_blocking`.

---

embassy-usb/src/msos.rs

According to the [Microsoft documentation][1] the `RegMultiSz` value should be terminated by an empty UTF-16 string, i.e. 2 null bytes instead of only one.
This also matches what this [Google article][2] is doing.
It seems to be working regardless, at least for me, but it is probably best to follow the spec.
Beware though that this will make the descriptor one byte larger which can panic the `Builder` when supplied with a buffer that had exactly the required size before.
[1]: https://learn.microsoft.com/en-us/windows/win32/sysinfo/registry-value-types
[2]: https://developer.chrome.com/articles/build-for-webusb/

embassy-usb: Fixed the final null terminator for RegMultiSz.

---

embassy-net/src/tcp.rs
embassy-net/src/udp.rs

raw & icmp sockets are not supported in embassy_net, so those are missing here.

Forward capacity impls

---

embassy-stm32/src/timer/complementary_pwm.rs
embassy-stm32/src/timer/simple_pwm.rs

Setting the compare_value to max_compare_value make the PWM output go low when the timer reach the max_compare_value and go high again on the next timer clock, when the value roll back to 0.
So to allow a 100% PWM that never goes low, the compare_value must be set to max_compare_value + 1.

stm32: allow setting PWM duty cycle to 100%

---

embassy-stm32/Cargo.toml
embassy-stm32/src/flash/h7.rs
embassy-stm32/src/flash/mod.rs
embassy-stm32/src/rcc/h7.rs

Flash latency was being calculated and set based on requested clock, but before the clock was actually configured.
STM32H7A/B devices has slightly different FLASH peripheral.

configure flash latency after axi clock and  handle different flash on STM32H7A/B devices

---

embassy-net/src/tcp.rs

Translation of tpc client ConnectError and Error to the appropriate embedded_io_async errors
Closes #1801

Add error translation to tcp errors

---

embassy-stm32/src/usart/mod.rs

This saves me 620 bytes on my G0 CM0+ where I don't use any u64's anywhere.
I've tested the new calculation with this: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=d617401ffcb409b8bb0cb2f25567b453
It produces identical results compared to the old calculation (at least with the parameters in my test).

Modified the STM Uart baud calculation to be fully 32-bit

---

embassy-stm32-wpan/src/mac/driver.rs
embassy-stm32-wpan/src/mac/runner.rs
embassy-stm32/src/can/bxcan.rs
embassy-sync/src/channel.rs
examples/nrf52840/src/bin/channel.rs
examples/nrf52840/src/bin/channel_sender_receiver.rs
examples/nrf52840/src/bin/uart_split.rs
examples/rp/src/bin/lora_p2p_send_multicore.rs
examples/rp/src/bin/multicore.rs
examples/stm32f3/src/bin/button_events.rs
examples/stm32h5/src/bin/usart_split.rs
examples/stm32h7/src/bin/usart_split.rs
tests/rp/src/bin/gpio_multicore.rs
tests/rp/src/bin/multicore.rs

(Was "Expose `poll_ready_to_{send,receive}` in `Sender`/`Receiver`")
These are useful methods when manually writing Futures.
@lulf suggested on Matrix to also expose `try_{recv,send}_with_context` in `Receiver` and `Sender`, but those are private in `Channel`.

Refactor Channel/Sender/Receiver poll methods

---

ci.sh
embassy-executor/src/arch/cortex_m.rs

This warning snuck in with #1774 and went unnoticed since. The constant is not needed if `executor-thread` is not active, so we can just move it into the `thread` module.

Avoid dead code warning

---

embassy-stm32/src/rtc/datetime.rs
examples/stm32f4/src/bin/rtc.rs

The `day_of_week_from_u8` implementation for `stm32` expects a number 0-6 which represents Mon-Sun, the current implementation for converting `chrono::Weekday` to `DayOfWeek` uses the `chrono` function `number_from_monday` which returns 1-7 representing Mon-Sun. This causes the following error to be thrown on Sundays and every other day the weekday to be off-by-one.
```
called `Result::unwrap()` on an `Err` value: InvalidDayOfWeek(7)
```
Replace the `number_from_monday` function call with `num_days_from_monday` which returns the expected 0-6 representing Mon-Sun.
The example RTC code hangs on the line `let mut rtc = Rtc::new(p.RTC, RtcConfig::default());`.
Configure the RTC clock source to use `LSI`.

Fix DateTime Conversion and RTC Example

---

cyw43/src/consts.rs
cyw43/src/control.rs
cyw43/src/events.rs
cyw43/src/lib.rs

In its current state, this PR introduces separate up/down functions, which are just used internally for now. As well as introducing a function for leaving an infra.

cyw43: Add utility functions.

---

embassy-stm32/src/timer/mod.rs

A frequency of 0 is wrong, but it shouldn't hardfault.
Now we simply panic instead.

Stm32 timer prevent hardfault when frequency is 0

---

examples/boot/application/rp/src/bin/a.rs

Aligned buffer size should be equal to flash write size (1 instead of 4)

rp: Fix write size in embassy-boot example app

---

embassy-stm32/src/rcc/f4.rs
embassy-stm32/src/rcc/mod.rs
embassy-stm32/src/rcc/wb.rs
embassy-stm32/src/rtc/mod.rs
embassy-stm32/src/rtc/v2.rs
embassy-stm32/src/rtc/v3.rs

this adjusts the prescalers appropriately if the lsi or hse is used.

stm32/rtc: autocompute prescalers

---

embassy-net/src/device.rs
embassy-net/src/lib.rs
embassy-net/src/tcp.rs
embassy-sync/src/channel.rs
embassy-sync/src/mutex.rs
embassy-time/src/instant.rs
examples/boot/application/rp/Cargo.toml
examples/boot/application/stm32f3/Cargo.toml
examples/boot/application/stm32f7/Cargo.toml
examples/boot/application/stm32h7/Cargo.toml
examples/boot/application/stm32l0/Cargo.toml
examples/boot/application/stm32l1/Cargo.toml
examples/boot/application/stm32l4/Cargo.toml
examples/boot/application/stm32wl/Cargo.toml
examples/boot/bootloader/nrf/Cargo.toml
examples/boot/bootloader/stm32/Cargo.toml

This PR tries to avoid including panic strings in the binary by preferring defmt::unwrap if available.

embassy-{net, sync, time}: Use fmt::unwrap

---

ci.sh
embassy-stm32/build.rs
embassy-stm32/src/i2c/v1.rs
embassy-stm32/src/i2c/v2.rs
embassy-stm32/src/spi/mod.rs
embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs
embassy-stm32/src/usart/ringbuffered.rs

This appears to work as designed, but the peripherals may currently leak refcounts. That will need to be examined before this can  be merged.

stm32: refcount peripheral enable/disable

---

embassy-stm32/Cargo.toml
embassy-stm32/src/adc/mod.rs
embassy-stm32/src/adc/v3.rs
embassy-stm32/src/rcc/wl.rs

Waiting for https://github.com/embassy-rs/stm32-data/pull/246.
Will also remove the use of adccommon_v3 CCR register for STM32G0x. Since the CCR register definition for this device seems to have some bits/names swapped (VBATEN/TSEN) compared to the common one.

ADC support for STM32WLx

---

embassy-net/src/lib.rs
examples/stm32f4/src/bin/eth.rs
examples/stm32f7/src/bin/eth.rs
examples/stm32h5/src/bin/eth.rs
examples/stm32h7/src/bin/eth.rs
examples/stm32h7/src/bin/eth_client.rs

This PR adds a function `wait_config_up` to the embassy_net `Stack`.
It will check whether `is_config_up` is true and if not register a waker that is woken in `apply_static_config` (e.g. by DHCP).
I added a not-working example to the docstring. Not sure whether we can make this run somehow.

embassy-net: add async wait_config_up

---

embassy-nrf/src/spim.rs

This implements SPIM TX workaround suggested from section 3.8.1 from Anomaly 109 addendum.
In workaround case we first keep track of original maxcnt values, then initiate "fake" transfer with zero-length maxcnt values. Once the "fake" transfer is triggered, we handle it, fill in the original maxcnt values and restart the transmission.

nrf: spim: Anomaly 109 workaround for SPIM peripheral (#460)

---

embassy-nrf/src/spim.rs
embassy-nrf/src/spis.rs
embassy-nrf/src/temp.rs
embassy-nrf/src/twim.rs

We can call SetConfig's set_config internally reducing code duplication and possibly reduce hard-to-detect issues with device reconfiguration in the future.

nrf: Use SetConfig trait internally where possible

---

examples/rp/src/bin/pio_ws2812.rs

The example spins too fast so it doesn't appear to change; it's delaying for microseconds instead of milliseconds. This commit slows it down and adds a comment noting the pin mapping for the Adafruit feather rp2040+RFM95 LoRA module, which has its Neopixel on pin 4 instead of 16.

Fix timing on RP2040 pio_ws2812.rs example

---

embassy-time/src/timer.rs

This PR attempts to allow resetting the Ticker in embassy-time. This could prove useful for the implementation of some network protocols, which require precise timing alignments.

embassy-time: Introduce reset function for Ticker.

---

embassy-lora/src/iv.rs

Handle rp2040-based LoRa boards in the same manner as LoRa boards for other MCUs with regard to detecting an IRQ on the DIO1 pin - wait for high rather than rising edge.
This is PR is a result of analysis within the following issue:
https://github.com/embassy-rs/lora-phy/issues/27.

Wait for high for DIO1 for rp2040-based LoRa boards

---

embassy-stm32/src/usart/mod.rs

When use `RartRx::read_until_idle` to read from uart, sometime it can't wake up. 
**Reason**:  while `abort` future is polling which is triggered by idle interrupt , at the same time the next data is start transferring, the `sr.idle()` return false, and the `abort` future still return `Poll::Pending` state, so it can't be wake up anymore.
**Solution**: Always enable idle interrupt when poll `abort` future

stm32/usart: fix read_until_idle not wake up issue

---

embassy-nrf/src/gpiote.rs

So when the nRF chip wakes up from systemoff sleep from a port event, it the `events_port` will be set. However, embassy currently resets this register on init before any interrupt.
This is a problem because the latch bits will be set and embassy puts the gpio in LDETECT mode. This means that  `events_port` is cleared while DETECT is high. If a new pin gets its DETECT signal, it won't trigger the  `events_port` because it seems that only happens on the overall DETECT signal. This means no new GPIOTE interrupt is triggered and input will not be captured.
TLDR: If we don't clear  `events_port`, then it will be picked up by the GPIOTE interrupt handler and be cleared there.

Fix gpiote when waking up from systemoff

---

embassy-executor/src/arch/wasm.rs
embassy-executor/src/raw/mod.rs
embassy-executor/src/raw/util.rs

In programs that contain large future objects, for example those which declare large buffers as locals in async functions:
```rust
async fn run() -> Result<(), RunError> {
let mut rx_meta = [PacketMetadata::EMPTY; 16];
let mut rx_buffer = [0; 4096];
let mut tx_meta = [PacketMetadata::EMPTY; 16];
let mut tx_buffer = [0; 4096];
// ...
```
`TaskPool::spawn_impl` can in some cases use an enormous amount of stack to instantiate the future into a `TaskStorage`:
```sh-session
$ cargo build --release
Compiling embassy-executor v0.3.0 (/home/hailey/code/embassy/embassy-executor)
Compiling bark-esp v0.1.0 (/home/hailey/code/bark-esp)
Finished release [optimized + debuginfo] target(s) in 1.36s
$ stack-usage target/xtensa-esp32-none-elf/release/bark-esp
FUNCTION …
```

Write to TaskStorage::future via never-inlined fn to encourage RVO

---

ci.sh
embassy-stm32/src/rcc/wb.rs

because the rtc code was not run in this case, the backup domain was not reset, which contaminated the HIL test.

stm32: fix  wpan_ble test

---

examples/stm32wb/src/bin/eddystone_beacon.rs
examples/stm32wb/src/bin/gatt_server.rs
examples/stm32wb/src/bin/tl_mbox.rs
examples/stm32wb/src/bin/tl_mbox_ble.rs

The combined bluetooth and mac firmware should work everywhere, and also resolved an issue I was having trying to run the examples.

Update stm32wb examples to use ble/mac firmware.

---

embassy-stm32/Cargo.toml
embassy-stm32/src/rcc/bus.rs
embassy-stm32/src/rcc/c0.rs
embassy-stm32/src/rcc/f1.rs
embassy-stm32/src/rcc/f2.rs
embassy-stm32/src/rcc/g0.rs
embassy-stm32/src/rcc/g4.rs
embassy-stm32/src/rcc/h5.rs
embassy-stm32/src/rcc/h7.rs
embassy-stm32/src/rcc/l0.rs
embassy-stm32/src/rcc/l1.rs
embassy-stm32/src/rcc/l4.rs
embassy-stm32/src/rcc/l5.rs
embassy-stm32/src/rcc/u5.rs
embassy-stm32/src/rcc/wb.rs
embassy-stm32/src/rcc/wl.rs
examples/stm32f2/src/bin/pll.rs
examples/stm32h5/src/bin/eth.rs
examples/stm32h5/src/bin/usb_serial.rs

this may require the addition of enums in metapac.

stm32/rcc: convert bus prescalers to pac enums

---

embassy-stm32/src/spi/mod.rs
embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs
embassy-stm32/src/usart/ringbuffered.rs

Allows the uart to be reconfigured after initialization.

stm32: Implement `set_config` for Uart structs

---

embassy-stm32/src/rcc/f2.rs

According to [RM0033](https://www.st.com/resource/en/reference_manual/rm0033-stm32f205xx-stm32f207xx-stm32f215xx-and-stm32f217xx-advanced-armbased-32bit-mcus-stmicroelectronics.pdf), the top voltage range goes to 3.6 V instead of 4.6 V. I also adjusted the wording to match the table headers (with regards to the unit "V"):

stm32/f2: Fix typo in RCC voltage range docs

---

embassy-stm32/src/exti.rs

This seems straightforward. Not sure if the method was left out intentionally.

stm32/exti: Add get_level() to ExtiInput

---

embassy-nrf/Cargo.toml
embassy-nrf/src/spim.rs

On nRF52832, a workaround is used to avoid corruption of SPIM DMA transfers (anomaly 109). Because the logic setting up the real transfers was in the interrupt handler, naive executors that just poll (like  `embassy_futures::block_on`) would resolve without making (or starting) the transfer.
Move the workaround code from the interrupt handler to a `poll_fn` so that the it runs regardless of whether the event was detected through polling or by the interrupt handler triggering the waker.

spim: Fix nRF52832 SPIM with polling executors

---

examples/stm32f4/src/bin/rtc.rs

lsi must be enabled otherwise a assertion fails

stm32: fix rtc example

---

embassy-lora/Cargo.toml
examples/nrf52840/Cargo.toml
examples/nrf52840/src/bin/lora_cad.rs
examples/nrf52840/src/bin/lora_lorawan.rs
examples/nrf52840/src/bin/lora_p2p_receive.rs
examples/nrf52840/src/bin/lora_p2p_receive_duty_cycle.rs
examples/nrf52840/src/bin/lora_p2p_send.rs
examples/rp/Cargo.toml
examples/rp/src/bin/lora_lorawan.rs
examples/rp/src/bin/lora_p2p_receive.rs
examples/rp/src/bin/lora_p2p_send.rs
examples/rp/src/bin/lora_p2p_send_multicore.rs
examples/stm32l0/Cargo.toml
examples/stm32l0/src/bin/lora_cad.rs
examples/stm32l0/src/bin/lora_lorawan.rs
examples/stm32l0/src/bin/lora_p2p_receive.rs
examples/stm32l0/src/bin/lora_p2p_send.rs
examples/stm32wl/Cargo.toml
examples/stm32wl/src/bin/lora_lorawan.rs
examples/stm32wl/src/bin/lora_p2p_receive.rs
examples/stm32wl/src/bin/lora_p2p_send.rs

Update rust-lorawan and embassy to use lora-phy version 2.  This includes the latest released version of embedded-hal-async.

Update rust-lorawan and embassy to use lora-phy version 2

---

embassy-stm32/src/usart/mod.rs
tests/stm32/src/bin/usart.rs

Without this, it seems flushing returns earlier than it should?

stm32/usart: enable fifo mode on usartv4.

---

embassy-stm32/src/adc/f1.rs
embassy-stm32/src/adc/f3.rs
embassy-stm32/src/adc/mod.rs
embassy-stm32/src/adc/v1.rs
embassy-stm32/src/adc/v2.rs
examples/stm32f0/src/bin/adc.rs
examples/stm32f1/src/bin/adc.rs
examples/stm32f4/src/bin/adc.rs
examples/stm32f7/src/bin/adc.rs

stm32: more adc cleanup

---

embassy-stm32/src/rcc/f7.rs
embassy-stm32/src/rcc/mod.rs

Re-implemented RTC configuration for `STM32F7` boards, based on code for `F4` boards.
PR for issue #1957

Restore RTC configuration for `STM32F7` boards

---

embassy-net-enc28j60/src/lib.rs

Title. Changes the `receive` method on the enc28j60 to return the size of the packet rather than a mutable slice of the packet itself.

enc28j60: return packet length from receive() instead of mut slice

---

embassy-stm32/src/timer/mod.rs

This PR adds support for the input capture filter.

Add support for STM32 input capture filter

---

embassy-stm32/src/timer/mod.rs

Writing examples found I forgot to copy two methods into the 32 bit general purpose instance.

Forgot set_count_direction and set_clock_division in 32 bit instance

---

embassy-net-enc28j60/src/lib.rs

Title. Just a little getter to avoid having to wrap the struct in a tuple or something when implementing application-specific traits.

enc28j60: expose a the MAC address via `address()` getter

---

embassy-stm32/src/timer/mod.rs

Reverts embassy-rs/embassy#1969
This was unfortunately wrong, and later tests I wrote showed it. 
The 32 bit trait inherits from the 16 bit trait in this case, so it doesn't need these functions (and adding them makes it ambiguous).

Revert "Forgot set_count_direction and set_clock_division in 32 bit instance"

---

examples/wasm/README.md

noticed an errant "s" in the wasm/http example

fix typo / update wasm example

---

embassy-stm32/src/timer/mod.rs

There are currently inconsistencies between the trait inheritance of the sealed traits
and what they implement.
In particular, the CaptureCompare32BitInstance trait does not require the CaptureCompare16BitInstance trait,
however, all 32 bit counts implement both traits. As they have overlapping functions, this causes
disambiguation issues when you try to use any 32 bit timers.
This is exacerbated by the fact that all channel pins implement CaptureCompare16BitInstance, whether the pins
belong to a 32 bit timer or not.
There are two ways to fix this:
1. Cleanly separate the traits, remove the 16 bit capture traits from 32bit capture timers,
create a set of traits for 32 bit capture pins, and modify the build script to generate 32 bit pin
traits for 32 bit pins.
This requires duplicating …

Fix trait inconsistency between sealed traits and implementations

---

embassy-rp/src/gpio.rs
examples/rp/src/bin/usb_hid_keyboard.rs

Allows the schmitt, slew and drive strength to be set from Flex. Input and Output[OpenDrain] also expose the appropriate setters.

feat (rp2040): allow schmitt, slew, and drive strength be set from Flex, Input, Output

---

embassy-stm32/src/rng.rs

Most stm32 are little endian. The code in `rng.rs` was converting the generated `u32`s to big_endian before using their bytes. This is not needed.
I did some ad hoc measurement of the speed of `async_fill_bytes`and saw a small but measurable improvement.

stm32: avoid useless endian conversion in rng

---

embassy-stm32/build.rs
embassy-stm32/src/qspi/enums.rs
embassy-stm32/src/qspi/mod.rs

This PR supports using QSPI bank 2 on stm32 by introducing a second constructor that accepts the pins implementing the BK2 traits.
It does not yet allow for using both banks, but at least you can use bank 2 for now, e.g., if BK1 pins are used by another peripheral or so.
Further, a "precautionary step" according to the STM32H7 errata sheet is added. It looks very odd, but it is what the recommended "workaround" looks like. Hope it avoids some unwanted surprises in the future.

[STM32] QUADSPI support bank 2

---

embassy-usb/src/class/cdc_acm.rs

This allows an async wait for changes in dts for example.

Add a signal for when the CDC control state changes

---

embassy-rp/src/gpio.rs
embassy-rp/src/uart/buffered.rs
tests/stm32/src/bin/dac.rs

They're heavily spamming logs for HIL tests, and I don't believe they're valuable now that the thing they helped debug in their young age is now solid and mature.

Remove a few ultra-verbose logs.

---

embassy-stm32/src/gpio.rs

Pins in open-drain mode are outputs and inputs simultaneously.

stm32/gpio: Implement `eh1::digital::InputPin` for `OutputOpenDrain`

---

embassy-stm32/src/rcc/u5.rs
examples/stm32u5/src/bin/usb_serial.rs

This commit allows STM32U5 devices to operate at 160 MHz.
On STM32U5, MSIS can run at 48 MHz and HSE can reach 50 MHz. Faster clocks require using PLL1's R output, though PLL1 can serve other functions besides using the R output for the system clock. This commit extracts a public `PllConfig` struct, primarily to place associated constructors on that type, but also with an eye towards enabling the P and Q outputs in a later commit.
STM32U5 PLLs have various frequency requirements on each stage: after the `m` prescaler, after the `n` multiplier, and after the `r` divider. This commit implements the associated checks as assertions.
This commit fixes clock calculation and PLL register configuration errors in PLL initialization.
STM32U5 has a PWR peripheral which can be configured to push …

stm32: u5: implement >55 MHz clock speeds

---

embassy-rp/src/bootsel.rs
embassy-rp/src/flash.rs
embassy-rp/src/lib.rs
tests/rp/src/bin/bootsel.rs

This module adds support for polling the BOOTSEL button found on the Pi Pico and most other rp2040 boards.
~~It's theoretically possible to create a fully safe interface, but it would be quite invasive (it needs to consume and wrap all DMA channels, CORE1 and FLASH). I don't think it's worth the effort.~~

rp2040: BOOTSEL button support

---

embassy-embedded-hal/src/flash/partition/mod.rs
embassy-rp/src/i2c.rs
embassy-rp/src/i2c_slave.rs
embassy-stm32/src/dac/mod.rs
embassy-stm32/src/i2c/mod.rs
embassy-stm32/src/rng.rs
embassy-stm32/src/sai/mod.rs
embassy-stm32/src/spi/mod.rs
examples/stm32h7/src/bin/camera.rs
examples/stm32l4/src/bin/spe_adin1110_http_server.rs

I did a search for `enum Error`, and added `PartialEq, Eq` where it was missing. You could maybe also make an argument for adding `Clone`, open to thoughts!

Add some uncontroversial derives to Error types

---

embassy-stm32/src/eth/generic_smi.rs
embassy-stm32/src/eth/mod.rs
embassy-stm32/src/eth/v1/mod.rs
embassy-stm32/src/eth/v2/mod.rs
examples/stm32f4/src/bin/eth.rs
examples/stm32f7/src/bin/eth.rs
examples/stm32h5/src/bin/eth.rs
examples/stm32h7/src/bin/eth.rs
examples/stm32h7/src/bin/eth_client.rs
tests/stm32/src/bin/eth.rs

Previously, PHY addressing was a concern of the `Ethernet` struct which limited the `PHY` implementations which very often have to manage multiple PHYs internally and thus possibly need to address many of them.
This change extends `StationManagement` to allow addressing different PHY addresses via SMI.

stm32/eth: Move `phy_addr` from `Ethernet` to `PHY`

---

embassy-rp/src/i2c.rs
embassy-rp/src/i2c_slave.rs

The RP2040 datasheet indicates that I2C pins should have a limited slew rate (Page 440 - 4.3.1.3.). This configures that for both `I2c` and `I2cSlave`.
In addition, the pin configuration has been centralized to a single fn.

fix (rp i2c): set i2c slew rate to spec value

---

embassy-rp/src/i2c.rs

Update the start and stop flags for all read/write/read_write methods to match those in the default blocking implementation of these methods (as well as other RP2040 I2C implementations, and expected I2C behavior).
Flags used correctly elsewhere: https://github.com/embassy-rs/embassy/blob/022d870d616575805ace9b37ea87bae1fd90cb84/embassy-rp/src/i2c.rs#L561
rp-rs implementation: https://github.com/rp-rs/rp-hal/blob/c4d3fa882acc5b19269d20ff74f65f1e53e81ee9/rp2040-hal/src/i2c/controller.rs#L313
Also adds a write_read_async method that doesn't require using embedded-hal, as this is required to use I2C in an idiomatic fashion (see TI Application Report [SLVA704](https://www.ti.com/lit/an/slva704/slva704.pdf)).

fix (rp i2c): fix restart/stop flags for i2c master methods

---

embassy-stm32/src/rcc/bd.rs

stm32/rcc: LSE xtal is 32768hz, not 32000hz.

---

embassy-hal-internal/src/interrupt.rs
embassy-hal-internal/src/macros.rs
embassy-stm32/build.rs
embassy-stm32/src/dac/mod.rs
embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/dmamux.rs
embassy-stm32/src/dma/gpdma.rs
embassy-stm32/src/dma/mod.rs
embassy-stm32/src/exti.rs
embassy-stm32/src/gpio.rs
embassy-stm32/src/lib.rs
embassy-stm32/src/rcc/mod.rs
embassy-stm32/src/time_driver.rs

Saves 292 bytes on stm32f0 bilnky with max optimizations (from 3132 to 2840).
depends on #2035

Avoid creating many tiny critical sections in embassy-stm32::init

---

embassy-stm32/src/spi/mod.rs
embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs
embassy-stm32/src/usart/ringbuffered.rs

https://github.com/embassy-rs/embassy/pull/1984 removed this, which meant that you had to import embassy-hal-common into your project to use these methods.

make set_config concrete methods public again

---

embassy-net/src/lib.rs

The query is transmitted on the next `Stack::poll` which may or may not be happening in a timely manner. This PR is an attempt to fix this delay.

Wake Stack's polling task after queueing a DNS query

---

embassy-usb/build.rs
embassy-usb/src/builder.rs
embassy-usb/src/class/cdc_acm.rs
embassy-usb/src/class/cdc_ncm/mod.rs
embassy-usb/src/class/hid.rs
embassy-usb/src/class/midi.rs
embassy-usb/src/control.rs
embassy-usb/src/descriptor.rs
embassy-usb/src/descriptor_reader.rs
embassy-usb/src/lib.rs
embassy-usb/src/msos.rs
embassy-usb/src/types.rs

Just a constification of this one function I think I need in a const context. Plus a whole load of clippy fixes. The earlier commit is just normal clippy, the later one contains more pedantic fixes, some of them really do improve the quality IMHO, but you be the judge and let me know.

Constify UsbDevice Config::new (and clippy fixes) in embassy-usb

---

embassy-rp/src/pwm.rs

Adds comments to the PWM config type summarizing the information provided in the [RP2040 datasheet](https://datasheets.raspberrypi.com/rp2040/rp2040-datasheet.pdf) - **4.5. PWM**

Add docs to RP2040 PWM config

---

examples/nrf52840-rtic/memory.x
examples/nrf52840/memory.x

Existing comment were outdated. Provide an example configuration for using the softdevice with the nRF52 examples.
Fixes #2079

docs: add linker script comments

---

embassy-net/src/lib.rs

Previously, because DHCP DISCOVER is sent before the link is established, socket has to timeout first. Which takes extra 10 s.
Now if the state of the link changed to up, socket is explicitly reset so the DISCOVER is repeated much earlier and DHCP configuration is acquired much faster.

net: Reset DHCP socket when the link up is detected

---

embassy-stm32/src/usart/buffered.rs
embassy-stm32/src/usart/mod.rs
embassy-stm32/src/usart/ringbuffered.rs

* `CR1` `UE` must be false when setting word length and parity bits.
* use `type ConfigError = ConfigError` instead of `type ConfigError = ()`
* In mod.rs there is `fn configure()` which uses write to set `CR1`. This disables `RXNEIE` and `IDLEIE` in `CR1` and those must be re-enabled again. Otherwise receive does not work anymore.
https://github.com/embassy-rs/embassy/blob/ca27590afac33019dbc81489117b33fd7e3063a5/embassy-stm32/src/usart/mod.rs#L998-L999
vs
https://github.com/embassy-rs/embassy/blob/ca27590afac33019dbc81489117b33fd7e3063a5/embassy-stm32/src/usart/buffered.rs#L236-L237
Edit: `usart_v4` is correct.
Tested with stm32g081 by reconfiguring baudrate, parity and stop bits.

Fix stm32 uart set_config

---

embassy-stm32/src/rtc/datetime.rs

Unsure if this is true for other chips, but for the stm32f2 RTC, the weekday units field is between `0b001` and `0b111`.
Always fun to find a bug that only happens on a Sunday :upside_down_face:.

stm32: RTC fix DoW range off-by-one error

---

embassy-time/Cargo.toml
embassy-time/src/driver_mock.rs
embassy-time/src/lib.rs

This PR adds a new driver to embassy-time that exposes an API to manually advance the time.
The goal is to be able to use this driver to test code that works with `Instant` and `Duration`. I think if support for `Timer` functionality is needed, people would probably be well served with the driver provided by the `std` feature.

time: add `MockDriver` for testing purposes

---

embassy-embedded-hal/src/lib.rs
embassy-lora/src/lib.rs
embassy-net/src/lib.rs
embassy-nrf/src/lib.rs
embassy-rp/src/lib.rs
embassy-stm32/src/lib.rs
embassy-sync/src/lib.rs
examples/std/src/bin/net_ppp.rs

Unfortunately, Xtensa (ESP32) needs to use a forked compiler. This compiler follows the 6-week release schedule of stable rustc, but with nightly features enabled. This means, for us it would be best if the feature gates could be kept until the feature hits stable rust, so we could benefit of the latest embassy changes, too.

Re-add impl_trait_projections

---

embassy-time/src/driver_mock.rs

When I implemented this I used the std driver as a reference, but now I realize that the implementation of `now()`should use `as_ticks()` instead of `as_micros()`.

time: fix MockDriver::now()

---

embassy-stm32/Cargo.toml
embassy-stm32/src/rcc/l4l5.rs

The rcc::Config adc_clock_source was removed from the STM32WL when the rcc/wl.rs was consolidated into rcc/l4l5.rs. This field was omitted from the rcc::Config on the other family members covered in rcc/l4l5.rs. This brings the field and supporting enums back into rcc::Config.
Changes per discussion with dirbiao in matrix channel.

Reinstate rcc::Config adc_clock_source field

---

embassy-net-adin1110/Cargo.toml

<https://github.com/dbrgn/embedded-hal-mock/pull/86> was merged and released into `0.10.0-rc.1` :tada:

embedded-hal-mock: git -> 0.10.0-rc.1

---

embassy-stm32/src/low_power.rs
embassy-stm32/src/time_driver.rs

This begins to explain the intended operation of the low-power executor.

stm32: Add some documentation to `low_power`

---

examples/stm32f4/src/bin/usb_raw.rs

I based this off the usb_cdc example and just changed it to implement some control transfer handling directly. However, the host-to-device transfers start at byte 4 of the data the host sent, and then have 4 junk bytes at the end.
The bug must be in the embassy-stm32 usb_otg driver, as this example works OK on G4 (which is the plain usb driver).

Add raw USB example using control transfers

---

embassy-stm32/build.rs
embassy-stm32/src/opamp.rs
examples/stm32f334/src/bin/opamp.rs

On G4, unlike F3, the opamps have a mode to route the output to an ADC channel instead of to a pin, so you can sample them with the ADC without "wasting" a pin if you don't otherwise need the output signal on your board. This PR adds support for this functionality, along with a new `OpAmpInternalOutput` type which implements `AdcPin` as appropriate.
I've tested this on a G431 and it configures the opamp and lets me read it correctly with the ADC.
Unlike  the existing `OpAmpOutput`, the new `OpAmpInternalOutput` _doesn't_ hold on to the pin used to construct it. I'm not sure what the objective is with holding on to the pin. On the one hand, it stops the user later reconfiguring the pin as an output or alt function or something. However, that also stops the user using this pin with other …

stm32: support internal output on g4 opamps

---

embassy-stm32/build.rs
embassy-stm32/src/fmc.rs

This PR fixes a typo in the build.rs file that caused the FMC ClkPin to not be implemented (was `Clk`, changed to `CLK`) and adds a basic "raw" implementation for the `Fmc` struct so one gets access to the Rcc `enable_and_reset()` function.
Essentially it makes it a little more convenient to manually configure FMC for purposes that are either not implemented by stm32-fmc or where the FMC peripheral is used for other things like reading an ADC by exposing the `enable()` function.

STM32: Add raw access to FMC peripheral and fix typo in build.rs

---

embassy-stm32/src/rcc/f4f7.rs
embassy-stm32/src/usb_otg/usb.rs
embassy-usb/src/lib.rs

- usb: reject instead of panic on CONTROL OUT longer than the buf.
- stm32/rcc: set highest VOS on some F4s with no overdrive.
- stm32/otg: log TRDT
- stm32/otg: fix CONTROL OUT transfers on F4.

stm32/otg: fix CONTROL OUT transfers on F4.

---

embassy-stm32/src/rcc/f4f7.rs

this is a tiny fix after commit [stm32/rcc: set highest VOS on some F4s with no overdrive.](https://github.com/embassy-rs/embassy/commit/b8679c0cc85e5eb65bd996ee18deac4a952b1b10)
VOS can be set when use PLL (depending on target speed) on any chips, not only the chips without over-drive.

check PLL settings before set VOS

---

embassy-net/CHANGELOG.md
embassy-net/src/tcp.rs

`embedded_io_async::Read` should return immediately if its output buffer can't hold any data. The easiest way to ensure that is to handle the case at `TcpIo`'s level, changing its semantics a bit, but probably for the better.

Ensure TcpIo not blocking when reading into empty slice

---

embassy-usb-logger/Cargo.toml
embassy-usb-logger/src/lib.rs
examples/rp/Cargo.toml
examples/rp/src/bin/pio_uart.rs
examples/rp/src/bin/usb_ethernet.rs
examples/rp/src/bin/usb_hid_keyboard.rs
examples/rp/src/bin/usb_midi.rs
examples/rp/src/bin/usb_raw.rs
examples/rp/src/bin/usb_serial.rs

Added the msos-descriptor feature to the examples to allow WinUSB support.
This also led to having to add this feature to embassy-usb-logger aswell.

rp: Add USB raw example + msos-descriptor to examples and usb-logger

---

embassy-stm32/src/dma/gpdma.rs

See e.g. STM32H503 RM section 15.4.4.
1. Write 1 into GPDMA_CxCR.SUSP
2. Poll GPDMA_CxSR.SUSPF until it is 1
3. Write 1 into GPDMA_CxCR.RESET
This fixes #2171 for me - instead of hanging forever, my UART read fails with a framing error (as it should!)
This *should* be the correct behaviour in any instance where a GPDMA transfer needs to be aborted.
Old behaviour step by step:
1. Reset all bits on CxCR except relevant interrupt enables.
This has the effect of writing 0 to EN, RESET and SUSP. Writing 0 to EN and RESET has no effect, per RM. Writing 0 to SUSP resumes the channel if it was already suspended (irrelevant in this case).
2. Poll TCF, waiting for it to be set
This is fine if one expects the transfer to proceed, but that may not be the case, and if Transfer is being dropped, the …

stm32/gpdma: fix drop() to use documented method for aborting transfer

---

embassy-net/CHANGELOG.md
embassy-net/Cargo.toml
embassy-net/src/dns.rs
embassy-net/src/lib.rs

Not sure if this is a good fix perse, but it allows for extending DNS setting in `smoltcp` up to 8 entries. 
If this is not done these interfaces are hard linked to whatever the return of `smoltcp` is.
Other ways to achieve this is welcome. :)

Fix for embassy net dns entries not being extensible

---

cyw43/src/control.rs
cyw43/src/lib.rs

Notably, a method to remove addresses is missing. I can add this if wanted but I ran out of time for now.
In reference to #2176.

cyw43: Add Control method to add multicast HW address

---

embassy-stm32/src/i2c/v2.rs

Recently timeouts were added to STM32 I2C API but unfortunately after that inorder to use any async I2C API user must always opt in for `feature "time"` even if user wanted to use async API without timeouts.
Many people are using `embassy-stm32` with RTIC executor which has its own Monotonic time implementation and they might not want to opt in additional timer (using `feature "time"`), but still would like to use async I2C API (but without timeout support).
This PR exposes following methods even if `feature "time"` is not used:
```rust
pub async fn write(&mut self, address: u8, write: &[u8]) -> Result<(), Error>
pub async fn write_vectored(&mut self, address: u8, write: &[&[u8]]) -> Result<(), Error>
pub async fn read(&mut self, address: u8, buffer: &mut [u8]) -> Result<(), Error>
pub …
```

STM32 I2C: expose async API without needing "time" feature.

---

ci.sh
embassy-net/src/lib.rs

I think the code hidden behind the `igmp` feature got left behind in #2076 where `medium` was added to `DriverAdapter`.
This PR fixes errors like:
```
error[E0063]: missing field `medium` in initializer of `DriverAdapter<'_, '_, _>`
--> src/lib.rs:619:31
|
619 |             let mut smoldev = DriverAdapter {
|                               ^^^^^^^^^^^^^ missing `medium`
error[E0063]: missing field `medium` in initializer of `DriverAdapter<'_, '_, _>`
--> src/lib.rs:656:31
|
656 |             let mut smoldev = DriverAdapter {
|                               ^^^^^^^^^^^^^ missing `medium`
For more information about this error, try `rustc --explain E0063`.
error: could not compile `embassy-net` (lib) due to 2 previous errors
```

populate `medium` in DriverAdapter struct in IGMP code

---

embassy-stm32/src/rcc/h.rs

Naive fix to clock source of ADC on STM32H7 (issue #2167)
In a nutshell, the default configuration for the v4 ADC selects clock source `ADCSEL[1:0]=0`. For the H5, that might be fine, but for the H7, that selects `PLL2_P` which is not configured. Using `ADCSEL[1:0]=2` selects the peripheral clock, which happens to be acceptable.
I hope to get advice on rust side of how to do this better.
- I just hard coded the value `2`. Note, the original hard coded `0` so I don't feel that bad.
- The mechanism to vary H7 from H5 (conditional compilation) is probably not done the way it should be
- I'm not sure the H7 and H5 are the only micros that use the v4 ADC.  If not, I've certainly done this wrong and should use something like `#[cfg(!stm32h7)]` if there is such a syntax
- I don't even know if …

stm32h7 ADC: Fix stalled clock in default h7 config

---

embassy-sync/README.md
embassy-sync/src/channel.rs
embassy-sync/src/channel/priority.rs
embassy-sync/src/lib.rs
embassy-sync/src/priority_channel.rs

Adds a priority channel which will sift higher priority items to the front of the channel.
- Is it okay to use heapless items in the public API? I'm currently using `Kind`, `Min` and `Max` from heapless publicly.
- Can the duplication between the normal channels be reduced further?
- More tests? I don't want to end up duplicating the tests within `heapless::BinaryHeap`, but if you have other test case ideas let me know I'll add them.

Priority channel

---

embassy-stm32/src/opamp.rs
examples/stm32f334/src/bin/opamp.rs

Previously we enabled the opamp as soon as `new()` is called, but for all supported use cases the user has to then call `buffer_int` or `buffer_ext` (which also set the relevant enable bit).
However, that means if someone is going to call `buffer_int`, the opamp is briefly enabled in external output mode, where its output drives a pin, until it's configured for internal mode. This glitch could potentially cause issues if that pin is being used for something else.
You can't do anything with the opamp object even if it's enabled, except manually use the PAC to configure it in ways we don't support - in which case you can also manually use the PAC to enable it.

STM32: Don't enable opamps in new(), wait until configured

---

.github/ci/build-stable.sh
.github/ci/build.sh

- Removes the slow "updating crates.io index, updating git" at start of the job.
- Avoids CI being randomly slower if a widely-used dep (like serde) gets bumped causing rebuilding everything.

ci: cache lockfiles

---

embassy-stm32/src/i2c/v2.rs

`embedded-hal-async` works without needing `time`.

stm32 i2c: allow EHA traits without time feature

---

embassy-stm32/Cargo.toml
embassy-stm32/build.rs
embassy-stm32/src/i2c/mod.rs
embassy-stm32/src/i2c/v1.rs
embassy-stm32/src/i2c/v2.rs
examples/stm32f4/src/bin/i2c.rs
examples/stm32f4/src/bin/i2c_async.rs
examples/stm32f4/src/bin/i2c_comparison.rs
examples/stm32h5/src/bin/i2c.rs
examples/stm32h7/src/bin/camera.rs
examples/stm32h7/src/bin/i2c.rs
examples/stm32l4/src/bin/i2c.rs
examples/stm32l4/src/bin/i2c_blocking_async.rs
examples/stm32l4/src/bin/i2c_dma.rs
examples/stm32l4/src/bin/spe_adin1110_http_server.rs

- Implemented async `write`, `read`, and `write_read` methods for v1 I2C
- minimal usage example i2c_async
- Benchmarking and comparison example in i2c_comparison, with parallel async transactions taking half the time as equivalent blocking transactions:
There are still some TODO comments and things that I’m uncertain about, and the code would definitely benefit from thorough review from people who have more experience working with STM32s and/or have been writing async rust for longer than a week.
Fixes #620

Implemented async I2C for v1

---

embassy-stm32/Cargo.toml
embassy-stm32/build.rs
embassy-stm32/src/dac/mod.rs
embassy-stm32/src/dac/tsel.rs
embassy-stm32/src/rcc/f3.rs
examples/stm32f4/src/bin/dac.rs
examples/stm32h7/src/bin/dac.rs
examples/stm32h7/src/bin/dac_dma.rs
examples/stm32l4/src/bin/dac.rs
examples/stm32l4/src/bin/dac_dma.rs
tests/stm32/src/bin/dac.rs

To be considered alongside https://github.com/embassy-rs/stm32-data/pull/306
The current trigger selection is wrong for almost all STM32s and needlessly splits into TSEL1/2 even though no chips make a distinction based on channel (!). However, there is significant difference in the TSEL enum between chips, so it's very burdensome to define it in the PAC. The PAC PR above reworks DAC support to improve accuracy and compatibility between all STM32s, and changes TSEL to always take an integer instead of an enum.
This PR adds an enum of trigger sources for every STM32, accurate except for where triggers differ between DAC1/2 and where triggers can be remapped in SYSCFG (indicated with doc comments), and updates the current driver to use it.
There's a few other changes:
* The existing `mode: …

STM32 DAC: update to new PAC, combine ch1/ch2, fix trigger selection

---

embassy-nrf/src/chips/nrf52805.rs
embassy-nrf/src/chips/nrf52810.rs
embassy-nrf/src/chips/nrf52811.rs
embassy-nrf/src/chips/nrf52820.rs
embassy-nrf/src/chips/nrf52832.rs
embassy-nrf/src/chips/nrf52833.rs
embassy-nrf/src/chips/nrf52840.rs
embassy-nrf/src/lib.rs

The APPROTECT stuff involving the Config debug field was not working correctly for chips other than nRF52840.  As noted in the page linked in the comment in lib.rs, different chip types have different minimum build codes when the APPROTECT improvements were made.  The old code used 'F' for everything, but that's valid only for 52840.

minimum build code for new APPROTECT is chip type-specific

---

embassy-stm32/src/lib.rs
embassy-stm32/src/uid.rs

Based on #1253 but updated to use the now-available UID peripheral from stm32-metapac.
I'm not 100% sure if it's nicer to return the `&'static` references or just return directly a `[u8; 12]` and `[u8; 24]`; we can avoid the critical section and all the unsafe code if we just return arrays, but it wastes a bit of stack. For the `&str`, I don't see any other way, and I guess a major use case will be passing this to the USB serial number, so perhaps it's worth keeping as-is.
I added the `LOADED` check to prevent needing a critical section and computation loop on every call of `uid_hex()`/`uid_hex_bytes()`, but probably the most common case is to only call it once, in which case the memory and load/store is wasted, so I could remove it.
Tested only on stm32g4 hardware.

STM32: Add UID driver

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/basic_application.adoc
docs/modules/ROOT/pages/delaying_a_task.adoc
docs/modules/ROOT/pages/getting_started.adoc
docs/modules/ROOT/pages/index.adoc

New: delaying_a_task.adoc, copied as-is from the wiki and placed in the navigation until we have a better place for it (or remove/replace it)
index: Tweaked the structure, added some content from the wiki, and made some general copy edits to improve clarity.
getting_started.adoc: Corrected various out-of-date information, added troubleshooting tips from the wiki, added some new information, various other small edits.
basic_application.adoc: Corrected out-of-date information, various clarifications and edits.
After these changes, IMO most of the content on the github wiki is no longer necessary and can be removed for clarity. The few sections I didn‘t integrate or copy over were either out of date or unfinished.

Moved content from the wiki to the docs

---

examples/stm32h7/src/bin/eth.rs
examples/stm32h7/src/bin/eth_client.rs

This PR fixes the STM32H7 Ethernet examples.
The examples enable `dhcpv4` and `dns` features. Both use one socket, meaning that we need one extra socket for our firmware TCP socket.

stm32/h7: fix h7 examples

---

embassy-stm32/Cargo.toml
embassy-stm32/build.rs
embassy-stm32/src/adc/f1.rs
embassy-stm32/src/adc/f3_v1_1.rs
embassy-stm32/src/adc/mod.rs
embassy-stm32/src/adc/resolution.rs
embassy-stm32/src/adc/sample_time.rs
embassy-stm32/src/can/mod.rs
embassy-stm32/src/rcc/g4.rs
embassy-stm32/src/rcc/mod.rs
tests/stm32/Cargo.toml
tests/stm32/src/bin/dac_l1.rs
tests/stm32/src/common.rs

Adds support for the f3_v1_1, it seems to be different enough to the regular f3 to warrant its own file but I can try to merge it with the adc/f3.rs if deemed necessary.
Depends on https://github.com/embassy-rs/stm32-data/pull/309 but I haven't included the updated stm32-metapac tag.
I'm happy to take any notes, it's my first contribution to embassy so I'm still working through the style.

stm32: add ADC f3_v1_1

---

docs/modules/ROOT/pages/faq.adoc

If we want the smallest binary, we probably want codegen-units = 1, and disable incremental builds.

Tweak FAQ size profile suggestions

---

embassy-hal-internal/src/atomic_ring_buffer.rs
embassy-hal-internal/src/drop.rs
embassy-hal-internal/src/lib.rs
embassy-hal-internal/src/macros.rs
embassy-hal-internal/src/peripheral.rs
embassy-hal-internal/src/ratio.rs

* Make some fields and functions non-public where possible.
* Enable doc warnings for missing public API docs.

docs: document all public apis of embedded-hal-internal

---

embassy-boot/boot/src/boot_loader.rs

Some basic comments to deal with #2279.
Ideally it would be nice to have some documentation for `memory.x` as well, but this seems all to be target-specific (nrf vs pico vs stm).

embassy-boot: Add explanation to dfu vs active size assertion

---

embassy-stm32/src/rcc/h.rs

This PR addresses clock setup related issues for MCUs with a maximum clock rate of more than 480MHz. Closes #2291.
- Allow PLL1 DIVP of 1.
- Adapted frequency limits.
- Adapter flash latency and programming delay.
The maximum allowed clock frequency is now 520MHz. It will be increased to 550MHz when the CPU frequency boost feature is implemented.

[embassy-stm32]: Fixes for STM32H7 series MCUs referenced in RM0468

---

embassy-stm32/src/qspi/mod.rs

The `new_bk1` should probably use `Flash1` not `Flash2`.

STM32 QSPI: Fix flash selection.

---

embassy-stm32/src/flash/f0.rs
embassy-stm32/src/flash/f3.rs
embassy-stm32/src/flash/f4.rs
embassy-stm32/src/flash/f7.rs
embassy-stm32/src/flash/g.rs
embassy-stm32/src/flash/h7.rs
embassy-stm32/src/flash/l.rs
embassy-stm32/src/flash/mod.rs

I checked the G4 RM and the required operations match up with what's already done for G0, so I combined the two. It seems like there's probably quite a lot of crossover with other families too, but I didn't attempt a refactor.
Many G4 devices have dual flash banks, but as far as I can tell the current stm32-data only knows about single banks for G4. By default, G4s with dual banks have the DBANK bit reset, so they can be treated as having one large bank, so I believe everything should work until someone wants to actually use the dual banks. At the moment I only have a single-bank G4 to test with so I can't find out for sure. I'll leave adding dual bank registers and HAL support for G4 to someone else...
I have tested this successfully on an STM32G431CB.

STM32: Enable flash support for STM32G4

---

embassy-stm32/src/time_driver.rs
embassy-time/src/driver.rs

Detect potential race condition (should be rare) and return false back to caller, allowing them to handle the possibility that either the alarm was never set because it was in the past (old meaning of false), or that in fact the alarm was set and may have fired within the race window (new meaning of false). In either case, the caller needs to make sure the callback got called.

STM32: Fix race in alarm setting, which impacted scheduling.

---

embassy-nrf/Cargo.toml
embassy-nrf/src/qspi.rs

I gated this behind a feature since I'm not sure it can be supported by all kinds of flash connected to qspi.

feat: support multiwrite flash traits if configured

---

embassy-stm32/src/can/bxcan.rs

- stm32/can: cleanup interrupt traits.
- stm32/can: docs.

stm32/can: docs, cleanup interrupt handling.y

---

embassy-stm32/src/rtc/mod.rs

STM32 RTC does store year as last two digits of a year and is 2000 year based, not 1970 unix time start.
Having the offset set right is important for the calendar to properly handle leap years.
With 1970 base setting the RTC time to 2024-02-28 23:59:59 and waiting one sec does make it jump to 2024-03-01 23:59:50 with is wrong because 2024 is a leap year.
With 2000 base it works correctly and doesn't skip 02-29.
Tested on STM32F401

fix stm32 rtc year from 1970 base 2000 to make leap years work

---

docs/modules/ROOT/pages/faq.adoc

Since the last release, esp-hal provides executors for both Xtensa and RISC-V SoCs. This means the FAQ should recommend esp-hal for all ESP32 users.

FAQ: Remove Xtensa specifier

---

embassy-stm32/src/rtc/mod.rs

This was accidentally made private during the doc updates.

stm32: make time provider public again

---

embassy-stm32/src/usb/usb.rs

stm32: USB IN endpoints use IN wakers

---

embassy-stm32/src/lib.rs

Apparently the dbg_stop bits etc keep the value true over a reset. This means when it is set to true once you have to power off the mcu to reset it to false. I was able to reproduce this on my NUCLEO-L552ZE-Q.
With this PR when setting config.enable_debug_during_sleep to false it sets the dbg_stop bits etc. to false.

dbgmcu: set bits to false when disabled

---

embassy-stm32/src/rtc/mod.rs
embassy-stm32/src/rtc/v3.rs

This PR adds support for the low-power executor for the STM32L5 series. I tested this with a NUCLEO-L552ZE-Q board.
This PR depends on this PR in stm32-data: embassy-rs/stm32-data#325

Add low-power support for stm32l5

---

embassy-stm32/src/i2c/v1.rs

This seems to help with my hanging problem, though I'm unsure if this
is the "right" solution.
If it is, it is possible we should do this in more places, since interrupts seem to usually disable themselves after firing.

STM32: Re-enable I2Cv1 Interrupts if poll-fn is not ready

---

embassy-stm32/src/i2c/v1.rs

Adds an in-code breadcrumb for https://github.com/embassy-rs/embassy/issues/2372

stm32: Add breadcrumb to i2cv1 investigation

---

embassy-nrf/src/buffered_uarte.rs

This was likely forgotten as part of c46418f12. Without this, when creating a uarte instance, dropping it and then creating another instance, this instance would never receive any bytes.
Please note that I've not yet understood the whole uarte interrupt machinery in it's entirety, but only made this change based on "pattern matching" and the observation that `rx_started` is not reset otherwise. I have observed tested that this change makes the "enable -> disable -> enable" use case work again after c46418f12 in my project, though. Maybe @Dirbaio as the author of c46418f12 can review this?

Reset rx_started state of nrf buffered_uarte on init

---

embassy-executor-macros/src/macros/task.rs
embassy-executor/tests/test.rs

Extend the task macro to allow cfging arguments away

---

README.md
docs/modules/ROOT/pages/index.adoc

This PR fixes the LoRa section of the README (typo introduced in https://github.com/embassy-rs/embassy/commit/d7eb067b4c63bf8a8e9d986f032cd8013f7cdca2). 
It also updates the docs so that the section [here](https://embassy.dev/book/dev/index.html#_lora) is up to date.

Fix LoRa-related links in README and docs

---

embassy-stm32/Cargo.toml
embassy-stm32/src/lib.rs
embassy-stm32/src/low_power.rs
examples/stm32l5/Cargo.toml
examples/stm32l5/src/bin/stop.rs

This PR adds support for the low-power modes STOP1 and STOP2. 
In this image enable_debug_during_sleep is true (by default) and the power-consumption is around 700uA. This is already better than normal because of the sleep mode.
In this image enable_debug_during_sleep is set to false and the power-consumption is much lower (170uA). The blinky example has a pretty high interval (300ms). With a lower interval I tested a power-consumption of ~12uA (no wakeup in this measurement). With an interval of 1s I measured around 50uA (active led uses 60uA).

low-power: add stop support for stm32l5

---

embassy-stm32/build.rs
embassy-stm32/src/rcc/g0.rs
embassy-stm32/src/rcc/mod.rs

Many clocks in the G0 were not listed nor configurable, this resulted in the PWM frequency calculation being wrong, amongst other things.

Add Missing Clocks on G0 to `Clocks`

---

embassy-net/src/tcp.rs

ref: #1890 
This PR aims to implement `embedded_io_async::ReadReady` and `embedded_io_async::WriteReady` traits for `TcpSocket` as well as `TcpReader`/`TcpWriter`
I saw there are already existing fns ( `may_recv()` and `may_send()` ) which are basically the same, so I just wrapped them in trait impl ( like it is done for other traits )
Though, traits expects to return an `Error` ( whenever there is io error ), but implementation of `may_recv()` or `may_send()` return a `bool` instead of `Result<>`! please let me know if something else was expected here!
Thank you :smile:

impl ReadReady and WriteReady for tcp

---

embassy-nrf/src/spim.rs
embassy-nrf/src/spis.rs

This PR introduces `new_tx_nosck` function to create new SPI(S|M) driver, without SCK pin.
related to #2345

add new_tx_nosck for nrf

---

embassy-stm32/src/rcc/u5.rs
examples/stm32u5/src/bin/usb_serial.rs

This MR adds support for setting the P and Q dividers in the STM32 U5 RCC. This is used when setting the SAI clock.

Update STM32 RCC U5 to support P and Q dividers

---

embassy-nrf/src/qspi.rs

Being able to modify this is important especially when running the interface at higher frequencies. In my case stuff got glitchy at a frequency of 32MHz which makes sense considering the default rx_delay is 2/64Mhz = 1/32MHz.
Regarding the implementation I was not sure if it would be better to add an additional enum for the config value (since valid values are between 0 and 7) or if this would be overkill. So far I went with an u8 and documented the valid value range in a comment, but we can of course change that.

Expose rx_delay in nrf qspi config

---

embassy-stm32/src/rcc/g0.rs
examples/stm32g0/.cargo/config.toml
examples/stm32g0/Cargo.toml
examples/stm32g0/src/bin/usb_serial.rs

This wires up the USB clock in STM32G0 RCC, with that done USB can be used on the models that support it.  It also adds a version of USB-serial example using the CRS.
Tested on a custom board with a STM32G0B1CBT6.

stm32: Add G0 USB RCC and example

---

embassy-boot/boot/src/firmware_updater/asynch.rs

I run into this issue when using async firmware updater on rp2040. Because READ_SIZE is 4 and WRITE_SIZE is 1 the aligned buffer of 1 is insufficient causing the flash subsystem to return an error.

boot: Take maximum of READ_SIZE and WRITE_SIZE when checking sizes, fixes #2382

---

embassy-usb/src/class/cdc_acm.rs

Just a tiny addition to the docs after I spent way too long to get `read_packet` to work with a too small buffer

Add buffer size info to read_packet docs

---

docs/modules/ROOT/examples/layer-by-layer/blinky-hal/src/main.rs
embassy-nrf/src/gpio.rs
embassy-nrf/src/gpiote.rs
embassy-rp/src/gpio.rs
embassy-stm32/src/exti.rs
embassy-stm32/src/gpio.rs
embassy-time/CHANGELOG.md
examples/rp/src/bin/button.rs
examples/stm32c0/src/bin/button.rs
examples/stm32f3/src/bin/button.rs
examples/stm32f4/src/bin/button.rs
examples/stm32f7/src/bin/button.rs
examples/stm32g0/src/bin/button.rs
examples/stm32g4/src/bin/button.rs
examples/stm32l0/src/bin/button.rs
examples/stm32l4/src/bin/button.rs
examples/stm32l4/src/bin/spe_adin1110_http_server.rs
examples/stm32l4/src/bin/spi_blocking_async.rs
examples/stm32l4/src/bin/spi_dma.rs
examples/stm32wl/src/bin/button.rs
tests/rp/src/bin/gpio.rs
tests/rp/src/bin/pwm.rs
tests/stm32/src/bin/gpio.rs

With the embedded-hal rc3 update I changed them to require `&mut self`, but
in retrospect I think `&self` is better, for extra flexibility.
This PR reverts the changes from the rc3 update to inherent methods.

Change GPIO inherent methods back to `&self`.

---

docs/modules/ROOT/nav.adoc
docs/modules/ROOT/pages/sharing_peripherals.adoc
examples/rp/src/bin/blinky_two_tasks.rs

I'm very new to embassy and am enjoying it very much. This PR contains a small example showcasing how to share a pin between two tasks. I took me some time to figure it out so I figure it may be useful to another beginner in the future. Please let me know if the global `Mutex<Option<PeripheralRef<AnyPin>>>` type is the idiomatic way to do it, as well as if something else can be improved.

Add example of pin sharing between tasks

---

.github/ci/test.sh
ci.sh
embassy-time/src/driver.rs
embassy-time/src/driver_mock.rs
embassy-time/src/queue.rs
embassy-time/src/queue_generic.rs

Fixes #2412.
I think the most contentious change is utilising `MockDriver` in the tests inside `queue_generic.rs`, but it seemed a shame not to.

Extend mock time driver to support alarms

---

ci.sh
embassy-nrf/README.md
examples/nrf9160/.cargo/config.toml
examples/nrf9160/Cargo.toml
examples/nrf9160/build.rs
examples/nrf9160/memory.x
examples/nrf9160/src/bin/blinky.rs

It occurred to me we don't have nrf91 example. The nrf91 example assumes the SPM module (for instance installed using https://github.com/tweedegolf/nrf9160-rust-starter/). Not sure where to best explain that?

Embassy nrf docs and nrf91 example

---

embassy-stm32/src/usb/usb.rs
examples/stm32l1/Cargo.toml
examples/stm32l1/src/bin/usb_serial.rs

the USB implementation didn't enable the internal USB Pull-Up of the L1s.
Additional setting the Alternate Functions messes up USB and it doesn't work anymore.
PR disables the setting for the L1s buuuuut now warnings are generated and I don't know how to fix them :pleading_face:

changes to get usb working on a L1. Adds a usb_serial example too

---

embassy-stm32-wpan/Cargo.toml

Reverts embassy-rs/embassy#2457
https://github.com/OueslatiGhaith/stm32wb-hci/issues/8 got fixed and the regression yanked, worth seeing if CI is still green.

Revert "stm32-wpan: Pin dep to work around regression"

---

embassy-rp/src/uart/mod.rs

This adds a function called "read_to_break" that receives until one of the following happen:
1. We receive the whole buffer amount
2. We receive a line break interrupt
In the latter case, we figure out how many bytes we DID get, and then return that subslice. In the former case, we return the whole subslice.
All other errors are returned the same.
One note:
This is basically a big copy/paste of `read`. I should probably clean that up, I could do the DMA reg check in a function that basically does:
```rust
pub async fn read_to_break<'a>(&mut self, buf: &'a mut [u8]) -> Result<&'a mut [u8], Error> {
match self.read(buf) {
Ok(()) => Ok(buf),
Err(Break) => {
// get bytes received...
Ok(&mut buf[..count])
}
Err(e) => Err(e)
}
}
```
But then we'd have to unwrap `self.rx_dma` again, which is …

Add a basic RP "read to break" function

---

cyw43/src/structs.rs

Taken from the Infineon WHD repository:
https://github.com/Infineon/wifi-host-driver/blob/04ee318cc96bffa7d69a1e076c008e2364453f82/WiFi_Host_Driver/inc/whd_types.h#L814
FYI I seem to be getting sound values for RSSI and noise, but the SNR field is always zero for some reason.

Add more fields to the BssInfo packet struct

---

ci.sh

The ci pipeline is currently not compiling stm32l5 with the low-power feature activated like for the stm32l0 for example. I was wondering why the ci tests were still successful for #2368 even though the registers are not merged in stm32-data (embassy-rs/stm32-data#325). This should change it and only make embassy compile for stm32l5 with the low-power feature when the registers are merged in stm32-data.

ci: add low-power feature for stm32l5

---

embassy-stm32/src/adc/resolution.rs

Useful for generating ADC lookup tables at compile time

Make adc::Resolution::to_max_count const

---

embassy-stm32/src/timer/simple_pwm.rs

To use two channels in complementary mode, e.g. to drive a buzzer, a combination of mode PWM1 and PWM2 is necessary.

stm32/simple_pwm: add set_output_compare_mode

---

cyw43/Cargo.toml
cyw43/src/control.rs
cyw43/src/events.rs
examples/rp/src/bin/wifi_scan.rs

I have extended the scan APIs. I followed the mentioned reference implementation.
It is not tested though and it would be very kind if someone could before merging, my debug probe hasn't arrived yet.

feat: Extended the Scan API

---

embassy-stm32/src/usart/buffered.rs

`usart_v4` uses internal FIFO and therefore actually all bytes are not yet sent out although `state.tx_buf.is_empty()`.
Code to demonstrate the problem:
```rust
let t = Mono::now();
pin.set_high();
rs485_tx.write_all(&tx_data).await.ok();
rs485_tx.flush().await.ok();
pin.set_low();
let diff = (Mono::now() - t).to_micros();
defmt::info!("tx {} us", diff);
```
Here red line shows `pin`. So `flush` finishes although in reality 9 bytes were not yet sent out from the FIFO.
With this patch `flush` finishes right after TX is done.
Page 1008:
7. Write the data to send in the `USART_TDR` register. Repeat this for each data to be transmitted in case of single buffer.
* When FIFO mode is disabled, writing a data to the `USART_TDR` clears the `TXE` flag.
* When FIFO mode is enabled, writing a data to …

stm32: fix buffered uart flush

---

examples/rp/src/bin/pio_i2s.rs

This is an example for generating audio in real-time and playing it back through an i2s DAC.
Note that the double buffered dma transfer assumes that `pio::StateMachineTx::dma_push` does immediately start the dma transfer and that polling the returned future is only required to wait for the transfer to finish. I hope this is a safe assumption.

add pio_i2s example for RP2040

---

docs/modules/ROOT/pages/getting_started.adoc

There was a little mistake in the formatting on the Getting Started page of the docs. This is just a quick fix to what I think the intended markup was.

Fix the backticks on the getting started page

---

embassy-nrf/src/pwm.rs

So it can be used outside of the crate to calculate max duty

use constant for the pwm clock

---

embassy-nrf/src/spim.rs
embassy-nrf/src/spis.rs

Add bit order to the Spim and Spis drivers.

nrf/spi: add bit order config

---

examples/std/README.md

The previous given command `nc -l 8000` doesn't let me see anything and lead to a "WARN connect error: ConnectionReset". By explicitly changing the `local-port` of `nc` with the `-p` I can now see the `Hello` message printed, and the warning log disappeared.

fix: typo in netcat command for std example

---

embassy-nrf/src/pwm.rs

1) implement retriving the current duty
2) Do not wait for seqend if the pwm is disabled, because then an infinity loop occurs
I will finish implementing my driver (Driving a Buzzer) to see if I have more improvements

PWM Improvements

---

embassy-rp/src/uart/mod.rs

This fixes #2490.
In rare cases the line break can be triggered without any data having been read which causes both `next_addr` and `sval` to be the same value. Subtracting 1 and `sval` from `next_addr` causes an underflow panic in debug mode and  a high chance of panic in release mode when the user uses the returned `usize::Max` value to try and index their data

Fix underflow in embassy-rp uartrx.read_to_break

---

docs/modules/ROOT/pages/faq.adoc

These aren't *amazing* docs, but they are better than none, and are lightly edited from comments today in chat.

[FAQ]: Add some comments from chat

---

embassy-stm32/build.rs
embassy-stm32/src/timer/complementary_pwm.rs
embassy-stm32/src/timer/mod.rs
embassy-stm32/src/timer/simple_pwm.rs
examples/stm32f4/src/bin/ws2812_pwm.rs

Notice:
- Remove TIM6 DMA exclusion from *build.rs*, though a few chip still need extra setup to guaranty TIM DMA actually work, (won't implement until someone actually encounter this problem). 
- Rename `.gen_waveform()` to `.waveform_up()`, to match up with new `.waveform_chx()`
P.S.
I have to copy&paste™ entire "waveform for UP" implement, and do a few modification. It's too tricky to exclude some code with a `$()?` inside a *MacroTranscriber*:
`.waveform_up()` requires user input a `timer::Channel`, but `.waveform_chx()` don't. I don't know how to achieve this inside one macro.

impl waveform with TIM OC Channel DMA

---

embassy-sync/src/ring_buffer.rs

See #2507
I haven't tested this past running `cargo test`, and haven't verified it's actually all zeroes on init now, but the only non-zero that was there came from the `true` that is now `false`. If necessary I can test later to confirm it really works as desired.

sync/pipe: be able to be zero-initialized

---

embassy-stm32/src/rcc/wba.rs

STM32WBA's HSE speed cannot be configured: it *has* to run at 32 MHz.
I'm not sure the `PllSource` enum is still needed at this point but since this is my first contribution I went for something minimal. Let me know if `PllSource` should just go.
As a side note, because their frequencies are fixed, the datasheet of that chip refers to the high-speed clocks as HSI16 and HSE32. I'd be willing to contribute a change in that direction if it'd be useful.

STM32WBA's high speed external clock has to run at 32 MHz

---

embassy-stm32/src/adc/v2.rs

I recently tested the ADC on STM32F215, and it seems to work great with the exception of these two small differences compared to F4/F7.
PS. F2 ADC is listed as "?" in the stm32 register versions Google sheet. I quickly compared the F2 reference manual with ADC v2 register definitions in stm32-data and couldn't find differences, so at least to me it looks like a match and the current v2 assumption seems correct.

F2 ADC fixes

---

embassy-stm32-wpan/Cargo.toml
embassy-stm32-wpan/build.rs
embassy-stm32-wpan/tl_mbox_extended_wb1.x.in
embassy-stm32-wpan/tl_mbox_extended_wbx5.x.in

Build script chooses the 'x.in' to copy over to 'tl_mbox.x' based on features

STM32WB: Add scatter memory files for extended BLE stack

---

embassy-stm32/src/rcc/wba.rs

This is a start of #2515 for STM32WBA
- Supposedly no regression in terms of features as compared to the previous `wba.rs` implementation
- HSE prescaler
- Voltage range support
- Default config matches MCU's reset state
- Setting of SRAM wait states
- PLL
- Setting of Hclk5 divider

Migrate STM32WBA to RCCv3

---

docs/modules/ROOT/pages/embassy_in_the_wild.adoc

I developed a simple system for air quality monitoring (CO2, temperature and humidity) based on nRF52 using the nrf-softdevice. It could help as an example for people starting with the softdevice.
OT: Do you want Embassy in the wild section to also have links to commecial/proprietary projects (of course with descriptions to what is embassy used for there), or should it be kept to open-source projects only?

docs: Embassy in the wild - add air quality monitoring system

---

embassy-nrf/Cargo.toml
embassy-nrf/src/uarte.rs

This PR adds a mechanism to handle RX errors for UART RX transactions.
Closes #2500.

NRF: handle `uarte` RX errors

---

embassy-stm32/src/rcc/h.rs

fix(stm32/h7): use correct unit in vco clock check

---

embassy-stm32/src/flash/h7.rs

PR #1014 introduced memory barriers to H7 flash driver to mitigate PGSERR errors.
Despite initial implementations, there was a noticeable frequency of these errors during write operations.
The changes in this PR results in a significant enhancement to the resilience against Program Sequence Errors (PGSERR) in the H7 flash module in my experience.
I believe this is related to this note from rm0399 §4.3.9:
> Any write access requested while the PG1/2 bit is cleared to 0 is rejected. In this case, no  error is generated on the bus, but the PGSERR1/2 flag is raised.
Although I didn't experience any issues during erase operations, this PR also adds memory barriers during erase operations to be on the safe side.
[Zephyr's STM32H7 flash …

fix(stm32h7/flash): enhance resilience to program sequence errors (pgserr)

---

docs/modules/ROOT/pages/best_practices.adoc
docs/modules/ROOT/pages/faq.adoc

I ran into the dependency graph conflicts when I wanted to pull in embassy-nrf from specific git revision (after #2547 was merged), and while at it, also found some irrelevant stuff in other areas of docs.
PS. What's the release-plan going to be for embassy-nrf crate? I guess there should be a fix version up in crates.io. (And another thing I noticed between 0.1.0 and master was API change regarding dropped GPIO generics).

Faq fixes due to embassy-time crate split

---

embassy-stm32/src/dma/bdma.rs
embassy-stm32/src/dma/dma.rs
embassy-stm32/src/dma/ringbuffer.rs

Add write_immediate() function to STM32 DMA ringbuffer API to pre-fill the buffer before starting the DMA.

Add write_immediate() function to STM32 DMA ringbufer API

---

ci.sh
embassy-executor/Cargo.toml
embassy-executor/src/raw/mod.rs

Could not compile when `rtos-trace` was enabled due to missing embassy_time feature. Note that I added `embassy-time` for the `rtos-trace` feature
We could probably derive from `embassy-time-driver::now()` if it's preferred and don't want to depend on `embassy-time`

fix: rtos-trace time missing

---

embassy-usb-logger/src/lib.rs
examples/rp/src/bin/usb_serial_with_logger.rs

This can be used in cases where the user wants to log something via usb but the usb connection is already in use.
It also serves as an example on how to create multiple usb classes with one device.
Finally this fixes an issue in the usb logger where messages that were exactly MAX_PACKET_SIZE (in this case 64) bytes long wouldn't show up in the log straight away, as explained in the [CdcAcmClass](https://docs.embassy.dev/embassy-usb/git/default/class/cdc_acm/struct.CdcAcmClass.html) (see the third point about messages with exactly the length of MAX_PACKET_SIZE)

Adds function and macro to create usb logger without device (also fixes a logger issue)

---

examples/stm32f0/Cargo.toml

Hey,
This is the default for nearly all examples and helps locate bugs.

Print panics via defmt per default for the stm32f0 example

---

embassy-stm32/src/gpio.rs

FIX: Correct typo in stm32 gpio

---

embassy-nrf/src/spim.rs
embassy-nrf/src/util.rs

On some chips (notably nrf52832), the maximum DMA transfer length was 255 which caused some hard to understand issues when interfacing with various devices over SPI bus.
Tested with nrf52832 + SPI flash (+ DFU flashing over BLE with SPI-NOR page size of 256 bytes).

NRF: Implement chunked DMA transfers for SPIM

---

embassy-rp/src/i2c_slave.rs
examples/rp/src/bin/i2c_slave.rs

This commit takes the fixes and error reporting improvements from jcdickinson's work in #2169 and applies them without overlaying a software state machine on top of the hardware state machine.
Also allows configuration of response to 'general call' writes.

Improve rp2040 i2c slave

---

embassy-nrf/src/pdm.rs

The PDM peripheral gain was not being correctly converted from a fixed-point type to the bits type.  The table below shows the behaviour before and after the patch, and [here](https://infocenter.nordicsemi.com/topic/com.nordic.infocenter.nrf52832.ps.v1.1/pdm.html?cp=5_2_0_42_6_6#register.GAINL) is the register documentation from the microcontroller's manual.
Gain | Before | After
------|--------|------
-20dB |   0x00 |  0x00
-19dB |   0x01 |  0x02
-18dB |   0x02 |  0x04
-17dB |   0x03 |  0x06
-16dB |   0x04 |  0x08
-15dB |   0x05 |  0x0a
-14dB |   0x06 |  0x0c
-13dB |   0x07 |  0x0e
-12dB |   0x08 |  0x10
-11dB |   0x09 |  0x12
-10dB |   0x0a |  0x14
-9dB |   0x0b |  0x16
-8dB |   0x0c |  0x18
-7dB |   0x0d |  0x1a
-6dB |   0x0e |  0x1c
-5dB |   0x0f |  0x1e
-4dB |   0x10 |  0x20
-3dB | …

embassy-nrf: Fix PDM gain register value derivation
