embassy-rs/embassy

embassy-macros/src/lib.rs, embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/gpiote.rs, embassy-nrf/src/interrupt.rs, embassy-nrf/src/lib.rs, embassy-nrf/src/qspi.rs, embassy-nrf/src/rtc.rs, embassy/src/interrupt.rs, embassy/src/lib.rs, examples/src/bin/gpiote.rs, examples/src/bin/gpiote_port.rs, examples/src/bin/multiprio.rs, examples/src/bin/qspi.rs, examples/src/bin/rtc_async.rs, examples/src/bin/rtc_raw.rs, examples/src/bin/uart.rs
=> Owned IRQs

embassy-stm32f4-examples/src/serial.rs, embassy-stm32f4/src/serial.rs
wip to implement uart on stm32f4 serial interface.
=>  implement uart on serial interface

embassy-stm32f4-examples/src/bin/serial.rs, embassy-stm32f4/src/serial.rs
this is a minor cleanup to stabilize (for good) the interface. the previous interface was messier and did not support all configuration options.
=> minor cleanup to interface

embassy/src/lib.rs, embassy/src/util/signal.rs
fixes #28 
Adds a new InterruptSignal that fires on an interrupt.
=> add InterruptSignal

embassy-macros/src/lib.rs, embassy-nrf-examples/Cargo.toml, embassy-nrf/Cargo.toml, embassy-stm32f4-examples/Cargo.toml, embassy-stm32f4/Cargo.toml, embassy/Cargo.toml, embassy/src/executor/mod.rs, embassy/src/interrupt.rs, embassy/src/util/signal.rs
=> Update to cortex-m 0.7

embassy-nrf-examples/src/bin/multiprio.rs, embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/gpiote.rs, embassy-nrf/src/rtc.rs, embassy-nrf/src/uarte.rs, embassy-nrf/src/util/peripheral.rs, embassy-stm32f4/src/rtc.rs, embassy-stm32f4/src/serial.rs, embassy/src/executor/mod.rs, embassy/src/interrupt.rs, embassy/src/util/signal.rs
=> move most interrupt methods to InterruptExt extension trait. Fixes #35

embassy-stm32f4-examples/Cargo.toml, embassy-stm32f4-examples/src/bin/serial.rs, embassy-stm32f4/src/serial.rs
depends on: stm32-rs/stm32f4xx-hal#251
=> impl. generics on serial

embassy-stm32f4-examples/src/bin/exti.rs, embassy-stm32f4/src/exti.rs, embassy-stm32l0/src/exti.rs
=> cleanup exti and remove static mut

embassy-stm32f4-examples/src/bin/exti.rs, embassy-stm32f4/src/exti.rs, embassy-stm32l0/Cargo.toml, embassy-stm32l0/src/exti.rs
=> Add WaitFor{Low,High} for stm32l0 exti pins

.github/workflows/rust.yml, ci.sh, embassy/src/io/traits.rs, embassy/src/io/util/read.rs, embassy/src/io/util/read_buf.rs
Could also be a separate GH workflow job, either way :shrug:
=> Run cargo fmt in CI

embassy/src/time/duration.rs, embassy/src/time/instant.rs, embassy/src/time/mod.rs
=> Add some documentation for the timing module

embassy/Cargo.toml, embassy/src/util/critical_section.rs, embassy/src/util/mod.rs, embassy/src/util/signal.rs
@Dirbaio Version of #135 that makes critical section independent of signal.
=> Allow signals to be used when building for std

embassy-nrf/src/gpiote.rs
This adds an impl of WaitForAnyEdge for PortInput that can be used to detect state transitions.
=> Add detection of edge transitions for ports

embassy-stm32/src/f4/spi.rs
=> stm32: fix spi/write

embassy-nrf/src/gpio.rs
We discussed this on the chat.
I'm in no way attached to the name and encourage better suggestions.
=> Add a pin variant that can change between disconnected/input/output.

embassy-nrf/src/spim.rs
This is a partial impl of #136
=> Implement the blocking hal api for SPIM.

embassy-macros/Cargo.toml, embassy-macros/src/chip/stm32.rs, embassy-macros/src/lib.rs, embassy-stm32/Cargo.toml, embassy-stm32/src/lib.rs, embassy-stm32/src/rcc/h7/mod.rs, embassy-stm32/src/rcc/l0/mod.rs, embassy-stm32/src/rcc/mod.rs
* Hook RCC config into chip config and use chip-specific RCC init function
* RTC/clock setup is ignored for now
=> Enable stm32 macro

embassy-stm32/gen.py
In the case where GPIO mapping could look like this:
PA5:
SPI1_SCK: 0
The pin would not get any generated impl because the if expression would
evaluate to false.
Fix this for all cases in gen.py by comparing against None
=> Handle case where pin value could be 0

embassy-stm32/src/spi/mod.rs, embassy-stm32/src/spi/v2.rs
* SPI write v2 was hanging in write due to an infinite loop
* SPI word write was not followed by a read back
The u8 and u16 write/read logic have been refactored into write_word and
read_word.
=> Refactor SPI and fix write bug

embassy-stm32/src/dma/v2.rs
=> stm32: Adjust some fences around DMA

.github/workflows/rust.yml, embassy-nrf/src/gpiote.rs, embassy-stm32/src/adc/v3.rs, examples/stm32l4/src/bin/adc.rs
@rukai can finally get some rest :)
=> Deny warnings in CI

.github/workflows/rust.yml, embassy/src/executor/timer.rs, embassy/src/io/util/copy_buf.rs, embassy/src/util/signal.rs
Also found some doctests that were failing
=> Add tests to our CI

embassy-stm32/src/i2c/mod.rs, embassy-stm32/src/i2c/v2.rs
~~Still have to find something to test these bigger transfers.~~
=> i2c-v2: Support transfers with more than 255 bytes

examples/stm32f4/Cargo.toml, examples/stm32f4/src/bin/blinky.rs, examples/stm32f4/src/bin/button.rs, examples/stm32f4/src/bin/button_exti.rs, examples/stm32f4/src/bin/spi.rs, examples/stm32f4/src/bin/usart.rs, examples/stm32f4/src/bin/usart_dma.rs
* Remove dependency on stm32f4 pac crate
* Remove unused `ZeroClock`
=> Cleanup stm32f4 examples

examples/stm32f4/src/bin/blinky.rs, examples/stm32f4/src/bin/button.rs, examples/stm32f4/src/bin/button_exti.rs, examples/stm32f4/src/bin/spi.rs, examples/stm32f4/src/bin/usart.rs, examples/stm32f4/src/bin/usart_dma.rs, examples/stm32h7/src/bin/blinky.rs, examples/stm32h7/src/bin/dac.rs, examples/stm32h7/src/bin/eth.rs, examples/stm32h7/src/bin/usart.rs, examples/stm32h7/src/bin/usart_dma.rs, examples/stm32l4/Cargo.toml, examples/stm32l4/src/bin/adc.rs, examples/stm32l4/src/bin/blinky.rs, examples/stm32l4/src/bin/button.rs, examples/stm32l4/src/bin/button_exti.rs, examples/stm32l4/src/bin/dac.rs, examples/stm32l4/src/bin/spi.rs, examples/stm32l4/src/bin/usart.rs, examples/stm32l4/src/bin/usart_dma.rs, examples/stm32wb55/Cargo.toml, examples/stm32wb55/src/bin/blinky.rs
=> stm32 examples: No need to enable GPIO clocks manually

embassy-stm32/src/rcc/f0/mod.rs, embassy-stm32/src/rcc/l0/mod.rs, embassy-stm32/src/rcc/wl5x/mod.rs, examples/stm32f0/src/bin/hello.rs, examples/stm32f0/src/example_common.rs, examples/stm32l0/src/bin/blinky.rs, examples/stm32l0/src/bin/button_exti.rs, examples/stm32l4/Cargo.toml, examples/stm32l4/src/bin/adc.rs, examples/stm32l4/src/bin/blinky.rs, examples/stm32l4/src/bin/button.rs, examples/stm32l4/src/bin/button_exti.rs, examples/stm32l4/src/bin/dac.rs, examples/stm32l4/src/bin/spi.rs, examples/stm32l4/src/bin/spi_dma.rs, examples/stm32l4/src/bin/usart.rs, examples/stm32l4/src/bin/usart_dma.rs
=> Misc stm32 fixes

embassy-stm32/src/rcc/h7/mod.rs, examples/stm32h7/Cargo.toml, examples/stm32h7/src/bin/blinky.rs, examples/stm32h7/src/bin/dac.rs, examples/stm32h7/src/bin/spi.rs, examples/stm32h7/src/bin/spi_dma.rs, examples/stm32h7/src/bin/usart.rs, examples/stm32h7/src/bin/usart_dma.rs
Clean up H7 examples to remove all vegan HALs and PACs.
=> Enhance Rcc configuration to be more fluentish.

embassy-stm32/src/usart/v1.rs, embassy-stm32/src/usart/v2.rs, examples/stm32f4/src/bin/usart.rs, examples/stm32h7/src/bin/usart.rs, examples/stm32l0/src/bin/usart_dma.rs, examples/stm32l4/src/bin/usart.rs
* Rename existing read() to bread() (blocking)
Only tested with v2 usart on L0.
=> Add uart::Read DMA-based implementation

embassy-stm32/src/i2c/mod.rs, embassy-stm32/src/i2c/v2.rs
~~I still want to do more tests before merging...~~
=> i2c-v2: Implement write_dma and write_dma_vectored

embassy/src/util/mutex.rs
=> util: fix unsoundness when dropping ThreadModeMutex outside thread mode.

embassy-stm32/src/dma/bdma.rs, embassy-stm32/src/dma/dma.rs
Using `fence` instead of `compiler_fence` because of M7.
=> stm32: Add fences to DMA code

xtask/.cargo/config, xtask/Cargo.toml, xtask/src/main.rs
```
cd xtask
cargo xtask <command>
```
Commands include `ci` and it's components.
=> First shot at xtask support.

embassy-nrf/src/lib.rs, embassy-nrf/src/time_driver.rs
=> nrf/time: allow configuring the rtc irq prio

embassy-macros/src/lib.rs, embassy/src/executor/arch/arm.rs, embassy/src/executor/arch/std.rs, embassy/src/executor/mod.rs, embassy/src/executor/raw/mod.rs, embassy/src/executor/raw/run_queue.rs, embassy/src/executor/raw/waker.rs, embassy/src/executor/spawner.rs, embassy/src/time/driver.rs, embassy/src/time/mod.rs, examples/nrf/src/bin/raw_spawn.rs
=> Executor docs

embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/timer.rs, embassy-nrf/src/uarte.rs, examples/nrf/src/bin/awaitable_timer.rs
useful for hooking up the PPI to an Event without needing interrupt
tested with buffered_uart example on nRF52840-DK
the names are aweful but descriptive, I'm very open to suggestions
=> Typestate nrf timer

.gitignore, .vscode/settings.json, embassy-hal-common/Cargo.toml, embassy-macros/Cargo.toml, embassy-net/Cargo.toml, embassy-nrf/Cargo.toml, embassy-rp/Cargo.toml, embassy-stm32/Cargo.toml, embassy-traits/Cargo.toml, embassy/Cargo.toml, embassy/src/util/mpsc.rs, examples/nrf/Cargo.toml, examples/rp/Cargo.toml, examples/std/Cargo.toml, examples/std/src/serial_port.rs, examples/stm32f0/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32g0/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l0/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32wb55/Cargo.toml, examples/stm32wl55/Cargo.toml, stm32-metapac-gen/Cargo.toml, stm32-metapac/Cargo.toml, xtask/Cargo.toml
We're at the latest major version of everything :) 
...except `bxcan`, it has some api-breaking changes that can't be that quickly fixed..
=> Update lots of deps

embassy-stm32/Cargo.toml, embassy-stm32/src/rcc/l4/mod.rs
This PR depends on https://github.com/embassy-rs/stm32-data/pull/88
=> Add MSI and PLL clock source for L4

embassy-hal-common/Cargo.toml, embassy-lora/Cargo.toml, embassy-net/Cargo.toml, embassy-nrf/Cargo.toml, embassy-rp/Cargo.toml, embassy-stm32/Cargo.toml, embassy-stm32/src/can/bxcan.rs, embassy-traits/Cargo.toml, embassy/Cargo.toml, examples/nrf/Cargo.toml, examples/rp/Cargo.toml, examples/std/Cargo.toml, examples/stm32f0/Cargo.toml, examples/stm32f1/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32f4/src/bin/can.rs, examples/stm32f7/Cargo.toml, examples/stm32g0/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l0/Cargo.toml, examples/stm32l1/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32u5/.cargo/config.toml, examples/stm32u5/Cargo.toml, examples/stm32u5/src/bin/boot.rs, examples/stm32wb55/Cargo.toml, examples/stm32wl55/Cargo.toml
=> Update to defmt 3.0ish.

examples/stm32u5/.cargo/config.toml
- Correct ISA
- Remove commented-out cruft.
=> Adjust the config.toml for U5.

embassy-nrf/src/saadc.rs
=> nrf: saadc do not reexport pac enums

embassy-nrf/src/saadc.rs, embassy/src/channel/signal.rs
Some documentation to help us along with `Signal` and `Saadc`.
=> Some documentation corrections and expansion

embassy-stm32/src/spi/v2.rs
Fix a bug where DMA writes were not fully completed and only a single
byte out of two were written.
=> Ensure SPI DMA write is completed

embassy-net/Cargo.toml, embassy-net/src/config/dhcp.rs, embassy-net/src/config/mod.rs, embassy-net/src/config/statik.rs, embassy-net/src/lib.rs, embassy-net/src/stack.rs, embassy-net/src/tcp_socket.rs, examples/std/src/bin/net.rs, examples/std/src/serial_port.rs, examples/std/src/tuntap.rs
=> net: update smoltcp

embassy-stm32/src/can/bxcan.rs, embassy-stm32/src/dma/dmamux.rs, embassy-stm32/src/gpio.rs, embassy-stm32/src/rcc/mod.rs, examples/stm32f1/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32f7/Cargo.toml, examples/stm32f7/src/bin/eth.rs, examples/stm32g0/Cargo.toml, examples/stm32g0/build.rs, examples/stm32g0/memory.x, examples/stm32h7/Cargo.toml, examples/stm32h7/src/bin/eth.rs, examples/stm32l0/Cargo.toml, examples/stm32l1/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32u5/Cargo.toml, examples/stm32wb55/Cargo.toml, examples/stm32wl55/Cargo.toml, stm32-metapac-gen/src/data.rs, stm32-metapac-gen/src/lib.rs, stm32-metapac-gen/src/main.rs
Main imrpvement is RCC regs info comes from yamls now.
=> Stm32 data upate 4

embassy-lora/Cargo.toml, embassy-lora/src/sx127x/mod.rs, embassy-lora/src/sx127x/sx127x_lora/mod.rs, embassy-stm32/src/spi/v2.rs, embassy-stm32/src/spi/v3.rs, examples/stm32l0/Cargo.toml, examples/stm32l0/src/bin/lorawan.rs, examples/stm32wl55/Cargo.toml
It also contains a fix to SPI DMA transfer/read_write operations to ensure MISO doesn't contain any old data.
=> Refactor sx127x driver to use async SPI

embassy-net/README.md, examples/std/Cargo.toml
=> Fix embassy-net documentation of running examples.

embassy-stm32/src/dma/bdma.rs, embassy-stm32/src/dma/dma.rs, embassy-stm32/src/dma/mod.rs, embassy-stm32/src/i2c/v2.rs, embassy-stm32/src/spi/v1.rs, embassy-stm32/src/spi/v2.rs, embassy-stm32/src/spi/v3.rs, embassy-stm32/src/usart/v1.rs, embassy-stm32/src/usart/v2.rs
This should be an improved version of the PR by @theunkn0wn1.
=> Low level DMA channel API.

tests/stm32/src/bin/usart.rs, tests/stm32/src/bin/usart_dma.rs
H7 usart_dma fails with a super strange error, looks like defmt corruption. Will investigate.
=> stm32/tests: add uart, uart_dma tests.

embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/uarte.rs, examples/nrf/src/bin/buffered_uart.rs
Please see https://github.com/embassy-rs/embassy/issues/536 for the rationale.
=> Documents the nRF BufferedUarte problem

embassy-hal-common/src/usb/mod.rs, embassy-nrf/Cargo.toml, embassy-nrf/src/chips/nrf52820.rs, embassy-nrf/src/chips/nrf52833.rs, embassy-nrf/src/chips/nrf52840.rs, embassy-nrf/src/chips/nrf5340_app.rs, embassy-nrf/src/lib.rs, embassy-nrf/src/usb.rs, examples/nrf/Cargo.toml, examples/nrf/src/bin/usb_uart.rs, examples/nrf/src/bin/usb_uart_io.rs
Frankensteined together from this old pr https://github.com/embassy-rs/embassy/pull/115 and nrf-usdb
~Doesnt currently work..~
=> nrf: async usb

examples/stm32f3/src/bin/multiprio.rs, examples/stm32f4/src/bin/multiprio.rs
Example tested on stm32f303discovery and stm32f405 feather.
=> Port multiprio example to stm32f3 and stm32f4 platforms

examples/stm32f3/src/bin/button_events.rs
This is a more elaborate example of using buttons and leds. 
Tested on STM32F3DISCOVERY
=> Add button_events example for stm32f3

embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/gpio.rs, embassy-nrf/src/pwm.rs, embassy-nrf/src/spim.rs, embassy-nrf/src/uarte.rs, examples/nrf/src/bin/pwm.rs, examples/nrf/src/bin/pwm_double_sequence.rs, examples/nrf/src/bin/pwm_sequence.rs, examples/nrf/src/bin/pwm_sequence_ppi.rs, examples/nrf/src/bin/pwm_sequence_ws2812b.rs, examples/nrf/src/bin/pwm_servo.rs, examples/nrf/src/bin/uart.rs, examples/nrf/src/bin/uart_idle.rs, examples/nrf/src/bin/uart_split.rs
=> nrf: remove OptionalPin

embassy-nrf/src/spim.rs, embassy-rp/src/gpio.rs, embassy-rp/src/spi.rs, embassy-stm32/src/gpio.rs, examples/rp/src/bin/spi.rs, examples/rp/src/bin/spi_display.rs
Mirror of https://github.com/embassy-rs/embassy/pull/605 for rp2040
=> rp: remove OptionalPin

examples/stm32f3/src/bin/button_events.rs
Allow blinking to be interrupted by button presses in this sample.
=> Improve logic for processing button events

ci.sh, docs/modules/ROOT/examples/layer-by-layer/.cargo/config.toml, docs/modules/ROOT/examples/layer-by-layer/Cargo.toml, docs/modules/ROOT/examples/layer-by-layer/blinky-async/Cargo.toml, docs/modules/ROOT/examples/layer-by-layer/blinky-async/src/main.rs, docs/modules/ROOT/examples/layer-by-layer/blinky-hal/Cargo.toml, docs/modules/ROOT/examples/layer-by-layer/blinky-hal/src/main.rs, docs/modules/ROOT/examples/layer-by-layer/blinky-irq/Cargo.toml, docs/modules/ROOT/examples/layer-by-layer/blinky-irq/src/main.rs, docs/modules/ROOT/examples/layer-by-layer/blinky-pac/Cargo.toml, docs/modules/ROOT/examples/layer-by-layer/blinky-pac/src/main.rs, docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/layer_by_layer.adoc
The guide demonstrates the functionality offered by each
layer in Embassy, using code examples.
=> Add documentation about the different embassy abstraction layers

ci.sh, embassy-stm32/build.rs, embassy-stm32/src/adc/v3.rs, embassy-stm32/src/dac/v2.rs, embassy-stm32/src/dma/bdma.rs, embassy-stm32/src/dma/dmamux.rs, embassy-stm32/src/exti.rs, embassy-stm32/src/rcc/l0.rs, embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/time_driver.rs
=> stm32: build fixes for troublesome chips

embassy-stm32/src/usart/mod.rs
* On v1 interrupts cannot be cleared individually.
Instead they are cleared implicitly by reading or writing DR (which we do now).
* Multiple error flags can be set at the same time:
Handle them all in one go intstead of re-entering the ISR for each one so that
we do not lose any error flags on v1 hardware.
* Wake when the RX buffer becomes full: This allows fast running chips to pull data
from the buffer before receiving the next byte.
Tested on v1 hardware, lets see if v2 still succeeds on CI.
=> stm32 usart: Fix RX interrupt flag handling

embassy-boot/boot/src/lib.rs
Ensure 4 byte alignment of writes to boot magic.
Reduce log level
=> Fix potential unaligned write

embassy-nrf/src/usb.rs, examples/nrf/src/bin/usb/cdc_acm.rs
Removes UnsafeCell from cdc_acm::Control and avoids an extra memcpy in embassy_nrf::Usb when it's not necessary.
=> A couple async_usb_stack improvements.

embassy-nrf/src/usb.rs, embassy-usb/src/driver.rs, embassy-usb/src/lib.rs
=> Async USB: Move data chunking from the driver to the lib

embassy-boot/boot/src/lib.rs
=> Avoid writing bootloader flash if not needed

embassy-usb/src/control.rs, embassy-usb/src/lib.rs
This moves the `ControlPipe` struct into the `control` module and implements a typestate pattern to ensure the methods of `ControlPipe` are only called at valid times during the control transaction process. This eliminates the assertions used previously and moves the checks to compile time. Otherwise, functionality is unchanged.
=> Refactor ControlPipe to use the typestate pattern

embassy/src/channel/channel.rs
* Add internal DynamicChannel trait implemented by Channel that allows
polling for internal state in a lock safe manner and does not require
knowing the channel size.
* Existing usage of Sender and Receiver is preserved and does not use
dynamic dispatch.
* Add DynamicSender and DynamicReceiver types that references the
channel using the DynamicChannel trait and does not require the const
generic channel size parameter.
Having the ability not know the channel size is very convenient when you don't want to change all of your channel using code when tuning the size. With this change, existing usage can be kept, and those willing to pay the price for dynamic dispatch may do so.
=> Add types for channel dynamic dispatch

embassy-boot/boot/src/lib.rs, embassy-boot/nrf/.cargo/config.toml, embassy-boot/nrf/Cargo.toml, embassy-boot/nrf/src/lib.rs, embassy-boot/nrf/src/main.rs, examples/boot/.cargo/config.toml, examples/boot/Cargo.toml, examples/boot/src/bin/a.rs
Includes e-s and e-s-a impls for nrf QSPI
WIP: Working on testing it.
=> Bootloader external flash

embassy-macros/src/macros/task.rs, embassy/src/executor/arch/cortex_m.rs, embassy/src/executor/spawner.rs, examples/nrf/src/bin/multiprio.rs, examples/nrf/src/bin/self_spawn.rs, examples/stm32f3/src/bin/multiprio.rs, examples/stm32f4/src/bin/multiprio.rs
See individual commits.
bors r+
=> Executor and task macro fixes.

embassy-nrf/src/uarte.rs
I needed this method because I was writing a driver for the sim7000 modem. Its a line based protocol so the read until idle was very useful to me. Unfortunately unlike the primary `Uarte` struct the `UarteWithIdle` didn't have `split()`. So I added it 😄
=> Add split method to UarteWithIdle in nrf hal

embassy/src/executor/raw/mod.rs
This commit contains a suggestion to rename `TaskStorage::spawn_allocate`.
The motivation for this is when reading through the code I was
expecting something else to happen in this method, due to `allocate` in
the method name.
I'm very new to this code base so I may be wrong in thinking this
is a good change, but I wanted to open this PR to get some feedback.
=> Rename spawn_allocate to spawn_mark_used

ci.sh, embassy-stm32/src/exti.rs, embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/usb_otg.rs
=> stm32: Fix stm32f107 build.

embassy-nrf/src/buffered_uarte.rs
=> nrf/buffered_uarte: fix out of bounds on read.

embassy-usb-ncm/src/lib.rs
This allows the CDC-NCM class struct to be Send, so you can run
it at a different priority than the main USB stack task.
bors r+
=> usb-ncm: remove useless Cell.

embassy-lora/Cargo.toml, embassy-nrf/Cargo.toml, embassy-rp/Cargo.toml, embassy-stm32/Cargo.toml, embassy/Cargo.toml, examples/rp/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l4/Cargo.toml, tests/stm32/Cargo.toml
=> Update embedded-hal-async to 0.1.0-alpha.1

embassy-nrf/src/usb.rs, embassy-usb/src/builder.rs, embassy-usb/src/driver.rs, embassy-usb/src/lib.rs
See individual commit messages. 
These changes help implementing the driver for STM32 USBD (#709)
=> Misc USB improvements, for stm32

embassy/src/channel/channel.rs
This was unclear from the docs.
=> Channel clarification

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/lib.rs, embassy-stm32/src/usb/mod.rs, embassy-stm32/src/usb/usb.rs, examples/stm32f1/Cargo.toml, examples/stm32f1/src/bin/usb_serial.rs, examples/stm32f3/src/bin/usb_serial.rs, examples/stm32l5/.cargo/config.toml, examples/stm32l5/Cargo.toml, examples/stm32l5/build.rs, examples/stm32l5/src/bin/button_exti.rs, examples/stm32l5/src/bin/rng.rs, examples/stm32l5/src/bin/usb_ethernet.rs, examples/stm32l5/src/bin/usb_hid_mouse.rs, examples/stm32l5/src/bin/usb_serial.rs
=> embassy-usb stm32

embassy-stm32/src/flash/l.rs
The page index was wrong because it doesn't take FLASH_BASE into account. 
For l4, the page index register also depends on a bank selection register.
=> Use correct index and bank for stm32 flash

embassy-cortex-m/src/executor.rs, embassy-cortex-m/src/interrupt.rs, embassy-cortex-m/src/lib.rs, embassy-cortex-m/src/peripheral.rs, embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/gpio.rs, embassy-nrf/src/lib.rs, embassy-nrf/src/uarte.rs, embassy/src/channel/pubsub/mod.rs
embassy-cortex-m is covered now, making some progress on embassy-nrf, but not complete.
=> More API docs

embassy/src/blocking_mutex/mod.rs, embassy/src/blocking_mutex/raw.rs, embassy/src/channel/mpmc.rs, embassy/src/channel/pubsub/mod.rs, embassy/src/channel/signal.rs, embassy/src/executor/raw/mod.rs, embassy/src/executor/raw/waker.rs, embassy/src/executor/spawner.rs, embassy/src/lib.rs, embassy/src/util/forever.rs, embassy/src/util/select.rs, embassy/src/waitqueue/waker.rs, embassy/src/waitqueue/waker_agnostic.rs
See individual commit messages.
=> Misc API and doc fixes.

embassy-nrf/src/uarte.rs
Allow creating UarteRx/UarteTx directly. This allows using uart unidirectionally
(rx-only or tx-only), without having to 'waste' a pin for the unused direction.
=> nrf/uart: add support for tx-only and rx-only uart.

ci.sh, embassy-cortex-m/Cargo.toml, embassy-cortex-m/src/interrupt.rs, embassy-lora/Cargo.toml, embassy-net/Cargo.toml, embassy-nrf/Cargo.toml, embassy-rp/Cargo.toml, embassy-stm32/Cargo.toml, embassy-stm32/src/rcc/f1.rs, embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/usb/usb.rs, embassy-usb-hid/Cargo.toml, embassy-usb-ncm/Cargo.toml, embassy-usb-serial/Cargo.toml, embassy-usb/Cargo.toml, embassy/Cargo.toml, stm32-metapac-gen/src/lib.rs
See individual commit messages for details.
=> More misc fixes.

embassy-embedded-hal/src/shared_bus/blocking/i2c.rs, embassy-embedded-hal/src/shared_bus/blocking/mod.rs, embassy-embedded-hal/src/shared_bus/blocking/spi.rs, embassy-embedded-hal/src/shared_bus/mod.rs
Blocking versions of the shared buses
=> Add blocking shared bus for i2c and SPI

embassy-stm32/src/exti.rs, embassy-stm32/src/gpio.rs, tests/stm32/src/bin/gpio.rs
Add Flex GPIO type for embassy-stm32 as it is the case for  embassy-nrf.
=> Gpio dynamic flex

ci.sh
This allows running `./ci.sh` under windows
=> Fix ci for windows (msys, git bash)

embassy-stm32/src/flash/f4.rs, embassy-stm32/src/flash/mod.rs, embassy-stm32/src/lib.rs, examples/stm32f4/Cargo.toml, examples/stm32f4/src/bin/flash.rs
Pending on https://github.com/embassy-rs/stm32-data/pull/152
=> Add F4 flash driver

embassy-stm32/src/pwm/mod.rs, embassy-stm32/src/timer/mod.rs
=> Reintroduce Gp16 trait for advanced timers

embassy-rp/Cargo.toml, embassy-rp/src/gpio.rs, examples/rp/src/bin/gpio_async.rs, tests/rp/Cargo.toml, tests/rp/src/bin/gpio_async.rs
This commit adds support for embedded-hal-async to the Embassy
Raspberry PI crate.
=> Add embedded_hal_async support for embassy-rp

embassy-cortex-m/src/interrupt.rs, embassy-cortex-m/src/lib.rs, embassy-embedded-hal/src/adapter.rs, embassy-embedded-hal/src/lib.rs, embassy-embedded-hal/src/shared_bus/asynch/i2c.rs, embassy-embedded-hal/src/shared_bus/asynch/spi.rs, embassy-embedded-hal/src/shared_bus/blocking/i2c.rs, embassy-embedded-hal/src/shared_bus/blocking/spi.rs, embassy-embedded-hal/src/shared_bus/mod.rs
=> Add some docs.

embassy-nrf/src/qspi.rs
Fixes #886 among some of the TODOs which have been flying around in the source file :)
I'll make one more commit to remove some old commented out code from the file and take some time this evening to verify that it works.
=> Extend QSPI config with freq, delay, spi mode, and address mode

embassy-stm32/src/gpio.rs, embassy-stm32/src/i2c/v1.rs, embassy-stm32/src/i2c/v2.rs, examples/stm32h7/src/bin/camera.rs, examples/stm32l4/src/bin/i2c.rs, examples/stm32l4/src/bin/i2c_blocking_async.rs, examples/stm32l4/src/bin/i2c_dma.rs
I wasn't sure if I should put frequency into config struct, so left it separate as in SPI periph.
Also added Copy derives to gpio types, not sure why they weren't?
=> Implement I2C pullup configuration

embassy-hal-common/Cargo.toml
=> hal-common: Remove unused dep

embassy-net/Cargo.toml
=> net: update atomic-pool, atomic-polyfill.

embassy-rp/Cargo.toml, embassy-rp/src/dma.rs, embassy-rp/src/uart.rs, examples/rp/src/bin/uart.rs
async read/write is still `todo!()`, awaiting DMA implementation.
=> (embassy-rp): Implement remaining logic for blocking UART

tests/stm32/src/bin/usart.rs, tests/stm32/src/bin/usart_dma.rs
=> Lpuart hil

embassy-executor/src/raw/mod.rs, embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/gpio.rs, embassy-nrf/src/nvmc.rs, embassy-nrf/src/ppi/mod.rs, embassy-nrf/src/ppi/ppi.rs, embassy-time/src/driver.rs, embassy-usb/src/builder.rs, embassy-usb/src/control.rs, embassy-usb/src/driver.rs
Fixing a few doc warnings in embassy-executor, embassy-time, embassy-usb and embassy-nrf. There are more left, but I need a break :D
=> Doc warnings

embassy-sync/Cargo.toml
=> Add missing std feature for embassy-sync

embassy-nrf/src/buffered_uarte.rs
I haven't completed testing this yet. I'm creating this PR early so that I can get corrected if I went way off course.
This PR adds a `split()` method to `BufferedUarte` as discussed on matrix.
=> Add split() method to BufferedUarte in embassy-nrf

embassy-lora/Cargo.toml, embassy-lora/src/lib.rs, embassy-lora/src/stm32wl/mod.rs, embassy-stm32/src/rcc/wl.rs, embassy-stm32/src/spi/mod.rs, embassy-stm32/src/subghz/mod.rs, examples/stm32l0/Cargo.toml, examples/stm32l0/src/bin/lorawan.rs, examples/stm32wl/Cargo.toml, examples/stm32wl/src/bin/lorawan.rs, examples/stm32wl/src/bin/subghz.rs
Trying too get `embassy-lora` running on a [LoRa-E5 Dev Board](https://wiki.seeedstudio.com/LoRa_E5_Dev_Board/).
I can see the join message arriving in the The Things Network console but the device does not receive the accept message yet.
Opening this PR anyway because I think there are some nice things to decouple the lora crate from the nucleo board.
@lulf Could you test if this PR breaks your LoRa setup? Marking as draft for the time being.
=> Misc LoRaWAN improvements

embassy-usb-hid/Cargo.toml, examples/nrf/Cargo.toml, examples/stm32l5/Cargo.toml
Changes: https://github.com/twitchyliquid64/usbd-hid/compare/ccfda68832495a4e91410c5c32f35ede77a4c42c..2f1c984f2c16c9c5d68548b5cbff2dabb004ce17
=> usbd-hid: 0.5.2 -> 0.6.0

embassy-rp/src/dma.rs, embassy-rp/src/spi.rs
=> rp: fix async SPI read and write

embassy-boot/boot/src/lib.rs
Fixes a bug in the partition assertions that ensures that the state page(s) have enough space for 2x active partition range.
Add unit test to verify that panic is observed.
=> Take into account size of revert index

embassy-rp/Cargo.toml, embassy-rp/src/clocks.rs, embassy-rp/src/lib.rs, embassy-rp/src/rtc/datetime_chrono.rs, embassy-rp/src/rtc/datetime_no_deps.rs, embassy-rp/src/rtc/filter.rs, embassy-rp/src/rtc/mod.rs
Basically a 1:1 port of the great implementation effort made by `rp-hal`
=> (embassy-rp): Implement RealTimeClock

embassy-stm32/src/can/bxcan.rs
This PR adds a non-blocking constructor to the Bxcan Can wrapper struct. This allows for the creation of the Can periferal without blocking for a sync with the Can bus.
=> Add non blocking Bxcan constructor

ci.sh, embassy-rp/Cargo.toml, embassy-rp/src/intrinsics.rs
=> rp: Disable intrinsics by default.

embassy-embedded-hal/Cargo.toml, embassy-embedded-hal/src/shared_bus/asynch/spi.rs, embassy-embedded-hal/src/shared_bus/blocking/i2c.rs, embassy-embedded-hal/src/shared_bus/blocking/spi.rs, embassy-lora/Cargo.toml, embassy-nrf/Cargo.toml, embassy-nrf/src/gpio.rs, embassy-nrf/src/gpiote.rs, embassy-nrf/src/spim.rs, embassy-nrf/src/twim.rs, embassy-nrf/src/uarte.rs, embassy-rp/Cargo.toml, embassy-rp/src/gpio.rs, embassy-rp/src/i2c.rs, embassy-rp/src/spi.rs, embassy-rp/src/uart/mod.rs, embassy-stm32/Cargo.toml, embassy-stm32/src/exti.rs, embassy-stm32/src/gpio.rs, embassy-stm32/src/i2c/v1.rs, embassy-stm32/src/i2c/v2.rs, embassy-stm32/src/spi/mod.rs, embassy-time/Cargo.toml, embassy-time/src/delay.rs, examples/rp/src/bin/spi_display.rs, examples/stm32h7/Cargo.toml, examples/stm32l4/Cargo.toml, tests/rp/Cargo.toml, tests/stm32/Cargo.toml
Pinning to ensure CI don't accidentally break.
=> Update embedded-hal versions and explicitly pin

embassy-sync/Cargo.toml, embassy-sync/README.md
Updates the README.md based on embassy-futures structure.
=> Add required info to embassy-sync package

docs/modules/ROOT/pages/bootloader.adoc
=> Add note on partition sizes to bootloader docs

embassy-rp/src/i2c.rs, examples/rp/Cargo.toml, examples/rp/src/bin/i2c_async.rs
This implements an interrupt-driven async i2c master. It is based on https://github.com/embassy-rs/embassy/pull/914, a bit of https://github.com/embassy-rs/embassy/pull/978 and @ithinuel's https://github.com/ithinuel/rp2040-async-i2c.git
This is still work-in-progress, and is currently untested.
=> rp pico async i2c implementation

embassy-rp/src/i2c.rs
If they both share one waker, there's the possibility that some wakeups could get lost.
=> rp i2c: have separate wakers for each i2c unit

embassy-rp/src/usb.rs
This fixes failures when `defmt` feature isn't enabled (timing related).
=> rp usb: wait for accept() completion

embassy-rp/src/usb.rs
I'm not totally certain, but this looks like a typo?
=> Fix mistaken EP_IN_WAKERS

embassy-stm32/src/usart/mod.rs
fixes #1045 
regression was introduced with PR #1031
=> embassy-stm32: Fix bug when Uart::read future is dropped and DMA request was not stopped

embassy-rp/src/adc.rs, embassy-rp/src/lib.rs, examples/rp/src/bin/adc.rs
=> embassy-rp: Add basic ADC module

embassy-macros/README.md, embassy-macros/src/lib.rs
Documents the main and task macros.
=> doc: add README to embassy-macro

embassy-sync/src/signal.rs, embassy-sync/src/waitqueue/waker.rs
These are a couple of places I've found `Default` to be handy
=> Add Default to some types

embassy-executor/Cargo.toml, embassy-executor/src/arch/riscv32.rs, embassy-macros/Cargo.toml, embassy-macros/src/macros/main.rs
With these changes I can run embassy on our RISC-V processor, please consider merging this, feedback is very welcome.
I don't fully understand the code in the executor, but I have implemented a critical section by globally disabling interrupts, which means the wfi inside the critical section will hang the whole thing.
=> riscv fixes

embassy-boot/boot/Cargo.toml
=> fix: bump embassy-boot version

ci.sh, embassy-rp/src/rtc/mod.rs, embassy-rp/src/usb.rs, embassy-stm32/src/usb/usb.rs, embassy-sync/src/lib.rs, embassy-sync/src/pipe.rs, embassy-time/src/delay.rs, embassy-time/src/lib.rs, embassy-usb-driver/src/lib.rs, embassy-usb/src/class/hid.rs
Some issues I ran across after the AFIT stuff was merged.
=> Async function in trait cleanup

embassy-net/Cargo.toml, examples/stm32h7/Cargo.toml
=> Bump embedded-nal-async to 0.3.0

ci.sh, docs/modules/ROOT/pages/bootloader.adoc, embassy-boot/rp/Cargo.toml, embassy-boot/rp/README.md, embassy-boot/rp/build.rs, embassy-boot/rp/src/fmt.rs, embassy-boot/rp/src/lib.rs, embassy-rp/src/flash.rs, examples/boot/application/rp/.cargo/config.toml, examples/boot/application/rp/Cargo.toml, examples/boot/application/rp/README.md, examples/boot/application/rp/build.rs, examples/boot/application/rp/memory.x, examples/boot/application/rp/src/bin/a.rs, examples/boot/application/rp/src/bin/b.rs, examples/boot/bootloader/rp/.cargo/config.toml, examples/boot/bootloader/rp/Cargo.toml, examples/boot/bootloader/rp/README.md, examples/boot/bootloader/rp/build.rs, examples/boot/bootloader/rp/memory.x, examples/boot/bootloader/rp/src/main.rs
Add embassy-boot support for RP2040, with examples for the Raspberry Pi Pico.
=> feat: embassy-boot for rp2040

embassy-rp/src/gpio.rs, tests/rp/src/bin/gpio.rs
Needed for onewire and similar protocols.
=> rp: implement input for OutputOpenDrain

embassy-net/Cargo.toml, embassy-net/src/device.rs, embassy-net/src/stack.rs, embassy-net/src/tcp.rs, embassy-net/src/udp.rs
=> net: remove unsafe, update smoltcp.

embassy-hal-common/src/atomic_ring_buffer.rs
=> Atomic ringbuf fixes

examples/stm32f0/Cargo.toml, examples/stm32f0/src/bin/button_controlled_blink.rs, examples/stm32f0/src/bin/button_exti.rs, examples/stm32f0/src/bin/priority.rs, examples/stm32f0/src/bin/wdg.rs
Hello @lulf,
I added some more examples to stm32f0 and tested on hardware.
With love,
Imran
=> Add examples for stm32f0

embassy-rp/Cargo.toml, examples/rp/Cargo.toml
=> rp: switch to released 0.2.1 pio crate.

embassy-rp/src/uart/buffered.rs
Fixes an issue where only the first byte was transmitted. Should improve throughput aswell.
=> rp: Fill and empty FIFOs in buffered uart interrupt

embassy-nrf/src/uarte.rs
Many thanks for maintaining this project. Here is a minor typo fix.
=> Fix a typo

examples/stm32wl/src/bin/random.rs
Thanks Lulf for the help!
This should be added as example so other people can look it up easily.
With love,
Mia
=> Add random example

embassy-macros/src/macros/task.rs
I noticed that when I created doc comments for my tasks that the doc comments got included on the inner function but not the outer functions, I personally prefer keeping the documentation as clean as possible so this PR aims to hide the inner function and then add doc comments to the outer function.
The actual changes include:
* adding #[doc(hidden)] onto the `task_inner` function
* I flip flopped on this one because I could imagine someone may want this in their docs, but decided to include but I think arguments could be made either way
* copy the attributes from `task_inner` to `task_outer`
* I don't work with proc_macros often so I am not entirely sure if the way I went about it is correct but it seems to work fine
* specifically: using `parse_quote` to create the `task_outer` as a …
=> clean up doc comment generation

embassy-usb-driver/src/lib.rs
The call sequence is a bit tricky, and there's some gotchas around the status stage, and aborts by sending a new SETUP. Document all this! :) 
bors r+
=> usb/driver: document ControlPipe.

embassy-hal-common/src/atomic_ring_buffer.rs, embassy-rp/src/uart/buffered.rs, examples/rp/src/bin/uart_buffered_split.rs
* Refactor init code
* Make it possible to drop RX without breaking TX (or vice versa)
* Correctly handle RX buffer full scenario
=> More rp2040 BufferedUart fixes

embassy-net/Cargo.toml, embassy-net/src/device.rs, embassy-net/src/lib.rs, examples/nrf52840/src/bin/usb_ethernet.rs, examples/rp/src/bin/usb_ethernet.rs, examples/std/Cargo.toml, examples/std/src/bin/net.rs, examples/std/src/bin/net_udp.rs, examples/stm32f7/src/bin/eth.rs, examples/stm32h7/src/bin/eth.rs, examples/stm32h7/src/bin/eth_client.rs, examples/stm32l5/src/bin/usb_ethernet.rs
This PR updates the smoltcp version to the newest master one as well as implements the feature specified in #1154 - to allow the dhcpv4 socket to be configured.
Currently it should be considered a WIP PR - requires testing.
@Dirbaio can you have a look and check if this is compatible with what we discussed on the matrix channel?
=> WIP: Smoltcp socket config

embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/time.rs
=> stm32/rcc: print actual freqs on boot.

embassy-nrf/src/gpio.rs
From implies Into, so this won't break anything.
=> Implement From<gpio::Level> for bool

embassy-net/src/device.rs, examples/stm32h7/Cargo.toml
add proto-ipv6 feature to stm32h7 example to catch issues in CI
=> add missing copy of icmpv6 checksum

embassy-rp/src/usb.rs
The datasheet allows isochronous USB endpoints to be up to 1023 bytes in size (see "4.1.2.5. DPSRAM"). This PR changes the check to allow this and also changes the length computation to align to 64 bytes (instead of hardcoded 64 bytes).
Embassy does not yet support isochronous USB endpoints, however I'm investigating adding support. This change is simple enough and should be correct according to the datasheet, so maybe future implementers don't run into this issue.
=> rp: allow isochronous USB endpoints to be up to 1023 bytes in size

embassy-executor/src/raw/mod.rs, embassy-executor/src/raw/util.rs, embassy-executor/src/spawner.rs
The third commit may be slightly more controversial than the first two. Personally, I think it makes the code more readable and easier to reason about, but I can drop it if you disagree.
=> executor: Minor refactoring

embassy-time/src/driver_std.rs
...or to summarize it in another way, the code in the alarm thread loop is written as if - when calling the user-supplied callback - the callback will *never, ever* call `alarm.set_alarm()`.
But this happens of course - at least with the generic timer queue implementation. Not sure if that would happen with `embassy-executor`'s own queue, but probably yes?
The end result on Linux is that the code deadlocks because when calling the user-supplied callback, the mutex of the alarms is locked, yet - the code in `set_alarm` tries to take the lock again leading to UB. (I suspect on Windows this will crash rather than deadlock but that's a bit irrelevant.)
(Note also that calling the user-supplied callback *outside* of the alarms' lock is also NOK, because at that time, the callback and/or …
=> STD driver needs a reentrant mutex; logic fixed to be reentrancy-safe

embassy-net/Cargo.toml
=> net: use released smoltcp 0.9.0

embassy-stm32/src/fmc/mod.rs
This has been validated with the Is42s16400j sdram on stm32f429.
=> feat(stm32): Add 16 data bit fmc ctor

rust-toolchain.toml
=> Update Rust nightly.

embassy-nrf/src/qspi.rs
QSPI can't cancel DMA transfers. Before we'd panic on cancel, now we blocking-wait instead.
Blocking is not great, but it's better than panicking, especially when using code that's hardware-agnostic through the embedded-storage traits.
=> nrf/qspi: do not panic when canceling futures.

embassy-net/Cargo.toml, embassy-net/src/dns.rs, embassy-net/src/lib.rs, examples/nrf52840/src/bin/usb_ethernet.rs, examples/std/Cargo.toml, examples/std/src/bin/net_dns.rs, examples/stm32h7/Cargo.toml
=> Add DNS socket to embassy-net

embassy-futures/src/yield_now.rs, embassy-nrf/src/gpiote.rs, embassy-rp/src/dma.rs, embassy-rp/src/gpio.rs, embassy-rp/src/pio.rs, embassy-stm32/src/dma/mod.rs, embassy-stm32/src/exti.rs, embassy-sync/src/channel.rs, embassy-sync/src/pipe.rs, embassy-time/src/timer.rs
I think that's all of them, I just grep'd for `impl.* Future for`
=> Add `#[must_use]` to all futures

embassy-net/src/lib.rs
fixes #1237 
I am not sure, if this is the right place to put this code. Alternatively, It could be in dns::DnsSocket or reqwless (and all other libraries that need to maybe resolve hostnames).
Are there other DNS query-types where it would make sense to try to parse an IP address?
=> embassy-net: DNS resolver detects when name is just an IP address

embassy-rp/src/uart/mod.rs
The following PR attepts to bring fuctionality to allow change od UART baudrate changes during runtime.
Changes where created under @Dirbaio supervision and discussed on issue:
[https://github.com/embassy-rs/embassy/issues/1241#issuecomment-1445500175]( https://github.com/embassy-rs/embassy/issues/1241#issuecomment-1445500175)
=> RP-PICO UART adding set_baudrate

embassy-hal-common/src/atomic_ring_buffer.rs
This allows a writer to access all of the free space in the buffer, even
when it's wrapping around.
=> hal-common/atomic_ring_buffer: add push_bufs() push_slices()

embassy-usb/src/class/cdc_acm.rs
This adds a `split(self)` function for the `CdcAcmClass`, allowing separate send and receive tasks.
=> embassy_usb: Add split() for cdc_acm

embassy-time/src/timer.rs
It was Unpin before #1248 
bors r+
=> time/ticker: make sure the future for .next() is Unpin.

embassy-nrf/src/lib.rs
This mirrors what nrfx does. Also it won't reboot/warn if NFCPINS is set to either 0xFFFF_FFFE or 0x0000_0000, which are all valid.
bors r+
=> nrf/uicr: only check lowest bit.

embassy-macros/src/macros/main.rs, embassy-macros/src/macros/task.rs, examples/stm32f4/src/bin/i2c.rs, examples/stm32f4/src/bin/sdmmc.rs, examples/stm32f7/src/bin/eth.rs, examples/stm32f7/src/bin/sdmmc.rs, examples/stm32h7/src/bin/eth.rs, examples/stm32h7/src/bin/eth_client.rs, examples/stm32h7/src/bin/i2c.rs, examples/stm32l4/src/bin/i2c.rs, examples/stm32l4/src/bin/i2c_blocking_async.rs, examples/stm32l4/src/bin/i2c_dma.rs
=> macros: better validation of function signatures.

embassy-net/Cargo.toml, embassy-net/src/lib.rs, embassy-net/src/udp.rs
This should make it possible to implement mDNS for embassy-net, which in turn is essential for smart home
=> Add multicast to udp socket

embassy-rp/src/uart/buffered.rs, embassy-rp/src/uart/mod.rs, tests/rp/src/bin/uart_upgrade.rs
Also implement blocking embedded-nal serial traits for BufferedUart
=> (embassy-rp): Allow upgrading a blocking uart to a BufferedUart

embassy-stm32/src/rcc/l0.rs, embassy-stm32/src/rcc/l1.rs, embassy-stm32/src/rcc/l4.rs, embassy-stm32/src/rcc/l5.rs, embassy-stm32/src/rcc/u5.rs, embassy-stm32/src/rcc/wb.rs, embassy-stm32/src/rcc/wl.rs
=> Fix APB clock calculation for several STM32 families

embassy-rp/src/dma.rs, embassy-rp/src/spi.rs, tests/rp/src/bin/spi_async.rs
=> fix(rp): spi transfer

embassy-sync/src/pipe.rs
There was some language copypasted from Channel talking about "messages" or "values", that is not really accurate with Pipe.
bors r+
=> sync/pipe: update to clarify docs that it is byte-oriented.

embassy-stm32/build.rs, embassy-stm32/src/lib.rs, embassy-stm32/src/qspi/enums.rs, embassy-stm32/src/qspi/mod.rs
Implemented with help of Tomasz Grześ <tomasz.grzes@gmail.com>.
Tested only on stm32f777zi.
=> Add support for `QSPI` in `stm32`

embassy-rp/src/uart/mod.rs
See [comment](https://github.com/embassy-rs/embassy/pull/1243#issuecomment-1492894626)
=> Fix set_baudrate on RP-PICO

embassy-rp/src/uart/buffered.rs
Prevents the read methods from getting stuck forever.
cc @MathiasKoch can you test if this fixes the problem you described in the chat?
=> rp: Allow zero len reads for buffered uart

embassy-boot/boot/src/boot_loader.rs, embassy-boot/boot/src/firmware_updater.rs, embassy-boot/boot/src/firmware_writer.rs, embassy-boot/boot/src/lib.rs, embassy-boot/boot/src/partition.rs
This change should not have any breaking changes.
=> Let bootloader partition have read/write/erase operations

embassy-boot/boot/src/partition.rs
This is needed now where FirmwareWriter is removed.
=> Expose read/write/erase on partition

embassy-stm32/src/adc/mod.rs, embassy-stm32/src/adc/resolution.rs, embassy-stm32/src/adc/sample_time.rs, embassy-stm32/src/adc/v1.rs, examples/stm32f0/src/bin/adc.rs
=> STM32: Adc V1

embassy-executor/src/raw/mod.rs, embassy-executor/src/raw/run_queue.rs
I couldn't figure out the correct orderings, so I just left them as SeqCst for now.
=> executor: Replace unsound critical sections with atomics

embassy-executor/Cargo.toml, rust-toolchain.toml
Forgot to update them in #1321 
bors r+
=> executor: fix doc features.

embassy-stm32/src/rcc/f4.rs, embassy-stm32/src/rcc/mod.rs
Adds the i2s pll on some f4 micros.
=> stm32/rcc: add i2s pll on some f4 micros

embassy-rp/Cargo.toml, embassy-rp/src/lib.rs
=> rp: switch to released rp-pac v1.0

embassy-hal-common/src/macros.rs, embassy-stm32/build.rs, examples/stm32g4/src/bin/pwm.rs
After multiple ways of looking at this, this is the best solution I could think of.
=> stm32: remove TIMX singleton when used on timer driver

embassy-rp/src/rom_data.rs
storing a full function pointer initialized to a resolver trampoline lets us avoid the runtime cost of checking whether we need to do the initialization. this also slightly reduces flash usage due to a slightly more space-efficient initialization procedure.
=> rp: optimize rom-func-cache for runtime

embassy-rp/Cargo.toml, embassy-rp/src/clocks.rs, embassy-rp/src/lib.rs, embassy-rp/src/pwm.rs, embassy-rp/src/usb.rs, examples/rp/src/bin/pwm.rs, tests/rp/src/bin/pwm.rs
add PWM api ~~including interrupts and async support.~~
depends on https://github.com/embassy-rs/rp-pac/pull/1
**TODO**:
=> rp: add PWM api

embassy-rp/Cargo.toml, embassy-rp/src/lib.rs, examples/rp/Cargo.toml
We shouldn't have Cargo features if their only purpose is reduce cold build time a bit.
bors r+
=> rp: remove pio Cargo feature.

embassy-rp/src/flash.rs
This PR changes the old behaviour during flash operations where all DMA transfers were paused during the flash operation.
The new approach is to wait for any DMA operating in flash region to finish and let RAM transfers continue.
=> rp: DMA behaviour during flash operations

embassy-rp/src/i2c.rs
=> Add `Transactional` trait to rp's i2c impl

embassy-stm32/src/usart/mod.rs
This PR aborts the DMA transfer in the event of a UART error. Otherwise, the transfer will never complete, and an error will not be returned.
=> stm32/uart: abort on error

embassy-rp/src/lib.rs, embassy-rp/src/pio.rs, examples/rp/src/bin/pio_async.rs, examples/rp/src/bin/pio_dma.rs, examples/rp/src/bin/ws2812-pio.rs
the pio module is currently in a Bit of a State. this is far from all that's needed to make it more useful, but it's a start.
=> rp/pio: bit of a rework

embassy-rp/src/uart/mod.rs, tests/rp/src/bin/uart_dma.rs
forgot to remove these when they were no longer necessary or useful. oops.
=> rp: remove leftovers from #1414

embassy-stm32/Cargo.toml, embassy-stm32/src/usart/buffered.rs, embassy-stm32/src/usart/mod.rs, tests/stm32/Cargo.toml, tests/stm32/build.rs, tests/stm32/src/bin/spi.rs, tests/stm32/src/bin/usart.rs, tests/stm32/src/bin/usart_dma.rs, tests/stm32/src/bin/usart_rx_ringbuffered.rs, tests/stm32/src/example_common.rs
Fixes #1183 
Fixes #1418 
bors r+
=> stm32/usart: add OVER8 and PRESC, add baudrate test.

embassy-stm32/src/rcc/f1.rs
See figure 2. Clock tree page 12 DS5319 Rev 18
https://www.st.com/resource/en/datasheet/stm32f103cb.pdf
=> Support PLLXTPRE switch.

docs/modules/ROOT/pages/getting_started.adoc, embassy-hal-common/src/atomic_ring_buffer.rs, embassy-nrf/src/nvmc.rs, embassy-nrf/src/twim.rs, embassy-nrf/src/twis.rs, embassy-rp/src/flash.rs, embassy-rp/src/i2c.rs, embassy-rp/src/uart/buffered.rs, embassy-rp/src/uart/mod.rs, embassy-stm32/src/time_driver.rs, embassy-stm32/src/usart/mod.rs, embassy-usb-driver/src/lib.rs, embassy-usb/src/class/cdc_ncm/mod.rs, embassy-usb/src/class/hid.rs, embassy-usb/src/msos.rs, examples/nrf52840/src/bin/pubsub.rs, examples/nrf52840/src/bin/usb_serial.rs, examples/nrf52840/src/bin/usb_serial_multitask.rs, examples/nrf52840/src/bin/usb_serial_winusb.rs, examples/rp/src/bin/usb_serial.rs, examples/stm32f0/src/bin/button_controlled_blink.rs, examples/stm32f4/src/bin/usb_serial.rs, examples/stm32f7/src/bin/usb_serial.rs, examples/stm32h5/src/bin/usb_serial.rs, examples/stm32h7/src/bin/usb_serial.rs, examples/stm32l4/src/bin/usb_serial.rs, examples/stm32u5/src/bin/usb_serial.rs, examples/stm32wl/src/bin/uart_async.rs
This pull request fixes some typos, no functional changes intended.
=> Fix some typos

embassy-stm32/src/usart/mod.rs, tests/stm32/src/bin/usart.rs
Clear and report the error flags one by one and pop the data byte only after all error flags were handled.
For v1/v2 we emulate the v3/v4 behaviour by buffering the status register because a read to the data register clears all flags at once which means we might loose all but the first error.
Only tested on stm32f3 discovery board with loopback. Let‘s see what CI says for the other families.
Fixes #1452
=> stm32 uart: Fix error flag handling for blocking operations

embassy-stm32/src/flash/f0.rs, embassy-stm32/src/flash/mod.rs
i've copied and modified the f3 implementation and it seems to be working.
=> stm32f0 flash implementation

embassy-embedded-hal/src/lib.rs, embassy-net/src/lib.rs, embassy-nrf/src/lib.rs, embassy-stm32/src/lib.rs, embassy-usb/src/lib.rs
=> Remove unused `feature(type_alias_impl_trait)`.

embassy-net-driver/README.md, embassy-net-driver/src/lib.rs, embassy-net/Cargo.toml, embassy-net/src/dns.rs, embassy-net/src/lib.rs, embassy-net/src/tcp.rs, embassy-net/src/time.rs, embassy-net/src/udp.rs, examples/nrf52840/src/bin/usb_ethernet.rs, examples/rp/src/bin/usb_ethernet.rs, examples/std/src/bin/net.rs, examples/std/src/bin/net_udp.rs, examples/stm32f4/src/bin/usb_ethernet.rs, examples/stm32f7/src/bin/eth.rs, examples/stm32h5/src/bin/eth.rs, examples/stm32h7/src/bin/eth.rs, examples/stm32l5/src/bin/usb_ethernet.rs
=> net: do not use smoltcp Instant/Duration in public API, docs.

embassy-rp/src/multicore.rs
=> rp/multicore: ensure stack is 8-byte aligned.

ci.sh, embassy-stm32/src/lib.rs, embassy-stm32/src/usb/usb.rs
=> stm32/usb: do not require embassy-time.

embassy-stm32/src/ipcc.rs, embassy-stm32/src/tl_mbox/ble.rs, embassy-stm32/src/tl_mbox/channels.rs, embassy-stm32/src/tl_mbox/consts.rs, embassy-stm32/src/tl_mbox/evt.rs, embassy-stm32/src/tl_mbox/mm.rs, embassy-stm32/src/tl_mbox/mod.rs, embassy-stm32/src/tl_mbox/shci.rs, embassy-stm32/src/tl_mbox/sys.rs, embassy-stm32/src/tl_mbox/unsafe_linked_list.rs, examples/stm32wb/memory.x, examples/stm32wb/src/bin/tl_mbox.rs, examples/stm32wb/src/bin/tl_mbox_tx_rx.rs, tests/stm32/Cargo.toml, tests/stm32/build.rs, tests/stm32/memory_ble.x, tests/stm32/src/bin/ble.rs
Hello,
This pull request is related to #1397 and #1401, inspired by #24, built upon the work done in #1405 and #1424, and was tested on an stm32wb55rg.
This pull request aims to add read and write functionality to the TL mailbox for stm32wb microcontrollers
=> TL Mbox read and write for stm32wb

embassy-embedded-hal/src/shared_bus/asynch/i2c.rs
Not sure why this was a todo before, but this seems to be working fine in my limited testing.
=> embassy-embedded-hal: Add i2c transaction to I2cDevice

embassy-stm32/src/rcc/l4.rs
To select and setup LSE and/or LSI
=> feature(embassy-stm32): add RTC MUX selection to embassy-stm32 L4 family

embassy-stm32/src/usart/mod.rs
Effectively setting cr3.onebit
=> Add assume_noise_free to usart configuration

embassy-embedded-hal/src/flash/mod.rs, embassy-embedded-hal/src/flash/partition/asynch.rs, embassy-embedded-hal/src/flash/partition/blocking.rs, embassy-embedded-hal/src/flash/partition/mod.rs
~~This currently does not compile as the blocking mutex does not provide a `&mut T`?~~ This should be ready.
=> Add BlockingPartition

.github/ci/build-stable.sh, .github/ci/build.sh, .github/ci/test.sh, ci_stable.sh, embassy-embedded-hal/src/shared_bus/blocking/i2c.rs, embassy-embedded-hal/src/shared_bus/blocking/spi.rs, embassy-hal-common/src/atomic_ring_buffer.rs, embassy-nrf/src/time_driver.rs, embassy-stm32/src/flash/common.rs, embassy-stm32/src/pwm/complementary_pwm.rs, embassy-time/Cargo.toml, embassy-time/src/driver.rs, embassy-time/src/queue_generic.rs, embassy-time/src/timer.rs
=> ci: add stable build, add tests.

.github/ci/doc.sh, ci.sh, embassy-stm32/src/rtc/v3.rs
Let's see if it explodes or not. On GHA it would explode because it ran out of disk space.
=> Add embsasy-stm32 docs build.

embassy-rp/src/spi.rs
see https://github.com/raspberrypi/pico-sdk/blob/master/src/rp2_common/hardware_spi/spi.c#L27-L28
=> rp/spi: enable rxdmae/txdmae only once at init.

embassy-rp/src/gpio.rs, embassy-stm32/src/gpio.rs
See #1171 but for STM and RP also
=> Replace Into<bool> for Level with From<Level> for bool

embassy-nrf/src/uarte.rs
Introduce `with_idle()` to upgrade an `UarteRx` instance to `UarteRxWithIdle`. Use the method in the split constructor aswell.
=> embassy-nrf: Idle detection for RX only uarte

ci.sh, embassy-net-esp-hosted/Cargo.toml, embassy-net-esp-hosted/src/control.rs, embassy-net-esp-hosted/src/esp_hosted_config.proto, embassy-net-esp-hosted/src/fmt.rs, embassy-net-esp-hosted/src/ioctl.rs, embassy-net-esp-hosted/src/lib.rs, embassy-net-esp-hosted/src/proto.rs, examples/nrf52840/Cargo.toml, examples/nrf52840/src/bin/wifi_esp_hosted.rs, tests/nrf/Cargo.toml, tests/nrf/src/bin/wifi_esp_hosted_perf.rs
https://github.com/espressif/esp-hosted
TODO:
=>  esp-hosted embassy-net driver.

embassy-rp/src/adc.rs
Changed ```Adc::blocking_read``` to behave the same way as the async ```Adc::read``` by disabling the pull-up and pull-down resistors before starting the adc.
Note that this increases the time it takes the function to run slightly, in my measurements with default settings it took on average 3.00 µs instead of 2.89 µs.
=> disable pull-up and down resistors for rp adc blocking_read

embassy-usb/src/class/cdc_ncm/mod.rs, embassy-usb/src/lib.rs
=> usb: add missing builder reexports.

embassy-nrf/src/ppi/mod.rs
Added utility methods to NRF Task + Event structs.
=> feature(1355): Add trigger to task, triggered + clear to Event

embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/gpiote.rs, embassy-nrf/src/ppi/dppi.rs, embassy-nrf/src/ppi/mod.rs, embassy-nrf/src/ppi/ppi.rs, embassy-nrf/src/pwm.rs, embassy-nrf/src/saadc.rs, embassy-nrf/src/timer.rs
Added in lifetimes for ppi Events + Tasks
=> feature(1354): Added lifetimes to Event + Tasks

embassy-rp/src/lib.rs, embassy-rp/src/pio.rs, examples/rp/src/bin/pio_async.rs, examples/rp/src/bin/pio_dma.rs, examples/rp/src/bin/pio_hd44780.rs, examples/rp/src/bin/pio_ws2812.rs, examples/rp/src/bin/wifi_ap_tcp_server.rs, examples/rp/src/bin/wifi_blinky.rs, examples/rp/src/bin/wifi_scan.rs, examples/rp/src/bin/wifi_tcp_server.rs, tests/rp/Cargo.toml, tests/rp/src/bin/cyw43-perf.rs, tests/rp/src/bin/pio_irq.rs
=> rp/pio: use bind_interrupts for irqs

embassy-net/src/udp.rs
=> Adding polling functions for udp send_to and recv_from.

embassy-stm32/src/eth/generic_smi.rs, embassy-stm32/src/eth/mod.rs, embassy-stm32/src/eth/v1/mod.rs, embassy-stm32/src/eth/v2/mod.rs, examples/stm32f4/src/bin/eth.rs, examples/stm32f7/src/bin/eth.rs, examples/stm32h5/src/bin/eth.rs, examples/stm32h7/src/bin/eth.rs, examples/stm32h7/src/bin/eth_client.rs
=> stm32/eth: solve busy-loop polling

embassy-stm32-wpan/src/mac/commands.rs, embassy-stm32-wpan/src/mac/event.rs, embassy-stm32-wpan/src/mac/helpers.rs, embassy-stm32-wpan/src/mac/indications.rs, embassy-stm32-wpan/src/mac/mod.rs, embassy-stm32-wpan/src/mac/responses.rs, embassy-stm32-wpan/src/mac/typedefs.rs, embassy-stm32-wpan/src/sub/mac.rs, examples/stm32wb/src/bin/mac_ffd.rs, examples/stm32wb/src/bin/mac_rfd.rs, tests/stm32/src/bin/wpan_mac.rs
...and correctly control tx buffer lifetime.
=> wpan/mac: use slice view to avoid copy

embassy-net/src/lib.rs
The original [multicast PR](https://github.com/embassy-rs/embassy/pull/1264/files#diff-dd4daeb7962fbcb73155aa6ce2683eba0c7182796936378e1e8d4dc22d04b2b5R308) implemented multicast support by requiring the Driver to implement `smoltcp::phy::Device`. 
However, I don't think the "implements `smoltcp::phy::Device`" contract is fulfilled when the driver is based on `embassy-net-driver-channel` (e.g., [the W5500 driver](https://github.com/embassy-rs/embassy/blob/main/embassy-net-w5500/Cargo.toml#L13)), rendering multicast support unavailable on these drivers.
Moreover, the current API is blocking, which is weird. To my understanding, joining/leaving a multicast group involves sending a packet, so these should be async as the sending might fail (queue full)?
Disclaimer: Not sure if I arranged and …
=> Fix multicast support

README.md, examples/stm32c0/Cargo.toml, examples/stm32f0/Cargo.toml, examples/stm32f1/Cargo.toml, examples/stm32f2/Cargo.toml, examples/stm32f3/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32f7/Cargo.toml, examples/stm32g0/Cargo.toml, examples/stm32g4/Cargo.toml, examples/stm32h5/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l0/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32l5/Cargo.toml, examples/stm32u5/Cargo.toml, examples/stm32wb/Cargo.toml, examples/stm32wl/Cargo.toml
This caught me out yesterday and someone else on Matrix today, so it seems like an easy beginner's mistake, and the only symptom is that the example programs OK but then totally fails to run with no error.
=> Add notes about setting chip name correctly for examples

tests/stm32/Cargo.toml, tests/stm32/src/bin/dac.rs, tests/stm32/src/common.rs
=> [STM32] Add DAC HIL test with ADC

ci.sh, embassy-net/src/lib.rs
/cc @xoviat 
I had some duplicate work lying around with @xoviat's #1655 (and I still have some more), and this is part of the result of some rebase conflicts. @xoviat, to what extent are you planning to add sixlowpan to Embassy?
=> Allow ethernet and 802.15.4 to coexist

examples/rp/src/bin/pio_uart.rs
Prevent UART from only getting 0s from the output
=> Uart pio fix zeros

embassy-stm32/src/flash/g0.rs, embassy-stm32/src/flash/mod.rs, examples/stm32g0/src/bin/flash.rs
This pull request adds flash support for STM32G0 series in Embassy. The implementation has been tested and works as expected. Also, added a working example. Feedback is welcome.
=> Added STM32G0 Flash Support

embassy-rp/src/rom_data.rs
When #1384 changed the ROM cache optimization it unfortunately introduced some subtle breakage.  The flash functions assume that a call to `::ptr()` returns the actual ROM address (since they need to operate without any calls into XIP), but after the optimization the first call will return the trampoline.  The trampoline itself is (likely) located in flash, so when the flash operation functions try to use it with XIP disabled, they immediately hard fault.
So this just separates out the `::ptr()` function into a version that uses the full optimization for the direct calls and one that uses a slightly less efficient version but will always return a ROM pointer.
=> rp: Fix ROM cache ptr() returning the trampoline

embassy-rp/src/adc.rs, embassy-rp/src/lib.rs, examples/rp/src/bin/adc.rs, tests/rp/src/bin/adc.rs
minimal dma-from-adc implementation to get things started that can hopefully be the basis for an update of #1608. we just happen to need dma adc a bit earlier and without continuous sampling support, so here we are :)
=> rp: add dma-from-adc

embassy-rp/src/gpio.rs
this temporarily takes ownership of pins, mostly because we want to clean up the dormant-wake bits after a wakeup and because doing anything *else* with the input while we're waiting for a wakeup isn't possible at all. doing it like this lets us not impose any cost on those who don't use dormant wakes.
the error type for dormant-wake setup is dependent on the static type of the pin being used. this allows us to support dormant-wake for AnyPin and still allowing eg unwrap-infallibe in cases where pin types are statically known.
=> rp: add dormant-wake functionality for Input

.vscode/settings.json, embassy-net-enc28j60/Cargo.toml, embassy-net-enc28j60/README.md, embassy-net-enc28j60/src/bank0.rs, embassy-net-enc28j60/src/bank1.rs, embassy-net-enc28j60/src/bank2.rs, embassy-net-enc28j60/src/bank3.rs, embassy-net-enc28j60/src/common.rs, embassy-net-enc28j60/src/fmt.rs, embassy-net-enc28j60/src/header.rs, embassy-net-enc28j60/src/lib.rs, embassy-net-enc28j60/src/macros.rs, embassy-net-enc28j60/src/phy.rs, embassy-net-enc28j60/src/traits.rs, examples/nrf52840/Cargo.toml, examples/nrf52840/src/bin/ethernet_enc28j60.rs
based on https://github.com/japaric/enc28j60
TODO:
no time to do the remaining items, will do later. Driver works fine as-is if you're OK with 100% cpu usage, I've been using in production for years.
=> wip: enc28j60 driver.

embassy-net/src/tcp.rs
- Add async versions of smoltcp's `send` and `recv` closure based API.
Two things I'm not sure about:
- I copied the docs for the functions from smoltcp, is this correct, or should I link to the smoltcp docs instead?
- How to handle `Err(tcp::RecvError::Finished)`, I don't think this is an error, but we can't return `Ok()` because the type is defined by the return type closure. For now I just treated it as an error, because it should only happen when the socket is closed.
=> embassy-net:tcp:write_with/read_with

embassy-rp/src/dma.rs
I have no idea why this fixes it, but...
¯\\\_(ツ)_/¯
=> rp: fix async spi read sometimes hanging.

embassy-stm32/src/rcc/f2.rs
This makes sure to check the RCC settings and derived clocks for hardware compatibility before applying them. Previously the check would be run _after_ setting the parameters, possibly making the execution unreliable when parameters are out of bounds.
=> stm32f2: Check RCC settings before applying

embassy-net-esp-hosted/src/control.rs, embassy-net-esp-hosted/src/lib.rs, examples/nrf52840/src/bin/wifi_esp_hosted.rs, tests/nrf/src/bin/wifi_esp_hosted_perf.rs
See individual commit messages.
=> net-esp-hosted: misc improvements.

ci.sh, embassy-lora/Cargo.toml, embassy-stm32/src/adc/mod.rs, embassy-stm32/src/adc/sample_time.rs, embassy-stm32/src/rcc/mod.rs
originally broke in https://github.com/embassy-rs/embassy/pull/1762
=> stm32: fix f37x build.

embassy-usb/src/class/cdc_ncm/mod.rs
NCM is working without any issues with hardcoded buffer length of 64 on USB FullSpeed. But on USB HighSpeed, where maximum packet size for bulk endpoints is 512, it is failing. Even if 64 is provided to the CdcNcmClass:new().
Probably the underlying USB driver or USB hardware is still sending full packets even if length 64 is configured, leaving majority of the packet filled with zeros.
Tested on STM32H743ZI in FS mode and on STM32H747XI in HS mode (ULPI). Pings and simple TCP loopback are working fine now, Wireshark also do not show any apparent issues.
=> Fix hardcoded buffer length in USB NCM causing broken link on USB 2.0.

embassy-executor/CHANGELOG.md, embassy-executor/src/raw/mod.rs, embassy-executor/src/spawner.rs
This change should allow custom TaskStorage implementations
=> Make `AvailableTask` public

cyw43/src/bus.rs
This PR lowers gSPI bus overhead during wlan iface writes by ***quite*** a lot for small packet transfers. Below are a couple "hello world" transfers over gSPI before the change. After the change everything after the space should be "trimmed". Resolves #1809.
<details>
```
cmd× 1 addr=    0x0  fn=     wlan  sz=  84 write= true autoinc= true data=0x5400abff2802000e00000000000020000000d85ed34303eb28cdc1054d3e080045000034000040004006b668c0a80178c0a8019304d2d6f2bf2a63aa092b1b145018100066b3000068656c6c6f20776f726c640a 00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000 …
```
=> rp::wlan_write: avoid ineffectual writing of entire buffer over spi

embassy-stm32/src/rcc/f4.rs, embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/rtc/mod.rs, embassy-stm32/src/rtc/v2.rs
=> stm32/rtc: add start/stop wakeup

embassy-net-driver-channel/src/lib.rs, embassy-net-ppp/Cargo.toml, embassy-net-ppp/README.md, embassy-net-ppp/src/fmt.rs, embassy-net-ppp/src/lib.rs, embassy-net/Cargo.toml, embassy-net/src/lib.rs, examples/std/Cargo.toml, examples/std/src/bin/net_ppp.rs
=> Add embassy-net-ppp driver.

embassy-stm32/src/rng.rs
If no data was available to read then the loop would wait for an interrupt and skip to the next chunk without writing the current one. This could cause the given slice to only be partially filled with random data.
Fixed by moving the wait to before actually writing data to the chunk.
=> stm32: fix wait for RNG data

ci.sh
This reverts commit c5732ce2857ce4028a2e03abeb65254200473e5a.
=> Revert "ci: remove failing tests"

embassy-stm32/src/rcc/f2.rs
This is essentially a port of this https://github.com/embassy-rs/embassy/pull/1785 to the F2, as well as re-adding the work around added in https://github.com/embassy-rs/embassy/pull/1721. Doesn't currently support HSE as the RTC clock source.
=> [F2] Allow the RTC clock source to be configured with the new RTC mechanism

embassy-stm32/Cargo.toml, embassy-stm32/src/adc/v4.rs, embassy-stm32/src/rcc/g4.rs, embassy-stm32/src/rcc/mod.rs, examples/stm32g4/Cargo.toml, examples/stm32g4/src/bin/adc.rs
I also create PR embassy-rs/stm32-data#244 for STM32G4 ADC.
but my stm32-data PR will break embassy-stm32 build until this PR is merged.
What is the recommended workflow for this case?
=> initial support for STM32G4 ADC

embassy-net-adin1110/src/lib.rs, embassy-net-adin1110/src/mdio.rs, embassy-net-adin1110/src/phy.rs
Some spelling, comments and document fixes.
Re-enable mdio tests.
=> Adin1110: documents and comment fixes

embassy-stm32/src/adc/f1.rs, embassy-stm32/src/hrtim/mod.rs, embassy-stm32/src/hrtim/traits.rs, embassy-stm32/src/rcc/f1.rs, embassy-stm32/src/rcc/f3.rs, embassy-stm32/src/rcc/mod.rs, examples/stm32f334/src/bin/adc.rs, examples/stm32f334/src/bin/pwm.rs
this adds high resolution for hrtim on f334 and consolidates the adc member of the clocks struct
=> stm32/f3: add high res for hrtim and misc.

embassy-stm32/Cargo.toml, embassy-stm32/src/sdmmc/mod.rs
Draft until https://github.com/embassy-rs/stm32-data/pull/250 is merged.
=> Handle stbiterr in 4bit wide mode for sdmmc_v1

embassy-net/src/udp.rs
When I forgot to call `bind` before sending, I received a "NoRoute" error, which was confusing.
This PR attempts to provide a more helpful error in this case.
Maybe there are other cases where this may happen. If so, please let me know so I can add them.
=> embassy-net: Improve error when socket is not bound

embassy-stm32/Cargo.toml, examples/stm32h5/Cargo.toml, examples/stm32h7/Cargo.toml
=> stm32: bump fmc version

embassy-stm32/src/rtc/v2.rs
=> Fix low-power feature for STM32L0

embassy-stm32/build.rs, embassy-stm32/src/adc/f3.rs, embassy-stm32/src/adc/mod.rs, embassy-stm32/src/rcc/f3.rs
generate adc_common, which is more flexible than the current hardcoding
=> stm32: generate adc_common and misc.

embassy-stm32/src/rtc/mod.rs
This struct allows users to acquire the current time without putting `Rtc` in a mutex and passing that around. This is allowed because reading from the rtc registers is atomic.
I also added `#[non_exhaustive]` to `Rtc` as it was possible to construct it when the `low-power` feature wasn't enabled.
=> stm32: Add RtcTimeProvider struct to Rtc module

embassy-stm32-wpan/src/sub/ble.rs, embassy-stm32-wpan/src/sub/mac.rs, embassy-stm32-wpan/src/sub/mm.rs, embassy-stm32-wpan/src/sub/sys.rs, embassy-stm32/src/rcc/bd.rs, embassy-stm32/src/rcc/f2.rs, embassy-stm32/src/rcc/f4.rs, embassy-stm32/src/rcc/l0.rs, embassy-stm32/src/rcc/l4.rs, embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/rcc/wb.rs, embassy-stm32/src/rcc/wl.rs, embassy-stm32/src/rtc/mod.rs, tests/stm32/src/bin/rtc.rs, tests/stm32/src/bin/stop.rs
=> stm32: update configure_ls and misc cleanup

embassy-stm32/src/rcc/bd.rs, embassy-stm32/src/rtc/mod.rs
see matrix: [https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$EgVA3feRvfxNGKcBCyZJatOqWE3AdC3LxCcGsSfD4oI?via=matrix.org&via=tchncs.de&via=rubdos.be](https://matrix.to/#/!YoLPkieCYHGzdjUhOK:matrix.org/$EgVA3feRvfxNGKcBCyZJatOqWE3AdC3LxCcGsSfD4oI?via=matrix.org&via=tchncs.de&via=rubdos.be)
=> fix low-power: APB1 needed for LSE

embassy-stm32/src/rtc/v2.rs, embassy-stm32/src/time_driver.rs, tests/stm32/src/bin/stop.rs
credit from chrenderle/embassy@7ddddc4e30d34d4876ad784a5f3253a2049fdfcf, this also adds a regression test and consolidates all timer driver ops to a single critical section.
=> stm32/low-power: create one critical-section for all time ops

embassy-stm32/src/rtc/v2.rs
I don't have time to review this today, will look tomorrow.
=> stm32/lp: clamp requested_duration

embassy-stm32/src/timer/mod.rs
This pull requests add support to embassy_stm32 for the input capture mode
registers. It covers most of them. I will add the remainder in a future PR.
It is a fairly straightforward approach. The only non-obvious things are:
1. The input capture polarity is controlled by two registers, so we introduce an enum
to represent it
2. The TI selection register has the wrong definitions in the SVD file, and is often
confusing to users, so we introduce an enum to make obvious what it is controlling.
=> Add support for input capture function

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/lib.rs
This PR replaces #1895 since it was necessary to rebase and update stm32-metapac. To avoid breaking the other branch, I created a new PR here.
=> [STM32] Handle STM32H7 "_C" pins (rebased)

examples/rp/src/bin/wifi_ap_tcp_server.rs, examples/rp/src/bin/wifi_blinky.rs, examples/rp/src/bin/wifi_scan.rs, examples/rp/src/bin/wifi_tcp_server.rs
- Update firmware blob sizes in `from_raw_parts` to current size
- Add wait for DHCP for `wifi_tcp_server` (caused confusion in #1234, #1791)
Love this project, thanks!
=> cyw43: Update examples

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/rcc/c0.rs, embassy-stm32/src/rcc/f2.rs, embassy-stm32/src/rcc/f3.rs, embassy-stm32/src/rcc/g0.rs, embassy-stm32/src/rcc/g4.rs, embassy-stm32/src/rcc/h.rs, embassy-stm32/src/rcc/l0.rs, embassy-stm32/src/rcc/l1.rs, embassy-stm32/src/rcc/l4.rs, embassy-stm32/src/rcc/l5.rs, embassy-stm32/src/rcc/wb.rs, embassy-stm32/src/rcc/wba.rs, embassy-stm32/src/rcc/wl.rs, embassy-stm32/src/time.rs, examples/stm32f334/src/bin/adc.rs, examples/stm32f334/src/bin/opamp.rs, examples/stm32g4/src/bin/adc.rs, tests/stm32/src/common.rs
=> stm32/rcc: use more PLL etc enums from PAC.

embassy-stm32/build.rs, embassy-stm32/src/rcc/h.rs, embassy-stm32/src/rcc/mod.rs
failing tests:
- out/tests/stm32h563zi/spi_dma
- out/tests/stm32h563zi/spi
- out/tests/stm32h563zi/usart_dma
- out/tests/stm32h563zi/usart
=> stm32: add rcc mux for h5

embassy-usb/src/class/midi.rs, embassy-usb/src/class/mod.rs, examples/rp/src/bin/usb_midi.rs
=> embassy-usb: Add MIDI class

embassy-executor/src/raw/waker.rs
Detailed discussion is here: https://github.com/rust-lang/rust/issues/117047
=> Fix #2100 - function address comparison

embassy-stm32/src/low_power.rs, embassy-stm32/src/rtc/datetime.rs, embassy-stm32/src/rtc/mod.rs, embassy-stm32/src/rtc/v2.rs, embassy-stm32/src/rtc/v3.rs
- move to bypassshadow by default
- cleanup misc. stop and rtc code
=> stm32/rtc: misc and low-power cleanup 

examples/rp/src/bin/pwm_input.rs
Example how to measure the frequency of an input signal using the PWM module.
=> rp: Add PWM input example

embassy-stm32/src/usb_otg/usb.rs
=> stm32/otg: fix enumeration on non-f4 chips.

embassy-executor/CHANGELOG.md, embassy-executor/Cargo.toml, embassy-executor/src/arch/riscv32.rs
The PR also removes an unused dependency.
=> Executor: Yeet core::sync::atomic from risc-v

examples/rp/Cargo.toml, examples/rp/src/bin/usb_raw_bulk.rs
Example of using USB without a pre-defined class, but instead using raw USB bulk transfers.
=> rp: Add USB raw bulk example

examples/rp/src/bin/usb_raw_bulk.rs
...to clarify you don't actually *need* a custom control handler if you only care about the bulk transfers, if that was unclear :)
=> rp: Remove control handler from USB raw bulk example

embassy-stm32/src/eth/v2/descriptors.rs
=> stm32: resolve eth/v2 security bug

ci.sh, embassy-stm32/build.rs, embassy-stm32/src/sai/mod.rs
=> stm32/sai: fix build on chips with only SAI4 (like stm32h725re), improve sync config.

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/faq.adoc
Just provoking @Dirbaio to make his life easier in the future :)
=> Add FAQ with one question from chat

embassy-embedded-hal/src/shared_bus/blocking/spi.rs
New behaviour: check for `DelayUs` presence in operations instead of shortcircuiting.
Closes #2227
=> embassy-embedded-hal: shared_bus/blocking/spi: fix build and behaviour when "time" feature disabled

embassy-nrf/src/qspi.rs
=> nrf52/qspi: avoid infinite busy-wait read/write with zero-len buf

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/new_project.adoc
* Based off an example, noting what to copy, what to change and why
* Briefly summarizing how to require embassy crates via github
* All steps tested and proven working at the time of writing
=> Added a step-by-step guide to starting a new embassy project

docs/modules/ROOT/nav.adoc, docs/modules/ROOT/pages/best_practices.adoc
As discussed earlier today in the chat, this is my first draft of a "best practices" page.
The advice in there at the moment is not embassy-specific, but applies to general embedded Rust development (or even Rust in general).
Hopefully in the future we will be able to add a lot more content here.
The consensus today was that we should first start collecting advice and write it down before discussing where it should go and where it should only be referenced (e.g., general embedded rust advice could go in the rust embedded book and this page here contains a link to the section of the book).
Feedback is of course very welcome! Both by beginners ("is the advice understandable?") and experienced developers ("is it good advice?").
--
For the interested reader: Here you can explore the assembly …
=> [Docs] Add best practices page

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/time_driver.rs
Add GP TIM9 and TIM11 to be used as time_driver
=> Add GP TIM9 and TIM11 to be used as time_driver candidates

embassy-stm32/src/usart/mod.rs
=> stm32: usart pin inversion

embassy-boot/boot/src/boot_loader.rs
Tables describing the a-b flashing were all garbled up in the cargo doc output, so fix up the syntax.
=> embassy-boot: Fix formatting for tables

embassy-rp/src/uart/mod.rs
Closes #2305 
I'm not sure how to test this, but it now matches ehal v0.2 impl.
=> Fix nb on rp uart

embassy-stm32/src/i2c/mod.rs
By moving conditional code inside the functions, we can reduce duplication and in one case we can even eliminate one...
=> stm32: i2c: Clean up conditional code a bit

embassy-rp/src/adc.rs, embassy-rp/src/clocks.rs, embassy-rp/src/dma.rs, embassy-rp/src/flash.rs, embassy-rp/src/gpio.rs, embassy-rp/src/i2c.rs, embassy-rp/src/i2c_slave.rs, embassy-rp/src/lib.rs, embassy-rp/src/pio/mod.rs, embassy-rp/src/pwm.rs, embassy-rp/src/rtc/mod.rs, embassy-rp/src/timer.rs, embassy-rp/src/uart/buffered.rs, embassy-rp/src/uart/mod.rs, embassy-rp/src/usb.rs
=> docs: document all embassy-rp public apis

embassy-stm32/Cargo.toml, embassy-stm32/src/dma/bdma.rs, embassy-stm32/src/dma/dma.rs
~pending on [stm32-data#316](https://github.com/embassy-rs/stm32-data/pull/316)~
=> match up with "DMA cleanup" metapac change

.vscode/settings.json, embassy-stm32/src/usart/buffered.rs, embassy-stm32/src/usart/mod.rs, embassy-stm32/src/usart/ringbuffered.rs
Added basic descriptions to everything not documented, made some minor grammar changes to existing documentation
=> stm32: Documented usart public API

embassy-nrf/Cargo.toml, embassy-nrf/src/lib.rs
Definitely worth skimming over the descriptions as I added a few new ones but am not familiar with NRF devices and might have gotten something wrong
=> [embassy-nrf] auto-documented features

embassy-rp/Cargo.toml, embassy-rp/src/lib.rs
Couldn’t figure out what some of these do so left less-than-stellar descriptions, but at least they’re visible now
=> [embassy-rp] auto-documented feature flags

embassy-stm32/Cargo.toml, embassy-stm32/src/can/bxcan.rs, embassy-stm32/src/rtc/v2.rs, embassy-stm32/src/rtc/v3.rs, embassy-stm32/src/spi/mod.rs, examples/stm32f4/src/bin/ws2812_pwm_dma.rs, examples/stm32h7/src/bin/dac_dma.rs, examples/stm32l4/src/bin/dac_dma.rs
and refactor a few code with cargo clippy
=> update metapac after stm32-data PR323

embassy-stm32/src/rtc/mod.rs, embassy-stm32/src/rtc/v3.rs
Hello,
_First time contributing, so please let me know where I can improve here. Super open to fixes or better style_
Trying to enable the `low-power` mode support for the STM32G0 series.
I've based this off `RM0454 Rev 5` for the STM32G070 series.
This does build and run locally and appears to work; but I haven't done in depth testing (are there any guides on how to best test this otherwise, or add automatic testing?).
=> Extend RTC low power mode for STM32G0

examples/stm32g0/src/bin/hf_timer.rs
Add an example for using the high frequency timer feature with the now functioning clock controls.
=> Add High Frequency (128MHz) Timer Example For G0

embassy-net/CHANGELOG.md, embassy-net/Cargo.toml, embassy-net/src/lib.rs, examples/nrf52840/Cargo.toml, examples/nrf5340/Cargo.toml, examples/rp/Cargo.toml, examples/std/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32f7/Cargo.toml, examples/stm32h5/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32l5/Cargo.toml, examples/stm32wb/Cargo.toml, examples/stm32wba/Cargo.toml, tests/nrf/Cargo.toml, tests/perf-client/Cargo.toml, tests/rp/Cargo.toml, tests/stm32/Cargo.toml
Bumping to 0.3 because the removal of the nightly feature is a breaking change. Also removed some left over cfg's.
=> New embassy-net release 0.3

cyw43/Cargo.toml, embassy-embedded-hal/Cargo.toml, embassy-net-adin1110/Cargo.toml, embassy-net-adin1110/src/lib.rs, embassy-net-enc28j60/Cargo.toml, embassy-net-esp-hosted/Cargo.toml, embassy-net-wiznet/Cargo.toml, embassy-nrf/Cargo.toml, embassy-rp/Cargo.toml, embassy-rp/src/gpio.rs, embassy-stm32/Cargo.toml, embassy-stm32/src/gpio.rs, embassy-time/Cargo.toml, examples/nrf52840/Cargo.toml, examples/rp/Cargo.toml, examples/stm32h5/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l4/Cargo.toml, tests/nrf/Cargo.toml, tests/rp/Cargo.toml, tests/stm32/Cargo.toml
- nrf/gpio: add toggle.
- Update embedded-hal to v1.0
=> Update embedded-hal to v1.0

embassy-executor-macros/Cargo.toml
The only change was https://github.com/embassy-rs/embassy/pull/2380 which isn't a breaking change.
I'm sure you're sick of releasing crates at this point, but could you manage one more :pray:.
=> embassy-executor-macros v0.4.1

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/time_driver.rs
Adds timer-driver tim21 and tim22 that are available on L0
=> adds timer-driver for tim21 and tim22 (on L0)

.gitattributes
Remove annoying red background when view on Github. May need a full webpage refresh to let modification take effect.
=> mark json file inside .vscode folder as jsonc

embassy-time/src/lib.rs, embassy-time/src/timer.rs, examples/rp/src/bin/debounce.rs
Small qol function. I was using with_timeout to do what I'm doing in the example, but with that method the timeouts are additive, this just makes it a little easier to think about.
=> Add timeout_at convenience function and example.

ci.sh, embassy-stm32/src/rcc/f0.rs, embassy-stm32/src/rcc/l.rs
=> stm32/rcc: fix build for some f0 and l4 chips.

embassy-nrf/src/spim.rs, embassy-nrf/src/spis.rs
On most nRF chips, maximum buffer size for EasyDMA is 255, thus we never got any data when attempting to use 256 bytes as RX/TX buffer.
Maybe it makes sense to expose maximum tx/rx buffer size?
=> nrf: spim/spis: Add size checks for EasyDMA buffer

README.md
=> docs: use correct link to book

docs/modules/ROOT/pages/new_project.adoc, docs/modules/ROOT/pages/project_structure.adoc
- Update the docs to show some available project generation repos
- Add some features descriptions to `project-structure`
=> Add Generation Repos to Docs

embassy-stm32/src/timer/mod.rs
=> timer-doc-fix

embassy-stm32/Cargo.toml, embassy-stm32/src/rcc/f3.rs, embassy-stm32/src/rcc/mco.rs, examples/stm32f3/src/bin/hello.rs, examples/stm32f3/src/bin/usb_serial.rs, examples/stm32f334/src/bin/adc.rs, examples/stm32f334/src/bin/hello.rs, examples/stm32f334/src/bin/opamp.rs, examples/stm32f334/src/bin/pwm.rs, tests/stm32/src/common.rs
=> stm32/rcc: port F3 RCC to new API

embassy-boot/src/firmware_updater/asynch.rs
This PR fixes #2542.
I didn't know how to implement the change in magic size everywhere as suggested by lulf in the issue. What I've done here is to keep the magic size at size of WRITE_SIZE, and slice the buffer for writes to also be size of WRITE_SIZE. To make sure that reads are aligned to READ_SIZE, I avoid the second read for progress whenever the data is available in the first read. I have tested this on RP2040 and it works.
=> Fix unaligned buffer in async updater

cyw43/src/runner.rs
By reusing the buffer in `cyw43::Runner::run()`, two buffers can be removed. This reduces stack usage significantly by 4 KiB, and therefore the task pool size for Runner by the same amount.
I'm not 100% sure why separate buffers were used before. Maybe they're aliased somewhere through unsafe code, but I could not spot anything.
=> cyw43: Reuse buf to reduce stack usage

embassy-rp/src/gpio.rs
Fixes: https://github.com/embassy-rs/embassy/issues/2577
=> Add unsafe constructor for AnyPin

embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/nvmc.rs, embassy-nrf/src/pdm.rs, embassy-nrf/src/pwm.rs, embassy-nrf/src/qdec.rs, embassy-nrf/src/qspi.rs, embassy-nrf/src/rng.rs, embassy-nrf/src/temp.rs, embassy-nrf/src/twim.rs, embassy-nrf/src/twis.rs, embassy-nrf/src/uarte.rs
Cleans up ~30 issues pointed out by clippy, though there are still some left which would either require annotations or involve touching some code I wouldn't touch for now..
=> nrf: Add some fixes for issues pointed out by clippy

embassy-stm32/src/flash/h50.rs, embassy-stm32/src/flash/mod.rs
=> Flash support for STM32H50x [wip]

embassy-stm32/src/can/fd/config.rs, embassy-stm32/src/can/fd/filter.rs, embassy-stm32/src/can/fdcan.rs, examples/stm32g4/src/bin/can.rs, tests/stm32/src/bin/fdcan.rs
Fix review comments from:
https://github.com/embassy-rs/embassy/pull/2571
=> Cleanup of FDCAN module, mostly review comments.

embassy-stm32/src/adc/mod.rs, embassy-stm32/src/adc/resolution.rs, embassy-stm32/src/adc/sample_time.rs, embassy-stm32/src/adc/v3.rs
Most similar to `adc_v3` so the impl lives there. Blocking only for now.
Depends on https://github.com/embassy-rs/stm32-data/pull/407.
Tested temperature reads, seems fine
=> ADC support for H5

embassy-stm32/src/can/fd/peripheral.rs, embassy-stm32/src/can/fdcan.rs, embassy-stm32/src/can/frame.rs
Trying to untangle some duplicated code, etc.
=> stm32: can: fd: some refactoring

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/ipcc.rs, embassy-stm32/src/rcc/c0.rs, embassy-stm32/src/rcc/f013.rs, embassy-stm32/src/rcc/f247.rs, embassy-stm32/src/rcc/g0.rs, embassy-stm32/src/rcc/g4.rs, embassy-stm32/src/rcc/h.rs, embassy-stm32/src/rcc/l.rs, embassy-stm32/src/rcc/mod.rs, embassy-stm32/src/rcc/u5.rs, embassy-stm32/src/rcc/wba.rs, embassy-stm32/src/usb_otg/usb.rs, examples/stm32f334/src/bin/pwm.rs, examples/stm32g0/src/bin/hf_timer.rs, examples/stm32g0/src/bin/usb_serial.rs, examples/stm32g4/src/bin/adc.rs, examples/stm32g4/src/bin/can.rs, examples/stm32g4/src/bin/pll.rs, examples/stm32g4/src/bin/usb_serial.rs, examples/stm32h5/src/bin/can.rs, examples/stm32h5/src/bin/usb_serial.rs, examples/stm32h7/src/bin/adc.rs, examples/stm32h7/src/bin/can.rs, examples/stm32h7/src/bin/dac.rs, examples/stm32h7/src/bin/dac_dma.rs, examples/stm32l4/src/bin/adc.rs, tests/stm32/src/bin/fdcan.rs, tests/stm32/src/common.rs
ports https://github.com/embassy-rs/embassy/pull/2583 to all chips
requires https://github.com/embassy-rs/stm32-data/pull/423
=> stm32: autogenerate mux config for all chips.

ci.sh
update according to ST info https://www.st.com/content/st_com/en/arm-32-bit-microcontrollers/arm-cortex-m33.html
=> ci stm32: update U5 H5 WBA target to Armv8-M

examples/stm32f4/Cargo.toml, examples/stm32f4/src/bin/usb_hid_mouse.rs
Tested on stm32f407vg (Discovery Board)
=> stm32: add usb_hid_mouse example

examples/stm32f4/src/bin/usb_hid_keyboard.rs
Tested on STM32F407VG Discovery board.
=> stm32: add usb_hid_keyboard example

embassy-stm32/src/ucpd.rs, tests/stm32/Cargo.toml, tests/stm32/src/bin/ucpd.rs
Test sends messages between a sink and a source in either direction.
Also checks if hard resets are detected.
=> STM32 UCPD CI Test

embassy-stm32/src/can/fd/peripheral.rs, tests/stm32/src/bin/fdcan.rs
Fix for https://github.com/embassy-rs/embassy/issues/2702
Tested for CAN2 but should fix CAN3 on devices that support it also.
=> FDCAN: Fix offset issue preventing CAN2 and CAN3 from working.

embassy-sync/src/signal.rs
Burned a few brain cells figuring this one out haha. Signaled does not clear the signal.
=> Doc update: signaled does not clear signal

embassy-usb-logger/src/lib.rs
Re-try to write the remainder of a log message to avoid truncation due to short write at pipe wraparound.
=> usb-logger: avoid data loss at pipe wraparound

embassy-stm32/src/usart/buffered.rs
=> STM32 BufferedUart: wake receive task for each received byte

embassy-nrf/src/lib.rs
=> nRF52840/config: add dcdc voltage parameter

embassy-sync/src/lib.rs, embassy-sync/src/once_lock.rs
=> Add `OnceLock` sync primitive

embassy-boot/src/boot_loader.rs
use 4/5/6 as new firmware for better understanding
=> boot: update comments

embassy-sync/src/semaphore.rs
- `acquire` and `acquire_all` futures were `!Send`, even for `M: RawMutex + Send` due to the captured `Cell`.
- If multiple `acquire` tasks were queued, waking the first would not wake the second, even if there were permits remaining after the first `acquire` completed.
=> Fix `FairSemaphore` bugs

docs/modules/ROOT/pages/embassy_in_the_wild.adoc
=> Added YLab project to "in the wild"

embassy-stm32/src/usb/otg.rs
fix OTG_HS in FS mode, such as in the f429zi-disc1 board.
=> stm32/otg: fix OTG_HS in FS mode.

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/adc/g4.rs, embassy-stm32/src/adc/mod.rs, embassy-stm32/src/crc/v1.rs, embassy-stm32/src/crc/v2v3.rs, embassy-stm32/src/flash/f4.rs, embassy-stm32/src/flash/h50.rs, embassy-stm32/src/flash/mod.rs, embassy-stm32/src/spi/mod.rs, examples/stm32g4/src/bin/adc.rs
Fix for issue https://github.com/embassy-rs/stm32-data/issues/459
=> Fix for SPI and CRC reg changes in stm32-data

embassy-stm32/src/usb/otg.rs
Lifted from this branch which was tested to prevent spurious stall errors.
https://github.com/embassy-rs/embassy/compare/embassy-rs:e38f101...jamesmunns:3302923
=> Add critical sections to avoid USB OTG Errata

examples/stm32l4/.cargo/config.toml
Reverts some change made in https://github.com/embassy-rs/embassy/pull/1792
=> L4 Example: probe-run to probe-rs

docs/modules/ROOT/pages/layer_by_layer.adoc
=> Update layer_by_layer.adoc to fix a typo

embassy-sync/src/channel.rs
Adding ready_to_receive() to enable waiting to receive without actually receiving
=> Adding ready_to_receive to Channel and Receiver

embassy-stm32/src/usart/mod.rs
Extra trace detail to help troubleshoot USART config via defmt.
This might be nice to have.  Only potential draw back is a slight perf. hit with the trace logging, but I would assume any release build can set a higher logging level, i.e. INFO etc.
=> Add trace logging for USART

embassy-usb-dfu/Cargo.toml, embassy-usb-logger/Cargo.toml, embassy-usb/CHANGELOG.md, embassy-usb/Cargo.toml, examples/boot/application/stm32wb-dfu/Cargo.toml, examples/boot/bootloader/stm32wb-dfu/Cargo.toml, examples/nrf52840/Cargo.toml, examples/nrf5340/Cargo.toml, examples/rp/Cargo.toml, examples/stm32f1/Cargo.toml, examples/stm32f3/Cargo.toml, examples/stm32f334/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32f7/Cargo.toml, examples/stm32g0/Cargo.toml, examples/stm32g4/Cargo.toml, examples/stm32h5/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32l1/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32l5/Cargo.toml, examples/stm32u0/Cargo.toml, examples/stm32u5/Cargo.toml
=> embassy-usb: Update version and add changelog

embassy-nrf/src/usb/mod.rs
I have an application where it would be useful to receive asynchronous notifications of the USB endpoint becoming disabled as well as enabled.
=> Add `wait_disabled` method to `embassy_nrf::usb::Endpoint`

examples/rp/src/bin/usb_webusb.rs
Add the Microsoft OS Descriptor (MSOS/MOD) descriptor
=> rp: WebUSB example - add Windows compatibility

embassy-stm32/Cargo.toml
=> stm32/i2c: actually add h7rs support.

docs/modules/ROOT/pages/faq.adoc, examples/stm32h7/build.rs, examples/stm32h7/memory.x, examples/stm32h7/src/bin/spi_bdma.rs
=> Add example for bdma

embassy-sync/src/mutex.rs
Adds trait implementations to match those in `std`:
- `Mutex<M, T>`
- [`From<T>`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#486-493)
- [`Default`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#495-501)
- [`Debug`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#503-521)
- `MutexGuard`
- [`Debug`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#556-561)
- [`Display`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#563-568)
- `MappedMutexGuard`
- [`Debug`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#672-677)
- [`Display`](https://doc.rust-lang.org/1.78.0/src/std/sync/mutex.rs.html#679-684)
=> embassy_sync::Mutex: Implement traits to match std

examples/stm32f7/src/bin/qspi.rs
PR for https://github.com/embassy-rs/embassy/issues/2921
=> Example usage of QSPI

embassy-stm32/src/ucpd.rs
=> [UCPD] Use `ChannelAndRequest` helper

docs/modules/ROOT/pages/faq.adoc
This adds an opinionated process for supporting a brand new (family of) chip(s) in Embassy.
=> FAQ: "How to add support for a new chip"

docs/modules/ROOT/pages/faq.adoc
Sections were incorrectly nested one level too deep
=> FAQ: Fix section nesting

embassy-hal-internal/src/atomic_ring_buffer.rs, embassy-rp/src/uart/buffered.rs, embassy-rp/src/uart/mod.rs
PR addressing the bug explained in #2949.
=> Fix drop implementation of `BufferedUartRx` and `BufferedUartTx` in `embassy-rp`

embassy-usb/CHANGELOG.md
Updating the changelog with PRs, I think this is the only one but I'll keep looking
=> embassy-usb - update 0.2 changelog

embassy-usb-logger/CHANGELOG.md, embassy-usb-logger/Cargo.toml, examples/rp/Cargo.toml
=> Add a CHANGELOG to embassy-usb-logger and bump its version

embassy-usb-synopsys-otg/src/lib.rs
Adds a driver configuration option to enable transceiver delay, which is necessary for some ULPI PHYs.
See also: https://github.com/stm32-rs/synopsys-usb-otg/pull/17
=> usb: add transceiver delay option

embassy-stm32/src/qspi/mod.rs, examples/stm32f7/src/bin/qspi.rs
=> stm32/qspi: remove DMA generic param.

LICENSE-CC-BY-SA, docs/README.md
This matches the Rust Embedded books
=> Explicitly license the book prose CC-BY-SA

docs/pages/faq.adoc
=> FAQ: One vs Many tasks

embassy-rp/src/lib.rs
=> rp: fix spinlocks staying locked after reset.

docs/pages/faq.adoc
=> docs: faq: Fix link to bdma example and improve wording.

embassy-stm32/src/opamp.rs
**OPAMP1** on stm32g4 can be internally connected to **DAC3CH1**, this is currently not supported by the OpAmp struct in embassy.
Add a buffer_dac method to the OpAmp Struct to enable this particular configuration.
=> Make OpAmp usable in follower configuration for internal DAC channel

embassy-time/Cargo.toml, embassy-time/src/lib.rs
This PR adds a few features to provide timestamps formatted using the display hints introduced in https://github.com/knurling-rs/defmt/pull/789
=> embassy-time: add timestamp features

embassy-stm32/src/can/fd/peripheral.rs, embassy-stm32/src/can/fdcan.rs
Remove generic argument from CanBuilder.
=> Remove generic argument from FDCAN CanBuilder.

examples/rp/src/bin/zerocopy.rs
=> rp: Add zerocopy channel example

embassy-net/src/dns.rs
Currently, a DNS query with AddrType::Either will always result to an A query returning a v4 address, even when the stack is only configured in v6 and/or the host name only associated with a v6 address, which makes it pretty useless.
This change allows get_host_by_name() to make up to 2 queries (A and AAAA) for AddrType::Either (depending on wether the first query is successful or not), and it will prioritize the appropriate query depending on which stack version is configured.
=> dns: properly handle AddrType::Either in get_host_by_name()

embassy-executor/src/raw/waker.rs
follow-up to https://github.com/embassy-rs/embassy/pull/3059
=> minimize cfg code in task_from_waker

examples/stm32u5/src/bin/tsc.rs
Add example executable for the U5 family demonstrating the touch sensitive controller peripheral
=> Add example for touch sensitive controller

examples/rp/src/bin/wifi_ap_tcp_server.rs, examples/rp/src/bin/wifi_blinky.rs, examples/rp/src/bin/wifi_scan.rs, examples/rp/src/bin/wifi_tcp_server.rs
my own mistake, no less - sorry...
=> typo: was missing "bin"

examples/stm32g0/Cargo.toml, examples/stm32g0/src/bin/adc.rs, examples/stm32g0/src/bin/rtc.rs, examples/stm32g0/src/bin/usart.rs, examples/stm32g0/src/bin/usart_buffered.rs, examples/stm32g0/src/bin/usart_dma.rs
Add `usart`  `usart_dma ` `usart_buffered  ` `irq   ` `adc  ` examples for `stm32g0`
Tested correctly with `STM32G031G8Ux`
=> Add examples for stm32g0

examples/stm32wb/src/bin/eddystone_beacon.rs, examples/stm32wb/src/bin/gatt_server.rs, examples/stm32wb/src/bin/mac_ffd.rs, examples/stm32wb/src/bin/mac_ffd_net.rs, examples/stm32wb/src/bin/mac_rfd.rs, examples/stm32wb/src/bin/tl_mbox.rs, examples/stm32wb/src/bin/tl_mbox_ble.rs, examples/stm32wb/src/bin/tl_mbox_mac.rs
File removed in commit https://github.com/embassy-rs/embassy/commit/c19967dcf24d5223de5fd9b390371dc24aeccc1d
=> examples: stm32wb: remove comment about memory.x file

examples/rp/Cargo.toml, examples/rp/src/bin/wifi_webrequest.rs
After myself and 2 others had the same question in 3 days on matrix: Maybe You want an example?
This is not strictly an embassy thing, but it took me (= new to Rust and fairly new to embedded) quite some time & a lot of kind help on matrix to figure out. So my guess is others might benefit.
(thanks @jamesmunns especially!)
Word of caution: Binary size grew > 10xxkb and flashing that somehow corrupts the device and the code fails. The exact same code copied into my own project works just fine. So I added a secction to `cargo.toml` to reduce binary size:
```toml
[profile.dev]
lto = true
opt-level = "z"
```
That way the code now runs without issue, with less than half the original binary size. 
-> if that is not okay, then the entire thing should not go into the repo without some other …
=> Add http request example to rp

embassy-boot-nrf/src/lib.rs, embassy-boot-rp/src/lib.rs, embassy-boot-stm32/src/lib.rs, embassy-boot/src/test_flash/asynch.rs, embassy-stm32/src/can/bxcan/registers.rs, embassy-stm32/src/flash/asynch.rs, embassy-stm32/src/flash/common.rs, embassy-stm32/src/flash/f0.rs, embassy-stm32/src/flash/f1f3.rs, embassy-stm32/src/flash/f4.rs, embassy-stm32/src/flash/f7.rs, embassy-stm32/src/flash/g.rs, embassy-stm32/src/flash/h50.rs, embassy-stm32/src/flash/h7.rs, embassy-stm32/src/flash/l.rs, embassy-stm32/src/flash/u0.rs, embassy-stm32/src/flash/u5.rs, embassy-stm32/src/rcc/mod.rs
Cherry-picked commits from #3129 that are strictly about removing implicit panic call-sites
=> Less implicit panics

embassy-net/src/tcp.rs
=> Add check for closed connection to `read_ready()`

embassy-stm32/src/usart/mod.rs
After #2895 I discoverer the same problems:
- At read-read-write-write-read sequence MCU can read bytes which was sent over `write`.
- The `read` at start MCU can cause infinity loop because `tc` bit will be set only after `write`.
To fix it I allow either transmitter (`cr1.te()`) or receiver (`cr1.re()`) at `write`, `read` and `flush` calls.
Tested on `STM32F446RE` with two Half-Duplex protocols: Smart Audio and CRSF.
=> WIP: STM32 Half-Duplex: fix sequential reads and writes

embassy-stm32/src/adc/v3.rs, examples/stm32g0/src/bin/adc_oversampling.rs
Add adc oversampling to support 16bit adc reads.
Also add usage examples
=> Add adc oversampling support

embassy-stm32/src/adc/v4.rs
The Adc v4 peripheral includes a hardware oversampler. This PR adds an averaging interface that keeps most of the current interface backwards compatible while allowing for the common use-case of hardware-averaging. A more comprehensive oversampler interface may be exposed in the future.
=> stm32 - Adc v4 - Add averaging support.

examples/stm32h7/src/bin/spi_bdma.rs
Please refer [here](https://github.com/embassy-rs/embassy/pull/2904#issuecomment-2133482150) to see why this change is necessary.
I couldn't test this example because I have a Daisy Seed board(it has STM32H750), but all the SPI6 pins are connected to the SDRAM, and I can't use them. I confirmed it can be build, and run. But not yet tested it can transmit or receive bytes.
I accidentally commit `Merge branch main...`(`e2aa5ef376d0137e92e1f033801cfcaf9084597a`) commit. This commit is not intended to be part of the submission, and I would like to request that they be excluded from the merge.
I can create a new pull request with only the intended changes.
Or you can review the pull request and merge only the necessary changes, excluding the unwanted one.
closes #2905
=> Fix BDMA example for soundness

docs/pages/faq.adoc, docs/pages/sharing_peripherals.adoc, examples/rp/src/bin/sharing.rs
We get a lot of questions about how to share things between tasks, so i thought an example would be a good idea, showcasing some common scenarios.
=> Add example for sharing things between tasks

docs/pages/faq.adoc, examples/rp/Cargo.toml, examples/rp/src/bin/assign_resources.rs
After kind help from @Dirbaio on matrix and @9names pointing out this was a regular question.
-> In the hope this will help others.
=> add assign_resources rp example

embassy-nrf/src/buffered_uarte.rs, embassy-stm32/src/usart/buffered.rs
#3165 was done recently -> apparently not done for nrf or stm, too. 
I cannot test on my machine, so let us see what ci makes of it.
=> Impl read ready for buffered uart

embassy-net/src/tcp.rs
Such that every new socket from that `TcpClient` gets the timeout.
=> (embassy-net): Allow setting socket timeout for embedded-nal TcpClient

embassy-stm32/src/sdmmc/mod.rs
The sdmmc module currently allows the user to pass in a data_block buffer to perform DMA data transfers. However, cmd_block buffers are created on the stack internally. This poses a problem if the stack RAM does not work with DMA. An example of this is the stm32h735 mcu which can have RAM as ITCM memory (0x20000000) and AXISRAM for use with DMA (0x24000000).
This change allows the user to pass in a statically allocated buffer in a location of their choosing when using the sdmmc module. There are two new functions that mirror existing functions so as to ensure backwards compatibility:
```rust
/// Initializes card (if present) and sets the bus at the specified frequency.
pub async fn init_card(&mut self, freq: Hertz) -> Result<(), Error> {
let mut cmd_buffer = CmdBlock::new(); …
```
=> embassy-stm32: Allow cmd block to be passed in for sdmmc dma transfers

ci.sh, tests/rp/src/bin/timer.rs
- **ci: add instructions to install cargo-batch if not installed.**
- **tests/rp: add timer test.**
=> tests/rp: add timer test.

embassy-net/src/lib.rs
`smoltcp::socket::dns::Socket::update_servers()` will panic if a slice exceeding a fixed length is passed to it. Since `embassy-rs` never sets the said const, the default is used. Currently this is 1 (and we can be sure it will never be lower).
If there's an update in `smoltcp` API to expose the maximum length allowed with a `const fn`, the `DNS_MAX_SERVER_COUNT` could be set using it (see https://github.com/smoltcp-rs/smoltcp/pull/962).
=> embassy-net: dns: bound the dns_servers slice

embassy-rp/src/uart/mod.rs
Adds 'read_to_break_with_count' to the RP2040 uart implementation, an extension of 'read_to_break'.
This makes it possible to restart the read immediately after a break has been detected, even if the break is still going on when the read is restarted. Most uart framing where 'read_to_break' is used has some sort of header byte, which can be used to make sure that the read actually read until the next break and doesn't detect the break that was already detected
=> RP2040: Add read_to_break_with_count

embassy-rp/README.md
There is no feature `time` in embassy-rp. Is it `time-driver`? Is it something else?
=> Fix possible typo in embassy-rp README.md

embassy-net-esp-hosted/src/proto.rs, embassy-net/src/lib.rs, embassy-stm32-wpan/src/mac/commands.rs, examples/nrf52840/src/bin/ethernet_enc28j60.rs, examples/nrf52840/src/bin/usb_ethernet.rs, examples/nrf52840/src/bin/wifi_esp_hosted.rs, examples/rp/src/bin/ethernet_w5500_multisocket.rs, examples/rp/src/bin/ethernet_w5500_tcp_client.rs, examples/rp/src/bin/ethernet_w5500_tcp_server.rs, examples/rp/src/bin/ethernet_w5500_udp.rs, examples/rp/src/bin/usb_ethernet.rs, examples/rp/src/bin/wifi_ap_tcp_server.rs, examples/rp/src/bin/wifi_tcp_server.rs, examples/rp/src/bin/wifi_webrequest.rs, examples/std/src/bin/net.rs, examples/std/src/bin/net_dns.rs, examples/std/src/bin/net_ppp.rs, examples/std/src/bin/net_udp.rs, examples/std/src/bin/tcp_accept.rs, examples/stm32f4/src/bin/eth.rs, examples/stm32f4/src/bin/eth_w5500.rs, examples/stm32f4/src/bin/usb_ethernet.rs, examples/stm32f7/src/bin/eth.rs, examples/stm32h5/src/bin/eth.rs, examples/stm32h7/src/bin/eth.rs, examples/stm32h7/src/bin/eth_client.rs, examples/stm32h7/src/bin/eth_client_mii.rs, examples/stm32l4/src/bin/spe_adin1110_http_server.rs, examples/stm32l5/src/bin/usb_ethernet.rs
- **examples: ensure at least 3 sockets to avoid running out (DHCP, DNS, the user's)**
- **Silence some unused warnings on nightly.**
=> Misc fixes.

embassy-rp/src/flash.rs
Missed this in the review, good catch from @8cichy8
PS. I don't have an option to enable maintainer commits? Maybe because I don't own this fork? 
E: Yup, just did a quick test, I can't enable maintainer commits on prs from my work org, but can from my personal fork.
=> rp: Fix commented out code in flash.rs

docs/pages/embassy_in_the_wild.adoc
Want this? 
It is a hobby project, so likely interesting only to beginners,
=> add one more embassy in the wild example

embassy-sync/README.md
=> Fix link to PriorityChannel

docs/pages/faq.adoc
=> Update faq.adoc - "code doesn't work in release mode"

embassy-usb-logger/src/lib.rs
fixes #3294
example usage: 
https://github.com/endsummercamp/minibadge/blob/master/antani_sw/src/usb.rs#L69-L78
=> support custom log formatting for usb logger

embassy-executor/src/lib.rs, embassy-executor/src/raw/waker.rs, rust-toolchain-nightly.toml
https://doc.rust-lang.org/nightly/core/task/struct.Waker.html#method.data
https://doc.rust-lang.org/nightly/core/task/struct.Waker.html#method.vtable
=> fix: nightly api changed during the night

embassy-stm32/src/flash/f2.rs, embassy-stm32/src/flash/mod.rs
Blocking flash drivers for STM32F2 series
=> stm32: add f2 flash support (blocking)

embassy-futures/src/select.rs
=> fix: `select_slice` is unsound.

embassy-rp/src/clocks.rs
=> rp23: Disable pad isolation on clock in/out pins

embassy-sync/src/pubsub/mod.rs
https://github.com/embassy-rs/embassy/pull/2969 appears to have broken direct `publish_immediate()` on `pubsub::Channel`, as it functionally made `PubSubBehavior` private and didn't delegate this method to the new (private) `SealedPubSubBehavior`.
This change moves `publish_immediate`, `capacity`, and `is_full` from `SealedPubSubBehavior` to `PubSubBehavior` in order to restore them to `pub` visibility.
=> embassy_sync/pubsub: fix PubSubBehavior visibility

examples/rp23/memory.x
See https://github.com/rp-rs/rp-hal/issues/853 and https://github.com/rp-rs/rp-hal/pull/854
=> rp23: add missing binary info in linker script

embassy-sync/README.md
was not mentioned, easier for people to find that way
=> Add Watch to embassy-sync README

embassy-sync/src/watch.rs
Just fixes some Sender/Receiver typos.
=> docs: fix Sender/Receiver typo

embassy-sync/CHANGELOG.md, embassy-sync/src/zerocopy_channel.rs
Added these functions for consistency with other modules.
=> embassy-sync: add clear, len, is_empty and is_full functions to zerocopy_channel

embassy-sync/CHANGELOG.md, embassy-sync/src/blocking_mutex/mod.rs, embassy-sync/src/mutex.rs, embassy-sync/src/pubsub/mod.rs
This PR does not address all clippy lints, the author of the `Watch` primitive should probably have a closer look on what clippy suggests.
=> embassy-sync: documentation and clippy fixes

embassy-stm32/src/usart/buffered.rs, embassy-stm32/src/usart/mod.rs
I have a setup where I need to set a PULLUP.
=> stm32: add RX Pull configuration option to USART

embassy-net-driver-channel/src/lib.rs, embassy-net-driver/src/lib.rs, embassy-net-enc28j60/src/lib.rs, embassy-net-tuntap/src/lib.rs, embassy-net/src/driver_util.rs, embassy-net/src/tcp.rs, embassy-rp/src/lib.rs, embassy-rp/src/multicore.rs, embassy-stm32-wpan/src/lib.rs, embassy-stm32-wpan/src/mac/commands.rs, embassy-stm32-wpan/src/mac/driver.rs, embassy-stm32/src/eth/mod.rs, embassy-stm32/src/low_power.rs, embassy-stm32/src/rcc/mod.rs, examples/stm32h7/src/bin/sai.rs, examples/stm32h7/src/bin/spi_bdma.rs, rust-toolchain-nightly.toml, tests/nrf/src/bin/buffered_uart_spam.rs, tests/stm32/src/bin/usart_rx_ringbuffered.rs
=> Update nighlty, fix warnings.

embassy-futures/src/select.rs
Added select with 5 and 6 futures since I need it for my project.
=> embassy-futures: add select 5 and 6

embassy-net/Cargo.toml, embassy-net/src/raw.rs, embassy-net/src/udp.rs
=> net: Add flush for UDP and Raw sockets.

embassy-stm32/src/can/bxcan/mod.rs
1. If one received frames under an `interrupt_free` section using `try_read`, in my case `init` in RTIC, the RX IRQ will fire and clear it's enable bit after `interrupt_free` is complete. There is no frame to read so RX is now unconditionally disabled forever.
2. On clearing of RX IRQ, TX stops silently. This happens due to the use of `write` instead of `modify` when modifying IRQ enable bits.
Solution 1: Enable RX IRQs on `try_read` when no frames are available. This solution also solves the issue of very delayed handling of the RX IRQ which would cause the same issue.
Solution 2: Use `modify` instead of `write`.
=> This fixes 2 issues where STM32 BXCAN would hang

ci.sh, embassy-stm32/src/ospi/mod.rs, examples/stm32h7/src/bin/ospi_memory_mapped.rs, examples/stm32h7b0/.cargo/config.toml, examples/stm32h7b0/Cargo.toml, examples/stm32h7b0/build.rs, examples/stm32h7b0/memory.x, examples/stm32h7b0/src/bin/ospi_memory_mapped.rs
Verified on weact stm32h7b0 board + w25q64 spi flash, code at: https://github.com/HaoboGu/eg-demo/blob/058defff156bab29cc9abeef3db08750d5cc5458/src/w25q.rs#L68-L93
=> Add memory mapped mode for stm32 ospi

embassy-stm32/src/qspi/mod.rs
Expose an async API and add some sanity checks.
Closes #3474 
Closes #3473
=> STM32 Qspi async

embassy-net/src/raw.rs
This PR reexports some types from smoltcp for use with raw sockets.
=> Reexported some smoltcp types for raw socket.

embassy-rp/src/pio/mod.rs
=> rp/pio: ensure PADS IE=1 which is not the default in rp235x.

embassy-time-driver/src/lib.rs
=> Enhanced docs for time driver

embassy-stm32/src/low_power.rs, embassy-stm32/src/rtc/low_power.rs, embassy-stm32/src/rtc/mod.rs, embassy-stm32/src/rtc/v3.rs
I can confirm it works on my Nucleo-U575ZI-Q. The power consumption measured is ~16uA.
=> low-power: add support for stm32u5

embassy-nrf/src/pwm.rs
- **nrf/pwm: fix bad pin assignment.**
- **nrf/pwm: disconnect input.**
=> nrf/pwm: fix bad pin assignment, disconnect input.

embassy-executor-macros/src/macros/task.rs
This PR allows overriding the `embassy_executor` crate path.
We're [wrapping](https://future-proof-iot.github.io/RIOT-rs/dev/docs/api/riot_rs/attr.task.html) the `embassy_executor::task` to provide some convenience.
Without this PR, users of `riot_rs::task` must also explicitly add `embassy_executor` to their application's dependencies, even though riot-rs re-exports it.
=> executor: allow overriding `embassy_executor` path in `task` macro

docs/pages/embassy_in_the_wild.adoc
add link to https://github.com/1-rafael-1/simple-robot -> see if you want that, do not want to spam that list...
=> add simple-robot to Embassy in the wild

embassy-stm32/src/rcc/h.rs
=> Fix wrong unit

embassy-executor/CHANGELOG.md, embassy-executor/src/arch/avr.rs, embassy-executor/src/arch/cortex_m.rs, embassy-executor/src/arch/riscv32.rs, embassy-executor/src/arch/spin.rs, embassy-executor/src/arch/std.rs, embassy-executor/src/arch/wasm.rs, embassy-executor/src/raw/mod.rs, embassy-executor/tests/test.rs, embassy-stm32/src/low_power.rs
Untested. Let me know if I shouldn't waste time here because this was done for a reason.
=> Executor: Only set callback once

embassy-stm32/src/rcc/g4.rs
https://github.com/embassy-rs/embassy/pull/3574#discussion_r1860269356
=> fix: Add missing clock check

embassy-net/CHANGELOG.md, embassy-net/Cargo.toml, examples/nrf52840/Cargo.toml, examples/nrf5340/Cargo.toml, examples/nrf9160/Cargo.toml, examples/rp/Cargo.toml, examples/rp23/Cargo.toml, examples/std/Cargo.toml, examples/stm32f4/Cargo.toml, examples/stm32f7/Cargo.toml, examples/stm32h5/Cargo.toml, examples/stm32h7/Cargo.toml, examples/stm32h755cm4/Cargo.toml, examples/stm32h755cm7/Cargo.toml, examples/stm32h7b0/Cargo.toml, examples/stm32h7rs/Cargo.toml, examples/stm32l4/Cargo.toml, examples/stm32l5/Cargo.toml, examples/stm32wb/Cargo.toml, examples/stm32wba/Cargo.toml, tests/nrf/Cargo.toml, tests/perf-client/Cargo.toml, tests/rp/Cargo.toml, tests/stm32/Cargo.toml
- **net: update to smoltcp v0.12.0**
- **net: release v0.5.0**
=> net: release v0.5.0 with smoltcp v0.12

embassy-stm32/src/adc/g4.rs, examples/stm32g4/src/bin/adc_dma.rs
I referenced the implementation of [the G0 series](https://github.com/embassy-rs/embassy/blob/main/embassy-stm32/src/adc/v3.rs).
It currently works correctly on my STM32G431CBU6.
=> STM32: Implement Asynchronous ADC Reading for G4

examples/rp/src/bin/wifi_scan.rs
=> Update RP Wifi Scan Example: Remove code that isn't used by the example (minor cleanup)

embassy-usb/src/builder.rs, embassy-usb/src/lib.rs
Forgot to expose UsbVersion publically
#3599
=> Expose UsbVersion

embassy-stm32/Cargo.toml, embassy-stm32/src/hrtim/mod.rs, examples/stm32f334/src/bin/pwm.rs
This PR updates the HRTIM driver per https://github.com/embassy-rs/stm32-data/pull/544
Cheers!
=> STM32: bump to latest stm32-metapac

embassy-nrf/src/nfct.rs
Now it works both with android and iOS, and both with and without logs.
=> nrf/nfct: actually fix frame timing.

cyw43/src/ioctl.rs, embassy-executor/src/spawner.rs, embassy-net-esp-hosted/src/ioctl.rs, embassy-net-nrf91/src/lib.rs, embassy-net/src/raw.rs, embassy-net/src/tcp.rs, embassy-net/src/udp.rs, embassy-nrf/src/buffered_uarte.rs, embassy-nrf/src/qspi.rs, embassy-nrf/src/usb/mod.rs, embassy-nrf/src/usb/vbus_detect.rs, embassy-rp/src/adc.rs, embassy-sync/src/mutex.rs, embassy-sync/src/once_lock.rs, embassy-sync/src/watch.rs, embassy-sync/src/zerocopy_channel.rs, embassy-usb/src/class/cdc_acm.rs, embassy-usb/src/class/uac1/speaker.rs
Not everything - I've been ignoring HALs and where the desugar would be unreasonably complicated (functions involving generics, for example).
=> Desugar some async fns

embassy-stm32/src/eth/v1/mod.rs
Should fix: https://github.com/embassy-rs/embassy/issues/2496
=> Fixed stm32 v1 ethernet driver multicast reception

examples/std/README.md, examples/std/src/bin/net.rs, examples/std/tap.sh
Did some minor cosmetic cleanups to the README and demo in `examples/std`.
=> std example cosmetics

embassy-nrf/CHANGELOG.md
Didn't notice that 0.3 was already released..
=> nrf: Add some notes to changelog

cyw43-pio/Cargo.toml, embassy-rp/Cargo.toml, embassy-rp/src/pio/mod.rs, examples/rp/Cargo.toml, examples/rp23/Cargo.toml, examples/rp23/src/bin/pio_rotary_encoder_rxf.rs, tests/rp/Cargo.toml
This requires changes in `pio` too if we want the example to work (ping @CBJamo). Probably a new release?
=> RP235x: Add the new FJOIN_RX_xxx options

ci.sh, embassy-stm32/build.rs
- **Fix issue with enabled split-pxy feature**
- **stm32: test split pins in CI.**
=> Fix issue with enabled split-pxy feature

embassy-sync/src/zerocopy_channel.rs
Zero-copy channels could not be used between interrupts and thread-mode tasks because the internal buffer is stored as a raw pointer. A wrapper struct implementing the Sync trait fixes this.
=> Fix issue #3828

embassy-rp/src/watchdog.rs
This allows to query if and why the last system reset was caused by the watchdog.
=> Expose the watchdog reset reason

README.md
=> docs: fix esp wording and mention trouble

embassy-stm32/src/i2c/v2.rs
For I2C devices that support variable length reads, sending chunks of data as long as the master keeps ACK:ing after each received byte, sequential reads will sometimes get out of sync, causing additional reads to return invalid data.
This was caused by a delay between awaiting the DMA read and sending the software STOP signal, which may result in the slave to have time to send a byte of data in between, causing potential miss-alignment. This would then cause subsequent reads to return invalid data.
Async write-reads now no longer send STOP after the initial write, matching the behaviour of the blocking version.
=> fix: Fix for async I2C v2 driver sequential read/write reads. Fixes #3887

embassy-stm32/src/i2c/v2.rs
Currently when error occurs, we have to wait for timeout, which is less than ideal. Enable related interrupts, and return Err when error occurs.
=> stm32: i2c-v2: Add error handling

README.md, docs/pages/hal.adoc, docs/pages/overview.adoc
Hello, I've been working on a [HAL for the Microchip PolarFire SoC (MPFS](https://github.com/AlexCharlton/mpfs-hal)), and it includes a crate with Embassy support.
While it is not yet complete, I think it has enough features to be useful at this point, so I figured referencing it in the README would be helpful.
=> Update README.md to include a reference to mpfs-hal

embassy-stm32/src/usart/ringbuffered.rs
In the discussion in https://github.com/embassy-rs/embassy/pull/3480, I reported that the changes introduced in https://github.com/embassy-rs/embassy/pull/3930 break the GPDMA ringbuffer implementation. Now I could figure out the problem: In my setup, the remote side is still powering on while the RX ringbuffer is already set up. The floating pin causes RX errors which are never cleared. I could reliably reproduce this with a simple test project on a nucleo-u545re-q board with an open RX pin.
The changes in https://github.com/embassy-rs/embassy/pull/3930 revealed that issue because before, all interrupt flags have always been cleared. https://github.com/embassy-rs/embassy/pull/3930 changes this to only clear the IDLE interrupt flag as the comment says but this keeps the error flags around …
=> Recover from errors in ringbuffered usart

embassy-stm32/Cargo.toml, embassy-stm32/build.rs, embassy-stm32/src/adc/c0.rs, embassy-stm32/src/adc/mod.rs, embassy-stm32/src/flash/f4.rs, embassy-stm32/src/flash/h5.rs, embassy-stm32/src/flash/h50.rs, embassy-stm32/src/flash/mod.rs, embassy-stm32/src/flash/u5.rs, embassy-stm32/src/ospi/mod.rs, embassy-stm32/src/rcc/c0.rs, examples/stm32c0/src/bin/adc.rs
- **Update stm32-data.**
- **Added ADC support for STM32C0.**
- **feat(stm32): Add OTP flash region (again)**
- **Fix compile error in ospi**
=> update stm32-data, add C0 adc, add OTP memory regions.

embassy-usb/src/class/cdc_acm.rs
Make CDC ACM state constructor `const`.
=> Make CDC ACM state constructor `const`

embassy-stm32/build.rs, embassy-stm32/src/cryp/mod.rs, embassy-stm32/src/dac/mod.rs, embassy-stm32/src/dma/mod.rs, embassy-stm32/src/dma/util.rs, embassy-stm32/src/hash/mod.rs, embassy-stm32/src/macros.rs, embassy-stm32/src/sdmmc/mod.rs, embassy-stm32/src/spi/mod.rs, examples/stm32f4/src/bin/dac.rs, examples/stm32h7/src/bin/dac.rs, examples/stm32h7/src/bin/dac_dma.rs, examples/stm32l4/src/bin/dac.rs, examples/stm32l4/src/bin/dac_dma.rs, examples/stm32u0/src/bin/dac.rs, tests/stm32/src/bin/dac.rs, tests/stm32/src/bin/dac_l1.rs, tests/stm32/src/bin/hash.rs
- **stm32/dac: dedup pin and DMA traits, demacrofify.**
- **stm32/dac: remove DMA generic params.**
- **stm32/sdmmc: remove DMA generic param.**
- **stm32/hash: remove DMA generic param.**
- **stm32/cryp: remove DMA generic param.**
=> stm32: remove DMA generic params, remove NoDma.

embassy-mspm0/src/gpio.rs
Regarding a discussion in the matrix chat, I ended up thinking about the mspm0 gpio implementation.
For an InputFuture, we clear RIS and then configure the event the hardware should listen for. However what if the current value in the event register is `rising_edge` and the input future being constructed is `falling_edge`.
Since we read `RIS` to determine if an edge event happens, it is possible that between clearing `RIS` and setting the new event, the old edge event may happen. This might end up with `RIS` being set. Then when the future is polled, the value of `RIS` is checked: meaning the old event may have been captured. That could of course mean the wrong edge was captured.
To fix this, we tell the hardware to listen to no events temporarily before clearing the interrupt. Then when …
=> mspm0: disable events before clearing gpio RIS

embassy-stm32/src/usart/ringbuffered.rs
This uses the `embedded-io-async::Read` impl to implement the `nb` variant. Since `embedded_hal_nb` traits are also implemented for other types, I find it consistent to have it here as well. Forwarding from `nb` to `async` seems a bit hacky at first, but it should be fine as far as I can tell and it successfully prevents code duplication.
=> Add embedded_hal_nb::serial::Read impl for RingBufferedUartRx

embassy-stm32/src/i2c/v2.rs
fix: Fix for #3888 async I2C read bug for introduced in #3887 in STM32 I2C v2 driver
In fixing a different timing related bug, #3887, a new bug was introduced causing I2C reads longer than 255 bytes to timeout for some I2C devices, #3888.
The issue was caused by incorrect branch order, and poll function being called unnecessarily.
Async I2C read poll function now only looks for I2C transfer complete reload (TCR) interrupts, intead of TCR and transfer complete (TC) interrupts, since TC interrupts are not raised when AUTOEND bit is set.
=> fix: Fix for #3888 async I2C read bug for introduced in #3887 

embassy-mspm0/Cargo.toml, embassy-mspm0/build.rs, embassy-mspm0/src/gpio.rs, embassy-mspm0/src/lib.rs, embassy-mspm0/src/macros.rs, embassy-mspm0/src/uart.rs, examples/mspm0c1104/Cargo.toml, examples/mspm0c1104/src/bin/uart.rs, examples/mspm0g3507/Cargo.toml, examples/mspm0g3507/src/bin/uart.rs, examples/mspm0g3519/Cargo.toml, examples/mspm0g3519/src/bin/uart.rs, examples/mspm0l1306/Cargo.toml, examples/mspm0l1306/src/bin/uart.rs, examples/mspm0l2228/Cargo.toml, examples/mspm0l2228/src/bin/uart.rs
And examples.
G3519 can't execute this currently due to an unrelated WWDT0 issue (no idea why it's interrupt goes off, I am not even touching it).
=> mspm0: blocking uart driver

embassy-stm32/src/adc/f1.rs
Co-Authored-By: Tnze <cjd001113@outlook.com>
=> stm32/adc: enable interrupt for stm32f1

embassy-stm32/src/can/fd/config.rs
=> [embassy-stm32] Documentation correction

examples/stm32h742/.cargo/config.toml, examples/stm32h742/Cargo.toml, examples/stm32h742/build.rs, examples/stm32h742/src/bin/qspi.rs
modified qspi example for stm32f7 to work on stm32h742
=> added qspi example for stm32h742

examples/rp/src/bin/wifi_tcp_server.rs
=> update WiFi credentials to placeholders

ci.sh, embassy-boot-nrf/src/lib.rs, embassy-nrf/Cargo.toml, embassy-nrf/src/chips/nrf51.rs, embassy-nrf/src/chips/nrf52805.rs, embassy-nrf/src/chips/nrf52810.rs, embassy-nrf/src/chips/nrf52811.rs, embassy-nrf/src/chips/nrf52820.rs, embassy-nrf/src/chips/nrf52832.rs, embassy-nrf/src/chips/nrf52833.rs, embassy-nrf/src/chips/nrf52840.rs, embassy-nrf/src/chips/nrf5340_app.rs, embassy-nrf/src/chips/nrf5340_net.rs, embassy-nrf/src/chips/nrf9120.rs, embassy-nrf/src/chips/nrf9160.rs, embassy-nrf/src/lib.rs, embassy-nrf/src/wdt.rs
=> nrf53: add WDT support

embassy-stm32/src/adc/g4.rs, embassy-usb/src/builder.rs
Feel free to ignore this PR, but I always see these logs and they're almost never relevant. I think they make more sense at the trace level instead of the info level.
=> Logging: Make some things less chatty

embassy-usb-dfu/src/application.rs
This commit adds an interface that allows users to customise how the bootloader is informed that DFU mode is needed on the next boot.
=> [embassy-usb-dfu] Add generic DFU marking interface

embassy-nrf/src/lib.rs
=> nrf: _3v3 -> _3V3

embassy-stm32/Cargo.toml, embassy-stm32/src/rtc/mod.rs
rebase of #4219
- **Add support for rtc_v3h7rs**
- **Update stm32-metapac tag**
=> Add support for rtc_v3h7rs

embassy-nrf/src/lib.rs, embassy-nrf/src/rng.rs
This allows avoiding creating the irq handler if you're only going
to use it in blocking mode.
=> nrf/rng: add Blocking/Async Mode param.

embassy-imxrt/src/time_driver.rs
Before writing to MATCH_L/MATCH_H registers, wait for permission to do so by pollinmg MATCH_WR_RDY bit in CTRL register.
=> timer: ostimer: wait for match write ready

embassy-stm32/src/can/fdcan.rs
This PR uses the reference counting logic already implemented in the `fdcan` module to also call `set_as_disconnected` on the pins and to possibly disable the RCC clock. Before, only the "buffered" readers and writers have been counted to set the modes back to `NonBuffered` after the last one had been dropped. Now, all readers and writers are counted, a TX _and_ RX type like `Can` or `BufferedCan` counts as both.
This works because there is only one direction to initialize the types: `CanConfigurator` -> `Can` (unbuffered) -> `BufferedCan`/`BufferedCanFd` (-> drop). In other words: Since there is no way to go back from buffered to unbuffered without stealing the peripheral, users should definitely drop the old instance before. So when the last active instance is dropped, the modes are set …
=> Cleanup Pins and RCC for FDCAN on STM32

embassy-sync/src/channel.rs
Fix as per https://github.com/embassy-rs/embassy/pull/4262
=> Rename SendableDynamicReceiver to SendDynamicReceiver

embassy-stm32/src/rcc/u5.rs
Should close #3635 , and also fixes an issue where MSIK stops when HSI is enabled.
=> Use modify() for subsequent changes to RCC.cr()

embassy-stm32/src/rcc/mod.rs
This PR provides a means for user code to access the current clock configuration, addressing #3909.
We must ensure that the new `rcc::clocks()` function does not allow the user to hold a reference to `CLOCK_FREQS`: (1) before `embassy_stm32::init()`, (2) during `rcc::reinit()`. This is done using references to the `Peri<RCC>` singleton.
Change requests welcome.... I am still wrapping my head around the Peri struct
=> Add public function to get current clock configuration

docs/pages/new_project.adoc
Some people are trying to use cargo-embassy for our chips and end up disappointed. Let's link to the vendor-supported generator.
=> Link to esp-generate

embassy-stm32/src/usart/mod.rs
It fixes `impl embedded_hal_nb::serial::Write for usart::UartTx` because old code calls `blocking_write` in non blocking trait.
=> stm32: Fix impl embedded_hal_nb::serial::Write for usart::UartTx

embassy-stm32/src/opamp.rs
OpAmp::new() now resets the opamp and enables its clock. The clock disabled when the opamp is dropped. On families that use SYSCFGEN (F3 and G4), this is not done because clock is always on in Embassy.
This change makes use of the RCC driver, which uses a reference counter to prevent conflicts. The opamp itself is still disabled when its output is dropped.
The PR intentionally does not add opamp features for more families yet to make reviewing easier.
The following table shows the opamp clock enable bits for all families, taken from RMs and/or CubeMX generated code:
| Family  | Example     | RCC       |
| ------- | ----------- | --------- |
| L1 (*)  | STM32L152RE | COMPEN    |
| F3      | STM32F303K8 | SYSCFGEN  |
| L4      | STM32L432KC | OPAMPEN   |
| L4+     | STM32L4P5ZG | OPAMPEN …
=> Use proper RCC clock enable for opamps

ci.sh, embassy-stm32/Cargo.toml, embassy-stm32/src/rcc/mco.rs, embassy-stm32/src/usb/otg.rs
It has USB but not HSI48 which would break things. Only g0x1 has HSI48.
=> stm32: fix stm32g0b0 build.

embassy-nrf/src/lib.rs
In the nRF MDK, there is a workaround "UICR_HFXO_WORKAROUND"  that resests the HFXO values if they are erased. This is necessary on my nrf9151 to have the modem working properly.
I found this thanks to these two messages:
https://github.com/diondokter/nrf-modem/issues/32#issuecomment-2704598018  
https://devzone.nordicsemi.com/f/nordic-q-a/96093/nrf9160-porting-the-modem-library-to-work-with-bare-metal-application/435351?focus=true
I'm not sure I placed this workaround in the correct place, or if this should be handled by embassy-nrf.
I tested this on the nrf9151 of a Thingy91 X, without this workaround the modem gets stuck in initialization, with the workaround it works as intended.
=> feat(embassy-nrf): add uicr hfxo workaround

ci.sh, embassy-embedded-hal/Cargo.toml
default features considered harmful.
=> embassy-embedded-hal: make time feature non-default

examples/rp/src/bin/wifi_tcp_server.rs, examples/rp/src/bin/wifi_webrequest.rs
Fixes some logical errors in the state of the WiFi link.
=> examples: fix RP2040 link establishing logic

embassy-embedded-hal/src/adapter/yielding_async.rs, embassy-embedded-hal/src/flash/concat_flash.rs, embassy-embedded-hal/src/flash/partition/asynch.rs, embassy-embedded-hal/src/flash/partition/blocking.rs
I noticed a bunch of missing MultiwriteNorflash implementations.
So here they are.
=> Multi write flash adapters

embassy-nrf/src/chips/nrf54l15_app.rs, embassy-nrf/src/lib.rs, examples/nrf54l15/src/bin/temp.rs
Enable temp support on the nrf54l15
Alphabetize peripherals in the pac
=> Enable temp support on the nrf54l15

embassy-executor/src/raw/trace.rs
Fixes https://github.com/embassy-rs/embassy/issues/4545
=> Add missing feature gate for rtos-trace

ci.sh
https://github.com/embassy-rs/embassy/pull/4435 needs this
=> ci: 5340dk is dead

embassy-executor/CHANGELOG.md, embassy-executor/Cargo.toml, examples/nrf-rtos-trace/Cargo.toml
Upgrade rtos-trace for start/stop and marker support.
=> rtos-trace: upgraded feature support

examples/nrf52840/src/bin/nfct.rs
- **nrf: add NFCT NDEF example.**
- **Fix offset calculation**
=> nrf: add NFCT NDEF example

embassy-stm32/CHANGELOG.md, embassy-stm32/src/qspi/mod.rs, examples/stm32f7/src/bin/qspi.rs, examples/stm32h742/src/bin/qspi.rs, examples/stm32l432/src/bin/qspi_mmap.rs
Also tags qspi::Config as non_exhaustive
=> embassy-stm32: Configurable gpio speed for QSPI

embassy-nrf/CHANGELOG.md, embassy-nrf/src/gpiote.rs, embassy-nrf/src/timer.rs
=> nrf: add persist() for gpiote and timer

embassy-nxp/CHANGELOG.md, embassy-nxp/Cargo.toml, embassy-nxp/src/chips/lpc55.rs, embassy-nxp/src/dma.rs, embassy-nxp/src/dma/lpc55.rs, embassy-nxp/src/lib.rs, embassy-nxp/src/usart/lpc55.rs, examples/lpc55s69/src/bin/usart_async.rs
Hello! I've added for LPC55:
- DMA controller driver;
- Asynchronous mode for USART.
=> lpc55: dma and async usart

docs/examples/basic/Cargo.toml, embassy-boot-nrf/CHANGELOG.md, embassy-boot-nrf/Cargo.toml, embassy-nrf/CHANGELOG.md, embassy-nrf/Cargo.toml, examples/boot/application/nrf/Cargo.toml, examples/nrf-rtos-trace/Cargo.toml, examples/nrf51/Cargo.toml, examples/nrf52810/Cargo.toml, examples/nrf52840-edf/Cargo.toml, examples/nrf52840-rtic/Cargo.toml, examples/nrf52840/Cargo.toml, examples/nrf5340/Cargo.toml, examples/nrf54l15/Cargo.toml, examples/nrf9151/ns/Cargo.toml, examples/nrf9151/s/Cargo.toml, examples/nrf9160/Cargo.toml, tests/nrf/Cargo.toml
embassy-nrf-v0.8.0
embassy-boot-nrf-v0.9.0
=> chore: prepare crate releases
